apiVersion: v1
kind: Secret
metadata:
  name: vikunja
stringData:
  VIKUNJA_SERVICE_JWT_SECRET: ENC[AES256_GCM,data:aF1l7ASh7q8zyQtrhIeb1zlfSEBYgsyW5925ffbFGHtsvLORRaI8MuPVIQi+M1MxDT7sJhRwMLCzLtRF38VB9hSqZkU/HynMR4Bd0qJZmuAlfa0PCUeLBA==,iv:6WybA2sTdTHNN47jTfLnnPLETn1aiZ8dPTohIR1dodk=,tag:wnqtY3MQ+pwBBag3CDs4jg==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFpFWDVrL1Ar
        NTdWRHdoa3ZpVWpuK3Nyc1pWbk84Q0hodzB0M1I1K0owaE8yRlY2MkRqcVlkem5t
        ZElhTlNNVmFnVGRiaTNzeWJvNTFpOUh2SGptZTM2QUMvR3B1NjZoZVhCS3EyclVF
        MjFoSEtpNTRJMDk5cXE5amdSVU96OTJmWEVqUHpCZzVTcTZ3VUJrZjViakhkNTJn
        NEljdW9tVStDQmI1OHBUSnhKbXFMQkhReUdXZ3dNZUxTaG50dnZWdjlLREYzb1h0
        N2FJS25lNTNKYUQ3c2FNWkZ1QlJaZ0g5TG4vWFJpRThhSTJ6UDdEcVEySlhMZEpB
        LzJrYXNQaVpyaEVLMUE2bzJtMVdVMTBXSlZxTkVTdWJOay83QmtWNE5hUUk1Rzc4
        Q3dId3JBbElKSnZ3NlNkaE10Yi9neFc2NGhsaHdnZzJvQXp3eVA0NXl4SzRrckVx
        SWJpd0xKNUx1OXM2dHJDV2YxdFpVQmFucWVhMnNkdWR0aldnSUtwU2M0V01PSXN5
        SmFLZlg4c2ROR09mWDcyMWlNYU5OeldJbGVRNVRCYmNDdjVHTHh1a014dzQ5TDRH
        aHlZaUt3U3FOendQVmFIdDV4b1MyOHRpcmIyT3Z5SS9oNzk5WGRBc2NGZjY3b0Rl
        ZExlMEhPNHY5ekJGTFE0empEL2wxSERnVU1wMzNaVTFBUTVCeUxXbzRWbEFKcUVv
        ODR2TGs2UFRCRVlaTGhOQ2Z1a0RyWmFDczdIeDc2S3NkSFVYMzZURUtUOHlSK2Q0
        emFMSlpwSkkwVFMyRjlycnU0S2JKNWFzRmtvK2lHYmxlWVZUODhHeDhaVWsvN0VV
        QTlEbE5PRG1HUjFXcEEzLzBWZWZaS1kwWStvcGg2WVc0VDAvdDR3bWxNZUVZS3kx
        dTV5clJsNllJU2xVOGh1YnNUdHUxR0k1NlZHWW5ERElCVzVhbGpMZEdKak5iUEJ5
        dldKSTZQUnRzMnhVZHo5bGJYRkw4MVdXaTNlQ2xDYStEQnQ3ZU1OY3ByTWZYRW5Y
        VXVDWmdjQTM0RmlLMUpKQ3d0aUEwcUh0MVErOVJRMmoyVkNoTzFLQldjaDdsdjBh
        aFdqY0hhb254MWlzUm53emEyYTN3c0o5NUhCL1FEYmJRSnM0VGNCYUpXeU15bk5h
        N3MrSG1TRFBTWW03cllpOEhKckUzR0dJYXpiSWx3a2hubzh3NFBWa0JrazBKeDVS
        SzVyRUxlS3ZQVUVwcmR2bGtWL3dRbnVaM2NTaVlvNGEyWVpkajF4SThWQ0dyQllw
        RXNWS0k4Q1NxYUZvTW0yVEJrNXJwKzZQLzBIR1V0YTRzcDAyT04rVGtyZ1NoSlI2
        L05xdllJNTBFOHFWcERyamRJTHhpY2xQajUwc3FMZXpGeDhxRTY1WE5qSm02T2Z5
        b3lhTTVCSFNLOWVVcFd0eHoxTU5PQU90SDhxYm00Y2lweGx4OUdYNnVlbUtPSGwx
        Qm9WMkZQamwrcmdnTUF4bjlPWHVpMk4vMDVMMENXVGhad1hkODJhMGdDc3hER1Fm
        WUxZUENOS1hIOTlPc0ZIc1ZGbks3R3ZSMk5xazhhY3kxOTJzNUNITFZsbWc0UTUy
        VVVsNGpuei9qa1BqdjQvTENwT1Q3aWZVd2dIY1RKU1ZkTkhqRW5NUFF0SUN2RlZn
        VnBpZUZiMDhhWmtKcXBDbGl4REp3R2tjc1E1MTRKSlRqdFlaWlk4eTNCa3Fac2tD
        em92T08yRkxZY2M0dUpOcEc5Rkx3aFFMTlZiQlhubWxPaVFlSitlMDhxdkhxL1RM
        ZnhIdEdmNGFkZUZQNnMxOVRkcHV4WWpoU0JQY2VlR3VBbE93ZHc3RGZLTVcvU0lx
        TENCQjRwaG4xWjFIcTY4eTZmSDI3Wk11SjI4THZTVzVDVy9CdHZKWWtsQmljdGxx
        WS9zYlY4eGVBeGJ3aGRSN2VlVkEvWEhCMTlxMThiQmRwZElyNzltbHZxanpjUQpr
        SlJRODVuUXpYNFNWZHFNcVZuV1ZuTlBZZFpUUjU3eExrd2hSMDlRQWkwCi0tLSA2
        MnBQeWtRY0tHYXFzcTBSQmRFdUlIaVREWHhpU0R4eUJqVE1aSWVSWEJvCmZu3BV5
        SuLMyGdzLJb2OpCjQ+y6FslfqWfhJgVeiRMePQ3qae/AOab30lyR0LVFfkM/ZjgK
        bYjCLYvMKWRFWRw=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T17:22:16Z"
  mac: ENC[AES256_GCM,data:lPKFVJr9vxK53AwBxso3KdeDSmsJ82LdkOqj1AnFSOlixIa3jSUiyQnK0nNwoI5Adx0/bZ74BuPuur8IEVFbvB8g5UOU7C50PfJl6XmVj7lE3oz/Y+XClQ1LzCV/PLN8aIerwRewuibLeFLc7X7QB3RKzq7PlDM1TeNyUZ0yXo0=,iv:U+17edWXv3/jmNEr8sIDVyio4idAk35GFlt3mGKyKDk=,tag:EdJeV4ZtGVpbwvo+Y3B0EQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
