# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: deploy-key
  namespace: flux-system
stringData:
  identity: ENC[AES256_GCM,data:IXwg5Bbsffw7UjAjJova3+eVYpYcPUzeFWURsNFPXdloW+FQK54KjvBd9mDzhInAtaoXy1oA7yiVrxPd5BPps1HQckqzL81SmS/ivFRUEI7ndaq1zij+HtQIfuWy3NVxMNVGzH33m4V1z9odD+rQDhGVFwB0FGTU/D8SVtM4FELxezFO/Db9+iDi8/v/2q0wrnGaVJLNCn/0Goc2NiCbj1kVoFUO0Dtyedpo5F/JpYPCL/y7Ck6rvRf3Ar+/e+UYms1t2ZFgfDP6fjgi5E50Yd7UBMn3kwSAIQDjbMiKsTu0bjTIkN4bilXfc5ABSm+600RuTWV9kJxS5kyweUKk1y5IG9hJy+bCgPBcEkAj5TAJivLvbD2rjxSdx2lCb3GMAD3bp1uvkpdH8h/0GSFdheKZGbHSHaKO7Wkj+oIEILBweJgnWWrdO7dttPm9LVV9oQfIHbF86iBm73kNffK3kRmwHoSTnt0yNAENA5BYCKzNCtL5Nszfdf4iTLbPvn+1Opcoc4gN2MOGLF1PhMYC,iv:kknggvo4hIipbG7mBBR65cnTmeS8UWqqrVT3kpufyx4=,tag:3kIaUhZ4ChUCjSJ/+FyWYw==,type:str]
  known_hosts: ENC[AES256_GCM,data:VUbzDopUrJi7Z1/Pk64we3TOncPqZ/Swlj0P++Y9mzQ8DcNs2EAMh6zqVSKO5c7NrZD356aXlJl0RBkDxGL6+5SfoGjA83hCMz4J40/Bvlbu5jNiUwsXlmHH/l6MxJAm2KtbpdNDMhc1W8HXGiOxCGs+L3gm,iv:xbkSvwNAC0jRmn9tPre1wqYhe7Fqa5uL2nmcnAwiHA8=,tag:JgqTb2g4fWDREiur8GnZhw==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5ICtHbUNWQ29u
        Um5ZMFUzanc0L09pUGl0VzVxUmhLcHlUU1JuSkxtdzVMeWVTRkwzNjFMUG9HclpM
        MFZwaVoyRzMyTENUSjF3MGJYcjdRT2p2VnU0MFg1NmpJK2VFSVNtOGd5NGJoZ1g2
        cFJRTHhTR3YwYXpDQmhzWUo3ZXR4WmJqNmhVbzNpOS8zeDdxUFJOTDJaT2h4SDJQ
        ekE1aktTZ1VqSHo5SCs1d0xvYzJXNm5SemxjSGhQUTZFUG9IV1JsK2VRLzdPM0hk
        TzR0OExDb2krSnZOT2F0cnBua0luNHdUazJyMmpmUHM5aU1QOC9nUHhadXYrY0ti
        SGMwQmVvRUF5WTdyRU5Kak9rM1NNaTh6c0VieDhtdFlXUC9DbUVXREtFVElUMElI
        clRxZnNKck5EY0tTSE1UWGdGOHBNdUpkTVhpOUU4Qkx3UUFRZG15WGthZjZ5WHRm
        SGEzZ1dZSm4rc01zQkp0ZkpMaFdzWEtSYzZ5LytaMmp4c0Z3QVpmdFBsN1NBSnRB
        UjJXeHBGK0kxWkt2OFJWZUlWVm5vTXZNbFJaa2I5bmZ5SWRSQjFESURGWWtvTWJC
        WFFuNHF1TEVmN3FrNE5ncGpFQ3c1V3VoZ1cwY3dWYVg3RnA2RmMwMDFuLys2aHBV
        bWVPVWVEWUpSQjYvalhtS1AycUF2M3NDcEt0T1R5ZE1OZk41Y3R5MkM4MWhOSjFJ
        Y3E0SThFeU1GUVI5OU01Z2krdkJ2UmgzTzkyYUloQUxJNXBMSytkRjAweEo4VlUx
        a0RZTXRmM0orcElOU0FYRDlDTjBrZXhORHR1MDdUTFhuRFJodkl0YWlDWithRmVS
        WmdhVUxRb3BMYkYzaVBMMFVjbmZBNER1cURtVGhPMkpOd1czWTRySUZhbUlTSjNn
        TWUzYWd4aTlWcm00WXpxMDZEcFZyUytOV3I0cUthdVVvRVkwWnZtV2pSd0gwc1Jh
        VDQ5SzVORWtvMkNaeUhGRnRNSWZmZ1NhWno0cEdNUWxqMythanpSNWRjUXZoemlz
        M2hKNU1iNmV5YTNrMWVqcHhuSlJlazcwbVZYODhIZ1BtZFVQK04zYy8rUkoxeXNT
        bDJJSXlOK2Rod3hrUEhtQkZMMDluTGU1S01BSGxwcEJXWkxzYllOY0daSXFjL3NC
        MzBJYlNoMTdHdVNxVUY3RlgranVyNHo3WGpHbkI4TVdva21QVkRoMUtpR0F4NXNr
        TW40TjJiZDdRWW9mQ3dob3pxRU92TnN4NHJKWmQ3Q1ZYdUdIZGV3aFFDWHJ1Nzc2
        V3RRNTlDK1psVGFyaEpzZHVPc0s3Nm01dkl6N1Y4VnRGdmJ5ZjQ5RGFtWEUxQU8r
        YTVOQ0VQME9vODZCazJ0bzZVVHRPcjFFa1prc21RM3pNcGJVQW9vN2FYbGxQUUo1
        OGc3akNCUmJLRzU1a1RJbWpMMlhIcDlwcDQ1NS9oYzc2NEloL3A5UlJVZktsMkI5
        L1RkdFhKVHp0bFd4NVN1dzZrRXF0ZEErUTd1Sjd5V1VROWdFZmRKYjErYWk1dFAz
        SmEyakJFaVJrb1BIazgvOTZWMlJSNWJOb3pENE5UK2hINE05Kzc0Y3hEc1ZGRUs5
        VWlCQmJ0QTRVL3UwZDRwYkNtTlVCR3FEcG9NWW9qMFlXcVkxNlN2Ky9zNVJGeFUx
        OVNZR0gvdEpxUzJ3c3hTVkNiQkJWbFZLdjJGaWRPWnNmVXA5YkFHQXp1aFJGNERi
        d0oyajkzZHVxb2dNOHZuRVpQK1h4RjVPQmJSemIrNWoxcm5YR3BmU0hTQ0xrcGM1
        YnFwTTVxa2NkTm42MUFPd0E3cVJPSVkyaU93dXQ0SUJtUURBMXdxanNoemhUdUFK
        QXhLejBNdWNkcG1SZEJhUTFxalhBcHZjZmxXMU9EUEZyNjZmS3lIRWhjMVVCYjRp
        UVdIZ2pOR0dyT21jc1pGWkh1Q1YvOWh6SzhEZEsvbGp3bzY1dHkzdlRvYlFDZwo4
        V0liYVdVTkFteU1TRm13Ukg2ZktaYkE4S1gyK1RTMG5ZbUZTZFlTK3lrCi0tLSB6
        UzBRclQrNG1ucU5KdHlmN1BiRXhnV3FDS25ubERqQzBCclMzbkE1UktzCv63jtCA
        GGRgRm3fAMP5msYUlN5XqmouiQi5NX8bkR29BWTMU2tkXrzXwubDdh+kBS6TBfo/
        8m5eW/y4tq81HP8=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-03T05:10:48Z"
  mac: ENC[AES256_GCM,data:jzm2eJjQk/NALg/bvm5l9UsUO0au40NzlCNwLjj2u/WiI1DnWoOnPHBsmmvN2/TPRFiv6c0oxSHVqNA2v1/iY0+0NKykyIiunietI/1+83xbsAo8ocNIoRRyb4H+64yCkb2ddGTpbipTzIchg83cwtHxyG8QFu3+fUnm6KthysM=,iv:M0kX4ZyMMngaKrOAUblhY8Z54aOjpdYDBt7nliji0KA=,tag:HlYlYekMJZq+EuRhZF20Wg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
