# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: git-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:RTmTt7npOYy0PH+hy3Aer8JbVcXb81qH/t8pFi8VpbzGzEj2IqE14xigzAHt5YOQlAmoLonJKhEqoHVXrvx00IgZ2lN+VbTS,iv:d3wKzFGQnpHr4ogs6cttDf/rYtEUo5YbH5TWcsmz+zY=,tag:6ycl8nIdoKBQUtEQXcrS1A==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEVGUXVnY01F
        R2REOWw1TE5yZW5leDdScXp2U2pJdHBmUElFWk5UNlVwOGN6em1qU0g5Y3ZJYThU
        aUxva2o4c3JaQk9wajJNdlEzUCttSG5TbUxRd215L3Z4T084Q3JsNVR3S0JkNHZL
        cVVBUU1hOUQ0a3lIeG5GeDlMalBCanh3ZXdseS9iQTZKSzZOWEo4S3NwNmcvWSt1
        Q3oyMVp2RGMvaTRkeE5jZnVpRG5ieFFQZHVmM0FzSjFOQTR2MlVlNDZabHRCSllZ
        ektQNkVrOHBLYWloL1pkazA4M0V0eSsvM3ZrNW1oQ3FqVGx4MDNla1BwVU9KOFZh
        MXl6anplV09abzFyQ1prKzN1Ri9lMmxjVExMc3JtRWNMZzJ5YUVLNktSRjVRdVIv
        QmsvU0Q1L25aNUtETHNqZkluN0NSckg5bTRkN2hSY1ZFRFo0VkJlTW80YmwyM1Ew
        aXRpQUZhVlg1eXJJY3JqazBjNmFUeno3N25XcXlGcDNuU3o1Q3B6KzlLR05ZTWdE
        MWhGWll5amlTb2ZINEkxd1NoOC9SQWVvUTJsdFhCQ3BSUzJ2RUVNZUtXWm9TU0tL
        K3JpUzBteC9zdU1DS3BKc0pvVGJQVDFNcmZWbVF5Nm5ESksrMGFVU0toMXhFNTNy
        cXFpTTdxNDE1NVoybEFYbTlDUFVvd2pjMCtGRTdBVDZGQ3Y2SHFwS0dLTFY1NVZC
        WE4xTUVBakxtUm13NkxadmI4cURjOFNFZ3NCdnlGWndkc01WWlZ2akYxRWRia0s0
        OVU5bUtwSklSOG1FK0FsVmozWjFBNGFzWDJSeHBaVTg4K0N0Sm5aSEhheFhJcll5
        bUd6L0grVjZycWdEaVJGUjlYU3cwMVZHemgwTWJjRDZJckozZlREczJ4aHRvWG9I
        azRwQU5qbTJrWm9uTDkrajAvZmVSNnZNNFpuL3d2YTBzWFE2d2FRLzNpOHE5WGo3
        eEFDaFQ3dFlSKzQzWUkrUGdJeFA5L2VKRnVGVDB0OVlHNUZDVWt0ZFkyUUduT2dI
        TlZqa2pKVWQwbnAyMmRkVHloYjRuSFpnaEpuY3VFd2hFOHdhR2pQdWJUN3ZKcnFS
        U0ZHaW1FUEV2aFhETlU3Y1NvU2FUVEd4cWFTRXV2amZla3g5ZVBzdG1BZ0ZxU2VD
        aVFyWW0wOHhoaWttT0lwM3JpQkRpdGkzZnlPdEtIL1JBWlJBZkNCQWprVmc1RlFl
        K09KVldUMG9lMytMQVdFS0ZWWE9YY3RTNmJYc3g4S2N3OGliK0RiOGdEVzkxNFJQ
        R1BKYys5OHdTdkhhNmtYcFcrYmRVTnNLSWY0a1ExTmdGU2ZuTVhYcGluY2lJay9v
        YkNHOEhUZWRMUERva0JZY1R3am1vdWIrQlFUZVNHc3BMb0FoWTdOcmVYaS9XdFJI
        eVNtZ0VLVXkxSm4yR0RvNGgxN2MvakduY0ZtYzNIbnlNTEJxY25ibkxzTHRVQ3g5
        Q3V4UGZkcG9IT0ZmVkNwS0pvUFoveVRDdmxmYVNQZ1gyZ2pyczdLYVpOWFMvNVdS
        cG5tOVZ4YnJ0VkxSY05ra2pSNUZtaWV5VXVRWTRITWdiaFNzc0d0L0ZiemI5RUtK
        bng1Tk4rMmx3L0tnd0tNKy9VK2xMVXZIOHBCcGRxbUdYTWpUWENEN0NOT2Q5STh0
        OUJUbG1iZjNDNUR3My91MEt6bjFiM00xK2NyTVorLzhyL1lsNmxrZkFQendXeHBX
        N0tnZHhUc3Q1TVphTktHVko1eDh5MnpEb1JKUUErMkVwK05GT05NWnowd0kzM3VR
        Z3F4b1JPWENFcU1STWpPcEd3Sm1ZVkRtVzNmOVRreVBWME1tLzlPOTlxWG4reHVI
        T2NzWGQ4OFd2Ylg5bXpXNUlzZHJpdWR6b3IraHFQMUFHMHRKeFpYNW5OQ2hoZ0x3
        MnNST3Y1bGhVU2NiT0IrdFNCUzBQTGVsTWVaZWZVYmUvUHAwai9VUDdHVFRQUQpP
        K2xyQTFvTVB3OVlxcHllV3JLaUhoNXU1TVhaYXRjcW9FSVAyR0lIcUNjCi0tLSBW
        bkVEK3ZzeGRscnFreWpUTHRGTEJTT0o3ZS9vQis0K2xuNzFwS1l4Qm9JCrcThfo9
        O1pjbJp9pFFE5NO0YI4BIp7xgmkfbSgFv2/5fAfclxUhB1KLw+mqTGypwLnH4hjy
        iapmv7cZpTxuDag=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-15T16:00:18Z"
  mac: ENC[AES256_GCM,data:G6vziUavFley0rZDm8dfxzQw9a3CKsneULvWyiRHniZzJPNu7XS7HPHyE0U98+V8m3h8dEHyg4XgEV7Ktt6nkRScN55HIwXxS9S1NCCXCi/ddiggYDdVWjWH5aGaoyixtmPPfDMmOfvU0wuVODdwTOvlZIAZVJ6AAWP5wEPIexs=,iv:olYW4fRSi94fuq5oZNc8QRDp6OLc6hxtr3LMOTaqgSw=,tag:27BMplyPlULwbc86kecGFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
