apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:0PTRh+Xm3tnB9q5usCqPpXgdw+cvcv8eEAhtR14R8zfjeZhJTWN2hL9VRJ5U29I958Xzu4EXYO48GlKKuvYlM1L0ymu7p3PUz0lbRbicq78b7Vp+vvPc6StE299xZYWt4b8q0D5n9HDUa2yG+nWd7imQtuKNOQ==,iv:KPtoX23UCEiV56C/9EwHWaOMEXwvQx5edTFW+deRrDk=,tag:UHkLDHcjr4DTPRvdqz91BA==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG8rUEE1OHdE
        dDlOMG4xbDR1ZUx3MXRpVWxQVnVDZTdVT1BnL3QzeC9INnNtcGwzMzNmL0dRd2FZ
        TVJWZkJpSzRyM0JYUG92cXhieXBNendEMmRhMHVIWU5PUjN1b0NLTEVHTmZBZVl3
        c0JRZWZyM05ZL3IrNW1QdWh0VFAyOG5JTmo5eng1ZVhvQlNtU056eXQzNzE1MDV5
        VGs2NFFSVW9IdXd5dEl1enZndmhHd2gycEo2d0ZNbjNSYlpoT1lENmtkWlkyRm1z
        VFd6dEJJbitzdmppWm8yV1lFZldTZWF1Q2ttNU5ZaUFLbVE4azFlTzV6MVBJOGJM
        NzB1cmdoV3I3TDRCNmo2VXpRM0s0TXMxSXRpQmk2Smp1bUllUkZhMkxDTDhoVlZS
        NWxVcHk1S3BSR0VwcVRkZkN2YVZDMzJQckJQbm5EU0NXVXY4S055RU1tejUxR05z
        QzZNa1NYUm9pUXFYSHo3NldFenMrc0JaYkpKb3h6U3FVUzNoZTJCa1BKaHpXTnBs
        aG9HeE04dWxXV1ZnRkVScGVmbXlZSGNGZGJCdFlVeHR0RE43V1AvbXBPbzhmYzM5
        a3ZCRHBjbHY2dTFCWWN6VHFYc2c1MmFYdit3dml0V1hLL2dKMUtSazBqQW1RMFZj
        dnRTOFlac3pldlI1dGVNbUNvVGJzQWZLbUZQNlpzUmRVNTVOcUVTTTlSNXhaT1Mz
        NmsvY2NPV09ROVlGVDJIRk9HaVAxREwxV01BRTZ3MUkzMnBPcjViaWlOTWpNWE5p
        NkRiRGcwVWtiYnNaY2taNFlkbjB1bFo4bFdzZXdWWnllZ1R6WHpsNnBoUiszWUpu
        UGFqVENPUVV6SE5JM3Z1OVF5MmdBU1NUSUNkdGRTTGkwUkNuSHZwWWcxOGE0Rlly
        aVZmSXZGUkZUK3ArOTdMK1FzNnM0TWREa2JIekhQOVBqakNGMmF0NW9QdER1dHp2
        ZlhLc002RHVrQmdpTG5nRzVjdVI3TXhRUGlTS1ZsVlBEcUhuNURkc0RscStFbCs2
        UzZQZnAzREpwOFROZ1FrRkV0anNZOGMrZjlmN0QrdmNMeHFUbXlLbVE5bmxDT2ls
        OHhmZjFRYmp2YTRTLzhvWkVlUzA5QmsvZjR1REpDM0NlQXVTMkFJK2RlQTNHMzhp
        bE56WldNN2FNM1hrYXJFdXo1R243OFNOMnR3bkRWRXYzM0lYVDIvUjdCU3BGQ2pT
        MVJxNWVyQm0xdE5Oa0FiNWg1NG9DRUp6UTA1Y3RsdUJobkZtL0Zza3AvemwvUHpz
        RlNxOTVyTG1EN1RLMSt1UkI2YXlCWTdmMWU3Vjd4YzRjc0NpT21BdjdqZUJXZW8x
        bERtc1BXdWgxeEVtOENHS05DekxzUlZrQmszNWFjbjhJQm1PN0gzaEhjM2lncS9r
        b041WElNaTNuUThPbkJ3LzQ3S1ZYTzlOZmRCTWlHTkJTOVpWU3BIY1RiNGxXdDVU
        RFh3anVPQm5oQjVZU0ZoeVloTGJvNFYrRUJxU2N2ZjlGOGZIQm4yckVDbEVFcGlS
        UXRJSTdzQk9rNnNtZW04R2VvSTl2V2pDNXFFTlRQQ3NER1lRV2J4NFJIOUhBUTVZ
        cEJKS1J2TldzdzVxZmR3QkZ5ZXVSbzN2V3d6dThpUCtNT2FZUzFyTzM1WXZvak9i
        NzZhWmMxTDYzSExIN3RZQUsvOGlKUGdjMjkvRlo5WWg1bEh6UTFuTXNMVWtwaEp4
        NHdVcWNZRnNQWjlhK0lkNlNtRlRoVmFzOStsS3ZoeVpMdTZiblpaUWhVNmdxa0VX
        bUNsTE9nRVV1TnJFMWJpVWNaUXJUZFRpV1JRV3BFbUczMDRYOXNIaHRDVEs3NEJI
        dTAyalJKQ2NRc1R1TXpKWklKZDd3OGZKY0w2ZUp0c1F3ditTcVJrSWlzeFkyemtw
        SGFncHpBN1dBVkp0RzRodVVYQ0VNeGk0bEkyZmJtcWZiVmV3S3VDempFVXpCZwpP
        N3l5SlZTcm1ESG5zVlluU2xKdGJqZ2FJcGtFNUJvVDVhRXowM2loaG9VCi0tLSBI
        YlBMcWJGeVRYWHhMRHhBYWJPL21rb1JvQU5NcUtkdWV5YkhYWVArcjZnCp6ycpEW
        ITu5eBbaNZmHxpJ+Hzq2bxJ/4rmxxPdzKPn4sL9eoqTCIssIt9hfkfsIT8Wj15JO
        kJRCymrjnJ3W6pA=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-11T05:44:19Z"
  mac: ENC[AES256_GCM,data:m1HCn+SbJ2bdqBPNKFGaYr8eFJJ4xu0HT0X7SHyj9veYDzcqyOzPQXFw1QX/dlTZqIF/VTt/4QjXX7kp0tLrdOTwOXlS0yd/yZD3Yh930HVlMifmqp/XjU01lCS/gAz/PzT+zNmedY9pfHTlV5vAanrD1MkHYFX24UGmEaOpj5E=,iv:8yMD1ctG3QdsDBn+cG3beTbNCY4+2dxSEfZD2dyIhm8=,tag:kLpNYnX6unVTjnhPp/ZoGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
