---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stunner-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    template:
      engineVersion: v2
      data:
        secret: "{{ .secret }}"
        type: "ephemeral"
  dataFrom:
    - find:
        path: /stunner
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: stunner-auth
spec:
  updatePolicy: IfNotExists
  deletionPolicy: Delete
  secretStoreRefs:
    - name: infisical
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: pw
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: /stunner/secret
