# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: stunner-auth
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: matrix
stringData:
  type: ENC[AES256_GCM,data:O7uxUGikCoAv,iv:5uoaciOjzHpeNYCmLROGjF59L5BC2cymi7e2cFPpmz4=,tag:sOj90xNAdCcsJQ5Pc5HYwA==,type:str]
  secret: ENC[AES256_GCM,data:BzMWEN6ihJb6N3aMQHklrmbQEx6rjEyDEfNWE7kYwSeWoB6rOZoycOR0Km0G7/nsMszCkyoJS+eddXYNy6F6sA==,iv:zd/hFlkeWCpPxGE1FdcqruiFjhEo3dCTsi6QWvvtML4=,tag:LMkOjkgppD9Nz/NvXAe0LQ==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFMwanNRelVX
        RDhvSWw0MmFBMDJMZ252dksrMitnNUVSKzlWR1ozUm11MkNKT1VWcHVvZVpmNG5K
        U0lvMU1GdVFiQ1Jid0FxNjJ2NytnQUhxVEs4dWdoT1JRWTFvQk9jVm43NkpJWWNX
        ejhWOE9pQzA5SXZ1R0FuZVpZTjhZMGxjeTFGU0xKdDZEZXpVUU9zMk9KZy9jOWVZ
        bDFOclFVdkJqQkdCL0VlSnNxeUIvUmY2ZXlHNElDVHVOcXFPWndaZUNOdFNrV1I1
        R0M3L3FybVM4VGxIVDlnQ3pGbmVlVmRDS1dHTW1ubDJPTlRPSTJoeW5kczZzRnRx
        dkxPQmo4T3BxMlZDZUw0TlRhRnFNRlgyRzcxNW54RDNtekRlNDkxZnBDQkVLVGFp
        Y0JEYndqUFFRdUpoWHl5b3lVWjdFQnBYQ0grdW5rRWpOcThlZTdRbVNWWUF0dTF3
        YWN3ZHpldXdSWjdNYld0ZnZRUGdYa25hQ0l1bXJ5cUFxR0o1NEwzbXJvT2l3N2hv
        eXcxNUgvclJ2MjZaTDUraTdMTnZodW1kdUt4cWxkRTNMWEdnY2ljUU9zSXl3ZUx6
        NE5hNTNwb3lPVUJTYjIrQ004V2l5aGNLc1RSN2l5czdJTDJFYmxjdHVTWnhNbTUz
        QWwzSmZzYnlCaHg3aEdDU3JmUHVwUlNXbjF6WjdKZm5NWVQ3Z2JRamJYYU9oeFpU
        TzZVRktqME1iOWtQS3crdGx6NDhwUm5VMkdKWE9ITzhJRStBYXRNQ0U0eVkvbk9r
        QUloWmN1N3NDdko4VDVuL1hiMXJla3dKeldOVzNzRTBMZnpuWjhwYVNuNjcxalU1
        bTBUVlFLWURrQllEQnVCL2dZWHlVMDluMHB2dTNJMFdHQnhvTWpUSitHcnYzMXln
        L25qZTdLWU95NFd3NEQzbmozYjRwOHFXVk0vWW1veGhNM214dHpnWXd3N2VKT2Y1
        Tk1CaVJTWE5nU0xEZXZiazZHR0EzMzhkVW5tRFNWUllMUWpoVXJKb05vSmR5TnZ4
        WDR0ZDNVVUJZcGtuVnVYSWhMNmJnQmVBVjArNjFxcVFoL0ROdEVVYTY1TmY4SGxS
        aUpPbUVwM2NvNmlyN1NkdHNKVEFUZWNKRTNvbTlnTHRyeERDN1U2Mk5xVWNnTjBv
        cFJHNG5aTkZGU09VaXliR3RUd1dLM0ZIYTBaSWZRbVhqZ3B2TE9ZSGhRbTVZNGpP
        Z1ZvSEhINWZzVW9aaWhXMGpLRXRscXEweDVzb2JKVWQrUDdVTSsvYkM3bCtrcDlm
        b2dzMEhmR2xzNDVzWkpVQ0c1NC9ja29BWFVhN3ZqbWJ0ek45YWZ0Y2Y0S2hVVmdn
        cVhyamg1RERTelBLS0NGKzVoTCsveG1DaERlbUhrbkRlVjZZTWdaSVJDS1JkMVli
        OHZId0lodVpveGRkekJSVjhGQVB4WkJvNUtrN1BQL2JYQXg3R0dVQ3lqaXBqQ0cx
        ajZrY1REM3V4U00xdnpRdkF1clliTUtSclBYL2pkdlIwMWZUbGZDZnVMZ1F6dU0r
        Y0V1bEVrYXhudE4rSmhIZGkyZ09qYXJQL0s1SDBGVTFpOGorY1J1ZlJJbG15Z2wy
        MElrNVdRVXN3ZlBMcCswMytLSWRONjdwL1NNLzNoREtzYXNTSDdkY1Y4ai8vZm9W
        UFNSNFViV2ZGNXBYSU1lckZ2dlZsVHBrZDFoWlo1aC9QQmpMOHRGQ3UvNWtJekVv
        TWQxWmF3cW5pdzg2RHN1ZWlKNnE0OVJoaDlyQnhHNng2TlRvTkR3K09EUEU3SmZY
        aVp0ZzJ0cFNGOHpMYzQvbnNXclFJZFZJQmdwaGZLaTQrMk5lZFRkdjVDVWxQYUNp
        ZDI2bE9WOWNkWDY2SkhjZnJUTmhqY3BiZnBJcGxNU3BYTmJCeFdQSmFKUVVJUURS
        U0MwUi95RFVUTmJpR1NXN2RjZjhOVVNacWJEUWJibDdxWTU5UFlBODhLbm1MUQpO
        NzA4cEptdkhpekFmTmhZMHRmdGxCcmpvU0lJd1hyc2ZESTJtZDQ0eWhJCi0tLSBX
        MWFTbytKeVNjMFRETmlDL1ZQanZaWmo5WGhaV0ZjMk05U1FFcjgrY2E4CljBS/MM
        oivaKEF/11EI4n9og17WlSg6GRcxZxayqL5K1WjzkPnNYRK+lB8PfYebP5tLJI/Q
        kdrlTJwwdVfyqL0=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T14:57:26Z"
  mac: ENC[AES256_GCM,data:pHjuxtXsm+QIPvAPVMSEepiprr5dQgjvpBoD9uDi+Y7BikjHqrt4fs81WGENl/wkqGtyyPABlJTTX41tmMkLj0ea1aiJpvjnjHUB361uGcqUq4r9Q/06f0OW+P59EnfC7r2Ezw2O5hDy+NqFRcSl0d3pfg6tN62BPtuHsjk3ddM=,iv:g5YiamG/pFzpAmOA/N6snreRUPcQ/eu5f1eLyof7YVY=,tag:v02WF3Y6a0tkSL73Gm9Zvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
