---
apiVersion: v1
kind: Service
metadata:
  annotations:
    stunner.l7mp.io/enable-mixed-protocol-lb: "true"
    stunner.l7mp.io/related-gateway-name: network/stunner
    stunner.l7mp.io/service-type: ClusterIP
  labels:
    stunner.l7mp.io/owned-by: stunner
    stunner.l7mp.io/related-gateway-name: stunner
    stunner.l7mp.io/related-gateway-namespace: network
  name: stunner
  namespace: network
  ownerReferences:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      name: stunner
      uid: d5d9b44b-19f7-4838-b408-468d05280e40
spec:
  internalTrafficPolicy: Cluster
  ipFamilies: [IPv4]
  ipFamilyPolicy: SingleStack
  ports:
    - name: tls
      port: 5349
      protocol: TCP
      targetPort: 5349
    - name: udp
      port: 3478
      protocol: UDP
      targetPort: 3478
  selector:
    app: stunner
    stunner.l7mp.io/related-gateway-name: stunner
    stunner.l7mp.io/related-gateway-namespace: network
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
