apiVersion: v1
kind: Secret
metadata:
  name: mautrix-discord
stringData:
  as_token: ENC[AES256_GCM,data:3Xo9HThOnAmigcSaZ94EIcKIGi7wEu+ejU2+UwDlmlV9b6MzGko/KViUUZZ2OmqzDyNjX+GYSOkXIT1x5+i6Rg==,iv:WRV2edlnjGdjtHCGurcrTt++d0L6G0x+IW30ZynfXsc=,tag:DG1sJ1zKMK9i6HIJvGv2/Q==,type:str]
  hs_token: ENC[AES256_GCM,data:zlxHjf+6FwZ0U3Nilfc+SvT6F0z6gtPNjasze3maBfBjG6CrY1n2yn1RYNi3Beh1bbH/cg1a+SZP162Q/9N3lw==,iv:PAuLKLBBPh1g0xbsL3KoBBJJqqfCuqOAxBKHkYNQP44=,tag:W5s8rJVpa64p9T5gPU9rNQ==,type:str]
  avatar_proxy_key: ENC[AES256_GCM,data:GW0ceuxj35mCpmy6mSXY2ZCX8TX64PjrPZ2051c/UBA=,iv:YK1V0DIzlAMUzh9n5hdhKczX5EjzkBXwzRwYe4pXANc=,tag:pk7tfSE6a2A7sJ1p0gdt8w==,type:str]
  server_key: ENC[AES256_GCM,data:0RfpgI1kygAK7ox0geunnZ/4dn2NvbK/0+4Nd098SeRR7sCKKZFK9XswAOMMExDMK76a4bFdnWtSIQ==,iv:IMOvOIFSTGSIbrM2ZCWmx1TgO2iYtRz7hbWnRdA/l7g=,tag:RtGsVpMFVdGIFNSDPB0l2A==,type:str]
  double_puppet_token: ENC[AES256_GCM,data:YKSkf1qztU4kvKSZ9fGsBzzRbVeNf2uoYwr8rpUCIgU8JXZ4Xv/xyJOfX8yb7NlzKWkz9tZ3heq1ze9xI+c6YoPdB2wChxSD96l0MvQ2pdkVZ6/Hd3ROadbmpcl3YD1MEs57pGEl6UF84G5MCMJvm+qNwWeTxjgg46IEZXshef4=,iv:Ii+iencvbYx8nemo2AExzs4cKsNK/FH6uWQx09JSqXQ=,tag:DAW3cJdkckyyhAd6NAmx+Q==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDBzcllUK3Ju
        NXQ5Y2RFSi93Q3R4Vm9od1RJaEtNUEU1dGk4dzNQOFpJZGdwMUwvb3h4ZnB6ZEh2
        a21oMC9vN2tsL29RQ25aY3hoajYrdFl1V3RqRS9Pd2dwT0NPdmx5cEJVb0QxNTFy
        SlBvalVvQnhxNnJMRmgrNUUvUlQ2aGZJcXplR1RLQWJHcGtWWi9vZ09mbW9BaUVG
        YzI2ZytLTWFDWTROMmdHbVQ3KzZ3NFNxc3BEeUhadExzNWp4VnlMTk5VNFprc1dN
        c2U5UTMvMERaU1VmYUkrT2I3UWl3Qy85Sk5sMExDMjRsL1R1bnpLSWVqdnd1eUhJ
        OC9BU3I2cmduRVZwMmU5WGFSck1nVnQ5L2dLWUptYWZYYjVualBtU0V1dktJTzBN
        c3RFUFlpZ1dSNlMzYWYrak5McDY1UVJpVXdmWWpoZk1QN1F6alo1KzkvSGs5ODVr
        UlpMSzh6Y0VOWFN1bTdyTFlDM1BGd2l5czRCeXNtYUI3a1prREdRV1NXYnJNQ2d1
        V1Y4SmFMOE5tb3RtWUNuTS8xNGZCUnBJMlhTZWdtTTVIdXpyY0lnMnFxK01ZSHNw
        dmpwb0FtMUtKbnlZMHh6R2o4eEM4TFFodWt2ellsTEVWZkxlQk8vSUpCRTBoZmtX
        TGVoWE5uTW84bmRTZjhQU2ZOaG1DWU5KeGE5ak45MXgvUlBTM0lKRWFXY2h0VmVB
        QmdHbmlGM05Cc0ZXdXBlRmd0Kys2SkxDd2ZOZDQ2ZTNZazZWaVJsZG54aDFVdXpZ
        RTE5MEZhbTViVmgvWGNySmk4VHRuQTRxY0FUN082MDlhelBJRXM5VzIzQ0RNeDJI
        L295SU1ib3ZKTkhPc1BzR2xKWVRiLzJZcFRXQzRzZDRlSjBvMzdOa0taN2ZqM3pj
        L292V1BRc1VydVVWNVVNL0czWnFULzBzYUZDMUlGOXd2eCtGbDZYeUFJc2hYOTdX
        NkhRRHd4czlVbmFmMHpuUWZDampQT3BMUnlSY3pnaGcweVFhZnVNQ0hFWmp3OVNw
        Zk9rbUhWN2htaFdQWXEvSWJ6WXRuWUlmWW9DblJMYm9PUWF0RDl2ZSsramc0bFcx
        b0tlcWhqODVCaXM2dkhGYzBmSHZ2b0laR1EvWkVyQjFOR2pBU0FmRW5zYXJCbU1q
        clRocnRDK2YwU2hFcTRXekNrYVV2cHVZTDdLSmlZSkREQjI1OTIraW9OL1NtM1NI
        ZTIybXc3dmVsa1E5clZsTnRXMWUzdXhFaElRQzRoTURRVEhpcC9qUUMzRFF2T2JF
        OXBUR2wyV1g5TW1UVHZZOHFmSEp3QXhJZDZOT0kxRTBmcHVIYVBjSWVTcEhnSzkz
        bDBKNHJZbDl2MEswajdJSXZYS1kzNXpjZ0MySFYvZ3pKay9MVVNUbG1ZZTlqaWR6
        aW9ONzQxT1JHVFhDZ0lYelIxcUxJUEdiSFU5YTdGQnhtRHgxWnRyUzk1QkxPWld1
        NzRoYTgwb3ZPOUxuSkg3Rzh4NkcyZEh4VkVMT2w1T1lZUnpiZG9aOG9FV3RaeWcz
        TjBFY21lWkFYWk9VTTdDdVZvM1pJL2UrOHVIU0F6QTJqZ2xsS1NoV00xTzZFaG1I
        UnVKQzRTR2E4dlcxeDFOM2liQklnWnRyN2diZTlLcHN1VkdrLzJqQ1ZUTEFjSzdN
        VUxnc2tRMU5XWUQ2NlZLUkoyTUNVUXhaQnQwOTlCVU9VbC95d2hDMHFPSkVvbE94
        bHdIcUlPTjlDbExnSHlYSVl4V3lkV0NCdDRKc3gwTWRJYTBlU3BDRXlPYXI5elM2
        d0p3QVEyRENEa0pFSllDUjZRb08rQlNscTdVcjQ3MkV5ZThVejZpbW9CMENoN1dw
        dzJvYWhRVHAxQlRzcytTU1ArYzhyWVl1bFJCZGFQNnFsZUtucFhONzZBQWJCdUM2
        SmJPbUN2Q2lZVUZwcFVULzUvUmNHMldpaTFMMjZVbVJWQ2ZCZzl0ckNMajFLUQpq
        NXJaaThVV3NWckZ1eGE5c1VHUUY0UVRyMmVpOUlTU2xTdUFyY2tWK0VFCi0tLSB5
        cENuejI5WWluRXNUM1o1T0dZNDRDSytxNk9UZkhieE9PcERVWWJqUnkwCvAMZ8wV
        i6uRVbZjZmodDJzeAGfXZXv3JmS5zHBJ1sX0letESZ6n5sNL4xoWgUGmMqGwoI9v
        emvNz4krmpp2y3k=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-19T20:49:29Z"
  mac: ENC[AES256_GCM,data:mJktD37zcunICX5zDMES0J+p3usb5JvmpFaKbltbHFek1Z20E2cF7tD3H/pa+hb22HrQtB9APT3heyvBTYghqFOGf1nQWSmMn5wtCHnycyavPQlrbr7kN8BnlvYWZkqrofLdpUvrzyRjeNc+VeGGx7LPc5LsxuKwnqz3rynVK5A=,iv:u5eBAKczif07XqWQ/8HHzGrv2M4ylIPpK64+G1IIBxY=,tag:JUVepEIapcIuNF4N0dTqSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
