apiVersion: v1
kind: Secret
metadata:
  name: heisenbridge
stringData:
  as_token: ENC[AES256_GCM,data:NEsQ+EpSuSaQFJkUwlGUi7LUF4V0ora2XfggWPb/JdrMKNUhLUN+2MY3Shvjx2DGuPr06v/HmT13wtwN+x4T3g==,iv:AM844OQIIEzhZiaPg3lwsMnP1SeEi2XhOBiRAE8eziE=,tag:WwbinEMFMhrBLOwVzLHucA==,type:str]
  hs_token: ENC[AES256_GCM,data:Hko6Xh8UlaBUN8xR0yloV820LUXxFqLh/8FUca3GxvJpu17fCfZIvIOrDPU70BDumzIud74DUAJ6kL+Y+ocbRA==,iv:CzxsOmIYz1Uu3mfGcMtw0Qcpe6kRqHBWPHjWGrfp91o=,tag:Qr2zUFxD5svGtfj9DwN0Yg==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDk1anhVMTRz
        S3NjS214OC9jZEJuTVBjOVhYV3BDb3p5UDVlSlhhSE9QQXVmK3hVc1hseFRUL29P
        SytOOXFVVnoySGtaN1FlT2h5Q1daZTFiR3ErQ0RRL3ZlZWNpbFRRUm12aEUrdENT
        bG53dEZ6WFREb3pXSThYVzIwOWczYkhSWDZ3UmtIWmtBQW5uTVhKZGs2Vk5FNXpS
        V0dqVVRaVjd0eGRFQktVaU55TmI4Q04xVFlRUUJtamllWmowUVp0bFhxL0VkTEFv
        cFJGWlBtby9WUGsvZWRBK0pzQ3lRNTBtdWJkeng5eUQ5VzZWdDl1MkROT0JKNmcv
        T2hDc21hS3RCM0J5TG96c0RWcVc1S0I5N2UyaDJIQjR2SGlaT252VWdKYmwyaXll
        SjVhSTVTd3kvU1d5UUNVbnpiMzFLRVNVTHlXaWJYbVl0QjFVYnd4Y1hNdHJDbGZY
        SlJlb09Ob1BqR3cwYUs5cCtGcHVNWE5xSVZrYmxhWGMwN3pwSXNhNHBNYVJiNXpz
        bGxLbExNSk8zRDdHbmdzTXAxU1RxRDkwc2lNTmpzTkF1T2lNSkRIYjRkSmRkT2ZX
        RWhwRzFJWFhwSGwxUDZBeGk1Uyt3QjhiZ0x0bnl4K2d0YnpVenRjZG9yQ1JEa1Qr
        UjdSb1kxdDhRR0hBS3RLU21PWkZPOGIza3FkL1o4aHhXb0ZHbWZLYWFaK3BtNmdG
        NUp5bkM3c0VVYysxZlpkMzNJQzNFNCtBTHllRVdSRlZLRXFWSTJlWENIYzhLc2Nh
        em94UVZ0a0lHUzE1Um9lVEE5TWtCY0taVUY5NHdEODVLUC9iblRCQ2wxSVYxVUxH
        c3BWcUtZUTZlTTZsQjZmcXZUT3hHTWQwNk85ODVybzNxY0xlSjdYV0gzMUFDbGRR
        ZUgrZ2MrcWVuMXdYS3hlQ3VteEIvcjJ1MmRacDIzSDlvT1BDeVc0eUlYQ0g2ZG5O
        Z0U3aEMrQkVGRHBZcWQzTGxndWdXWU5RVW1VdG9zbThJM1ZtYm9mdnVpU093RlRB
        QmRwWFRVU0EyTFdUYU9YRVA4cmhiUGhPTE5ES0lxVXJZY1AwVkJRSzlzbEVQK0ty
        L09rN05DMndXakNlTFZ4UUNMRnN1b2V1eE1jazZDbDR4YzFXNUpINUVsN3IvLzdV
        MUxkSUwzM01ZNWNaQ2V0cy92Ky9sR1FzWVQvbXUxcFphYUduZHRSSTFxakNhY25r
        MjVYNEoxdHpFODlOM0lmaHRsODg2MCsrOWNvcXVocDFSZ2xiTXYvYVhQVWRLVDVn
        Rnp4Vld3cEJSNEgzSVRMQkNzYm43R0tMK0pUYmlHR2pRVE5WcEorZXg2QTZrd3NQ
        K3R1aS9FMnhiU2NHaW4vUU9US0NROHVBRkR1UDZxVUZ0VGVzYVhOV3h0bTFtcVRl
        NXk0ajFEQ3RHeFdOdnRpaCtOR2RNby9HR2VPa3hVekNlOFJzTGMxTjRGTlo2Slpu
        ODhMTnNoZUNxVDFQK08vUlFmZjJsNFNvVTlXQitUMlBGQ1grRHkzdXdUMklLdlZJ
        VjRWSEgwTVhaczVzeWdkUGJDM2pmMm1wNEFDaHNYZXljWi9PM1VJb3FOQ0pQbW5F
        dy9IRFJxOHAwSW1WQ0QyMUg4bndlYjE2ZDMxT255alFsb3pqNGZnL3FzeVNuTS9y
        dEtCNmhQSjdaK3NjY0NCWnNKejIvUVlHKy9Hd2o1TFhLRVNWcWpaZFBpUHdyTVpj
        cGNIM1ZxRVJ0aTJaTnc4cnljclhhRnlvZEdjUnBhaUNzWVNkM2pWTzhON3R2WGNB
        N1R1bFpqRUs2YmQycWdxUXA3UHowaUZqTWdSUm1FL2Erb1lEMkFmUGhnQ01aNmZI
        TUJCV1J2b2t1TVF4MnhKYWRWbWtwYUtUbE9rUG1veHVTV1Y4bzFSSitzMUs0Skps
        Yk9rU2MzZzk2c2JSSXF4dlcrSDhLb3F3bExLdGxCVGtnS2NzbVljMjlYTUJNdwpy
        SWNFTk1RTnZMc2JOY1B1UWkrb2prMFJFQ295TE4vbmRBRzgySEFyMXV3Ci0tLSB6
        bnk0QWtITldmcnp1eTJLSGVYeXRVTVl5Qy9hSlZFR245anpaaEMxazljCg7d1Nc8
        C4pjU/m9mbs78GECCrUO0cY+gYqZU5p++t3pzPjeWDuMFsnQyHJBBAe08RMVqB6R
        nzT7JYmkJLpJ0ss=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-07T20:46:49Z"
  mac: ENC[AES256_GCM,data:hTxE0H7CerCFOogxDI8jDZZNvZbxDzvw63ACCyh89TWXB2mJBe3ZP9pqkwDN3iITJh7JP0Bhn1YvOeHfcHBky+ozIoi5/RX3srAScEO561XTLnwrwiA5QXf5DE3eABhZa4vyMt3c9e7lDXjHcN1Jr/E+EUnybHy3mSqtiioH1vk=,iv:9kAa9CKWn951xmRMJz5Y6XpiMNZG/mFYjYikJaD3jtE=,tag:IPa4Y7iLU6QDkvVWrxrZ/Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
