---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./rssflow/ks.yaml
patches:
  - target:
      kind: Namespace
    patch: |-
      - op: add
        path: /metadata/annotations/instrumentation.opentelemetry.io~1inject-sdk
        value: observability/instrumentation
