---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: palworld
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.1.0
  url: oci://ghcr.io/m00nwtchr/charts/palworld
  # verify:
  #   matchOIDCIdentity:
  #     - issuer: ^https://token.actions.githubusercontent.com$
  #       subject: ^https://github.com/m00nwtchr/agones-palworld.*$
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app palworld
  namespace: &namespace games
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 15m
  values:
    palworld:
      image:
        repository: ghcr.io/pocketpairjp/palserver
        tag: v1.0.2.101103@sha256:09343cac3d92b997634f034ade4ce702388e156ec726668c85ad3bc47faa33f4
        pullPolicy: IfNotPresent
      env:
        PALWORLD_SERVER_NAME: "m00n's Palworld Server"
        PALWORLD_ALLOW_GLOBAL_PALBOX_IMPORT: "True"
        PALWORLD_BASE_CAMP_WORKER_MAX_NUM: "30"
      envFrom:
        - secretRef:
            name: *app

    pvc:
      existingClaim: *app

    service:
      type: LoadBalancer
      # clusterIP: None
