---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./palworld-chart-oci.yaml
  - ./helmrelease.yaml
  - ./listenerset.yaml
  - ./udproute.yaml
configMapGenerator:
  - name: palworld-config
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
    files:
      - resources/patch-palworld-settings.sh
configurations:
  - ./resources/kustomizeconfig.yaml
