[project]
name = "homelab-cluster"
revision = "1.0"

# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]
# DATABASE_URL = { description = "Database connection string", required = true }

# [profiles.development]
# Development profile inherits all secrets from default profile
# Only define secrets here that need different values or settings than default
# DATABASE_URL = { default = "sqlite:///dev.db" }
#
# New secrets
# REDIS_URL = { description = "Redis connection URL for caching", required = false, default = "redis://localhost:6379" }

KGUARDIAN_MCP_TOKEN = { description = "Token for the kguardian MCP server", required = false, ref = { item = "/kguardian/MCP_TOKEN" } }

[providers.infisical]
uri = "infisical://infisical.m00nlit.dev/f369ed08-4aa0-4f70-b2be-98dbd6c7d9d1?env=prod"

[providers.infisical.credentials]
client_id = "keyring"
client_secret = "keyring"
