[project]
name = "homelab-cluster"
revision = "1.0"

# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]

# [profiles.development]
KGUARDIAN_MCP_TOKEN = { description = "Token for the kguardian MCP server", required = false }

[providers.infisical]
uri = "infisical://infisical.m00nlit.dev/f369ed08-4aa0-4f70-b2be-98dbd6c7d9d1?env=prod"

[providers.infisical.credentials]
client_id = "keyring"
client_secret = "keyring"
