wordpressSkipInstall: ENC[AES256_GCM,data:lLzshw==,iv:nMryf+0yRZ/JuVJYhhaSmpIyvYoN4DKVfB0cdJBgHzk=,tag:Wa0SrpJCvPghEBVfRnfSTg==,type:bool]
overrideDatabaseSettings: ENC[AES256_GCM,data:k2NSoA==,iv:er5NO3lDniLUrsW3toVjICs0ju82lBJCnWjGxRRTEpI=,tag:+TU7hRQEvEK/IcsrTnYHXw==,type:bool]
mariadb:
  auth:
    rootPassword: ENC[AES256_GCM,data:psugavwO3foy7z4tnMZulw==,iv:43LK1IGLsxEsb9Tu2EyociCUYTBDShAWeUX+X9MXnu4=,tag:eIF399N43bhJcsRsYl6CIw==,type:str]
  enabled: ENC[AES256_GCM,data:4D6HCA==,iv:ba//J4AtDZSfA7XiORs+ta6BjIrhvFRXnh7GLUqfgNw=,tag:ZaulIhE2g3weldTD2kVqlA==,type:bool]
service:
  type: ENC[AES256_GCM,data:pqGPGYhqZQPU,iv:iHsY2/ysvwXLHX9iaT4vhbD/bbtuROe917VJflo76GE=,tag:d6IWcU0pZCYX+dMZoqesYg==,type:str]
persistence:
  existingClaim: ENC[AES256_GCM,data:C6jHrAya8ssY,iv:i8WZ3+O5umOMs7BpqBru15tLsr3UmklFCslTh+7gc08=,tag:wI46tn7UfLmRod2LQGjMhw==,type:str]
networkPolicy:
  enabled: ENC[AES256_GCM,data:PF3TRHM=,iv:86AXTKkb7+TvKyIvqgNff90uAGwOj4kITI2qbOE+MUI=,tag:75kQiClRRkN7IM6cK5Dctg==,type:bool]
#ENC[AES256_GCM,data:ZJ215c8PcCg=,iv:bMxsuo28put4DFIyt1MnQYR6X7UrglQYRI/PLiBC2/o=,tag:Mhz0Q/YIBfqGGWycRe6z+Q==,type:comment]
#ENC[AES256_GCM,data:lIWvE1q1PbWen2UFERtt3sjgK1/eSECO0Vd+fuc/yg==,iv:Vk69N5QmlKKeKnLDEPy8+Ba9xeMyJISch9igJm29MLY=,tag:MHU4hrPOw18XPz+xalZt8g==,type:comment]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGdrenBzRzJD
        VlpPemt5alpOTjh5MG1RVU1aK3lXTzBXZTVFK2kwODA3SHA4MW5CSTB1WDVIU3gr
        QkFBR21TSm5tTy9YVnpzK2c2ZkFLcFc4aU5GUE42cEdGMW1hcEFIdWtpWjFPZ1N6
        dCszYjJNUEp5eWNDTThEYkhieXFDZC84QmlQOTdkRzV0YmQ1dE9pMnRBTFdobVpF
        cFQyZnhpRDd2Q1JFbkh2WmRCYlN5WkFNbTNaUmU4OVliRG5qb0Y1UGs3YXJBWUl5
        aFVaL3ZEL1lkWUpaMXBCeEttVjB3Kzh1V3RpVUd0aHh3SGVkYjd3TTc1QUx3aGdi
        SXFoRmNYWm05UXZhRmhmOVcwcTBkaGJYNnQxNjlRbGdra29JNi90bGMvTXpyWFZi
        bFV4b2w0c3JSRE5sMHpabUxyNklQcXVYR0w2U0ZKdlY5UW1rNlppeWNHSEYweXZT
        dmlXZXE0STBsdkdyeGwxQ1dmVzkwd2U2c0lOT0QyMmp1RysyR0JWMHFWcjY1TFF4
        U0c3WkxRaVZtdUdPZy8xcmIwOExYRHZucm9UUGkyRVAvQmhzNFphajYyeURMbk00
        VEdwVGoxNnhWa1BqdjNORGFYa0tKVjM0L082VEtGOHJlU2RWKy83TkF1elBOSVhW
        N0hCbHpsQ1RjdXFjOTgyMjZUdDVObHNKdzRGaXE4bnJFa0MvOVBwZnJoZ2dpWldF
        ZHVqZWhoOTJWZmpPL21uVG1oZjNlclJWaWVVTVpIVzRoQlZwMlBrNTR0SFB6Z0Z6
        Wmw0eWVIVmU0dlovMytNNE5CcTZnMzJheG5XdU9BNllUdFhXN3NZaDBOUDFza3I2
        dTErQys5YVNCNWQ4TVUwREhReWk2Y3c4ZHgxVUFESW0yNkZxSWlvOFYxcTVKY2F3
        VG41Y01XZ2FvVlN4K0tubWxRYU5rRkdoYWo3TkgybzhXVElkN0VZbHcvRjdpMmpV
        ZjNZTnJsUjhiUFNoU0ZoQTVxSHhZdWdqa0VnSzBUZWpyVDc0R3UvSnZoMHFlbUNz
        UmVwQ21NdDQ4Qmd0cmFvTUhVNzJSWUJ0d3lYdzcrZDFocE96K1BoaEFJRHhVbHdW
        d0tBSE11Z1pZMWpsOUhEYm9ZK25DM2lUbmtZMWVDMGY3UUZ2UGRWRS94S1hFeDFY
        K3NERUpmSGVxU0xRR3g0aFNsZ1BHOTdnQVJOQUlZZnM5TFpmcTRyMUhXK1FjRFp4
        SGUzbHYvMHY5MGhiNG9JM0kvS2thOHBBUHpYTG82QWRuM0tVMnRaSnlSOUtseXlW
        VkczR3pLcEJtZTRMa01lMk1OWWpOcnBHOUpUU3c4WE5icGh3OUVHU3E2ai9tYWI1
        S1Zqa0N6dWVicXVueG5JaUVXdTRDNjdvbGtiU0VZYzNTQ3oyRWtxZTM0OGdBN2Vy
        U0Yxa3NnR2ExRnNqRXpZaVhIdDh0MzJKVG56V3ZIVnZKbWlJVDlOMi9BNGFWaitj
        aW1BRnIrc2oySkpaOW02c09oTzBDVFROSWlhTTNMNENEdHBoTi9adysvOTJnSXJ2
        QkVqNnk1YjZwWlY0UHd4dHpEUSsxb2tFWjZQRjBhbThiUVJYdHFnN2J0QWtpbFpD
        WWdlemYrWTduUVk2Nm1pWTQrZUdMaTFqTGtJUElJZW1hUTFRMSt1clA5Q3QyYzIz
        bGc1VEVhRUlhbDZQMHI3bnAzZkR1OCtPV0lzVkpkaUtDRy9MMU1RK3JsZjA1MEt4
        OWNpSEovWVhYeHl4L2NtbVozdkV6K2ZNOXNjQVBTaEkrbXFvOW5nTldSM3kvdjlK
        Y3RsMTZySGt5d25JdEF0RnU4RG8wdzN2MDFxZXJOOTZFWDNMM3pWdHN3Z3dpWEI4
        Y2ZZdEw2enkzMGx6SXFHQThnZmdBSXdyamlTUS9DV1VxTzFkdkxmcEZpa3NyNHFi
        bVF3S29qV2VzL0Z2TlpzMS9DWitZQm1pRC9GcUlWN0JlQXgwYUd4WFJKZEpIQQpW
        MHJRZzgrMnB2RWRkUnhZRDdJMUtzdlpuUVB5SDQvZHZzSTFybGhmQ25rCi0tLSBo
        VVdEQmJPZG55T0x4N25zSWlnUVlCSXg4U1Q5azluSWE2YkNDTGFBNHVBCtXHWG17
        p7Ff2uxkgSFhB35wxiuGD+GYQZ1Tq8LVCeiq5/sAtXwUV62tl0TWWDHMq/HokcPl
        ljE2gB+UbvHBtmQ=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T20:14:31Z"
  mac: ENC[AES256_GCM,data:e/lnqEoIYKhstKK+WmASb/EXHLG8Z5Qiv1mmykz9PlP/ccFj0QanQfGWPJl7t/ktfim/PuaXHrayXSqkT/oi/qUgA2ypEQXn49Jz9KU59t3KwAjI04bnTr3AGEb3ioAyNHj8Vz4GC+6ljg7srzqLWN12rzkJyk+jNkn4l3H5z7E=,iv:wXHx9NRkVYiL6tvz4x6IEXdLbEuHggb/XuIvmjc1MAg=,tag:B5f8sjKqrVYsGS0g2baWxQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
