# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: geoipupdate
stringData:
  GEOIPUPDATE_ACCOUNT_ID: ENC[AES256_GCM,data:ZIXfvlB+NA==,iv:+FgHLuoYOinK99PsV/q8wfQVELwsXV/JVtSPn1RFRhE=,tag:R4fkzS0GEPAwL4q5MMJkdw==,type:str]
  GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:HHfvUGb9v3vvBJ7e1vtEeu+LH9cfPZkGyice5FhtxC69TX5fyKKtqQ==,iv:XUdqRiD9T/iLuHmTrbslEmGYWk3zChHQ0vT0W0+/C+A=,tag:W+S76BQOzrMab6wzrI0/jQ==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG12TmZjSmRs
        UVhLengxL0txcTBQZWdrMHNRYWU2citJY3QzQ2Z6SjNyT0hVQlA2UCtpMFRvZ3JR
        SURueVBDRDZLY2FyVHNhN2orZENncVpabHJkYWdPRkQxaWFCL1dKUWNZRE8vVFlw
        Nm1xUy9xL3ZTK1VBdUlZVFNwaktwQk5yaXU5SlRkTERnYWhMYjlkUG9SUFE4TU1Q
        SDdzN1owREtPVHNndFNGNU5EdDV4cldldUFSUU9JNnViVVBBdXhHMjBlOEs1SVhI
        eERYVW52QVN5RlJJUFlQaS9YaGppZTdyWjBVMW52SnpLUjBhcG1ROXI0aFJjajcr
        MERsdTZGRHBwRU9teW5VcGRIek9PODdTSnE3M01wNEtVa1dqZys1R0l0S3NTKzJV
        S0pyaFdDK0laQSs0amFHMTdJN1hpOVBQcDlVa3NXZ3VUSEVlL1dUZzdFNHRkSEsr
        RFhKbEpHZ0VLU2VEY0ZIM0xNVzFwY2pDMlVQbW1DNVQ2bTl3ZTB2a3RlOExlRVlv
        ZHJhRk1Gc2pJeU94LzRZWnRldjJjTHZJMEl6RFlkODRZTThCY0VmTGsweHZLb01K
        MVNWY0twNTBtREdVNzVVMnFNU0U4alZQTDNjTk9rTy9GNXpETXQvL0l4eE02WklE
        VXdNV0UzOXZXdHZSL1pXV3hZTWwxRWpkU1UzdjZhdVk0V1AxcVRTWmZGWGFHbGEv
        aWFRWXZnbUtyOVF2VUJBZ2pjaDNUNmYxNGhtc0dBb1ZLd2I5RnNrVnI5dklQaklz
        YjVSQmRXSkduODFRVWZHUDFxOGwvWk1UaHh3S2IxR3REWmd5K1FWakkvVVgrYXBI
        UUZmcWZIK0pjbjExSjh5L1JRaURTUkRmanZJcEdhaVlEYXk4OFdYTFZkbWZTSGhn
        R05Qb0p5TS9mR1JNdTcrVFl1Y0pFMlNDNTJYSVpWc3JEWmZ1ZjM3dnFTdjlSYk1L
        WGl2dFovWlRVOEplZEc0Rnh3RnhYQzBzSzgybmh4OEhRVXB2ZFlSVTNlcFlLZnJs
        VkxtQmJkVy82b1lmOFJpbDRtbDZNVmJyQ3FrbGdIOTlJTnI0NnU5V2R4enpaaG4w
        YjA3cXhHdzdJY0p1R2tCcUF3QTVzUGVaWG9YSXZlUnNiSjJtMVRMcWhLTUpmSWg5
        d0ErTVJldlQ1c2E0TVhnZDhzdWlveXFVcWxRaFhXNU4xcWk1b0g5Ylg5ejVpUDFR
        TDlKTjBkTGZpZXlkRzZuL2xwSEplQktwRVpwYytZN2c5L0Fod3JsYk4wTVpWZ1Yz
        MGcrazV4TTJVakI2VlNsTjVydTArSFFNUHlNY2k5NmlpRHozcUxzZmtLMWczd2dv
        dVFDYzVsM05Td09tR3hoQlNyMEFKSlJKcFAxYVo0U3lPdy83YW40YWpVRk1qWVEw
        eXk0OXNtY2pzSjk4S05ZSDNCNWExTTJCaWY4T1lkTGgzazlQWGdiNG5ZYkEzTVRX
        bFQ0cFhHSFdOb0pXSVZzcVVQVlovL2gxN1EzUkdnRTIwcnI4dUJUek4rNTQ4QTJF
        U1NXMHF6aVJXMXBIQmtyakd2WjJCZ2krTnBWNzR4WERNeFhRQ0RGUXV6a21ZcU4x
        bENFK28ybjZXRXB1ekZBckI4TTZnbit6b1VTNWRzZU0xT1d0NlZoNG51NGZxMTVD
        bjFJZUd3Qkgvd1djdG4rRDV3eU8vN0VEMVhZVUNqcjQ0WjgxVTRIN1pzVlNmY0hB
        MWliY2FIdUliSjBOQjhPZ2c2dEhqWTNjdnBFVDZaNUJUZnBwR2JhdENJZllLNVJD
        RmlUbnlHRjVneUkyclNMRmpQVDdpcXVTaGFKdjJESHdWbWoyUDd2aStRRmxLY0xi
        TUxlVlZxYmkxak1sSzg0ZGhGYzE5Q2EzVEVENnlYVVJRb2EwR0tjTTl1RVMxeUE5
        c01wWkJKenFUU3JHUUIxZUswN2I2ZjBJRGgrcG10VFRoNnVTc3QzczVtWHZPZwph
        aVFUOUJ2TWx2OEJ3NjVBWWRsWE1QRE9DRTBkTnlZWTFGWjZsUmFXVnFVCi0tLSBo
        OEdVbDZuSGhsaDMwcXFDOXVUVW1SNytTV1libEpKejF5NkFIWkdqellFCn2Yl1Pu
        7vFLS1Cdl1nVjocLclk0tfgSgw1WLBBgkqMjPQzhG/aj25tT7JCeqfreiJzW/+L/
        Qw82Zq0IM97T8Go=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T02:17:26Z"
  mac: ENC[AES256_GCM,data:37EPiiqzV7EqYRR1EpOVAzj1sKIg2eI2GM+kTE93afW4AzJiShiIYrMyGZ84evy8XYgq1Z+P/4Y+7CHg1alnNQGc811gx6nVeF+7uMgKhaJ4JRw3BdNN7JBj8sZQDI9fiC7nbj7PDsBKMEjJyhAao/9P0qXA4g7xUPWQCXio1Dk=,iv:6rsKhN+atDqJ9R9xREBPbKmv/fgV5cA69g8dpFCyBfI=,tag:3rlT1sfRDKIYEELxxe9cJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
