# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: geoipupdate
stringData:
  GEOIPUPDATE_ACCOUNT_ID: ENC[AES256_GCM,data:ZIXfvlB+NA==,iv:+FgHLuoYOinK99PsV/q8wfQVELwsXV/JVtSPn1RFRhE=,tag:R4fkzS0GEPAwL4q5MMJkdw==,type:str]
  GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:CYzz6roFmwfD0iS9CAhktitdux71,iv:TMpje8Km9ESVynawmvx/Kw5UFqYu84DQq4hPn6Z3Ohc=,tag:EuZvn2iL3ZMJaR4nup5UDg==,type:str]
sops:
  age:
    - recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbS9hWUVRQW90TUFtTk1V
        NzZoTTQ4SU5VMDBjdGMxK1Y1MjJYRjZXaDBRCmdtOFcxcmNHa2ZkMXpROHFaUk43
        TjVxOU1pUXU2WGUvYWtCZlQ1SFBFUjQKLS0tIHJZdXp5Si9GNEJVTUprRlRFVmd5
        QWMwYTU2akpGQmVVQ2dJU3Y1WXVzNmsK0bmMNwR+22nduG1LyGId00uODGtCpQM0
        BZ8ZQMDIAm0MclZ8LWAGrbI/Uh4+RDsXn8GsQh97ZP8bqaFrazB1Hg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T02:16:28Z"
  mac: ENC[AES256_GCM,data:VHwqIjWyy2ymp/u4hjWsUa4ZOAmKzalPxQfbDtgszIbVZQYBq+rkEceJJiunn1DwiW2WjMGYDFvv1GL/TP4oVo65um4WM/xiZFSl+/fmVsSHgdsqBhcceA9IX+r67SUYoV1PqKMBf6g/75GOrt750nAgP/PKzltuT59QJ3vTPP0=,iv:sKjlJWpkBksKyl4SOvSc+raKsd0H61i2I+w22hgQU0c=,tag:ZmQe9B7nift8UX7ycXYGJg==,type:str]
  pgp:
    - created_at: "2026-04-04T17:16:01Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DC0EwVK2S0BUSAQdArExEnU5Wkr22wX2rloU1tLDX9AoDGtc9jC0ss68B0Xww
        QMm6Y3srMPzp1ZbjzTP7uetQ2f+Ng/lxGHr4T97f5j0VqxvPaErArXNeX7N5kmsB
        0l4BJDSvyN6E67QJLW5cuZTbduiSvL7b8/8esmzWfeJ4TQ+y+DGXmmzsizYZulUc
        u8VqnOJ8OZZqImCh0KZRRntTE2B+qdr412UIjgr2HEj2lU+sOHhD/kRKqc2H/sAq
        =ApnE
        -----END PGP MESSAGE-----
      fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
