---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app opencloud
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext: &podCtx
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image: &image
              repository: opencloudeu/opencloud-rolling
              tag: 7.3.0@sha256:f988f14779cbfe26dec78ea3fc2492ae063fe14a069857dd2d5a397a927fc361
            command:
              ["/bin/sh", "-c", "opencloud init || true; opencloud server"]
            env:
              OC_EXCLUDE_RUN_SERVICES: idp

              OC_URL: &ocUrl https://cloud.${SECRET_DOMAIN}
              OC_LOG_LEVEL: info
              OC_LOG_COLOR: false
              OC_LOG_PRETTY: false

              PROXY_TLS: false
              OC_INSECURE: false

              # email server (if configured)
              # NOTIFICATIONS_SMTP_HOST: "${SMTP_HOST}"
              # NOTIFICATIONS_SMTP_PORT: "${SMTP_PORT}"
              # NOTIFICATIONS_SMTP_SENDER: "${SMTP_SENDER:-OpenCloud Notifications <notifications@cloud.opencloud.test>}"
              # NOTIFICATIONS_SMTP_USERNAME: "${SMTP_USERNAME}"
              # NOTIFICATIONS_SMTP_PASSWORD: "${SMTP_PASSWORD}"
              # NOTIFICATIONS_SMTP_INSECURE: "${SMTP_INSECURE:-false}"
              # NOTIFICATIONS_SMTP_AUTHENTICATION: "${SMTP_AUTHENTICATION}"
              # NOTIFICATIONS_SMTP_ENCRYPTION: "${SMTP_TRANSPORT_ENCRYPTION:-none}"
              FRONTEND_ARCHIVER_MAX_SIZE: "10000000000"
              FRONTEND_CHECK_FOR_UPDATES: "true"
              PROXY_CSP_CONFIG_FILE_LOCATION: /etc/opencloud/csp.yaml

              # control the password enforcement and policy for public shares
              OC_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: true
              OC_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD: true
              OC_PASSWORD_POLICY_DISABLED: false
              OC_PASSWORD_POLICY_MIN_CHARACTERS: 8
              OC_PASSWORD_POLICY_MIN_LOWERCASE_CHARACTERS: 1
              OC_PASSWORD_POLICY_MIN_UPPERCASE_CHARACTERS: 1
              OC_PASSWORD_POLICY_MIN_DIGITS: 1
              OC_PASSWORD_POLICY_MIN_SPECIAL_CHARACTERS: 1

              # OC_LDAP_URI: ldaps://idm.${SECRET_DOMAIN}
              # OC_LDAP_SERVER_WRITE_ENABLED: "false"
              # OC_LDAP_BIND_DN: cn=anonymous,dc=idm,dc=m00nlit,dc=dev
              # OC_LDAP_BIND_PASSWORD: admin-password
              # OC_LDAP_USER_BASE_DN: dc=idm,dc=m00nlit,dc=dev
              # OC_LDAP_USER_SCHEMA_ID: uuid
              # OC_LDAP_DISABLE_USER_MECHANISM: none
              # OC_LDAP_GROUP_BASE_DN: dc=idm,dc=m00nlit,dc=dev
              # OC_LDAP_GROUP_SCHEMA_ID: uuid

              COLLABORA_DOMAIN: "collabora.${MAIN_DOMAIN}"
              NATS_NATS_HOST: "::"
              GATEWAY_GRPC_ADDR: "0.0.0.0:9142"
              FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: "eu.opencloud.api.collaboration"
              GRAPH_AVAILABLE_ROLES: "b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6"

              PROXY_AUTOPROVISION_ACCOUNTS: "true"
              PROXY_ROLE_ASSIGNMENT_DRIVER: "oidc"

              OC_OIDC_ISSUER: https://idm.${SECRET_DOMAIN}/oauth2/openid/opencloudandroid
              WEB_OPTION_ACCOUNT_EDIT_LINK_HREF: "https://idm.${SECRET_DOMAIN}/ui/profile"
              WEB_OIDC_CLIENT_ID: opencloudandroid
              PROXY_OIDC_REWRITE_WELLKNOWN: "true"
              PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: none # Needed because Kanidm uses different JWKS keys for different client IDs
              PROXY_USER_OIDC_CLAIM: "sub"
              PROXY_AUTOPROVISION_CLAIM_USERNAME: sub
              PROXY_USER_CS3_CLAIM: username

              OC_ADMIN_USER_ID: ""
              SETTINGS_SETUP_DEFAULT_ASSIGNMENTS: "false"
              GRAPH_ASSIGN_DEFAULT_USER_ROLE: "false"
              GRAPH_USERNAME_MATCH: "none"
            #            envFrom:
            #              - secretRef:
            #                  name: opencloud-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              # limits:
              #   memory: 512Mi
            securityContext: &ctx
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

          webfinger-proxy:
            image:
              repository: ghcr.io/2bros-group/opencloud-oidc-webfinger-proxy
              tag: v1.0.0@sha256:40dfe5aa1f716ca82870734d1e75d9727c5366ac5f97a1d1196cd5e4e38a457b
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 100Mi
            env:
              PORT: "9201"
              UPSTREAM_URL: https://cloud.${SECRET_DOMAIN}
              HREF_PATTERN: &href https://idm.${SECRET_DOMAIN}/oauth2/openid/
              HREF_REPLACEMENT: *href
              DEFAULT_SUFFIX: opencloud

      wopi:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext: *podCtx

        containers:
          app:
            image: *image
            command: ["/bin/sh", "-c", "opencloud collaboration server"]
            env:
              COLLABORATION_GRPC_ADDR: "0.0.0.0:9301"
              COLLABORATION_HTTP_ADDR: "0.0.0.0:9300"
              MICRO_REGISTRY: "nats-js-kv"
              MICRO_REGISTRY_ADDRESS: "opencloud.opencloud.svc.cluster.local:9233"
              COLLABORATION_WOPI_SRC: "https://wopi.${MAIN_DOMAIN}"
              COLLABORATION_APP_NAME: "CollaboraOnline"
              COLLABORATION_APP_PRODUCT: "Collabora"
              COLLABORATION_APP_ADDR: https://collabora.${MAIN_DOMAIN}
              COLLABORATION_APP_ICON: https://collabora.${MAIN_DOMAIN}/favicon.ico
              COLLABORATION_APP_INSECURE: true
              COLLABORATION_CS3API_DATAGATEWAY_INSECURE: true
              COLLABORATION_LOG_LEVEL: info
              OC_URL: *ocUrl
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              # limits:
              #   memory: 512Mi
            securityContext: *ctx

    service:
      app:
        forceRename: *app
        controller: *app
        ports:
          http:
            port: 80
            targetPort: 9200
          nats:
            port: 9233
          webfinger:
            port: 9201

      wopi:
        controller: wopi
        ipFamilies: [IPv4]
        ports:
          http:
            port: 80
            targetPort: 9300
          grpc:
            port: 9301

    route:
      collaboration:
        hostnames: ["wopi.${MAIN_DOMAIN}"]
        parentRefs:
          - name: tunnel
            namespace: network
          - name: internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: wopi
                port: 80

      app:
        hostnames: ["cloud.${SECRET_DOMAIN}"]
        parentRefs:
          - name: tunnel
            namespace: network
          - name: internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 80
            matches:
              - path:
                  type: PathPrefix
                  value: /
          # desktop UA
          - backendRefs:
              - identifier: app
                port: 9201
            matches:
              - path:
                  type: Exact
                  value: /.well-known/webfinger
                headers:
                  - type: RegularExpression
                    name: User-Agent
                    value: ".*mirall.*OpenCloud.*"
            filters:
              - type: RequestHeaderModifier
                requestHeaderModifier:
                  add:
                    - name: X-Issuer-Suffix
                      value: openclouddesktop
          # Android UA
          - backendRefs:
              - identifier: app
                port: 9201
            matches:
              - path:
                  type: Exact
                  value: /.well-known/webfinger
                headers:
                  - type: RegularExpression
                    name: User-Agent
                    value: ".*OpenCloud-android.*"
            filters:
              - type: RequestHeaderModifier
                requestHeaderModifier:
                  add:
                    - name: X-Issuer-Suffix
                      value: opencloudandroid
          # iOS UA
          - backendRefs:
              - identifier: app
                port: 9201
            matches:
              - path:
                  type: Exact
                  value: /.well-known/webfinger
                headers:
                  - type: RegularExpression
                    name: User-Agent
                    value: ".*OpenCloudApp"
            filters:
              - type: RequestHeaderModifier
                requestHeaderModifier:
                  add:
                    - name: X-Issuer-Suffix
                      value: opencloudios

    persistence:
      config:
        type: configMap
        name: opencloud-configmap
        globalMounts:
          - path: /etc/opencloud/csp.yaml
            subPath: csp.yaml
          - path: /etc/opencloud/proxy.yaml
            subPath: proxy.yaml

      secret:
        type: secret
        name: opencloud-secret
        globalMounts:
          - path: /etc/opencloud/opencloud.yaml
            subPath: opencloud.yaml

      data:
        existingClaim: *app
        globalMounts:
          - path: /var/lib/opencloud

      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
