apiVersion: v1
kind: Secret
metadata:
  name: seerr
stringData:
  api_key: ENC[AES256_GCM,data:pkT8ZgdUwGcxgW34C41v8NhWBiBONjQVHTAxV18XvfKapdmeaDsYPOvnNkWAsv1P1/7M/aewHhitBiMGa5CdEtAOMZs=,iv:OvguEY8NC/CD4fk/GxPAxSwPQxE+IIE5j+OrzahX0qw=,tag:Q1PuOqGb1wSIC2+sVNg+hA==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDBvK3NvTG52
        MjFPY0dOSHg1QVZ1K3dmN1lVRVRSVDk4Nk9IWXc5L2E4U25SSVBlNTRmaGhjcE53
        ZlowVVprSFBLOUVsZXljNFdMZVRlVVYyTW94Zkx3TjRJRXBmeE5MTWJJYkY3MVNX
        QXIzNWVJUUQ4anA0REV1U09ib3V6OUZLSUgveXlnYks2cysvK05MbThJQ2JkUU40
        aWd1V0pQZmlKZHdFZGdPVlVFNEtnN0NIUWt1VVFnc3UvcEQ1ME9SZUthcDZLb0hw
        eXp1NXJmL3JSMzF3TmpEVnVpdDVPbEZSTlQ4ZTh3UmJTcVlEUGlWcmdNV3Vjaits
        SjJ3SlRGKzFLYjBqUTVGQ254a2dXUWNtSS9IaldwSnhLL0pFUUNuSlA2aEZKNVNa
        aFdWSXJXOEppS2ZpWHNYakJaK25XTmJMTTFkWmZ1VHcwdVRoZENCNHlraFJPSTU3
        YmtjTzgyZHgrWGZjY0ZoYi9sTjVpTFMydTlPZzVjSWR2T3l5Q2NtQmhhVlBLejNk
        QWNBOGdHRERpMnRKbU5BRE84YWhHdDNRTU9Ienpud0hJSVdMLzk5ZENOSUJyOTdy
        ZS9LZWdwQWw5L3BlaDJWczYrbEd6dllWbzN2S3E1eGRnNkJ4UC9hNHFuTzRDWDBK
        bCsyMzh5ZmN5b29WTERBUUhuU1Jmb0RGTEw0NytpS05yc29PekZ0azVYRTloNG8z
        VkxGSlN6ZCswcmNwNzlxOUxtMGw0RUdUZEhYendHeHZpQ0hWWGY3VkFLSldpRFdW
        dWtrR204dkorOUwvRFNsaVdQaENlb09oa28reGRSTVZ6SXZzM1NqZkZKQUQ1dkUx
        WUc1YU8zbUhBcEYxay9VN1hjVFB4dE5qNlRsQi9ybnZLSlRBTG85TExLM2h6SmFD
        WWpaRWE5cGQ2WTZmaVNUOStPelNPTzlxektZd2xXd2dpSzIvblhVRlB1OFZVVzVF
        bE1zYWtPazBxMDZINGorMTdxMjEwV2Q1ZHhjZ2FYMjlsY1IyNlYrdDN0N05PSmZ5
        OXBPUE95Y1F2M0xldC94SzUyM0UzWTVMenRUZ2hOcHg1TVBHRDNsT1h2MnhqSjg3
        eFdycDQrN2pYRUorUW40anA5Rkp6cUlKZDBRbmoxVjZBdmJVUmQyTFltQWJwYWRL
        aTZDeE9SZGJVV0xXNzZIbDBMYk5kZFY2Z3FwWGtaTkRxNzRVQk1Tamg4QnNvUU5r
        eTBtWElKRk5ueWc1cDlhT3RDQTUxRndjckhVbGxqTHRlZVp1aGllN1BlMTN2L3U4
        akpvVDZrcDhRZ2FXYjBXWkswTElMWndRdU5nRmpoNWFYU0hoQk5RQmZYM2toQVVz
        TCtPM0luUk9zeEJwZ0lyakF1Q2VoRExVQnJkWWc4Q0hQU0VGcHVnREdFdjJla01t
        R1BMb3lYclpDS3FoVis1K05FN1pBczk3UXNZdkI2aXp1ZHo0Y0laVkVvRHpGZ1Jr
        SlowbWZIV1pLOTZOV0o0RHAxRlp3YUkreUhBUW9zZDNNaVdUS3VENVJTbEw1QWNK
        SFdQTTZQb0xRV3h6Q1N0SjF4eXdZOTB4WlE1WlBpbFh2L1pQdExJVXA5TmllZGtJ
        ZFltNTc5RzlPZHV4eGRHTmluL1cyOFg4c01MRDlKQWxBNzlGTFFYZjBndmpVU1Z1
        R3MxdE5QR1FWelR2VWsvVWJJUmhqandJVTYxYzh5bWNWSURhODVyUFB0RTRWZzVn
        c050Q0UzSURGaUZCL3hjVGVpbDJueUErUTNDTXVGOVc2VGdyZTVZVGhINXZnZDRm
        RnNCV3V2b0w3WDRLclRJT0tHWDFVblRLUWdWOXRoTUduRE9oaG1PTkNNSEZ0R083
        eHZRZEZweTJLU01jQmdsSVpxWTNCb2x2anRTVXl6YTRNVnQwTnduWGFFWlhqNjlN
        cEt3OWNzRGFTeUxraHFMVEsrQTloMHFxeUZtckRRZW0wVndGTlBnbFNDeW9Kdwp2
        Mzl3NndlK3JWVDdVVUVxanRTVTMrRDM0RUtvY21LZzJtZ2RQdjFCWlAwCi0tLSA5
        QUtSeWl6eFJ5RVltc2VCYmFHbWk3MU9FOXJDQkFERHFRZW8wOXRjZVNzCg8B3DED
        8931QFIbl6UAGU/yDOwcT+rNrc5kgJYJQIQffJP5XBm+9O+YV/gA+4YUr3Y0k7ov
        5tQVAthMZrQIbUs=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-06T22:45:30Z"
  mac: ENC[AES256_GCM,data:DnmV/MiCfKa6iJfnObdrJOO6RvhCzW58im/YyKZLQLZFjVZsC1XdQV4wduD7Nkn2FU12NGRuJYLb71h2uy/4HQMCG8LOqNxuqLKMMOy3J3gL0FpU6lX0QlLcliOA4hZtFLBuvvK4xT24MCDZJpUF0jTwnttDAMyo0oUauNaoyGY=,iv:plOgQjrKCPBigxO2EAXFQjZbJpn1m1rQ59f8lU9Hzbs=,tag:wUj2wPJKscCDV8ijp1FLRQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
