apiVersion: v1
kind: Secret
metadata:
  name: maubot
stringData:
  admin_password: ENC[AES256_GCM,data:knpMHRYDk/uD/cItqFA4XtFYllqmEAQ205DN4VFM50WCsHOPdaoCW1vxSTNrO0Ag1yF+t7sf3h9fEjj+7lgetHpL9bmktAdP,iv:ipJLWf1/1W+Pi2psTuj6hnp1eKKPZB8ob+uo7E8dDmQ=,tag:vcUY9FNPm30dGVZy/i7FJA==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGFrM0tESG9R
        L1FKSWtFZVNtOFN6Qi92RDhVeGZEbldWK2ZyMGhjbWlsbXRaQlN1T2hxbGxJTlRH
        S0tObmhDWVJFVTlYLzNsTHJmcVk3QmhHajBlWXpFa0RBTGx6cFc2YklNR0lWeFA2
        UFJpY3B5RGtiVkZMNW9XV0ljcE9uNnZ0MC9lcSttZGR4Q0J4dVp2S01aT1ZRM0d3
        ZzFFS2srUGFHdFRLUjRkZjd0elZiUlQ2dUFxRVVtdmlkbC8wbWN4U3Y4T1VYcThQ
        cGw3TGtySEhyWGl3UVJOb0NvdDJYZkM4ZVM5NXRRWDZWSDE4aDM0YTBlTEt4QTN0
        QzV1QXJIZVk1NFdzYjRKcFdDeTM1c3F4M0x1bFJlUDZETWR6VlU4eWxIQnNCSENG
        dFJkZHQ5cWt1dFdTMjlBWDRLRFJTRGZTL3J0Tk9aa2x6aEpncHJPVExWQkZOZk0y
        OUUrNE1WNVJ1SWxrTnR3SjVvclp4cTN6SkQxRXY5Mng3aGFMeUc0eGZJNlZjL2Q4
        ZXRwL2Y5WHl4OHpTSytNSWxMUE1JZXJlajc0U0dSWHdibTd5MlFGUmxIOGNDVnU1
        S1ZPb0xZMXFYRWJHSUNLNWo4VWZzSmVPNXZxZXc1bkJyWjFRclAyZFg2bDdQRWht
        dlBzYVRncFpSUGMwakNNRFdBVVlJdEhJcWdNNjM2ay9xK1dUKzdPS1A2enB5VDhS
        VnNnYUpIVERPZFZ1MEtnTzVLb2dUZnpjTVJtVnluUzdhOWIrZWpaSXdHQ3JDZEcz
        ZjRaVEJkTjBWV2NXSndYbDhWUHBDYWxJeGh6V2w5NklGNDJtVWVVYnViQ2dLbHFL
        bmN0UGVzc1Z0bE92aWwvdXRMcjFYVC9IaURSVXBTL2xaNmFZVWlmZ1RqMzN1VVJs
        d2p0V3plYWtpMkZPNkVLUTVpUHVWYktXc3d0WEE1VVNYVHhsYm5DWnJFbkhTekpZ
        RmpNcjUvbkx0REtEaXJrbTFpR21Vemt0L2JoYXpXRjR3UloyMVQrWmdHcThEN1Fz
        WGNmZDdNbDVjYU9yeW1UTjEvaEZUTnFnc1kvQ0w4aUluVmVoVGdRQnhHS25sWmVM
        L3RBcnY4MlkxbkVHZTZsa2xwTEpzN2NwZUJET1BLdkMyZ1BSeUZQWFhZdkhIRlk5
        V24yVHdIYWx4WVdidDBjRjZyaWV0eU1rS2VGU1hPNUpSSVJxQmFOQWtyNmhTT3ZV
        ZVM4NTlGaXBITzhBUGZrSDRKWWl2UmJBWnlFU0RaUUU2akJGRmFHdzRDMDlTNHEw
        ZEp0M0xGMURsYThVUXVSeVdsditEYU5mSUxROWdISFl0Y0c2Nit0M1VGcmFNOTVF
        Z3FUWmcrb2Fac29sSnVWTERSSWtoREY4V1YwQ1MwSW5rRjVyR3JjbkNQY0JpVER6
        b2NvSDY5Uk1MWGd1bE9FcmQzSy8wMUJHdjc3STNsVDMrQVY2SEZ2Y2NEck82NG9D
        emJiUm04UjM4bkdZeUViZkkzbm1xSkFQQ2tRajUzVGlqUHVUQ05FMFkxenJTMmxV
        OXFPQzJ1aERocTlHQXF3enZ2aS91MG9WS0RNcEx2WE95TWkxWk4yaFh6STVxWW16
        YlJDdjBvdzJmQUEzT1VMTXJlbTZjV0t4bm1NZHcwNHlManZoWkxJVkdLNURFTExk
        OXlEVUgrbW5TcHMwZE5TUVp6WGpFUnc3YXVtLzVxSVRadEd4VnJmK3dYaWIzUE9F
        OHdjTm9LU3g4TWd6VDB3bUlha2lSRGd6WWEwUlhkK3hWdWE2NWcwenQ5NEJ1WTlR
        WjNJa0tseXAyZHNCbGpjMTFEUS9pV2VaUXpLYnFMZFNReWFRZkJuUXVhMXE0czNB
        c0lwSFlIZmFkZ1VuNTFOVVkvYjd1V3F0REw3TVFNZW5mTWxuWVNwWVdBcnBNRTRi
        RlRleVMrVlF0dHVHUCs1Ni8wYXoxOVV1b3pQRFh0U3RoSG1pWmJYYlN0TU5TZwpk
        UzJ3WVZzNTgwSjJJOXd2WWNqMTMxWmdpUDhDUGFRVjBMN3hjUHR3VkxvCi0tLSA4
        WUhFWGpzUll3RWNENVJ5S0JOWXU1b0gybWc2NTJvZGdCWjVYQ29SN0ZvCmkhdqSk
        UVkk1OTd7FkGtImWtRelVyHvuyrc4kbBOTCRUHC0Q09aN2XyYoLm+hXBCfgIF7KP
        fqMWT/lnHgmo+4k=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-19T21:55:09Z"
  mac: ENC[AES256_GCM,data:pvxRwDRB0BRpzMwrNxAuHdQcPPCmbDbtP4LnYTvFfbAz81d5iyXzrEJttnlGTb+MxeTRRvJxKMEOtM3pGRdhkfCTCTa5NJ092zY7NTIsNC+fmQ+q4Kv2KHPGXY9Zup+CqEm2JLvrJkLYgttKncvyqUFmQCerUQdXLNh7ET+o7YU=,iv:ZPQNLlQtzZlFNPEISf7k7n2LNFz/+RZfpKw2YdHM1to=,tag:FDbyjlZU2UErlf0GEWEb3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
