oauth:
  clientId: ENC[AES256_GCM,data:w0MxVB8X2ijq+BTXa4/XY3QMbh9b1jO/VdaArhgWov/SpLk=,iv:abXT7/e1BtxQb0bVAUCj5/l4ANYw3qBIP5AqbnkKung=,tag:2KY8/BY9zceAhDpY61YOtQ==,type:str]
  audience: ENC[AES256_GCM,data:6VFkuQ53oTo3+eCfRHHb76FGyiZd70RK9WOrLeSTWao3TGBrOhe4wsHS6j3EnPnMn5VCE6U=,iv:ApMrfSx7G5lSoID3HORkvzb2+adTKp3EZu5czUP/01o=,tag:aUAUI2RR+GchCbeYYLljTA==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHdIZ3JERE9u
        WHdNUlZNY2JSRTVySEhxbUpOcWRqWUpZaGlFUEptelFGenZ6b2gvTGo3WGllMnpj
        RFZsRUkwaVNJaWp0OEF6MEpkZ295dk9SeVhHVlZJekxCNFBma2NmbHNMN3FCS2ll
        dHdYbmM1K04vaWY0cGxTNVpPTWRJdHdubVkrSmZ2M2d1N08zZ0ZkbDJFRk9IcGhV
        aXhKZmJuS2JLTlhwUlZ1TGtGcXlkaVd6NjlZVlN2MnlVbGZLcnU4RU90WnIxV2xJ
        MlgwOVBjeUx1M2wzNEhnM1pMZzljRXF4Qk01YkZyaEgrTnd1dHJkWmd2Zjltc3RJ
        Mm8zM3FsOGtuMXZtcVBsNDZTZjRvOFJlQUxQcThTV1lqZnlwTmszajBONmRBZkJh
        akxMM2daR2w5ZXkyNVltUlZYRXZUTEpGdkViSVcxcWNHWENFNWFzMDFOZzhwSDBt
        TjNhUWRDWXRwcXQ3RTdqQ0I1Tys4eXdENXJ3S0pvNHNjSnduaWMvcGdvUDdaZDlF
        ZnFzUndiSTAvU1poVjlzRy9FQXBsZkczRlo4a25TTWFxSm1GRWg1ajQ3VDJoaGhy
        QlUxNmpOcjduYUNyQllLdEdnRkx6clpkV1hLMWJERStxYXFBN3lkanBjTVgwMG1U
        dHNyYVdIeDRpYTNZY2pZa1Y5WUY2bnFuakh2eWlXUGlCM1BVL2l6NU93QnBkWjVG
        VTYwWG9WVVFhZ2dnaUJxZTdDREdrdnhpSFBOQk1CbXZ4djJLLzJ2TmdodDFPazYw
        dXRIbFNyK1RXTStYaE8xRUMwbVJtRUxSK1pNWmN1Y21xK1Y1bHZlemQzckorQUVl
        Rkx6ZGFhM3dsaTVOZ1A5ckRScFpMK2Ywa1dybVVBQWVLejRYcVNNL1N5cVVoNVFK
        Tkd0SzlQeCtwLzFTSFA4dE9XMkg0eFNBcVhmL3BtNjRPWVVmdGlwbGdHUC9TcnNV
        bGgwUWZrdVN4dyt5aFAxY0tHZU5LVTRTNkVHUkNxZlRzaUc1ZXV3ajZ5TEJpL3BV
        M3BRd040RkljdDVYVzFzVFkwUnNtT2F0cGdHMWZiVjI4TW5rM1FFZ2FmcnpnSEoz
        cTJLY0JhUXIxdWQrMS8rdXpCcUxFRTV4blkzRXcwZjZUdHNuUC9ZTk85QUxGQ25C
        TUZtdVZRcDJ6Y0VqTHVUWHRZUWh3emx3ZHkrVlhuWUQydXhkcmlGbUJZNm1HV08w
        RXRVTjFiVG5RaXhpVVRxWWN2Qk0vbkVJcWFqc09kZm5nZzVXYjdJNll2OHFYTG4x
        N3EyemVFOXZkWllWeTFmcy9kWEk0NlNpZFNVanJzbXB2ZXR0MHNKS2xRcWRhcFp5
        bmRRalB0YVE4Q1NmaDdHcllMUUJWWnROZDNqc3EwTEhkZW9SeXRsQzRjTVVHREFn
        K3IxTzhhd1JHZldFY01MU2dZUUpnSGkwOHZWQVRpUUM2U0NEV2FST24wOXQyNXFN
        VmdJY2JYNlpiZUF6WGxmY1Nza0ptYzJQT29PN1k2QjBpbEdPUzNJSXh0R1FBeUdl
        MzN6cmJSN3RldjJFWlV2cUpLYjd2VktORmd2QzZ3RTV6eVdzbHg0K0dLUXZ0dmVh
        SjBTTDYyZWxYNHI4ZUtycjZqZHBoeGFzVXBLV0F0Ri9mVGdGM1cvbTZ5UUN3SzND
        eTZTWTVGR05ISUtKdEhQYVVJbVRZM2tPVldiTEY5Q2M3a1lFMHFLY3JsQkJ6OGpV
        bWVIa1d2TE1uUjEyeDB2UTJqMVNmK2dPQ1lqL3NsR2Y3K0hEMUZiZDRvUEV0RmpV
        S3pEcHdTL2hlOWZYVk1rSGJiQXVMQm1kQk1zMXBIVVdpM0FiSmZSbE5pcDNkc1hs
        Q2JpZUh5dXNqUnd2YTdxc1FwandieW95TWdwWi8ydVlJMUxpSWlYNmpLajB5UHBk
        S1dMU0hHNURIcG1TeGNZdzZkaWFRRzh4Q2d0aERUb1lnbnNQVW45dCtNVkdXZwp2
        WXJxb0lGL2ZOV0ZVR1dYNXpEWkFSMURpQTJPakVXNHY0cVJrS3ppK1JFCi0tLSAv
        MSttQ3pBNnpRT0FBNS9rSGhKbnNROUxuY283dDFnWHNNT0RKZm1BZit3CgUX/zdW
        vTymbqawzrixy2THHKCH7r4ncA0GS0ywINZcSGGzjLNe9zx8FjCstSBvjkeuWCB5
        lRbNR+cA/2fLcCc=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T03:58:58Z"
  mac: ENC[AES256_GCM,data:SPa8HkrJSe6p6N0Pyz+4vKFkKovgfz7ELJWyDnHt81zD3rvsOi3mfYP+azMspOVOsoifWEqDr++3j2zAiw4vOS9N6TVDC6ZF1GkKDgrxP12Y+mCzVEnWqr95cNwdqM4b+R8Z+KN7YfKY2KlGx3SIjUKgTbOox9fkx6bCUqkuCO8=,iv:ONMaqpnkTqT1SbqGjPd9IUQMzhWMMSSXbJFRtJ0mXE8=,tag:lJ7vFzgcQ/7GdamhPexbhQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
