apiVersion: v1
kind: Secret
metadata:
  name: searxng
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:nOIPYvnNG48olGOEbBVDQeRB7DwO0hxK21F4as5bYbHUAXpeHYy0/qGdNQsOowFbfqfJjhv5gu8MbvKI0lSR2g==,iv:QuAI6DJbUyDM+3JMRwfr63U8G4wGrv8wU/3VDRJ9EQE=,tag:/FAcXLdYe7XUc99pjoEThQ==,type:str]
sops:
  age:
    - recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMFZxc0VmQkV2VTRqRzBC
        ZEJ1ZXFSZnJhT1V4TlpNbThlSjgvUVVkUG5rCk1wN2YrTGRscGx3VmJIeDE5bE9O
        ZTFXVGFPNWliQW42Q1YzS010OXlDWVUKLS0tIFZOVW8valF3Qk1leEF2Tk9zODRM
        SCtFeWJ0bHFFckczaklHUVJpSVpWQzAKAUI6+DE3TugGIRnGo8qCt8wl4ubGotc7
        cqlAFMJjIyHkOufNZbq7Bq2/Ex4nwq0wq5f8FbAQB9O+sB71stuIew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T18:35:17Z"
  mac: ENC[AES256_GCM,data:BYs889l3iEjOJKtxufyp9rZnChL2Ppy4Vgk8XdHAB2YKXbZ1wSaCOn/Lm2pkxM2tcomiamgyFN6Gd00ISyLIHGGfCltk2/pZJnhlqQ7Ia6hK41XsOPl+gzJZ1goaudY+vNXzbXZ7JCPYix6YCpN36v0cZSb6hZ02P1K5/amSMKc=,iv:fxz05N7PE73WvXYB5Qy8k/qeT8RVZvjna0y7raVTGjA=,tag:sjsspJc9nnVU2g4SpAdtzQ==,type:str]
  pgp:
    - created_at: "2025-06-19T02:12:25Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DC0EwVK2S0BUSAQdA/K0f5jrjrvPEk+D73ZbU+juAPhUC0moI8jsBkKL7gDow
        JeFcZJU/oQBa4IKMPbViXnZ4lphIpH38zrnGiZceCivu/iIatO8qytT0S44/j7H/
        0l4BuD04Jg+4d0Kv15lcAMeZaB1LCDLXqnVzap3nzNFHSHZv8IhKb6g6MWEkUr/y
        htdlMndiSLw816xZMy8+F5y5fRdaze3LLd6N7ryDC65w1wQA/TQFnpMcliRVSxgY
        =nW+9
        -----END PGP MESSAGE-----
      fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
