apiVersion: v1
kind: Secret
metadata:
  name: searxng
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:nOIPYvnNG48olGOEbBVDQeRB7DwO0hxK21F4as5bYbHUAXpeHYy0/qGdNQsOowFbfqfJjhv5gu8MbvKI0lSR2g==,iv:QuAI6DJbUyDM+3JMRwfr63U8G4wGrv8wU/3VDRJ9EQE=,tag:/FAcXLdYe7XUc99pjoEThQ==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGQ2TktXcUR6
        bnh4bVF4bTVmU0tabHZoWGlGZEszdEl2cndXSU0zcEozM0dDeU9XYUk3NTJiV25D
        MGNLTGROWmhrSzVSYTZNK29CWjVuejZFb3BHT0h2alBXUTJ3YlBoWlRaNjN1Y0Rr
        YjNhUzNscXc2RlphOE5BUjlySHpWMlhIWnJNSGhubUcwMVhka2UvdUtUbW9aVEJU
        K01DU0NWUExZYkRwakF6SEJtK0RtbmdNSWI0VWdGMFlqQTNVY3J4bFVFM3l5TUM1
        Nmw1a2x2ZGhlRW5mdGx2WS9QbllGc0tDdWEySE1QRm04OExoeFZHTFNzVEptSFM3
        K1Ezck5Bc2x2V1BhdGxMOUpwRkx0M1RMVC91Yk1ubnY3NnpqZFR6OHdTTXRXcy9R
        K1dZODJPZkIwWjF4WFNBVkFjKzdrZldPTis2N2RoSGpxVWlaZUxBUnZ5RHc2d1la
        UnpQUGhBVHIyNmZSS09FTG9XYjVRREhSTkRVL3N5RGdRN29jeW83a1FNVHRyeFdP
        enQxYmlLNmRSMXlLZ0xQUjJTNkxUUWM4SFduR056Z3l2RmQ2bFpCaDg0SWRucnhP
        aHdqK2hvYU1iRE9XQ2Vaci93OVNvbWhUWUR4RGt1Yms5STJVakIzZFZkdyt3MGtW
        Ylh0TjU1V3ErOElaaisyMWlSOUVnL09Bc3VGS24wVnEwZGIyeVJWeWp3enlZM2lp
        Y08vT0ZXbTJoSFZxcUtDaGdXTGZSK3VTd3Z1WGhpWWptQ05Ea2UzUUVReHFMS3Zp
        MTVWaFRERjdOTUszREE5aVZ4ZnlyNVdQdVVVTno1YldscW1KdzVrRitFZzlWSUFt
        MHRSQVdWN2tabU1abHFqSzJOQ3UvdDBSUzYrZG9USjVNVEFYUyt0dXk0b1Avb2Vu
        ekdzNS9uU3U1eXUvSGE3OVhnZlRFWXl2QVJ1MDBsWVVreCtTbmlnQmI3a1dSdWJY
        R3hacUpOenFZdkZPdlJjRjg1Ykx6NUtxY0t4QlcyRU1xNitCMmhmNlBReWllTUtz
        WmlZc3N2dUd3NkJMNHNTWlgxNE9HRGw4ckoxYVNnSDFzYS9YYkdPSkwvQW9iNS96
        c1Q2VDhNTERVK2wzQTZCRTRvb2tqbXBkNVlVeVN2d0ZrcXhOYWY4dkh1amp5dDhp
        OXJkcTlmMm02Y1FMREJrUzZ1akJHNGdFWXpzY3IrN3NpbFRtdU1HY2NPWmQ0V2tr
        SlhtdlhWRjdUS21KcmFXMVRoNXhmb3orYkJCUk5XRTFiVE5BQ0FuRVAyZk5mS1Yy
        N0lwK09lZEVTYW5VQUVKeS9HZjhtS0IrdE55NGdaWHcxNGpwYUhRcnRjckphOG9V
        TmZmdTNDTmMwcnBZQ2Y5M1VtNElQcXEvdDRFejZvektwUTljUWgzVjZTTDRFdTRC
        YnFiUTFCRlEvazNxcHhjaytSSVoycXV4NkNJRERLaDlpT1hDeGxRb25kYkVLdkN5
        UjVZRGw4ck5GbWdpOFlBQ3VMMXUxSG5kNTdCSXFzQXdOM0UwdFV5WEs1K1NvRThU
        YmRBeVp2MUVrclVJbGtIYXZIT0wyY2l2L0d2Wm1PWEV1SENyWnB2eS9vWHBVYkkx
        Ni9QM1lLRk1KVlRPTmd6TkcxZi9KN2V2Sll3a1U2WU1ra3N3RDBkWmZlV1drSnhO
        SkUxdE9YdGFsYmpFUk5od0pSWjA2cm00MFM2UWUyREpJR3VhZzh4aUlxQnZSR1o5
        dDlUWjhpcUdnOXZxTXJnWncxbEo0WmM3cGk5RlU2RHExcjdHS0NPMWpvcUFSOWlF
        Si9MSHAxV3ora2hBTE9ibHRRK2Q1Y1VNRkFhaU1SQS9mc01ocHQvTXViVDc4TVFx
        dEYweGtrRFowNG5JL094K2FWcTdmMGZsZUlvU0ZqVy9YVGFtdVFBaVhWNWJwei9x
        ZVVybk5pY0JrblVMR2UrYVVlZ1lSU3NLdElPZzlpcHk2VmN0UW83cGxtZlZRUQpq
        bXcxQWozUnVja0wyZVRFd0h3MTBtWFVoWVJCeThmekJaSFlPakF5KzhvCi0tLSBS
        UWY3RS91NXFnVFRLbCtkU0lRMkthZGoraDhSYUcveHVhWHNDdGh5MVF3CrvOxzX9
        zcLVmRMXRSekq7+dXM+YILTRGq1IIgAzaCNTsEJ6j6bZz+FLNZtoARYfbfwks43N
        ySgXCvXyRdJCKV4=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T18:35:17Z"
  mac: ENC[AES256_GCM,data:BYs889l3iEjOJKtxufyp9rZnChL2Ppy4Vgk8XdHAB2YKXbZ1wSaCOn/Lm2pkxM2tcomiamgyFN6Gd00ISyLIHGGfCltk2/pZJnhlqQ7Ia6hK41XsOPl+gzJZ1goaudY+vNXzbXZ7JCPYix6YCpN36v0cZSb6hZ02P1K5/amSMKc=,iv:fxz05N7PE73WvXYB5Qy8k/qeT8RVZvjna0y7raVTGjA=,tag:sjsspJc9nnVU2g4SpAdtzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
