# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: autobrr-secret
stringData:
  AUTOBRR__SESSION_SECRET: ENC[AES256_GCM,data:11omU6FNz7GBVCz/g17RfmFf5It1YkOUNNZX6DBLsFqXx6ihzncM4OPddihorM/Ca6nq+gyRtmIRIljpHlk9xffMqJUE6OqC,iv:vx52/OturCzwylILUi0Q6gUNO40NkWp+HKp3/G8Szn0=,tag:R/k9RR2bewgO1qgVqb4MhQ==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHhaSEZBMzRh
        Z0J3UU5TNVEvT2pEbm1TYWNjYmxKcU5tQlc1QmlyRmpqYkJvdC80bVRDaUxIZ2Ur
        M3NWb0srcm5GNU9JNTNhdHU2bElCQzVnTHVRbVhDS0JvY1lIUzNtRXh3NWxtb0Vx
        Si95SDVVZWdRbWk4cjRlcS9QWEUyNGFra21TQURMd3FUaVJPUFp0eFEyUFZpN0N6
        UW1kVkpXN0prTGJ3MWdWL1UzWjgxbjlLdm5BYk1OV083SHFEczVwQ3BHeXBXTDBH
        b1JodUF5dHFxazFKZEJFWk8rYmN4NUkrdFcwaDU0STgzcjlBOWtrdFVCRUdYeWJo
        bGQxblNRU2FJZ3dNaVZWcjBpUjU4VjJMSU04L1BjK0ZXRE5YTHRSVjRocVlPRE9Q
        VjRHZC91WnFtY05SUWdUUld4ajdEbnhMM3BGZmcvNVBKMElMZEhVa1JiQkxtd0dv
        LzNCQlFyWWxqdmR5Um1pNDQxd3p4OTRadWhNK0l2VzhRMTJRV1dWU2Q0cERCNUs2
        OTZGS1A5U3FuMFB1OElJQWN1bXdocDFVQk5QVlJGSVRURjZWczJFNThIMmZ0ekJm
        UU5jclEweVVVdkZOTFVueHhoVnlqOUlTL1RTOXRjQTFidUY2eXFSTlk4bDRYN2JW
        aFFWd0dnVEM0OXZNb3Rmb2dVdGthM0E1ZmFPMXZPQ1p6N0lLQ2dwWGVtejJoZzY0
        YlFVR3B0M1lvckNoNnVoSXFmMWFCUVpXVnNMS2YwWFFUOWt2TXhBWklVTzY4cjFM
        ajlrdnNERGZlYjRMZHZqZVNHSUtUVGl6bWh5eHdUSkhIdEdzb1g0K3JYN05ZMlp3
        TFRwUlo4WVpiNkxqZVRZM2pOMXlyOWFLR2lYS0JlQVlJWWlJVWFJL3hXd2dPVldr
        WkRZOXZlQm03N2U0RWtvcVozUUV4aWhnU3M1dkRwWmU0cGU1TWNHNUFjbFFMSk9H
        SjFQNVllUjNPT2pqQkMwbTFGQ01Ba0ZDTmRvRUtBa3FVRGFIWGFlWTMvSmZlb0U2
        YUYzWWowNVQrYTl3NjJPQ2VWM3FFQjE3ZWwvKzNHRkdZTGFCOEdsVUZiRnVIaWpk
        VnJhcW9sTXNuMWlTWjJRa1NWWFdVN2RsN2dkL05ybFdFMlJQWUdWMWRxU0ZJK2F4
        ZDRkbURHbFlIdGF3YXduWjg1WTYrRmJLdW11TDhXc1JGU0l3OW1uQ1JIMkpLY2hW
        ZFNQdDNqZDFnQTU3S1kxNE1sbmRyd00xNmdONDRLaE1QR1BNTFBiRkNhemNYMUd1
        czBmamx5aXM1Mit1QkFOS1daOUpPanduMkZtN2dTaVU2bUk0ZDFTb2g3NUIyUU5I
        WHRKQWNMc2ZobUFhTXlOenBHWGo0VjhTdlpIaGUxdmkwL2N1RE9ydVBIcVFMZldV
        N2R5REpqbHNDc0VpUml6RW5ONVJRMUVCUWNnZUt1WmU2M0Y5OFpzcU9najlaZ0JP
        NXRtbndrWGRoRmxPZjZ5T2VyZERIWE54L3BZY3BRamtHMXJoaUE1dERuc2FkVjhZ
        QTRoZnVWZlFYdjJ5a01RM0xaVVhZQUNKV1YzSjJXa1RXQWZDVkdtQkVjaDB0clRx
        anRxYkVZc2IxUXYwclFVSDcrMktMYXBzdW1zYjVHZVlvZFpGb0doWFRUdVYycnpU
        UTB1dWNzY1FMbHZMOWtJZUh4bit2R28wMzNmRFJiWXovSzYrS3VqMGVxbHU4QlhQ
        M2ZqRTdDZ1hXeGFRZ2pQeWo1SzRNSTU1WWg5c1c1MTkzR3NYbXhwa2IyVjhNWnZq
        SE1HWXdOS3IySGJDbVlyVUVBL2lhODNOTmk3RFdDb2srdmRIVTJPUWZkaU1XM3Jk
        OCtPWU01ejZCcjlYRlkzYkJ4d0MxVEtSZmhmc1B2QTZJQ2g4UWxqZ1p0YzVkc1dB
        dzJOMHV4Qk9DZytSSlhiMi9DTkhMT2FJc0N5azJHTWk0UTFmNm8rSjRHNDRGUQph
        WU1TRnlVSEo1Y0tnbk9yQnVCMzBNcWk2QVhYYnhJVmlxa2UxQTdlcStzCi0tLSBY
        cjBIVjV1bkYxZVRha3kwZ3M0VVh1Nklrb25qZ0FyQ2YvRktQY2tOMDUwCkG0hOji
        pvGW9/AAfgCNcYZc42yVyXlheux08+UrVeO6d+fwvmpo+S+qowBm9q+n8oCylWt0
        c+9oHVWVpSFBCwA=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-11T03:55:28Z"
  mac: ENC[AES256_GCM,data:AcgKEB25Ua6/Xc0nm5e65J8VhWy0PQLeQyW1S4o4puDCFfmlYWsxrFicKla9d2+C0Uoe0zNxbJk5yp+ByicAYVE2zn8s4tzubiqzTueGA5lz6BRyONNhst/kwsbS+fMS0MXIfbErceuiLwE/aVgqdPSd+W31/WOTVLUqyD250+k=,iv:6B4fAxr6lGDMPm7wDGfkEqIGpPdz1+LaOD+uc8MO2aQ=,tag:I6kb8ownBfw5zm6BSeO/vg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
