apiVersion: v1
kind: Secret
metadata:
  name: anubis-key
stringData:
  ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:eMQgoGBFFHofGFTzynFeAxXMS1Ge+UePhj5+XpOt2AEXgSOYSW5Va3D/Dx2jnb/RunFqYHj9whvqzYnF39CSBw==,iv:JkW09xM+a6OkFJ9mgDNlfIfWQ5CJB4Z4hKoXSaa9ZNA=,tag:dHkWSduE/uY0civ9xwLfZg==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFVrbEpLTjIz
        KzFlUWRXaW1Qa0V5cDBNL2VicVFIek9vRlVXNk1zcEx5ckdUQmlqOXJKanJoelNI
        MHdxYWN3QXFJS2hmSExaSkJiOTYxcExpd0dWVFlCaUtBckJ1UVZYU1JuVXI0VEFF
        b0h4WVVKL09zNDBIOGdkYUJmZXpVT1Q5QVhmckNkSTh6VUJ6dmpUOUliRWNEYXEx
        T25sbjd1bTkzTzhnT2ZLS09OaWpFbzRNQnIvVTJlN3F5bWVIUGRXL25jZzZLa25E
        enllVjI5NmxGNDVSSFV2bW80alVqMURlU2llMnp1ZzVsWE9Ta1gvWmFZTGI1WGJq
        cmU2bW1wVU1sS1VXTVFnbDU5MnhONXA5aHlYWnJmcnkzVjF1T0tMZXczZUszNlNr
        c3hxeEpqZjZHaFJ4T0ZDS2lwQlRrb24xcGFNZUY5OENEeHB5WTZiWmtSNHY1WTlz
        K3BRTUdzMVord2VCbk1XbGZrNHMvM2Z4WnY5UURyWFY2SGl3NU45ZnN4YW5BclNo
        cEwrZGpJay8zeDVOd0tyeDZPOFljTklHbnRsRG9aY1ZLSGtmWFlRbWMrVzQwN1Rw
        SENpWVBQUVZVTi92MmtvbXlFd2tkbDZLV1pJdG9TajAzcWFyYWd2ZVpvZTJsMFJz
        OXpFSi9wNjc3d1NJODk0OVpHWVhHM1daTFUzaFo5bFJvZjdIMlNpOGg1OFRRMHE4
        V1BGcnoyWlV5TmJ0aGdBQ1FIQ2VYbzU3UWcvREhibDFtVzZPc3ZTZXBrQ3RwNXRL
        cnJGRHVHeWUxV1p5M01VZjRXUjl4c0NnVTIwRm5UOFRCbW45cTFHN3JrVGxSU2k2
        RUZqT3BCM0REbTNNdUEzbERMN0hESG9uUTJBYzgzbVhkTDZSY2tMdk94dXZaeXRT
        RVZ0ZEhTOWdwVXo4MTZSQnhWdTdVNndpSGQwZ2ZBa3htdWF6emwvWGFvWXFvdm9P
        VTdJdG5ROEVxQWdGMElObEpQcEFyNmF4QmptQW0wL1VobUsvdWFxR1Q1V2VxaXlv
        UmZpNWgwSVZFUFhZdmplK0p0eThTKzB4UlBValdFamVxZnpLKzB2MnR1UnJPWG0y
        WVhOU3FyZ2ZLaUlNSlFrcTlrcVBjTXBnUXpYcU92UnV0TUxMSVZ3MUpKbDRObkgy
        bTVzb0hxcS9nTkdwWlpoT0pNK3Y0ZWZWYzRvcGpBYUlTNTNzY2RYSnYzNVhoUzls
        NksyTzNYZ2t4SE9ZcDJJaXAvTVhRVU9lV0RDdE4yOHhQbkQvdjNPZm9kZ0ZRUkVZ
        VGdETVltNUw5ckcvUXVST3FkbEF1RGVsOUJJYmIrd1RpM0tZa0dwc3FINmxIU3dC
        ZU1xUm10OVp6RTlpNE1lMHBuY3pEU3FOWU1OY29TNlgvTDkrNitnVk02ci9VcU1Z
        aGh1WTg5ZExYSFJ5aW9ybFZxMlI0VGpaYS9EMXllYnQvT1ZXSkc3V2dJdUdjTG55
        Y0dVWUlLMWttZk5EdlhCeDdZSlozZnFLNlRLZ1NiZyt0Q2krRHY5QlJnL2NJYXVL
        TjN5cmpQOWhqQWswQUtoT1R0a20wcnpiZVJLODJNaFF5QzVtQUZ3a0UrUlZVOUdR
        aVlPcXVjaDF5Uko4dFR6WGhPV1dKdml3b3hNdklqenZUYmhSMDZFcTVHWURiWGVL
        UitJRFlybXUrdHcxekthbE04NlF3Sk1UelZVNGwzUUJOSWFGRG9lMEZ1djJEVlQ3
        U1ZrWjJLbm0vU1NOMjM4L2N5aXBhSFBtR01UQWJsSkU2VXRtSlJ1RkV5cVppVkVP
        MU1ycGphampmTklDY25LeTJlS2d3TURoQW9mT010ZXFKQi9tSlhzY3YyQUtOQkpu
        WFdWM09NYlh1RWhncmJKMWlFRzAzbUc4eTRwOHBLUWM1bEpFTXpEM0ZnTmh0ck81
        cC8zNXd2UzNFVzdSUjJWM0pxRGhKZ29TcXV6ZjhvUzg0RFpOTTJGRHZ6ZGJGQQpV
        UERvQkI2Wk9QeFZWbHFKVTBSMTAzaTlDR0VJam84U0d4WXBCeEplTGRRCi0tLSBE
        YVBJRmVGNWZnblBQSG0yak4wcG1NZHB3NE5QSVJubFUyTy93SE9iVmFFCgKwvGsh
        RCfNdnGkcIl3BfoR/aax9KfXK4spqNzPp2vWZmTCtOrb2s1jERAhdXI5gNEg4kxk
        8AGcym9h/z9VFgI=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T17:51:27Z"
  mac: ENC[AES256_GCM,data:vadcX1kkLrQLRmHJKVwtdFdB38QbZan1g4hzzEFFDulIqLPKDoZEGqOUFuyBvpQSn77+WQKR/ii456IdaVFudxd+AiR4cnH31ZlK7VSc8yyLjvSYbgeEGIddPh/na3XmDGD6n8ktF7qSewvExodnhzukyyWp5L1l4E0/sUZs5XA=,iv:H2yRLvx6egG2ofO4mmkbOBviBKxc0d0iDQPWJrfOeOU=,tag:e2utX2cynKCTjAPg21Q6ZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
