myapikey: ENC[AES256_GCM,data:t//gvkggB3AejjDuHR2LYWwPJ8jyKMhIgnAwSylhWEq79yl65GDLF6ljzJ5B/j8xihrjbA9WvTpDx+fFA7yZ8nbi6KQuxqs8,iv:To75vlXfO0aeloMIyd6XaK8TmntoQ5R12qWAm9SZXMg=,tag:ILT6zd4JZRAuZo7IZDLdjA==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE12cUlyMllH
        OXQyWFZ1V3JhZWk0ZU5KWnFSNTBTekU1N2tLcFQrS1pDY1hvSkRlaWVvSFV5ZEtJ
        VHpDMmVsenFNWkp3Vksvckkrdzl5VnBXVndpbHVyTkV1bi9vMktvdFZndlUveFN5
        TCtzcFh3emlaSFRsMEJlSklNUDZZdjArRmlHdTU0OG1WK0NNTzlOdm4wRGFJbXZn
        ZkhSNmcwOW5lYkpKZjJ5b0Juc1ZtbjlIMGhmVnlVNGk3WkZvbnVaNjRZNzk2a1dj
        MEN6MVd6ZG1ETyt5MnovRXFnL2tPMDJNRGlvTTNmU3J3WmorUWgyUVh2enJNajEr
        TTczVGhrdThQVmRmQk40K3JYenRmaGEwRzFvaVJkRU5KQ29VbTAwSnJtM2k1Y2pC
        QlFyNDJGR3VvQjFsWW1LQVhCSVBBbm1mN05BelhqZFBJaXlUOFh5VFJtTEF4Yklt
        SkFrUDhiTjdQYjcvdmYyWElGSm5qN1NRU2M0T3o0enNlelNVUXhVUXpWdTVpYlhT
        a1VHeFhIRU55RHV3REE4NzFrck1rZk9lbHk0aEV6Y2VxaHpiRXYyOTlFNUNXbEgw
        cXNoeFIxaDQxdjlRK1ArZEMrd0pJRzdDcGU5NERHdnNRcmFnU2pLT3FrRThUWjBu
        ZmphSVQ4OHFXcThRUFYyWmJKb2JNOEdkT2ZQR21iTEl4S1R3Z05lRkc2ZzJJdlR3
        b3Jod2ZyQjU5WXJscmxmUGVKelVhd1lLY1RycDRTOTN4NkVDZkpaajhrQXZQOC8r
        MUJGeE5kU0NBYkd0RXcvNkVQSFFtelBKRFdEdjQ2YVR5S1ZHeWkzVkQxSU1Za1BB
        Y0hUQk5KN3YrRU5HaHVZczBicUNZRVZ4UVgxazZUY1MxcHJUT1JTNzkwc0paT3Ni
        aDVQZUMyOUhpM1BmbmFiNm5DeURCQzBFSVhoR1htS3ZHUklvcnJZN1dMbloyRkJo
        REhZd3o3RFQ2QVVrcWY0ZDBjUjdCM1N1SDltZjF5by94MExPM0VYQ1JBL2pBVENQ
        YjRpR21XZ0hTTFdIRm1HUUdmbWJVZVhZaENydkZnMTZ6d1Z3eEhRcExWQ25Lcy9Q
        WUlFZUltRzROWG9yWnpsNi8zUHhzTFdaT2czSE1uRksrQ2tZdW1GeGRQeDFTUVNZ
        Q295UkFwMnpiSGtSSEk3ejhnRUhBWVNTa1pYZ2NIdEZTaDRoNUhkclY4aGdMdmpU
        UTkxZkV2MXNPZlZwZytBcTBMWGpFNVRkM3QyenJteWFmWVlBRmpsdzZqdm1pdXZn
        VmNzOVRGTmhIcWtlWWZabzdxaGlaaGhTbERwenNTYWo2ZlJUalRuVmRMRE5DQWFL
        WmdHUEcvNTdJSlo5Y0VIbjFJdnZqY25JWHFzRHpWRUdXS0Q5UEpQM2psNjFKRWtm
        aldMOUp2RGF1WFVwRTE5ZjU5Smlnbnpwb0NheDBUaWExcGtOaGZYMXE2VC9PaDNw
        SHR0K3daL1pBWWdoaHMzYkNwZ25Hczh6NGpoT0NzeUxIbFVuTVdrTmhXVzFWWlht
        L2c1UElxRnY1MUZJYVFaVDRZQmVLcDdnY05kTDZrTjBJclVweU5sa1VrU0RyT2Fn
        WGVEMzRoN2RBSjdRanY1SU94eVl5SkRkaVM0U0ZrWjlLSDBvUDNSUVVMNkt2MVha
        cmRtK2o4amQ3OTBHck5BdE5MVDlPNlgzTk1sb3QvYlRYbVBQRlpaRnltTlA5Zzhy
        WEZ1bnI0RHdNNThwVHVnS1lTSVN1R3hZR2Fvd01kOU1TS3BOVGZHNWNYOFM4STNH
        MERMQXNublA4WktmbjZ1d3plT0w4dDBXSTBraC94SjFvNnJ0K3VHditpVk54cjdj
        OWxFVWF4T3RDVUg1NGNVM2FIMkNIMS9NRVl3SmpYTVBteUI1ZkxIcHZoUk9oaGZw
        dkU3dDNreVg0WmoyMmhLUlV0aXEvRFZwOHR2SDFtUExNaXhSc1lNd2tUT3JZUQpl
        WGtpT3pwQWorN1BoREpDMUpQK0xBZE9PZ21naWJYNngvY0h4ODN4SVFjCi0tLSBw
        elRwMUhBWGNLQ2tOYWRWZ2FtZ0NkZ2EwZ1hVenVJSlp6N1RyRi9TcmJzCn3p9/BB
        wq2YSwP4oddVyoKgwFGiSBPUXrS+zjUEuVKuzHT/ZrbnzT4hXwXn9JONGg9S+g8c
        vPmU6n9cGBfr7NQ=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-05T13:14:44Z"
  mac: ENC[AES256_GCM,data:odgqMyvb3/l7lmMUQ6Uh42x5vYQwkqHlu4e3vRzhtRZZCKZTCgsfv/dsDPvrD960rP2xo/MRXn9+c+/6wrScTxhyrAOEDnU+eFIriR6FyFMO7N5MdSw8Gp4U/umZQcOQqbEIpIZa6W0kbNbBJqb9d4JL4Nb9/XRKa6gFxZNPE7Y=,iv:0RtVsc/AuxmGbfLcwNf35XJSAJhjK9XLh1ManzAxmeA=,tag:oUEaD3/qR1XvpSTd2p1akQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
