---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: https://infisical.m00nlit.dev
      auth:
        kubernetesAuthCredentials:
          identityId:
            name: kubernetes-auth-credentials
            namespace: external-secrets
            key: identityId
      secretsScope:
        projectSlug: homelab
        environmentSlug: prod
        recursive: true
        expandSecretReferences: true
---
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-auth-credentials
type: Opaque
stringData:
  identityId: 377f2c7e-7575-4c23-ae05-5a4821c8f1a7
