apiVersion: v1
kind: Secret
metadata:
  name: bitwarden
stringData:
  BW_USER: ENC[AES256_GCM,data:C0zBlmj1e/qOOjGlDM8wGM6mAtMawFoOg65yyw==,iv:iHtM+Iu32a39paAWzgHFlbcm+J71FY7MGRqBk6/1OJQ=,tag:b4pFRdsXYv9XHb6CDtIZ6Q==,type:str]
  BW_PASSWORD: ENC[AES256_GCM,data:iboeHHRTQcJnv+33wUCNiOpTk1l/zO+5W8sxaZl2GJ1vyCTu5DR8rA==,iv:FrEPGvc3ilN9Ssf8evTbTiExgCImQDC8yYnwQ4o2w9M=,tag:AI10SfSE5vOlcCOcUbeUsg==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHJmaGhHMzdq
        cWk0Rm43bnNUbG5qNVViL3RyYWp4Y3R0YnFIbkFDOXFGUWwzbko4TnBDZm01WXJF
        Ryt6SFQrZFdIT2JiY0dwSmk3enpDTXdRVStsTm1XclhoNjUycjNYZHZmcnY3WTFF
        NTMvc3lja2xURnZRZVJhM2xzOE1sdjlmdDFvMGdnK21KUVNNRjhoeWdtTGcyNkVp
        SHBieE9UWlAwWkhpNG1xcWVRSHByd25PQkZMam5RS09OVlJ4ek4weisxdjFBSlls
        N3RGN1h6cWl0M3RvL0dDdWVhZ0dJYzBIOWk2My9sdlNXdERFcW5LM1lVRDluU2pJ
        QmZFdnFLb1NJaU9leDI2eWJyUEt2emkxRmxCemJyMUxzTnlxNnp3TzEvekVuR1M1
        TXEyK0hVam1pWmxzcEpBdmhJbnExK0VYSVcvQTVRNzFVRThyWVgxKzBCVG1wWWZX
        Zmd6M0tzazZlV3ZWdFkvNHdscXZiNTdVSGx0UW5ZKzlhMzFPdDd1OVhjeTVGRjc5
        N0I1cE5yMW1GZEV5TjcyVytmejdhc2tvUHJRZ3lHeW1tRFRxMysrMnNRNWNIU1NG
        c0ZtTm1hTmxJUkNzZzJqZWplU2xsd0toZ2hEZE1na2I0NVNkZXptNXRFZDFzdkc0
        OEpEaitGTlVTM1psNkJYelNSVGRudWE2bEdmVnE1QnBuZ0tjVG5QcTV6cVBrTllq
        TFltY2NaSFllVlpjUkRFZHlETldsazg0UTVlMDU2NEF4QnpKQThwYm9MRVZkNHho
        V1E1TjIzZHVVRDl5NlRleXRaTFBtQWdXT1pTa1ZSZGlUTjhRZTJidndKeXhDdkh6
        b3VOdzhGV0J0ZlZaWlJVSTdpY1RtZFhSeTlzeVBOVDlxbVpkRXQ5RVJ0cmdEbDFW
        aEozbG5wWWtEYmpZNTc0anppbnNSenQ3WTNMNFZyMUYyRTFvTDRYSElrcUo0a2RQ
        R0V1VnRBdDNQbmNBNExjNGpGWWZVN2pvSU1CRVFWaVRZdGM5ZHN2Z2hjcFgrWGN0
        N05VZVlSNWMxV2ZzNExFU1FzYXRmRkdMYlRRUG44ZXNGbWRZc2VtT2N5Qmt5QTlu
        VVZVT0ozRENxalR5UVFqUk9MckdXbDJuckZpdVNNT0MvTldXc0J2Znl2c25NcVIr
        UmNRckVFQ292NWt3Ympyc0E4WjlLL1htS2MwWnVDcWp1Z21GME5wbzN1OU5KTyt4
        Zkl5WUVubExWam55MUcvWVN6dWY3dHhZVkRlMFZNYk5XdVFLS2R0NXRLMXJSNFlj
        Z1FqZ0RaNFkzQUhZUjZicTJOMXFlc3I3ay82MXVSQ3I1VjcwdDdxclYzL2cyRC9w
        TUUyWkNkTkEyWVpSZmNaR1BTbHU0TzZwb2N2eTZ4elR4UlVtbVR4RmVVaVNRYnRN
        K2lnWjE2TFN5NW5jUDVNbjhPRHlsZElIeDNHZnU3Q2h1SzhQOGFtdERWcGhxb3hV
        UXdCSUVrbWdMODR5SEd6T3Bmb2lXUzhDTm85WnVDZHVRUlVlRUtXOXZicDRBbnpZ
        V2t6OWZCMWlhVm4veHk2cVpjdHV5VGkrb3VvK2djVlNiTDBGRk96d1A2NmtUektB
        c1k2anM1OENDbThmRWFFdXZSbkpwR2t2bVJBZXV4bHhpTDE3bzRtUm9Ecll1eTIw
        dXVKM2ZaSVN4NUhXWng1L0lUYlpvdWNhWXN0NWpndEkrWXQydEZ2VG9wbUxSUlc0
        QnZoUUdma3F1VjhmQUZ5YTRNdXhSdGl6MWtGOUNRYXFhYW0xYkZaL25Mc21pSW5u
        WVU4OVFSa0VQYjR3ejJtRDVpZmxWZXE4SUdKY3pUdGVhWHBlUndkNExHaENJUkdr
        cUtwYTJTdUtLZVVJYzNUMnNGM0QrbkJxNkZXRDhaMWs3aVd1RG1FVGhlRzlLVUI2
        SSt1cVNkZi9KbjRHcm1JOHYxS0wzbmhOTFlxcUs2ZjJlK0hyR2t3ek5MMzFDZwpu
        NE9CdXk3d2JBQWlnUU1ZVjZDZzJSdm8rS1BJMHRzQnNNY3RVOXduSTIwCi0tLSA0
        WW9HSlpBenZidFdDK1Y0NEJyREFIcVRHTm44alhBVXlyaDdFcU9MSGI4Chdwmgcf
        MftrFUkPo8Iiu0nHxsu6SnyZXuhGkHcPsmQtdSQ43zj6h9+kS7fufyDL7y0VRsi0
        cQDdlsJDs8Zenjc=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-05T10:25:35Z"
  mac: ENC[AES256_GCM,data:RKX0sOnI9UPnd6C8Gj2qTSJYrrTtSeplH8RvSrM/JoDUAmqpDEPR6K960gRCjl/3X4iROisje1OwQ9sKehu4+nA/btmVPvYycGqWfzMbWn+XuxaXOgPyHvgVEpNcTkfcoCgPVoIWd4uEudZ7fy5RixMUZS1RkVEr7zlhLN4jaJE=,iv:5OIxULmojxizxcSivmi0HruDoV3uIZJD5HarW0AW6Wc=,tag:41lusQVFq3Fb8BE1+CkzYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
