# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: groq-secret
stringData:
  Authorization: ENC[AES256_GCM,data:rToePm2AqlwzMMt/Eule+4Sj26zrXaEpFTLOVVemtS1QvI+5Fo33vmU+zfWyh/fibgLcP3Gr+/8=,iv:jko/6HCWMYd3BrN/i8V0ge9edPQq1FchvXBC3tLuwX4=,tag:c8vAQpZGCAyK6xXjACi2tA==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHVyRFRFVWJS
        QUFqZXZOTWVESjVwdHhrSUpaVDZ5dFQ0YjV3cmpRM0FVM3NHaWFvMEVuQnc1eWh4
        NWFQcUJTek5EeFIxSmY5OEMrek5XQ01KVkZLNHdsK2pnUEFlSDFGeVBWTkltR0lH
        RUtXbkI1RFVvMTlyNElPV21JTXVTaWphWGkvOWJoeFhFZ2luV1ltMFN6eFZoUWZa
        QlRMWndvN1I2ZE5MMHdEc1JldGFUdVdpZnU4U2dmUzB2QlJIS09WYzFIYVVVOUVv
        OWhTOXkwNXF0Q3dYZW5TWUg4YW43MDg5WlovaHhqaHp0NFlHemNhYmhPRlcwRTVr
        WXZqV0FHZDk5SUNvZmFMbkxwZlFFb2VxMFJ1RFhMWUtlYUx1TnlzQ0dtRVpldnpl
        UDdVMWJCbC9md0F5TWdxa1FMckRjeWppTEpTcUZ6UXE3RjhSM0pRWTlOMHNDNmJu
        MVNFZUlGS0xuNFppL1hwWW5DekRrVWVZNWZKZ1BDdUJFY01TLzFMVGNockphSTh1
        TTZHK2NxZlZlQlMzbWJTWTNZUnlMWWR6YWFnaWl4UUlsSzFGQjNnaUh6TkR2NURn
        QzBDL28xek5lZC9LeFJ0RVFZMDlLN3ZjT0dWYndPblhKZ2dUb2lJVnN6ODlPNmdZ
        dGRrUC9ORi9tdklEYit4OWNSdlhkY214KzUwSTFodTJGRzcxZW15ckp3Z2l0MDFH
        TzlXVW9RaEoyYnVienV3ZkJ3Vm15Q2ZCWjdKdGdQVUVxeC93dHBTS3VOWVl2Y3FT
        Lzd0Q1lyOWZubDY0a1BVSnErMThGM0w2R1I4TDZNNjVyVE5ZbmQ0Qnp5bHVTWTBN
        VCswSEEzanM3NVd1OWVSWmhzYVVGc1ZvYTU0SU5ESkhONHZSTSt4UW82TTY1Qmtp
        Uno5dTNkbE9KQ0IzcXhaZmh0OXBxVG1LTjdYMzJBTGt3eURmL1RYWitpUXZrZEFD
        OWFQQXNkVVhpb0JQR0FpUmJ3ZkovdWhsbnlLVllHR1ZqMFFRT1c4Q1pqUG5wd2JS
        Y0pJWUZWTW5SSW0vM2JPZzhCb2FSV05nZU16cDNENGdweUtkOVc5Yzh2NFdpbDdU
        aVE0TUxVT1U1Y0ZneUkxcklhK0ZHRWtHWGJGMjd4N2V1ck4vY1NvbDhKOEtFSG5E
        a2JIVkhrZzlYZkYwT2p6cjI2UmtpM0t1VTFPTEJ4OWRDcU1pcWs3T0NlOGkyaFVl
        MlpBdnRQUHNCZE9yMnl4YUVBTTdFTGFaTFBHTkdXWTlaWlY4eTI5U1hiOXUzWm8v
        WUN2OCtoV0Z4dEhkQlVMNzZjWEtvNG5keStWMHRiZnNiQ0s1ZGRyNmszNGU5anVy
        UnF5cnVLWWllV1FDMnBNSjZIVXQ0VTZFcUQ4YlRVOTFhYzV0S1RyYlVaa09NcUtj
        aXE0Q05NUnZvY3ZtaGZ6YlhEQ0paRlRBaUZFMkQwaEtyTlJBMVh6WGwyUmJFbUR3
        OHhDVTRsNjFiZExiUGZ6eFBOejBpRHpGTlVCbldjemFTYWNidGlmSDk1RVk5YW9R
        T25oZUdKTC9SN1JScmNNVzF4aUlSSG5nSXBPamJHeDdwODJrQjkzTXRqa3FXcFlK
        WkdkRmpueGRocCtXK3c4a1BqMzBLSklVMTNaR1l6Und2cXloanp0alFkb01ZU0tF
        YTZvZWJUdVNBNHJnajhSYnBzd0JmN0p1dVFsbmdXRU9JenZERjMyK2tNUThlT0M3
        cm9TbFRkdmMxTkRrS3pndlBoQkZRRjlvKzBxREhDaWJOVzFqVExhK0F2VmtsV081
        OUtvOFRXWnRvNitqREhGa09SZ0hxUEVTd2MzOUI3Z3ZXandOM0pjalo5U1B3QXFo
        Qm9MUFM3MnNua1lRTDlwOWd0TEZaRXNqc1dpVVdVQkM4UEtiV25WQUh4R3VwWVlX
        VjZvZE1WTkJ3bDl3NmxhMUNUckk0UHd0RkF1TVJwSk55VER1bmRqRUdZYllQdwpZ
        aEp6dTFOUlhHcEMrU09PUU92aUNCRjlwRTNQL0tLdmM0V1hKS3RhVWJ3Ci0tLSB5
        Y3VVSDdoNkJnbkVQcUYrUTh5cnExSWtvbTZzdHM1YTNNTHpPblYzODhrCkMWb7PJ
        ao31wwqw9nZvt2qLBDT4iqoCee3BIeSxf+EppTttVUkc8h8CnoxVTzuZwrtHyvNY
        ZItsMrfRvYHF7NM=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T21:00:38Z"
  mac: ENC[AES256_GCM,data:vKSvHbT+/kRcuR3D2YQCBBhVjFFG3JdjEJnQ1QFAAKluvBwW1VW6t/CAzzP/N+ZIi9Qhg0SqgncjAaSwwWKSA0dUmdXCh7VoCkhU02JLcqDl7yHcbr/b4oSB0DqpsfwGdA4QSf59j3Ndt/hyW20Z09jVxklbxF/Qskha5+AdOvY=,iv:5wZWfKM4RL66pprJcgW+c9otLxSlWujnE1NU0pLQnts=,tag:7d7QBQzKhQ0zFOyLT2s59g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
