# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: litellm
stringData:
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:XQe+voWd2vCv3wb1qpiDn937F4Okta/j24jScyE/RL0lNq1u3kP4AF9LBVqPefPV1SPWtgKOIVleDxn+HK6wrBzvzG5NtlvdCxbZ,iv:kf3Wf7odHSYtuW6nP2A5BUiLUi1lfa0uZ/Ig2cu9gnk=,tag:hPAML3pkQ2/yCCQ9IOPZDg==,type:str]
  GROQ_API_KEY: ENC[AES256_GCM,data:qzdUitaJwWrT2ebZPdj0dg4kpkodOIgCiwU2jJgYBYe5qhCLfylAaDqkWKmBX2AJw/jHog06t58=,iv:18YWFi+HGkpM3Qq2NkifKYX6ch+ihVj9t0CWgSu27T0=,tag:1i9jE9+Hr+5npmKEMzAaHw==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGdkUHVsT3Vl
        T3FhK3YvSnVvSHNPOVFrWFZTNnVRZ0pJNVVvMkR1WFlJQy9Db3RRUU11ZDhYQjMv
        bEJoWjh3cVp4Ti9adGpMQUZYYVZTSkh3UFV4N2crenlrUE85UE9XUWRhdjJiZGJo
        UzRGcnJTVnNOK2pQMkpLNmtobkdFTkNqdWdBZjczUjVQaHhxeEZyUVdUczVTZW1O
        aW0wNXk2Qmo0d0xEM3FwV3M4OWV5TTJlL0dMU3RxMW1Ed3lsNVNaYjBERlNGTU1J
        aTdpby83UzBsYWRsTXNQQWRvdWJoU05kRmF4bDZpMEV2NWxEK3Nwd0Jsa1FvQnA0
        ZHNPWkEvM25BNEh0NFh5Q3RNdmRFdzJKUURVcDhIaXBWL3NwTjVyN0F6OVJVRysz
        Ukl0TGhQVE9xVURycjM0eFQ1R01uYnpmSGpXRkMxaUhVS0crekFBcjFnTUhGWDlj
        aGxGbnRkUjJHNTlUZ05CODJlVGdMdVdieThnT2hxVUJxaFQwVFlSdG5BOG1tM05h
        VURXcHMwTEd1ZldhemVxZ1gxdlN3dmdERGNNNTVtOWR6cjJVaWxCN0ZwMXd1Rkkz
        R1UzSDdtT1NBNW1TL1YwTEEweGxScmdkeW1yT0o3Vk4xU3puUUR3OE8rTGF4YnFm
        SUZTcFVpOVFvYjBBcVBHOXE3QUFiTVYvQmg0Y2J2dHlmT0d3b2ZXYWtKcGdXbyt5
        S1Z5U21kdzBKYnRDU3F5TWRqMGg1bFpxak81cWs4Zkx0c1FPOEl3Q3BKc0Z6TEhp
        WUZOamxzNXcxZU55ZVF4VWFCQTltd3F3c1NkNHFsUXFVZE50clVGNkJlVTBpTHhV
        c0lnM0FjVHhtbkU0ZHNxTjB5MXFyaDQvMmk2RjFzRUNEd2hqaXl5OWNWTlFTK0Jq
        Y1I0amhxak5kY0RZcmQwZTZGakg4NHJMN05INUpIZGdXMW5rWmRNUDhlTEFNNm10
        REwyZlMvWkdkNXZ1d2lveXEwazRsQVBvQnRWUS9UM1FJWUpLRnorY09WTlZKNUJC
        QUpLbDlyU0FURG9lMCtXQ3IzZEVZYjhad21SYk5pSEJZck5zb2NOcXhGYXdsMmxY
        QzFnUFQyd3FPZVBGUGVPMTArcm5FMVhpdTRUbUltd1pFNkVML3FndHMvcml6by8y
        ZlY1Q2xjMzljRkU2c1hSMzFhckNqOURCdFBXMDBaa1BBUHZweWcraHVHeGlZb2FE
        QUJxNlhEblJtQzg1RUxDMDF1S3hGaGd0NXNpWXFwekFNbXM3UmpQdWtxLzRpM0dx
        N3V2UlZKRkxETFB2eHBucVNDVWJJeFRWNEVuWmYrbHAzcnVtUlArV2Q0SmNHVkwv
        NTV4L0pKeHVCVjBqc2NLM0FINmxURXhBMVpCSkRNbVpDZG5lTmpXZGYyK1dnQmRo
        RENnNXBvVCs2ZlJBNUl3R1NoV1NWek1zVE1tQmxxZjRrNHU2anZONlBvV0htQTBS
        elNPUWlsaFc3WThhWTZUU1h4SWFjeUtrdVNzZ1lNYUo4c2poNEJMYURzZjRwcGZ5
        b1R2TnpLNkZNV2JPTWdoWEEvQTlxT2NEVnN1bWhWZnVzRk5zV1ZHR3VMMHV5Qkk4
        bVBCalRocVZnVkxraTR6UGZrbXAraUJnRmpKdERxUjVzc3RpZ0dxK3JKc1Q5azE3
        U2Z0TStWQ0c5ejQwc1RxR0s2dE1iRmZTNjhMTEJYVTBJMlpVSzIyS3FXMk9FT2w2
        OVZuVU00S3VPRGN0RUpCL0Nldkl4SVFwYUNyQUluaHp6Yk9VWThFdlkwQ1h6VzVF
        TGt5SjlpMnZJUWhYWUpCOERYZ1hsdStoeWJ3NlhTbS9SZCtFTU4rK0dtY3RWems4
        WjF5QjlqbU0wMXAwZW56Y0JJS0tUSHpRb2ZDejl3TWxSTnRZRGc2cHZvSFd6UDdi
        RklVUk5KR0JoWUJGZFF4aDBPT2REdjZEWVNEcnNHN0RhUm96WnNMak1xT3lNZwpM
        N3RYMUdybUhKemxpYjdIZytqRndSeVJSZDB0cm9hMllGeHRRMXppVmtjCi0tLSAw
        REMyd2ZTc3ZCTXJVVllxeGxTNlFmVjNpVmJ2aTlJL0tBbUVyc3VhMGU0Cm4rYFJT
        70LMphYiS6sdCdY5HIYsUrcr+R7c93IoC6ftm9EPs1RKyB46lkAZ52kGbLe+4Lej
        qpPworSyS+E/dC8=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-11T19:15:10Z"
  mac: ENC[AES256_GCM,data:0CoBBgesbMXbn1alGDtMXlcMZy+/QuzOHSRrFKS5qM4Qw9g15NYqAZbyILsYPTkc6t4Ga8BkJ4DEpXClEx1WnTIlD1xMsfQ4LKkq3APhDZFlhnbEEPob3ssbEfK7AFmEu5vDw15ZBvlusUGAAxsx3U5pMKTGdsJ1tDNBpHzjsnw=,iv:EzaU4uIRCOxlsdx4oSvqPEFbglI1P5umCQXKWbEQn70=,tag:WNHvn/FgWNIzlhUt1y4AJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
