# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: moltis
stringData:
  OPENROUTER_API_KEY: ENC[AES256_GCM,data:L+pzmwkhQ2ugdAZA1r1gbViFypT7Tniua2uNvds+QzhHu6Y6Bq02aNT7jW5wjBvxSdkoQPYUWQ65IR6kG4Um/B+0XHbop02DDQ==,iv:kiI2zA+ymFuRqnhW8eIXGRx9kGZEcTkDVidatWsy7S4=,tag:a/c5TNxvIxzIkW9JEX0cDw==,type:str]
  BRAVE_API_KEY: ENC[AES256_GCM,data:utTJasvP5fyZqapEQKM81sWDsrCh6+7pusfYlT6J4Q==,iv:HTghWfx1tygZhHft3bnbmOlO6QfFQXqCu3R0LvxyX8M=,tag:Mjm3eG+qPkITVFpOlhNqQA==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHEwTW5CQlRn
        ckl3bW9HL2ZDbDZnMXBwYzRPK240M2ViK1ZnSVBPb09TdXFXQjMzVGl2VG9McU1S
        S1M3aW52R3NkY1h5d2Y1RmlmaGRIUG41bjVuWHZONkN6MXRLKzZtN2QwOCs4VWVH
        bitGYkVVZkYyV004ajd2U3lCVVJhZ1V5Z3hkRTFEeFdVODBCOGhDYTB0TFVuRFhV
        MG5QVEVVOWF6K2dSdXhBMkpMb0djaG1HcGg2T0Uzb2NkNC8xWElRa3JqT2t1OS9Y
        VjNkY25RL1VuR3NVUkRkbTBZS0NyUHhqc2F0V2RZRFFZMEtFMTRpZHJFMmMrMlRo
        U0paOFRCTjZ1bEVnb3VjeVAwTmRmSXMvUGUvaHZiTUdHOU1ldEJveVlBRTQwa1Bn
        WDJ2eXJOcXc0eDFEclRTNFY2bmtSbEJhdWJmUGRRMGpPcWk4NkVwU09zaHBoaGFm
        a013czZyNGFkNWxlWkVrTEtMeDZhcnJ2WVdXS2E2Z2pGWWVIL0p6bDYraC84TUJU
        UmdvdzFBREpPOE55NEpJYUt4UWpoeWFTQ0ZZdXZYR0JlU0twQ2Q1anZpQmdaVWtp
        SXNYNEdQbDBUQTNoekJJWXZrcmoxR0Q1SCtpWE4rL1ZHYnh0cmhpNmYwMkZHUzQ2
        NklrRXo3cG9MTmpzVG5lRFA1MjNiNmwwakxHZ0c2emJjelJpaE9UdWNZeHlubXV5
        ZmtNa1NHcnNrbzZCVEZQSlp3OVZDMkN0RVdGNFdJVzYzSEZjNXdLOUdDSGJtVmFH
        ZE9qKzk4RnA0NnBteEJtc3h1WHhGSjBnbUNDZytkL1ExNGpyZ1hIK25NRmYvdCtT
        OU5uSVgydUFCaXZ3QVpVREhwWVFYc1Blai9kbXlnWFNhSVRyT3g3TjNSc2xKaDd5
        dUgwQUtXSld6YU1zNnQwd2JNZHpCRWp2Qmd6VWh0TmNmSklPNFF0aE1jditIRUpF
        SHhyb3g4Q3VLWjE0TE1pRHdhYkRTVENjek1XRHNQT1lNNkx0ei9YUHN4L3pYaytY
        UjhPYVE3UE5vU2I5TlY5by9kZ2w3M3grVnBxb1J3ckFtN1AwN2JJb3pPSkhKcXVw
        U0NjQmV4UnRKZjY2bEZ4aVlJMHlYNm9GMVNybnZLc3lqRFNROVFTWSt6cVQ5dVpt
        c2xMeXFIbVNEYWZXMFBod3NyT0hpTE9ES3dibEF5emgxVkdWeldTeEVCdXpjd2Uy
        eXNndnJDbWh3aGpnMVVseng2WGZOdkNoZ09TK000VDhXMlZ0N2RBQ21TQWZnc3Jh
        QXVWTzdkRVNtMDQwaVB2aG5Td3hYdFBGdGxnUlRHd3ZHL3pVS0d6bGtZeVNsNGlv
        VUNwRWV1eEw1M2hQR1QwZWVFODR4Vm9mY2xqSjkwWE5iczhWUUFTN0gvRzJlYUJX
        UDZKWCtQUkoycEp4Q1lNWmk4V01IVDY3MlRiN29BakYxeDg4RVJPUDhyQ1UyL3Zs
        bUZxYlhycWtnWVl0b2ZEajFwa2JSbCs0OVJlajVUSm4wVWVWbUdzVXRPYTJrWG9j
        cVBLLzdHS2JuZ0xVZS85ZG5kVEhuZ256aUh4NzJ3ZS8zZ3UramgxVWlYc3p5NWZp
        SVFud1RJWHBIaVVEbnFCQmJ0VDBKV3Q1UW0yS0JmbHhhUVNac0U3em1Cb0liVWwr
        UFFPblpaTllsV3ZwbElaN0JFZE90T0ZmVTdjT1J2VkgrY1l0VGRGMCtIais5ZUZ2
        QXk2WnR1QW1EbDRhQjY5NUIvdWpzOWU5dHFJa3VvMDBTTzRhcjVVTlJIRW5kVUh2
        YXhoL1poZTY1dmVoSVhsK2dIVHdFOGJhWjJ6Y2s4WFdDb2hrc0t2RjlOV2JuRmly
        ZkxGbG5xbCsvR3hBQkRGU1RYZTVHZmc3cHovRDd3YlVicUNOYnRyNjlaZndCWEtX
        djcvdGJ0eFg3ZmFHMHNDTGJQQXpwbFA5UjFHMXNzKzNWWmw4aFFkcmZBR1dXQQpY
        QlJoMUw4MVpOSjN6NHJPV0RRaFNLcm1HQitHODJNUXdRYWVvSGdTaXFNCi0tLSBt
        ZUl1TG9tT1JYTlhydmd1OTc5bE1uQUZrOGhYNVZwZjdXenBZSmNWRVpNCoqaRGo0
        3d/UE4S2LAgeYW6dSK7eaZcszP3oqiQwxiz2p/tf2MJxO3m7lcnbm0YGMs+JjdYc
        5gZlB+ietXK87Z4=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-26T08:13:42Z"
  mac: ENC[AES256_GCM,data:2Mi+LkiMHvo/wt+IugXSgOUeZvZ/JxF4TtJ0OfpQhe1KjUUe+SxplKuLEkh2AgfCBPr/DR47BL9G67l6aZxEzI85aq9YAcjJ5oLo6gIsXFcdX5SF9niojTa0XjLk0qUdraQTLspdYqhjzGhqw3ntjqxJEKJzTjXsQGYL0Sd01tE=,iv:ld0tTTsqITlx+6k2KAd5KCaKLK9wIlce+E/7J+BOYdU=,tag:0V8gG2w3xQHluatBAFNp3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
