---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dashbrr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: openebs
      namespace: openebs-system
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          automountServiceAccountToken: true
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch

        initContainers:
          discover:
            image: &image
              repository: ghcr.io/autobrr/dashbrr
              tag: v0.6.0@sha256:55289a0487008f13388e4541fc95079f3d3a9cd660dfba170861dd4b6f0b7292
            workingDir: /tmp
            args: ["config", "discover", "-k", "-y"]
            env:
              DASHBRR__DB_TYPE: "sqlite"
              DASHBRR__DB_PATH: "/tmp/data/dashbrr.db"
            envFrom:
              - secretRef:
                  name: *app
              - secretRef:
                  name: radarr
              - secretRef:
                  name: sonarr
              - secretRef:
                  name: lidarr
              - secretRef:
                  name: prowlarr
              - secretRef:
                  name: bazarr
            resources: &rs
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext: &ctx
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        containers:
          app:
            image: *image
            workingDir: /tmp
            env:
              TZ: ${TZ}
              DASHBRR__LISTEN_ADDR: "[::]:8080"
              DASHBRR__LOG_LEVEL: DEBUG

              DASHBRR__DB_TYPE: "sqlite"
              DASHBRR__DB_PATH: "/tmp/data/dashbrr.db"

              # DASHBRR__DB_TYPE: "postgres"
              DASHBRR__DB_HOST: "pooler-rw-se.postgres.svc"
              PGSSLROOTCERT: /var/run/secrets/root-ca/ca.crt
              PGSSLCERT: /var/run/secrets/postgresql/tls.crt
              PGSSLKEY: /var/run/secrets/postgresql/tls.key
              PGSSLMODE: verify-full

              DASHBRR__OIDC_ISSUER: https://idm.${MAIN_DOMAIN}/oauth2/openid/${APP}/
              DASHBRR__OIDC_CLIENT_ID: *app
              DASHBRR__OIDC_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: kanidm-${APP}-oidc
                    key: client-secret
              DASHBRR__OIDC_REDIRECT_URL: https://${APP}.${MAIN_DOMAIN}/api/auth/oidc/callback
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources: *rs
            securityContext: *ctx

    service:
      app:
        ports:
          http:
            port: 80
            targetPort: 8080

    rbac:
      roles:
        dashbrr-discovery:
          type: ClusterRole
          rules:
            - apiGroups: [""]
              resources: ["services"]
              verbs: ["get", "list", "watch"]
      bindings:
        dashbrr-discovery:
          type: ClusterRoleBinding
          roleRef:
            identifier: dashbrr-discovery
          subjects:
            - identifier: *app

    persistence:
      tmp:
        type: emptyDir
      data:
        existingClaim: *app
        globalMounts:
          - path: /tmp/data

    route:
      app:
        hostnames: ["{{ .Release.Name }}.${MAIN_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: network
