apiVersion: v1
kind: Secret
metadata:
  name: karakeep-secret
stringData:
  meilisearch_master_key: ENC[AES256_GCM,data:dDkd20j5MhP249bsWYj+WjbtrFsM0yLdeYXvFkjXaloCP83W+Mcj/XRE15jH77Gs,iv:RiZoK1SpaSFhxVzDsyyjsk28PlyhQItxl1wpcSR08es=,tag:I9r7SyEe9YOpyDhno0jsQA==,type:str]
  encryption_key: ENC[AES256_GCM,data:V5QBCV4DZu5zwi+DO/liRzIlWpyOHe2U9i2n3P5PgjS0OjXth04Het2iHiU+j1Lw,iv:fakncG0x0ipPnCA4jHa4pdVaMKLL3H1uEvypC5Y/yws=,tag:1basdS5KeJO0ft6v2SMLhA==,type:str]
  litellm_key: ENC[AES256_GCM,data:0skI/vuUbuPQgQUa4i+rCkmTwJT9t33qdw==,iv:3vxeR+dvxDldCdcLcxN4SsCFU1/Rtfe4EmF25SziNEY=,tag:CQZAbGMJr95RSSnxaelu3A==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEtySmYrQUF2
        S2N6REJsLzllTDExRGRuQzBEWjNZVWJReENId0JzbGdna0drWmw5VW1qSE5SYnlw
        cVhPWmpYb0EvVTA0MExuT3hxL0FpYjYxQ1ZHbjZMb3BVV0psS1pNMHRFVjliTjU2
        dEdMS0UyNGlYM1h4dUQxVmFNcElEamtkUUNlRU8xZFBNTEJoVTYyVWNnNlhhdEhI
        QXdHYkNlSG1WR0hKd3QzK20yd0RIQk1NdC9HQ2lrZHYvWjRLSUFpTk9MY281bHJp
        c3RIL1ZWQVJpTlZMaUJybzkyNDFuSEhkdmdCZXJCeDZNNDBsdzFqQ0Y4bXVYUUlS
        UGZxODJMRjFXaUk1SVppczlNMTV3UUxvNHFqMFVrTXJUMmlhY2hDbFQzc0RoejB4
        UnhvZnBoT0pvb2UzSWJmV2xNRFU4NjFFVnVSMEJxdThaeTFkZUZJM3NqTFZpa0h1
        WXEzS0JjZndLZnJua1JPWUZLbWZ5MTRzUFpLZTFqc1lEYVpQckwwNHRBMHZWTzBi
        akJ5S3BiSUJEMTNGSTdROFY5UEFDMDl0dnlRSmJKV1RuMkNuZGtLTXRVQkJJQm1N
        RU83Z3dOV1NpS1cwTGwzd09XazNoZTNLVkZvQVBwQUR3Uk5za3g1SGFmVkFnaGs2
        MWZYR2FQSG5xcjhCekQ3OHhmNVp4M2ZpRkdxenhMeTEyeGsxQjVURTFrQlNLcWhn
        S3Naejl1UDc4WlNCV0dTSGxXaWFtK0tUYzZMZGN5ZU1iNWF2dUZJV3ZMWktIZDRo
        MGw5VTB1b1RRMUtrT3k0NWFnWHZqNTZvd3NiSDM2RHlJOVYzQmpQU0JpNnFWTFRI
        dlNlaW41aDdmTks0QkZUcmRYL3JCclpkSS8rbmQvZTgyVlg2eEl3ckg5bWNDKzJ6
        ZnhSRDVSTGl6N2huWG52Z3YrVklXZUQ4NmNoZlhmd2FybjdmT3g0U01qQm9TNmZE
        N0tiRkpBcitSc0htUUc0cGxsNVd2SFpqRW5kSTI2TDRNMFlyYVN3VXgxY2Z4ank1
        UnR5Q2VDcFJJdzFDMncwSFpqVnNjWW9Sd2lCSXRjd0lKRXF6M25td2gxZ1ZIVkc2
        d1JnOTU2VXlNUUc1R1RvbzhBR0QybEZkcTg3TWtFSnNITW9nSDNOb3hkUnN3RmNl
        K3hoVFgwdTMyR3pwOUg0VGZxWGN3Z09EcUU5WjVqeThnYXlaanQraUxydFlaOXBP
        bnNleUU5eEVBZzhzVldQYlE3Zkp6OFpoaGZ2YVBIeWo0MmNoMWl2bVBCN05tK0Z3
        TkRvenRNa3NEMTBiVWZhU21neHZiZ1o5cXFTMEpYaDg0ajJsdUM5M0UyNDJiT0pt
        aGxKWUFMWTZLeEExWTF3YlExdWdkbWRJVFRiVUJUOThuUmh5SFp0b1Q4blk2Zngw
        SW40RHJkTEdxR2lMNktpSTNnUUdyUFYyaWRtd2lUSkExdzNOelZHZkZGYzdYYjJm
        UEhhY1JmVTg0dWNqL294R0lZMXRRQjRpTVhMVklWZGpQOTdITDZNQUNqSEFkNUpX
        ZGtRcjRPTkRJYWlramRwM3ZvMzNERTA2Y0JMMk1TNE1rZE9La2I0Tk8yR3diRmcy
        ZEVLRllWY0dqWTdrb2JVd2srYzNZMy83SFMzUU9MUWo2OUs1NHBxYTRpVVZYWmlB
        TVg5NXA2T2RKV2VNazZrWEsxWmM1Q3VocUZPSFJDNjExUFpPZVZJMU92bkVvMUg3
        OHN6U2xBdDIyb2kzcXI3OE5ybk0ya1ZvMFdMNmZSLzRWbGR2N2d4VUx2UmFzSlBo
        a3hFZFIwM1ZBVmoramdLV0s2cEdISmNyajNKZERSalNwK1hzbzlURkRRT2JOMDlX
        YktFaGZwc1ppMTR0NDF3Y0o5WXNkUlB2MjRKb1paYUt6ZUJEWGhiSkwwOTRUaEY1
        QXA0bm5teGUwQThKZ1ZMd3cxNWZ6U3dDb1JnRzUwOHc3NmJtQmR4VzVsck9iQQpv
        cVBubEZNTThwVHBWNTlWdmFFWEE1NU1za2QxNzRzWG55YWJQbDZwTit3Ci0tLSBw
        STdvUDcza1EyTEZjeW9TcXdLeFdJcjVickFrczBCWDRKYVlxamZRRW1BCoPgsCF3
        X37AzpE7I19zQgtQMJe05nZTf3SEJ1RMWebX/d/IAY6K7Q2MCihxAT8tG00Ib0gl
        1sNUDdRYP+Gi7ro=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-11T04:59:27Z"
  mac: ENC[AES256_GCM,data:2cXrXQD0XQI1Lc2Z0wiLvfjJAV3BXHj6+kqsJRMp4KPafTu8hiXjDvvFoFoRLE5kVikMzsfSJSz7/d8a//uaEV8kWMbOYtHyH1qdz6Yo/dS2Tr9XO9bbtxd5AqDLKpZ+4f4kPfkJBpKcYG5Ao6S4Nt57pdN6M5bC3LoYZDA8nJ4=,iv:dNiEcRXpx1EjtKvbgA4dHwFf9S6CrwrNvDJHFmgtkw4=,tag:Js7uWHYV7M2sSkhFkROSUg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
