---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app trek
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/oidc
    # - ../../../../components/database
    - ../../../../components/kopiur
    - ../../../../components/secret
  interval: 1h
  path: ./kubernetes/apps/default/trek/app
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
      DOMAIN: ${MAIN_DOMAIN}
      OIDC_DISPLAY_NAME: trek
      OIDC_CALLBACK: /api/auth/oidc/callback
      OIDC_DISABLE_PKCE: "true"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
