apiVersion: v1
kind: Secret
metadata:
  name: dawarich
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:djODz3GnCUBK1l/pLwvggHBfUmiZ45mxyEvPOGZUUhm+9njptksGdSdONZkkv5iQL8DuLOysMO9cSblXMKvUl+MzRmY1QYPbaQbNs52TGY9kv/QIswtL8a0/jIm+7Jy69bFlN3y0RjjFNHTb+IXX58bOixWJumURXh9nmkNtZSo=,iv:+DiOGiGb47mKsGRHuBSbDf6eSAM4fC3rnjAOoo7MrLM=,tag:0xH90WFa9IPR1KGnw+Tm4A==,type:str]
sops:
  age:
    - recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMFZxc0VmQkV2VTRqRzBC
        ZEJ1ZXFSZnJhT1V4TlpNbThlSjgvUVVkUG5rCk1wN2YrTGRscGx3VmJIeDE5bE9O
        ZTFXVGFPNWliQW42Q1YzS010OXlDWVUKLS0tIFZOVW8valF3Qk1leEF2Tk9zODRM
        SCtFeWJ0bHFFckczaklHUVJpSVpWQzAKAUI6+DE3TugGIRnGo8qCt8wl4ubGotc7
        cqlAFMJjIyHkOufNZbq7Bq2/Ex4nwq0wq5f8FbAQB9O+sB71stuIew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T01:24:30Z"
  mac: ENC[AES256_GCM,data:JeudbPObqNaaD5wQ63PXKUILTcOm5rkSuGGt3xqmSBwDk1Z1cS/5riHYD+CNkEZaB5Ivw/CviPFDueg/YWPpEjxBNpwS1L5G0bjHqRPHUSTCOcoTUK1DFZsa2aQDqa/itlwzZOQenSzbcgsKfR1f61QuN3E7ecoVlgz0MU4GaiA=,iv:V66yuiuvs9s3XBCR43hwAkS+qs/2rWkP1V3VW99q32s=,tag:U7GlAdhXBh/9k2RNh91jTA==,type:str]
  pgp:
    - created_at: "2025-06-19T02:12:25Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DC0EwVK2S0BUSAQdA/K0f5jrjrvPEk+D73ZbU+juAPhUC0moI8jsBkKL7gDow
        JeFcZJU/oQBa4IKMPbViXnZ4lphIpH38zrnGiZceCivu/iIatO8qytT0S44/j7H/
        0l4BuD04Jg+4d0Kv15lcAMeZaB1LCDLXqnVzap3nzNFHSHZv8IhKb6g6MWEkUr/y
        htdlMndiSLw816xZMy8+F5y5fRdaze3LLd6N7ryDC65w1wQA/TQFnpMcliRVSxgY
        =nW+9
        -----END PGP MESSAGE-----
      fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
