apiVersion: v1
kind: Secret
metadata:
  name: dawarich
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:djODz3GnCUBK1l/pLwvggHBfUmiZ45mxyEvPOGZUUhm+9njptksGdSdONZkkv5iQL8DuLOysMO9cSblXMKvUl+MzRmY1QYPbaQbNs52TGY9kv/QIswtL8a0/jIm+7Jy69bFlN3y0RjjFNHTb+IXX58bOixWJumURXh9nmkNtZSo=,iv:+DiOGiGb47mKsGRHuBSbDf6eSAM4fC3rnjAOoo7MrLM=,tag:0xH90WFa9IPR1KGnw+Tm4A==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDlWRnYzNFZR
        b2tnV013ZnRLdnF4OVpRRHJZL29LWExzcUF2Y1B1YW50UHZwdlNQWUZ2T215S1ov
        VGNtb201Ky9XeFFMSzZnbkFDWmk5V3pIU283OTdzVlVQSmlXbUtzZVFMVVQzVXEr
        N3BBZnd1TDRsT2VGVVlHUTZJdnk2d2ozaGJhY1NSYnZiYW1LUXVGby9yV0hFaWky
        NUkySTRCeTNiU2F4ZDdLTTlvWDJnemhmakd4NVpCUUdJc0lVeHYyK000S1hMM2th
        dDQ3b2h0UW5xMnl3bzgrQVlKOTZNZGlDV1NGajRtUWM1Um1PdFFsRllKOUM0VTcy
        WVZkQlV1RUVwQ1NBejVoaFRnSG44TFNPRXFXa0NieDRVYXpjN3BHSk9XTTZSUlRF
        MjkvWkRrMVFHOTBXTjIydlpGRjVaNkdvRkVnL2cwbXJOQS8wYWp1WmRUL0lwU3hH
        TFNuWVpBaktxdlBTZVVtYUM1YndBcFdJTTExTW9NSWVMQXk1R04va2MrWDhLMndN
        d3Q0dEN1TXZ2ck4wYU9FVk9COHdjRS9WNzNqc3BLdnFRMnBwYzhuazlkVlpDOVZY
        M3FKN2NEVm96V01nVlBVYnVvZXEvb291OUR6T0pnOFFkQ2NqYmpRZ29ndXh5NzZ2
        S2o4VjZINklNMy8vT1ZrUEQxV2xEQUNmTWx6aVBUTUxTMEVwdFpXb3B6czlJbWQ5
        UnVPSTRxUVRTdVcvY2hmQnVYZHgyTWg4c2w4aXJTR0d0cHhlSm8rVEZOZlBYeWpK
        QW5qdEhDOEF1ZVFWUkhWQVhXbTMwVjN6eEZuaWllbE03VjhLRVFiSlJDYVNEd2VI
        ZlZ6QU9ZUlJlNmE3ZEZoVGFCb0phYm9PeFJuRm96SlphSDhRR2dKN2Q0R0xmRkhR
        WnM3bnR1ckY2OE5qWm5qMzk5TVFZb1FuTXFXWWtjYzhPeXlkOVNXQmNCMXRrVlZ3
        WGpndmJ4S0FBeGViSHR5NjlSRHJOWEszcmg3Sk9mbGRiZkFSdVZoSXIyNExwY1Ex
        ck0zYnp0NnlTMmp1TzEvcFRUOU5rQ21IZFRQWUxFWFFnb28zaGhmcUx0TzFBWVY3
        dzBpQ3pmRzNkYTNPL1NPMXMxZEZSYmMrVVJzR09EVkhhSWZWbGROZnM1dk1NQ0I3
        UmRtYzBDVHVEZTFuZ29lV0pDaXJQdWpXaG1HUnZtYmFDL2RQU3hoa09XVFdSRjA0
        S0ZWWWxwNWpVOUhwYW1jbjVOVjVjMHVQUkV3R2NLaTYrc29qRERHL09DSjExdjlt
        SmVNMDBnWUVFRTQrWHVwaEcwS3I1ck5RY0VITnJuMVFuTWlOdGU0S0dZQ2FHYWd0
        VzVVL3RVV05KaUQyWVEvUnk3NEFRZFErS1VnVmNveHAzTm5zYTBWRnhGOVFOMW5y
        ZnJZMkVxdmNmQzBaSDc0WTF5UzZSOTVYL05nSi85eVVmVVRaNVRoZlRMeW96UjI2
        Z1NmZzNTSXhFQkp0cTN5QldSNGR3Q29hdTlyRlFscmFJNDZZbkNrbENBNEhvZzBT
        cVlVSlBmaXp1NFV5YmJNLzdGQXk5cWZxWHFqVmZGU0ROdHg5UTVOdnBPbFRyRThC
        RWVPMk50ZWtFaTZCbDRkY1laOUFZM3NVa29EVVFnSjVVQTExa081eG5TVGZnVVd0
        aVcyV1JkYjNwd1FvNXNDeTY4MkZ0SXE0RnVyeHNTZEVPSXBHcW5rTG4wUGI2MUhE
        d0pNWHFMSFdsRnNnNmNoTHI0TkVHK0lReS9nRFZFT1ZCQ283OEtmMFhTdTRISTd5
        OTdQbFN1eUdGazgrUXgzWjZyNXNLQVRsa3NOb0VMOHlOK0NQdWJHYXdzSWFiTlBj
        S0xWTmM4eFhjY1VCQzFnTjhFRmdBVmJwRGdwNU5TeFNPeEo2SUdaWjBJeWFxTWxt
        SDVQNnBGbERQcHovYnlobGFYd2dmdldoc2hSRC95cnVLSjNvV0JPenlzNnBLdwoy
        MUcvZnJ0S3N6V1U5dEYxQUhhbGdpV1liMitUeEVJdlpOVUwwN1o4a0JNCi0tLSA4
        ODVIUXM2cmhhSXo4bnZKdFlJMllKVk1vcjQ5UjdPU0R0L2U4cThhcXdzCjD8oetE
        gXoDtk+hwmWZwkSFWMP0nZrCrK1MUJ4wGNpOtKdvlqrKF19U0d/83ja3BJNYYhE/
        o5xrZrIGKd1v+Xw=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T01:24:30Z"
  mac: ENC[AES256_GCM,data:JeudbPObqNaaD5wQ63PXKUILTcOm5rkSuGGt3xqmSBwDk1Z1cS/5riHYD+CNkEZaB5Ivw/CviPFDueg/YWPpEjxBNpwS1L5G0bjHqRPHUSTCOcoTUK1DFZsa2aQDqa/itlwzZOQenSzbcgsKfR1f61QuN3E7ecoVlgz0MU4GaiA=,iv:V66yuiuvs9s3XBCR43hwAkS+qs/2rWkP1V3VW99q32s=,tag:U7GlAdhXBh/9k2RNh91jTA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
