---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: wordpress
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 29.1.1
    digest: sha256:7523872699c0e63fda9db0070e044ce76df4b7ed66ebe61bfef429ac168f144f
  url: oci://registry-1.docker.io/bitnamicharts/wordpress
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wordpress
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  valuesFrom:
    - kind: Secret
      name: wordpress-values
