apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:RwfDFbO05tSXWoUC7ou+IJYDtlpNhWzKUAWbOKkM7aaw8T/hLAeRPrKeIC4=,iv:/NlhNF0j6bGcDeWG3OyCCvo92jgSIp6bnpn6ovwrvQg=,tag:M6ICh8NNjS73O5IUIhRCpA==,type:str]
  GLUETUN_CONTROL_SERVER_API_KEY: ENC[AES256_GCM,data:HpxTMlGE,iv:KuZJ48OgC8D3E+xznbJxrHNONdJjb1NbP3ixTN/ItLg=,tag:9m22uyV7B5SR+IFt9NJfsg==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDNTcEdtT2hr
        MkZ1d21ha2VqYmRFNVFjVEpOazBRazhjRkI4WmlUOXZIN1JtazhtSy9VVXNLUWtl
        ZTNVUjloTzBLbVVzMWZNTE0vcEpmeDV1UGQ2SzFaLzlReW1QQmNaZ1ArckxtWUFv
        cldHSm9SbVgwS0lHSmc1SDlzaGlqcDFKR0pzT3BtbkZvMW4zYTdvYzZZSUUyS2dn
        aUEzR3AxSWM3TGlBY1pnU0tOVVQ2aWFOVzQ0OUZPRTZaeVlMOUV6RDZTOGRKbGJ4
        bDNxblNXeXhzRTJqQ2ExdlE4RElTdjQyT25abzBwTlk4QmZOamVKeEtVM1c1dklt
        emE4V1dNczBkOXJPbzJCSlNSV2RrTDFGeWpNTWJUZWExTGIwWHB0QXRoNWlucmRZ
        ZExPbURwbmd5WGJUM24rdVBSR0hQYWIzNkkya0VZeU1qL0I1T29kU0JnN216NlJq
        eWJjZG0vRUZMQ3VHSjhnUVJkRVRBRjQvZ2VsckU4NGV6K3orRGp5cUI2eUtNM0ZD
        MG5PWTZDY2dNUVVsSDFMZWlQRjN1N3F3TjFPVWJKWkhKbWxsNDdLQlA4bVpiN0Ez
        dFIreGhpVWVHV0lVc09ZajdJWXBGTmVud2ZvQ2ZoWDd2Y1JYZVFNSVhrbFN2K0pt
        dnBRZHlId2V6dXNoekd3RmVGRUpaUlZ1aHAzVysrbmZQZStyM1krb0ZhNXVRSWM5
        S3AyRWRkSjRYeFQ0Q1NDNU1vbnlJb2l2UHVXYmFWMWpOTGROeWJ1eEJ0MGQ3VDJj
        NitUZmJvdWtWM1JhMnpKeWxZVzh5dm1iR2ZEa3BYWVk1MnI1S2N1MTUzdjNuMGlY
        YjB4UE4xRzUyV01YYkROWWNxQWJDaTc0cGYxR1JDTC9TM1E2Mlk1ZU85Zk15dnNj
        NmlDNDhORSs2T0JYYjczRTlWN2t1ZVZnOUp0UFpjV2wva1o3MHdhYUN3Rm5aeDJL
        NCsybWQxb3FoSXlJUHBzMlMvUEZrMStzRGRoRVJPZXpHUEFPSHdQUHA2VVh0eFpm
        S2pMT01kVi9CQk10YWwyb2hvT0JVbXAwNkg1TnlXcDlpK0RERDJCVnZkNFVUM1U0
        OWEyMFhMVzBXWTh6Sy9nQ3QvdlJHdXA5c1I3L3FiN25CQ3VicXF1MkxBL2xnekJn
        ZDJMVUI3Tndlb3ROWHVLT0UrMCtBVzZRUlliSTNXWmtqVEFUZ1BGd2lxOFR3enMz
        WVNoMWpyVk0xQVhqMUR5MHJ4dUFoOEhYbU55bDFnOHNrOFh3eGlMdXBSS1FYMFVD
        ZkxJeElRYVF2R0dLOWxDdm02R2VjWTRaVFludVN6eVJpTHZlSFhueHFWd3c1RTZG
        TG1MVDRGeWxCbUZ3dit3UTg3N0RLSXdmSEpLV2NEaWNETGJ1Qit3c2xxL3lQcm9R
        NHowY1V1YUhseHVYWEJ4NEtjbjU5eWF6Z0tWNHY3dTJkd3M5UUtHb1BDWmNJNVBL
        aVVtWGdydE1wVEJlREtNc052R2o2ajdaQmpGOVBLTFRqbDd4dGgzS2ZVNHZYWkJZ
        aEN3WWREWkJ2NHZncjJpRlU5NlNOV3EzV08zaG1YOU1wWlhIYy9uWm42eUhMbTdG
        ek45VmxXelROQkVla3g4Nmd3RXJRQkIzVjJEa0R6OXZheHAzbGdvSldWTUVlbVhT
        eENmdm5WZ2ltL1N2M25ya2FEVW5wNm0xNnB6MVNDR2V3b253eGp2Zy9jZDNOYXQv
        bUFtWUJMRXZXQzBUSS9mVk9ZaHp4Q28zK3hEOEhYYnhVL2NiKzZpNm84UjR6TVhY
        ZzFjRzNud1BmNG5mZ0V2ZHNQaXRXYlFGdGZ2a21YVVhueDB3VXMxZmh5ZHl5YXps
        TFFJN2R1dy9SVFltUGtiN2FMay82Wm84YkZBTkozU3R3bjhiMXBUM0tmcWRTdjJy
        V1RuazdHK0xMQUZBb3ZGT3V1b0oxVnkxZlVpQlFCdzV4Y3BINGRIZDNLUE9HdwpP
        Zlp3R3VXY29TdXR0Um5XUjJuYVhmSHpFZElxUzJyMFZMQTRVN1EzcVRrCi0tLSBD
        RmlOeFMyTGlGL0hsL3FLdjFaTzNTZEZsVGJ0NTRDaG1JZStSM3VkdHFRCpYHERfo
        bIhy03ZOm1aHfSl15bk0/ErLXe+3Tyak5LJQ4lzZocgMrkIZKU+b+1ICvPS1DNkj
        CjotNbAKr+yRvnQ=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-26T00:43:56Z"
  mac: ENC[AES256_GCM,data:YeJiQ1QlYMP+uWCkm4geZvCQqCnQWA6galyvAew1Wy3h4mwL9c0pyI1pRjpncf3C2KoQ+LEb1jelXKL8vo/XxleYfSMeQH1pQD02H70fzg5Y29C9r8YVD5OcIAcvvzSGZ2KsLE+999QowpELskKhTRgFEaGe+S/t1go6nDC38dg=,iv:A2olL2OtZYWlYik9PEvzHRmI3IOh7oF0mgB/Ihil2c0=,tag:sxjNhSo1HtO1AVrGBzXREg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
