---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-forgejo
spec:
  schedule: "@hourly"
  discoveryFilter: m00n/*
  image: ghcr.io/renovatebot/renovate:43.59@sha256:bbde9510bd177bfe747530c7abf4fd6c1b6f905623a7725bc744dcdd5b8097fa
  secretRef: renovate-secret
  provider:
    name: forgejo
    endpoint: https://git.${SECRET_DOMAIN}/api/v1
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_GIT_AUTHOR
      value: "Renovate <renovate@${SECRET_DOMAIN}>"
    - name: RENOVATE_ONBOARDING_CONFIG
      value: |
        {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "extends": [
            'config:recommended'
          ]
        }
    - name: RENOVATE_BASE_DIR
      value: /data
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    - name: RENOVATE_BRANCH_PREFIX
      value: renovate-
  extraVolumes:
    - name: renovate-data
      persistentVolumeClaim:
        claimName: renovate-data
  extraVolumeMounts:
    - name: renovate-data
      mountPath: /data
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  webhook:
    enabled: true
