---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-forgejo
spec:
  schedule: "@hourly"
  discoveryFilter: m00n/*
  image: ghcr.io/renovatebot/renovate:43.59@sha256:38d2e54e1dafc61c58cb231bca4cb4b0bea7bbc7236589abd56be55eeaee62aa
  secretRef: renovate-secret
  provider:
    name: forgejo
    endpoint: https://git.${SECRET_DOMAIN}/api/v1
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_GIT_AUTHOR
      value: "Renovate <renovate@${SECRET_DOMAIN}>"
    - name: RENOVATE_ONBOARDING_CONFIG
      value: |
        {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "extends": [
            'config:recommended'
          ]
        }
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  webhook:
    enabled: true
