---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-forgejo
spec:
  schedule: "@hourly"
  discoveryFilters:
    - m00n/*
  image: ghcr.io/renovatebot/renovate:43.104@sha256:8248aad190150ce3f1016f9e93b45185679f075c428bca093e724a59f1fd426e
  secretRef: renovate-secret
  provider:
    name: forgejo
    endpoint: https://git.${SECRET_DOMAIN}/api/v1
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_GIT_AUTHOR
      value: "Renovate <renovate@${SECRET_DOMAIN}>"
    - name: RENOVATE_ONBOARDING_CONFIG
      value: |
        {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "extends": [
            'config:recommended'
          ]
        }
    - name: RENOVATE_BASE_DIR
      value: /data
    - name: RENOVATE_REPOSITORY_CACHE
      value: "enabled"
    - name: RENOVATE_REDIS_URL
      value: redis://localhost:6379
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    - name: RENOVATE_BRANCH_PREFIX
      value: renovate-
  extraVolumes:
    - name: renovate-data
      persistentVolumeClaim:
        claimName: renovate-data
    - name: dragonfly-stunnel
      configMap:
        name: dragonfly-stunnel
    - name: dragonfly-certs
      csi:
        driver: csi.cert-manager.io
        readOnly: true
        volumeAttributes:
          csi.cert-manager.io/issuer-name: dfguard-client-ca
          csi.cert-manager.io/issuer-kind: ClusterIssuer
          csi.cert-manager.io/key-algorithm: ECDSA
          csi.cert-manager.io/key-size: "384"
          csi.cert-manager.io/key-encoding: PKCS8
          csi.cert-manager.io/key-usages: client auth
          csi.cert-manager.io/dns-names: renovate
    - name: root-ca
      configMap:
        name: root-ca
        defaultMode: 288
  extraVolumeMounts:
    - name: renovate-data
      mountPath: /data
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  webhook:
    enabled: true
