apiVersion: v1
kind: Secret
metadata:
  name: renovate-secret
stringData:
  RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:kmY3q0DeC1Lv+hJPBlZ7g6Zi27jzsqa3VExrQeXRh80oE2BlzPjqsA==,iv:c5Cv/+zPJwYRf6+g7gpGdAA9GwPVelRdDyENJJMCoSo=,tag:SkpAyCGIXOPNTiwd/vx+qQ==,type:str]
  RENOVATE_GIT_PRIVATE_KEY: ENC[AES256_GCM,data:dMMsJ8twkuOd7q+9u5ICpiBgF+mEZYj9kI8Oo/uQ4v9C7iWlaRFY3A1KmfshjRaeEMF85ZgCF8nTi7Rd9SbS/6ZcgqhaLJT9tltaqgW9TxxDAbj7rM90G/SAbhb+ba6kbaK4ciQiW45LgVUC055HmspNlGwza5pdUkP4KH0nHFKn7rDt1dckUXpRBqorxsFaaHnh0p+pSjct3kI44jlYLmXu22NfebjQT2AQ1dvJsmz5BHu0T31wdiFDFPoEm1Nhh4MjcQKOJOPNl49tSnM+YR0Qye7Qe8ntUK1y4la0GjkyGSQzL7OMmb989LUbPiuD0K85vPVDWqEcddRiBWwRpsRCVXVTGeShjqbd0knRXKMD9GNszi9mvd/28Y8C7x6LTyEWrFbPX30X6nvT+l6KHbXimjY1uJbARoNEwr3xHcCGJ2UNHXKFTKFcLGEqYwJvWFg9b4xb5xhB1pmXGqUWlJ9HfHfwYn5su+B2x2UXD6KY0Wp9N5jI1rIKTgBSqty6SOhke8s3WodW1bNd00nudVo9E/Vn01oZokTinRkqitBu6iNNxK40D3tsloL7hgWXOLGwujPlQ58lYaS/9mkijRWukg==,iv:N1xYoOAyAyjAmTbx5e0BMVCF+KDTpbnmkF8fWRCe2Cc=,tag:mauTLjmoxoqr35pC/+BHJg==,type:str]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:reijQfhBl5cMYLHckoGGDMbXc7fwNSjZwL33g0ewqbyqYwCtfBHN2g==,iv:hG25RLeZwBhbrvi9+k1q0stUnmkNzWUAGJjnIj+eG8s=,tag:aB4mZe3g3nUFr7R/jtiENQ==,type:str]
  RENOVATE_HOST_RULES: ENC[AES256_GCM,data:O3nxfebzt+TR/UIErctFRdiiPFI/9b/EKENHj4GqICTQL9cZINjYqFWK7vZz35wj6i84HNveRBYbg/OFK8kCc7X5/kQd3XxbB35BbHt2MtW51w3B5hcapt0JmAdYe1T72RN9GXDAWteearjWsY/sO0MLvAtPVjH14Vatvqe2MUoNYSRIvIWbqK1zTqeNfd8xpSHrFhjvn2lzNg==,iv:6sl6TAAhnFlU80Zfwpe70j0Sz59T4OVFKRXSa39sRGU=,tag:1zV08KaUQ+4UbmtHItMlZQ==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFd5eEJaRlFB
        UWRjOHc0M09oSndDSHhOS2x6YzBWcUZnd25QL1VSN2QwQ1VqclNCLzZiUWRIVHln
        eUYwblZDVml0QWFvWU96Sml2MHdRMXB2eU0wb0RIeWRNK3BCNnhCWWQyUGZ2TmpV
        SHpEU01kN2hLZjRwbzR2dmw4VnV4Z1duL1QwQnZzVDBVSmhqem1iaHo0SUMxaXFU
        MlBsRjZHcG81YzR1ODBxTDcyTzgyN1pvWXdjQk1YK3BFQnpWZXE3amRWRGlPTzNl
        aTZiLytwT0RPcmMwQW1vdWdSOXNEeE1aRHl0WUZKWklkaDFPN2pEWjlRS1JOS2VR
        eXZ4UWpUbG5YRUM0M1cvOFBGNzQ1My93c2M3em9hVkV4QjU1c0RtUmxkVzc4ZW85
        MU1heEdHVGk5RmFrRlNIREo5NHN2aXVYbEl2SkdYakpFeHdXMCtqOXZxb0JJUHdl
        MGNiTXZUNkt0MmdIREl0UTEyVkdZSGVrWGJEVHNXMGF6QVR5dk1kMVR2NzJUVURN
        UlpQNVJvZnZ0MFJtdGd5VTcvSmxKVmpsYUhFZnBaT3h3TWg5a3gwZ1hJN2MwMW1U
        dkhYL0tkRDhPR1V5andlS2k4RGtsSVpWRjRFbzE3eFJqVE9kcTYwcXRXQlgweGkr
        T0ZyWXZJN2htWWdGaWZVaXE5YWJkUk93aTlOWWRnUGlBd1FVMThoc1lRY0lZNDR2
        QzVRRncvRFdrSjNWYWhxM2dDam9QZzJDeDQ5QnlwZVBoMjgwSUM1VEIweGZveHdL
        STZjbThsYVRoNCtZVGlBK2UrZFRxclFZbnlRQ09Edmp5d2RNU29SNzJROTBCNG9S
        ZzROU0hjODBKT09vdnpZeXNPWEpzdjJaTTQyNVJvYTRTOHVCTmkzWUFvcnBrMmk5
        K1Jtc2JTaSs0d0JzWWhEUzMzVEtOMDkzOWVHTlUxOXU4TERoN3NiTXlmUXArcVBu
        TVo0WHRqNkp0aTNBRUQvMUJtQ0JmWk1IUzVmYzJaRDlSY21HVG1LYjlBdFltYUtH
        MlNWT2dBY3lkRnAvemFneG15T3VhSEFOdDVraDlhSmh4TjJxcGk1aG5Ucm1GRk8z
        L1RUK2x1aWdxczNwcW5XVE51L1g0N3pjTFczKzFMTFdFMjBRak0yRUU0TFJaMGpo
        T1MxWVF4TTdYT0dqVTJrb0wxRXh3cW5QcjZFYkNrREx5V3Y0VkRZemFSN3ZyYU1G
        bXZaVzJld1Rnc3BCTmorNmtFNTFPYU9QeHNJK2pIOEhRd1AvekM5bm8zcDVyZm1o
        Z0pLV3VOODdPVi81S1ZWendnd2JFMzVxeHZLby9JbTh5aWRGMWpxM2g3OWdSL1dY
        RjlmcmxrRlZEamdvVERFbGpvVjRVR3dIVUtWNnAyY0FiQUJta1dqdTlDaG9rOWY0
        MllpZkt6UVpZemQyOTBEMlR3NVRKVFY4NytCNDZ2enZZZWZBY0ZVbmJiKzlPZ0ho
        NC9VcmN1WVU5QXh2MjlaT01rclRxZWIzZGhxYjJqdmNpdm53TVJETmtwTUlmNldC
        TlZ3bmZ4cTNwc0NhZ3UzU2dpTVNrU04zSEJENlNCc0h1amVUVjNHNEJSQ2tiVnVr
        YjF5c2M2K1BFQ085TjhITW05UkdOQWovMFpLVlVCUE0wNTRDSnZBWXUyTjZVS1FK
        Z2RILzYxOGdONWx1KzFtMG1jb2RoMGI0OGRSNUVxRFJJVlQ2SG5mL2ZyZDhFWDhY
        WHNNTEErRDFVNGtXYmRjOFdUL3JKdldaeFp1clhxZkE1cFFHMG16bUtHNzI0dkR0
        UDN4NEZiUWZ4aHR3L3lPV1p2UUNwMHJGRnNnc0t5bkF5c2lTTVAxOW80Ujh0bEU2
        a2E0cDBwWXNIQWo3UUp1ZzkzcnRiU3JoRHdVNDhwYzVtcVZzQkFJSEFsdGNwQnNh
        S3pnS1Q3VFFhdlEzcCthVTI0WlNNSlMxRVVuZi9RenEwS2pmR3N4VWlpQlpIZwpj
        U01PeE0yNlNucGZyVlU0cjNLVXhCeW0xbVJMekd2ZWdQOWZVOTl2L2YwCi0tLSBN
        c0NqZDZZUGlpeWw5S2lnVTcxK0JuNXZsQUFjWVN5cFR4U1R4UnkwRS93CgR3A3yP
        IfBC3pQ/WMF/k3JtAAmEZGGLK9vKGVHmhxLZcH8cvSO9wtoGKb1oHLn4p5DmZHzA
        P1ObBnWsvIp+70A=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T06:44:08Z"
  mac: ENC[AES256_GCM,data:BxD14rCetKGWFipUjGDf43W5Uex2bCYbCtjMDwJmy1Fc3/xUeqSlVpDi37M/CiInsdssUz6ehk/WP+PgqZIfesqFFiwLXTlbxELkZNUBWxu+fbsegVD6zUOJQ3RdNwMCXFUpYhUBiiFpt4kEui0InjVWJWkFMEYHlsR7LdG8PT0=,iv:wRUfMy+IVxxTyLnmt29cWVCdtpLSj23r8QHN8TTdMsE=,tag:XEN0lcWWvqroP/x3Hxn6xQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
