{
 "title": "ZFS2",
 "description": "Graphs ZFS ARC and ARC L2 Hit %, Hits, Misses, Size, and Zpool",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_exporter_build_info{job=~\"node-exporter\"},kubernetes_node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ZPOOL - Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "irate(node_zfs_zpool_rtime{job=\"node-exporter\",kubernetes_node=\"$node\"}[5m])",
     "legendFormat": "{{zpool}} - read"
    },
    {
     "expr": "irate(node_zfs_zpool_wtime{job=\"node-exporter\",kubernetes_node=~\"$node\"}[5m])",
     "legendFormat": "{{zpool}} - write"
    }
   ]
  },
  {
   "title": "ZPOOL - Ops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_zfs_zpool_dataset_reads{job=\"node-exporter\",kubernetes_node=~\"$node\"}[5m])",
     "legendFormat": "{{zpool}} - reads"
    },
    {
     "expr": "irate(node_zfs_zpool_dataset_writes{job=\"node-exporter\",kubernetes_node=~\"$node\"}[5m])",
     "legendFormat": "{{zpool}} - writes"
    }
   ]
  },
  { "title": "ARC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "ARC - Hit %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(node_zfs_arc_demand_data_hits{job=\"node-exporter\",kubernetes_node=~\"$node\"}[5m]) / (irate(node_zfs_arc_demand_data_hits{job=\"node-exporter\",kubernetes_node=~\"$node\"}[5m]) + irate(node_zfs_arc_demand_data_misses{job=\"node-exporter\",kubernetes_node=~\"$node\"}[5m])) * 100",
     "legendFormat": "data"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_hits{job=\"node-exporter\",instance=~\"$node:$port\"}[5m]) / (irate(node_zfs_arc_demand_metadata_hits{job=\"node-exporter\",instance=~\"$node:$port\"}[5m]) + irate(node_zfs_arc_demand_metadata_misses{job=\"node-exporter\",instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "metadata"
    }
   ]
  },
  {
   "title": "ARC - Hits, Misses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_zfs_arc_demand_data_hits{job=\"node-exporter\",kubernetes_node=~\"$node\"}[5m])",
     "legendFormat": "data_hits"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_hits{job=\"node-exporter\",kubernetes_node=~\"$node\"}[5m])",
     "legendFormat": "metadata_hits"
    },
    {
     "expr": "irate(node_zfs_arc_demand_data_misses{job=\"node-exporter\",kubernetes_node=~\"$node\"}[5m])",
     "legendFormat": "data_misses"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_misses{job=\"node-exporter\",kubernetes_node=~\"$node\"}[5m])",
     "legendFormat": "metadata_misses"
    }
   ]
  },
  {
   "title": "ARC - Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_data_size{job=\"node-exporter\",kubernetes_node=~\"$node\"}",
     "legendFormat": "data"
    },
    {
     "expr": "node_zfs_arc_metadata_size{job=\"node-exporter\",kubernetes_node=~\"$node\"}",
     "legendFormat": "metadata"
    },
    {
     "expr": "node_zfs_arc_anon_size{job=\"node-exporter\",kubernetes_node=~\"$node\"}",
     "legendFormat": "anon"
    },
    {
     "expr": "node_zfs_arc_hdr_size{job=\"node-exporter\",kubernetes_node=~\"$node\"}",
     "legendFormat": "hdr"
    },
    {
     "expr": "node_zfs_arc_other_size{job=\"node-exporter\",kubernetes_node=~\"$node\"}",
     "legendFormat": "other"
    }
   ]
  },
  { "title": "ARC L2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "ARC L2 - Hit %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "irate(node_zfs_arc_l2_hits{job=\"node-exporter\",kubernetes_node=~\"$node\"}[5m]) / (irate(node_zfs_arc_l2_hits{job=\"node-exporter\",kubernetes_node=~\"$node\"}[5m]) + irate(node_zfs_arc_l2_misses{job=\"node-exporter\",kubernetes_node=~\"$node\"}[5m])) * 100",
     "legendFormat": "L2"
    }
   ]
  },
  {
   "title": "ARC L2 - Hits, Misses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "irate(node_zfs_arc_l2_hits{job=\"node-exporter\",kubernetes_node=~\"$node\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(node_zfs_arc_l2_misses{job=\"node-exporter\",kubernetes_node=~\"$node\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "ARC L2 - Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "node_zfs_arc_l2_asize{job=\"node-exporter\",kubernetes_node=~\"$node\"}",
     "legendFormat": "asize"
    },
    {
     "expr": "node_zfs_arc_l2_hdr_size{job=\"node-exporter\",kubernetes_node=~\"$node\"}",
     "legendFormat": "metadata"
    },
    {
     "expr": "node_zfs_arc_l2_size{job=\"node-exporter\",kubernetes_node=~\"$node\"}",
     "legendFormat": "size"
    }
   ]
  }
 ]
}