# ---
# # yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/inference.llmkube.dev/model_v1alpha1.json
# apiVersion: inference.llmkube.dev/v1alpha1
# kind: Model
# metadata:
#   name: octen-embedding
# spec:
#   # source: https://huggingface.co/mradermacher/Octen-Embedding-0.6B-GGUF/resolve/main/Octen-Embedding-0.6B.Q8_0.gguf
#   source: https://huggingface.co/mradermacher/Octen-Embedding-0.6B-i1-GGUF/resolve/main/Octen-Embedding-0.6B.i1-Q4_K_M.gguf
#   format: gguf
#   # quantization: Q8_0
#   quantization: i1-Q4_K_M
#   hardware:
#     accelerator: cpu
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/inference.llmkube.dev/model_v1alpha1.json
apiVersion: inference.llmkube.dev/v1alpha1
kind: Model
metadata:
  name: jina-embeddings-v5-text-nano-retrieval
spec:
  source: https://huggingface.co/jinaai/jina-embeddings-v5-text-nano-retrieval/resolve/main/v5-nano-retrieval-Q8_0.gguf
  format: gguf
  quantization: Q8_0
  hardware:
    accelerator: cpu
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/inference.llmkube.dev/inferenceservice_v1alpha1.json
apiVersion: inference.llmkube.dev/v1alpha1
kind: InferenceService
metadata:
  name: embed
spec:
  modelRef: &model jina-embeddings-v5-text-nano-retrieval
  image: ghcr.io/ggml-org/llama.cpp:server@sha256:abb2f86d66c42ba6cca7590b48669c8152c1f94fc1356d97aed187cfc5a974b4
  replicas: 0

  priority: batch
  contextSize: &ctx 8192 # Max is 32768
  batchSize: 8192
  uBatchSize: 8192
  parallelSlots: 1

  flashAttention: true
  cacheTypeK: q8_0
  cacheTypeV: q8_0

  extraArgs:
    - --alias
    - *model
    - --embeddings
    - --pooling
    - last
    - --cont-batching
    - --threads
    - "6"
    - --threads-batch
    - "6"
    - --host
    - "::"

  # resources:
  #   cpu: 500m
  #   memory: 1Gi

  endpoint:
    port: 8080
    type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: embed-proxy
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
  ports:
    - port: 8080
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/keda.sh/scaledobject_v1alpha1.json
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: &app embed
spec:
  scaleTargetRef:
    apiVersion: inference.llmkube.dev/v1alpha1
    kind: InferenceService
    name: *app
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 600
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda.svc.cluster.local.:9090
        interceptorRoute: *app
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/http.keda.sh/interceptorroute_v1beta1.json
apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: &app embed
spec:
  target:
    service: *app
    port: 8080
  rules:
    - hosts: ["embed-proxy.ai.svc.cluster.local"]
  scalingMetric:
    concurrency:
      targetValue: 100
