---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./embeddings.yam
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  # - ./qwen35-9b.yaml
