---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/inference.llmkube.dev/model_v1alpha1.json
apiVersion: inference.llmkube.dev/v1alpha1
kind: Model
metadata:
  name: qwen3-reranker
spec:
  source: https://huggingface.co/ggml-org/Qwen3-Reranker-0.6B-Q8_0-GGUF/resolve/main/qwen3-reranker-0.6b-q8_0.gguf
  format: gguf
  quantization: Q8_0
  hardware:
    accelerator: cpu
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/inference.llmkube.dev/inferenceservice_v1alpha1.json
apiVersion: inference.llmkube.dev/v1alpha1
kind: InferenceService
metadata:
  name: rerank
spec:
  modelRef: qwen3-reranker
  image: ghcr.io/ggml-org/llama.cpp:server
  replicas: 0

  priority: batch
  contextSize: 8192
  batchSize: 4096
  uBatchSize: 4096
  parallelSlots: 4
  extraArgs:
    - --alias
    - qwen3-reranker
    - --rerank
    - --pooling
    - rank
    # - --n-gpu-layers
    # - "99"
    - --cont-batching
    - --threads
    - "6"
    - --threads-batch
    - "12"
    # - --metrics
    # - --no-mmap
    - --host
    - "::"

  # resources:
  #   cpu: 500m
  #   memory: 1Gi

  endpoint:
    port: 8080
    type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rerank-proxy
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
  ports:
    - port: 8080
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/keda.sh/scaledobject_v1alpha1.json
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: &app rerank
spec:
  scaleTargetRef:
    apiVersion: inference.llmkube.dev/v1alpha1
    kind: InferenceService
    name: *app
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 600
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda.svc.cluster.local.:9090
        interceptorRoute: *app
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/http.keda.sh/interceptorroute_v1beta1.json
apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: &app rerank
spec:
  target:
    service: *app
    port: 8080
  rules:
    - hosts: ["rerank-proxy.ai.svc.cluster.local"]
  scalingMetric:
    concurrency:
      targetValue: 100
