# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: n8n
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:U7bmRx9lPtrE4VEDXY5bpblNZB9gr56A4dKM8DeaIPo=,iv:h9iZtIxG/wGoaBB7N+J1C0gG84qDuJfqUt6qNXofrYc=,tag:LlzUJ1kfymtdI432ma4zkg==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG43eWxCQzNB
        RHlpQ2lQa0pkL1I1LysvUWJsT0c5dzFtdU5VZC9oL2JqWFI1V2NqWjFqdGJLdjI4
        NFNNczgwWjgweFZXNnQrL2Roc1pkZ09jNFhGS0dlVDlOejBwQWJtSmt0SkpEMjVC
        ejY1dStUWkZ0Z2lIZGJNS3lCaDhYRDN0ak94UndXWGovcFpDWnc3QzVSMVA5Sjkx
        c1V5WnlNdlJ3YUNveDhleDliMnYyYWJsR1k4SkhkQVc1OUdIdjh5czZOMFVVNEpD
        dTc0WmpyN3NUZjllTXQvRnZoMW1lRU1yYmduVVBGOHNJdnAzN2E2T2t4SG9qVW16
        MEhXVElxeXBIcjVucUtYcU5YZ0d2cTU0RGRFb3dSNEp1RlVWbjcvcFlWL3hzeEw5
        RUhFNCtnc1l0QnZpR0p4bHlKOHFkMzRta0IxTG9SOXB2TzcwYWFUbGNkektnV2dn
        UXRySjVQMXFSYkszcHg5TUc5RFhUZjVFay9pMXkwNGVVbFlNeG4rWVR6d1BTeTEz
        UFBZVnJOeFJ1Qm5aWEZoTFc1dmlwYzRNVUxMeU92Y0NDZEpNaGFEYkExYmdmNk5M
        NlEyckZoY2lPRmZucUc3bUFXYkJ1Uy9ta292RDR3VDhjeEFmZG5ERUEwQWFaNWNx
        OGM2dXVuZ1c0UG1nNE01dHNLcFJGdFpCUTY1KzNFUkltMlo4UzRCUGdyOUpSNEhE
        REVWblE3S1BmS2FxaXVmYmZPSjY0RTExQWV5c2x3YWlVTlZNNFg2RUU3YnBYbGRD
        UUhldUlCOGpQSDdFVGc0OUx6bDV1WVdPQ1NLSXRNTGhQbk1XOTFKVXZCb291MWs1
        cHFRQzgvZmFtVG5FWVRHMDNaYWpXRmdmcUFuS1EzUDc5YWNCdzh4ZUdJbGtRcUxn
        eWlmYjExQzR5SVYxT21lZlNLZU1acHk3YUFDVlc5QUkxTzVGYk9wQWhQWW9yc2ZO
        TkNaMVBuMlp4Wk4zdGZlVytiMTRiU3RFYkFKemoyRElPSVFwZEE3b0w4anlIUHFo
        U2ZYYTlmS0g4M2xDcm9RNkJzYlFlaFgwQzB4Z3JCOUc4S1hueXFiWVlGWGRqQjJM
        TmhGcnl4VEgyQ2Q4NVFlTDZZNnNWUjd3YnVCNnF3UEFzZWh3SkNPSjJhVGRKM3ZT
        RG5BR3JMNUU5MnRzT25RYTV5T2lHcDV0aXc1c3l1OHdqdExyTHVxNDVsSncwNjFq
        YkQ5WkswZE5scUtsME9QRTY4M1ZYUmZVVUVlS2o5eFZhVTZ5TDFwSzFxTW84QzZB
        bk9BMnNNeG9sR2YyYzBRTktwOHNxYStDQnh5S2VkZjNVMWJqQlg1d2VFVkZTcXhk
        cXVjK3VqelkxRFVqMmZnMlZSUjM2Wi9wemxuYngzV3hhRXJoNkM3eTBuRWlHeU85
        ZUswOEdJU3J4TDFiYld2VjdRT0x5SDVDN1l6MWhjQ1BLRnlsOGNUSFRuSGFGV2k5
        b29OdUJiTnBTdVNad2lpa1lYSno4d1cvelJUQXQ4QlVLMmhsNERGRnl1QUt2VGRG
        THlnSXBla1Q5c1ZITHZEMGxnTzBhZVBGKys3aHBFR2VFWWFiczZJb1JXVzIrWktZ
        MW1xZURGSWNCcEIxSk82Vm5MTTdZTGRGT25lUHg3dENmT0twemlwWCsyOGlGa2RX
        ejZVYjBRQkJxdEtRa3lHRENjdFM3VTFNcExVQlNLV3IwNHZEZEFXTXNZdnhjdEgw
        Wko1bU1BbkNjVDRqbG1xbnQycjdZWmg2a2hFVXk5Z0wzdmR5UEZyTW9EbFQwcFFU
        RE5oWkpOaW0yeEFReGlRZjNHRi9Ed2dVK3dwQlJoL3UrSWJQd2Npejh5VU1UdjNx
        Qi9hS0xFQlNjTjNGY3RoZXlpWUN5dGFHVW5VR1hsZnc0M2ZNNTFvNDRqbDF1cERl
        a2EyRHU0bHVzd2JSMXpOUUJlOXhuVVJNMHZ3R1B6YTBhRWNMaVJYUlNSMS9Qdwpo
        VTBoS0w4RXg2SGoxcWszdjErdjVJWGxLWDh4VUIxYUVOZzRpUFEveHJjCi0tLSBj
        T1I1WkUvcmZOajNZUXlCVHFTMUFMMVliSnMwdG1Dcnhma1NPU3FxUnRRCkHCbJKg
        ueLZNWiB0uoU+6xz7XzeU6VJAk5SHfkzG4JDw9rr6rLasNOSnBCJs1Qof3ng4lrB
        l/LIKVwFULryxpA=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-12T23:08:03Z"
  mac: ENC[AES256_GCM,data:Ko+vublu5x1XtdfSXyZ2Stdv52Pue37img3ME3DHyuek86GtcWybqaC3PXP1VKU3iYBqbz1A8qC702H0Hq/WN1KdhCnCOeC2l2O+rmIM/IgRo9eGewlL67mjWFEVZ3uDzbpuKxqNPg+cwVEpG1KeMMFQobwKykt/aEaswvM3wSc=,iv:kHdzESdpOVGwao1WVckpXnWkUekdZ8oRfLkkWHyMTZE=,tag:l/2+FMCzBmBkr1rZaYGUVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
