---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: external
spec:
  endpoints:
    - dnsName: external.${MAIN_DOMAIN}
      recordType: AAAA
      targets: ["2a02:a313:43e4:7080::7dc5"]

    - dnsName: ${MAIN_DOMAIN}
      recordType: CNAME
      targets: ["tunnel.${MAIN_DOMAIN}"]
    - dnsName: ${SECRET_DOMAIN}
      recordType: CNAME
      targets: ["tunnel.${MAIN_DOMAIN}"]
