---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/gateway.envoyproxy.io/envoyproxy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: internal
spec:
  ipFamily: DualStack
  backendTLS:
    ecdhCurves:
      - X25519
      - P-256
      - P-384
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
        container:
          image: mirror.gcr.io/envoyproxy/envoy:v1.37.1@sha256:29496a88fba9c4c9cdef4afe8fec70f536c5ba111b1c2bddbc5436b091ceca33
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 1Gi
      envoyService:
        externalTrafficPolicy: Cluster # For cilium ip sharing with stunner service
  #  shutdown:
  #    drainTimeout: 180s
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Gzip
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/gateway.envoyproxy.io/envoyproxy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: external
spec:
  ipFamily: IPv6
  backendTLS:
    ecdhCurves:
      - X25519
      - P-256
      - P-384
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
        pod:
          volumes:
            - name: geoip-db
              persistentVolumeClaim:
                claimName: geoip-db
        container:
          image: mirror.gcr.io/envoyproxy/envoy:v1.37.1@sha256:29496a88fba9c4c9cdef4afe8fec70f536c5ba111b1c2bddbc5436b091ceca33
          volumeMounts:
            - name: geoip-db
              mountPath: /etc/envoy/geoip
              readOnly: true
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 1Gi
      envoyService:
        loadBalancerClass: "io.cilium/node"
  #  shutdown:
  #    drainTimeout: 180s
  # geoIP:
  #   provider:
  #     type: MaxMind
  #     maxMind:
  #       anonymousIpDbSource:
  #         local:
  #           path: /etc/envoy/geoip/GeoIP2-Anonymous-IP-Test.mmdb
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Gzip
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/gateway.envoyproxy.io/envoyproxy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: cftunnel
spec:
  ipFamily: IPv6
  backendTLS:
    ecdhCurves:
      - X25519
      - P-256
      - P-384
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
        container:
          image: mirror.gcr.io/envoyproxy/envoy:v1.37.1@sha256:29496a88fba9c4c9cdef4afe8fec70f536c5ba111b1c2bddbc5436b091ceca33
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 1Gi
      envoyService:
        type: ClusterIP
  #  shutdown:
  #    drainTimeout: 180s
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Gzip
