# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: home-assistant
stringData:
  access_token: ENC[AES256_GCM,data:A2+MvC1hy3Z+76Ic5MWGK8EgDTFChO0gmQZGLwdjuxPlT8qXFl75CiHvKOIjgW/CnNm4qMjoWEer0klq1oqsrGWf7cSTf7riOiA3lyIlHafIuqDe1ndGVWvbpgQ+DASKLNA490wPermmTJ15YEzxl2XkqcAMequP5KZrysRH+CWarsnagAIfoavBbS2Hq15l+kRXMsPiB3QnpbQzxPZgPHZ7r7GyGymd86AiBKAPEKBcy/0pWScY,iv:MrxAxWNLsVOYisTu64v7bj2fq3wWglyRBDpm7n9QQ+Y=,tag:L4n4zu1Y0gwpqpDpSRqvuA==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHVmaGhTV005
        OFJNdm9Dd3hGcWpqKzdyeW0zK1dnRHU1S3FBdFBpVjJUVnNNTmR3UHdsYk5uTmtR
        TjVjUFRaaDZkeGhTZ3k2blJSQ1I4YjNvQS85Y2ZXWk1vbHYrdXlXYWdNNWNHWHpx
        UkhveUhrSlhQM0ZnQUR5SWRqZzhLelhqNXE5ZnFIOVNKa1BqVWhlL0s0NXRTZCsr
        QXB0a2hIdG0yTzhhazd4M1M5M3ZybnpZczFtdEFYVC91ZThPOStyNm9WRHowUGdi
        Z1RVOWg3RjdROGdyWXN5N2RzdXA5WENBSWlFc0c1RnE1UzJaRXZCdlFrRDBwN3Fj
        d0psbjVaWWFBQ1l3b3gvYm1nY2dkYk5DNUFqaEpvaDRJbEc0QSsyZlVkQUU3aGxK
        eHphYzNsUmFCR2hubk15VUJHSFc2WGU5TjBOMGw4Ymd5cDdpMThtZG1sc3FlVDFj
        ek9hbytHbkJaN2NLcnVhc0tkcWxIdnB5NURlVWJWaVJucnIzNUs3cXBOQWNCSCtP
        SDZubEwzd3B2WnFNVnVDUTZ5Q09ET2c2YVA4dFpyS1AzblJlai9lckRrK3c1bnNK
        dVUyODhjV21RMWJUTkJQV003TWlOUHZRMlg0MkNNWmRJWkFtZ1hGZmV0OWJIcU4r
        WDJHRFRYTk5RNmJ3bzdKaFpIT2F2c2lsOWQxcGIzOGo5QWI0QTQxSTFyV0RDV1ht
        aG1LaEQwZVdpMGN3emUwamJMQlEvbmNLQnpvNkIra0tyOUhHVFVCUjlQK1Q2dE5X
        RkpONWFsVE0rMS83TUg2ejRRZ1FlLzdnM21NSUZUQnNEQUd1dk52cDFOY3gyaFRS
        WkRRZDhqZFZZQjc3bzJVdHNzbGV2ZHZpZ04vRmxLWWorOHJ3QWJZMW5rNUV0eEwy
        K2Vndk9tck0wV2pvR2dJQWw5Z0t3RHpvWnQ3bW94bE5lcWMrN3UrTm1iU0dxeEhP
        ZkY3a280MWd5cEhXUEZSMVF1c25YeDVRK1h1SnlrUWtaaXg1cEI0WDZJd2l3ZE5Y
        K1NTUXZkVVRsN2JBalEwbFd0cGVHU2l5Sks0cC9SZWVIeXYzMmlaVWVwVkdyVnEw
        a3dVZVpCNk1pRFNaeGFmR2lka2U3VzhPbXBkQjE1eVhoY3puY3BOTWZub2Z0ZkVr
        bTF1WmVRbTZMaHVPN0VHekliWDJ1RDRWUUNETnNIMVNzeUQwTEliRDI2K3pOZ002
        RVlMbnJ5aW93M2oycWgwUzAxL1NXaGl5VGY1aHA5c0lhdFJwMzd6OEZ0VkVtck4w
        ZXhOTWRYTGtTbXdnOWYvQ0JNR2E1bU9mS2Uyby8yNUVLYTN6RVd4aGVWREkydjdk
        c2hLak42bHdqUHpUYnlXaGx2WkMzUUtpV0QwQjIvRHlkU0tFV2RGcFVQSytrOHdt
        S0FLaFhaVlBLeWFiOGppRjc5M1VjdzZSZ3NwaERqVHVYZVBhaEtMOEVaeUNxN2Na
        L25KMTg3dzZVaVFOWk12amd4eU11MXBhc3dLMGVpZERuUHgvWit6Qmt5NHdLOS9w
        N0FGVVlUSEZKNXlTYktVTmJ1S0J4aTNhbGpraGprdVUrS0NVTTJPRURkcXI4aVhJ
        eFJ5c3JFQ2sreXcvMFR2a285b3dVNW0wK01GdnVwci9CUkE2S3FPeUwxdU1aVE0y
        b0cvdVArZ1dvVmpDajRJUm5QMURWaGljOHlBWGQ5OTVCSnIxSkVudkNhbmlwR096
        eDc2NzVrL0lTWVdvdk1PZ1RoTytKTFEwc2srVzBZVHNDbHN6eTIwcm5WdDBXeWcv
        UjZJVTJxZnMzK1hVc2lVNWdTejgxbm9HQUdvVWhtdTIxMHhldjhEQWtDS21DcW95
        azl6enpwWnk3Nk5vS2I0MFAzMlVBZnNJTHMxTmpzTDU5V0dXVmRxMlpFdElhR1oz
        M3h5UkdtWUVySm9DV2hUVDBNM0dsUFd6SURaR1pxanhaaE80NlJFeGplK1lPZwow
        RWs0Rkp2Y0Q5Y3F2V3VuU1JmZTBNbVUwckhmU1oyV0NXWlNtZE9DejVzCi0tLSBN
        WjcvTHpZaG1FZmtqZElaZ1VibHRpK05BUm1ESTZ3dG55RGtNS2Qrai84CqC7H0i5
        KHO1xrUqYrBCegxK3cWvBacPAaq2ED+0FIiamvG4VqgdEWt2ojbgYQpb76rV0fJI
        VQpxpRvAjO+qtGk=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-11T04:41:53Z"
  mac: ENC[AES256_GCM,data:ZRx16ddSSsyn5AlkNxjveB/FH3IVopWTyqWzRwkwXxTu7InxcXQ1ssnWZ73BDHvsoFOdsfG8DfvZYyaFXsZqOk7ktdpFqlEAWfZDrV+2tPeVePuMWSOM6ajsQpQ9V+MXYeO4OfmTu3C/L8R9pPmpTdCtpi/R2DFU7mWtczkYUjY=,iv:mSVI6QCAdxaKXElZ5TElzRFC5Z3uKcmX0XxM6qRrqGw=,tag:bmMoEpx2245JMNtt9BJOAA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
