apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: homepage
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
  api_key: ENC[AES256_GCM,data:4y5w21WTeVOqTgKmANM9kxE2KRtdOX5rMTSyRUcFlTw=,iv:LCkLFT++gF0rLEKMzyjdGF7OTvY+Gg5ywjTmepo5uOA=,tag:xqUwAb9oQ2uguha9W2x+Dw==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDdmWklVY21U
        Y1NWKzAzQWxlaHlVM1FqbHYzL0dWOGY1d1pBSjJRQ2JuSUZUY2ZMTWR0TWtEa0NC
        YXErd0hGeGxnUjJjRkpaaHFpKzR3SUZRa2IyVmIxaWJ4eG9SVm9FdXRBU2VpZHoy
        c3d0aFBGK2JPc3NKUHBhQlowWXltTmRBdk5jbDhOZ3BFSzZZU1ZFNk5hY2tmcC90
        dE1ZYTMxNjFjVTA0cFFWZTVFV1RxaHBKS1dSb2k2YlFCOC9sNUFSejZ5U0VoYmds
        bG0wUG5NY0VkdFRUaERxQTVNT2xjVUdFUHBBWVNnblpZTU5KQU9FLzZHYkFaWkdi
        NXJIL3pFdEx3MzVLYmp3NWtPVzFOdytiZ2pzRXN1Um5jSDdCYlBUVWQrTmdORXVJ
        K1NFd05CWkFHV0w2K3k3T0pYQ1R0MWNsVHFUMXNOOTVuYzdHMVZuNjQ4NmR4bStT
        VlR0WHBZS3d0aUMraFFJQ2F5Y1MrVUxUcEZ4QlBuTldZY3Z5SElPSDhCY1U0WnBM
        WU1FTk9RRzk5SUo3eUphbDRJM3ZGcmppT1FER2tMTlZZditLaFpPNUVyaWp2Zzlq
        czQxSlBTZVZicXZQVEp2dWJPY0VYR0h1STlpd3JnMnhsVGcrRHBqa0NjTFlHSWds
        UVRHWGY4Wi9zL2I2VFhpelhxRVFzSTg0em0rUUc3TWUwSjliVDdjRnBXRThIUWdw
        ejhqYzhHa09Ta2JYVHlMVXMvMHhrdlVlZWhjQU1YNGxyZ0dteW8rNis5dUJSY3lm
        V1VCK3JsdW1uVnN2Y0dEN3QrWmprcWRtbVF6aW1qZWJubWpIWGFSQ1NkUnpjSlov
        ajRXZnh4OHV4RmpZNlAycnJhbkhhbE9FNGkvbjU2YThlZUhiV3FERmNvaVpaWFNJ
        UkpzQmhYY0V5WHdYbjMyL21vUzArZmhmWmxNMXMrUkdEdXdxR3I3cWxBZzhORkxC
        U0NneVVKUjlMT0ZmeE1qeE1naEd3RXJGb3ozN0FldUEzNnd3L0l4YTFEUmZWbVNZ
        bUtYc2Z2RmFMaFBLRi83d0k3Ym4rYkpwd2F1d1FiTitkM0pzS24xSEpvRU40T0Uz
        blczWE1WWFJzL0Z3NzRPRmdhWHFjUFRXNURaNGdkSklTZGhVelZuZmN4U1dmMy84
        elA2OU5SOHZnajFsYit5VFBLREJnOEhHRVlxTUpHSjNPMWpqc3ZZZlFyNmtBTGRL
        K1pZOE1WcXRjcGwvV1ArTDNjV25ZVzNNeGM4SVJic2ViT0I1ekR3QVFubWxWUDhQ
        anFySitPaFIxWkE0MnY5UzkrbzRlRkNjVEdITC82VDFMbE1ZaC9qeklmbG1mbjNI
        NlhGVGFMVm11ZGZVS2Qzb2RBeDVIWGNZd0Z5aTZPSEt4R1ArR0hmVldHcDBBZ2dP
        L0pZTUtuYlVONnhiU21HSUJiaWtSSFpENFRybktQLzVZamRRVC9sVnV3cHlFMm44
        bVQrUnFNLzdRWDlMN1VySms3b095andHY3k5RVFRYVhicytaMGxkOUNMQ2tVVjRP
        bUVBazBjaXhIaWVjRXhuVEpYell2dDcrWmdaN1kvL20vOWRGN25Za0VSeDJMMENk
        M0I3ODdkcnpwQ0tqOWVsQUJlWXdsVFUwak5HMDBxNkljNGhudDZlN3U1U2pjTlZ0
        MEpuV0pJOEtjZGM3L3ZvcTQ2K2tOUE1kY2NGdU5uUFFYUHc3bTR4TS9SdjBUTlRy
        SFF4TFhETnl0Smk4K0ZGaEdZejQ1cy85RU1DS3hOa292bmFJODBla0ltQWUwL2Vp
        eGFhZ0ZJaVNrUGpaTTNlTW1oS2ZRV2Z3d1RFaU5PQ0ZRTEx5ekFqUlhnM0FsakFD
        czVYV0xINkhxQkcvcVg0anMrY0Z1RUd0SmlyaUN5NSt5MmhGdDJiMlZVd1orQlJJ
        TFBRSk1uZi9kNFBqaFRpZ05HdzlXR2ZuSkRqS2EzTG5DRDB6NGNNbnBGd2NDdwpK
        YXZpdSt4dXRrdGMyVVU3dDFmUGxzWDhINCtIODRPVnJNcU50QStvOTl3Ci0tLSA3
        di9EL1BUWVF5NDJ0WWxybHJFRERmSGc0N05xUFN5L2U1d2RCdU5KalJvCrL/xK7z
        biWmgl0MbLSgUkOvzbtCsou7jrg3moxzkGA96XRlFacC8nVMDLFWxcnpezBWEi2s
        5kZmKDJOMN51wyw=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T18:41:33Z"
  mac: ENC[AES256_GCM,data:SMINYkIv5XjUNgHTP3mVqitIWEADa8JFpqIISFAO/PU1NO9pqz7jQwbtvsu16LGC0+gzzjexTpxquB/5HcE/qobPu9LXS2a/yBpfAgGU2Su238c+PrTrBODUmSO1IS6c4UAO9AA5QWccL9F5vR6x+CVT4+L6ZIMiD1Q/Vaihj1k=,iv:seBzklSp+pYkPK7L/PpM/IEJ9XP4ybT7OhgmEc06FO0=,tag:smZEbRgiTZO/F907YCZ0Hw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
