apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: homepage
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
  api_key: ENC[AES256_GCM,data:4y5w21WTeVOqTgKmANM9kxE2KRtdOX5rMTSyRUcFlTw=,iv:LCkLFT++gF0rLEKMzyjdGF7OTvY+Gg5ywjTmepo5uOA=,tag:xqUwAb9oQ2uguha9W2x+Dw==,type:str]
sops:
  age:
    - recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMFZxc0VmQkV2VTRqRzBC
        ZEJ1ZXFSZnJhT1V4TlpNbThlSjgvUVVkUG5rCk1wN2YrTGRscGx3VmJIeDE5bE9O
        ZTFXVGFPNWliQW42Q1YzS010OXlDWVUKLS0tIFZOVW8valF3Qk1leEF2Tk9zODRM
        SCtFeWJ0bHFFckczaklHUVJpSVpWQzAKAUI6+DE3TugGIRnGo8qCt8wl4ubGotc7
        cqlAFMJjIyHkOufNZbq7Bq2/Ex4nwq0wq5f8FbAQB9O+sB71stuIew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T18:41:33Z"
  mac: ENC[AES256_GCM,data:SMINYkIv5XjUNgHTP3mVqitIWEADa8JFpqIISFAO/PU1NO9pqz7jQwbtvsu16LGC0+gzzjexTpxquB/5HcE/qobPu9LXS2a/yBpfAgGU2Su238c+PrTrBODUmSO1IS6c4UAO9AA5QWccL9F5vR6x+CVT4+L6ZIMiD1Q/Vaihj1k=,iv:seBzklSp+pYkPK7L/PpM/IEJ9XP4ybT7OhgmEc06FO0=,tag:smZEbRgiTZO/F907YCZ0Hw==,type:str]
  pgp:
    - created_at: "2025-06-19T02:12:25Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DC0EwVK2S0BUSAQdA/K0f5jrjrvPEk+D73ZbU+juAPhUC0moI8jsBkKL7gDow
        JeFcZJU/oQBa4IKMPbViXnZ4lphIpH38zrnGiZceCivu/iIatO8qytT0S44/j7H/
        0l4BuD04Jg+4d0Kv15lcAMeZaB1LCDLXqnVzap3nzNFHSHZv8IhKb6g6MWEkUr/y
        htdlMndiSLw816xZMy8+F5y5fRdaze3LLd6N7ryDC65w1wQA/TQFnpMcliRVSxgY
        =nW+9
        -----END PGP MESSAGE-----
      fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
