---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kopiur
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.8.0
  url: oci://ghcr.io/home-operations/charts/kopiur
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/home-operations/kopiur.*$"
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kopiur
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    replicaCount: 2
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 2Gi
    streamingLists: true

    features:
      kopiaUi:
        enabled: true

    installScope: cluster

    monitoring:
      dashboards:
        enabled: true
        grafanaOperator:
          enabled: true
          matchLabels:
            grafana.internal/instance: grafana
      serviceMonitor:
        enabled: false
      prometheusRule:
        enabled: true
    observability:
      otlp:
        enabled: true
        endpoint: "http://otel-collector.observability.svc.cluster.local.:4317"

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532
      fsGroup: 65532
      fsGroupChangePolicy: OnRootMismatch
    webhook:
      replicaCount: 2
      certManager:
        enabled: true
