apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: homepage
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
  api_key: ENC[AES256_GCM,data:W9HHG51OWSTwObBs5RhCqBlIFRoQgOqflI1hDxHw11I=,iv:ctfiGDT/e/oSkmguYfAzuRPsdWqFb1wzR8nGCKeHHGY=,tag:rr/oWnWRbngSU/w2CKxDAQ==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFY3cGVpYmFQ
        Y2hYQ0FJUkJwOVEwU2ZMNmZzSHJiSkxhRFlOY0xlK1M2RVA3OHRGZTJTb0Zic0s5
        czE1UTZsQUtiZE1KbWdNcDkxQWppZHFDcTFyWWJLVStseWZQU2U2RFQwa3l0dllR
        MEovU3Q1STB3c1NnRklsVHcwZ3daVmVYeHFaQTZyV2t5b2s4SFJOWUREbHl1akpQ
        OFNBWTNaYlVYVjdEVURQMm9Md3pMUWRSc0VtLzlhZWorSEorYW93YTFRZUwybTRt
        cmgvNXRrUHM3bmJjZWVyWEhZZnd3d05kYWxnL3F5UXUzbjFMUldXSlJrcnRWa3Z5
        RmZWZUtTR0s0Y1NWbHlwYXRCWFVyK0p5RGRjZCt1aGVrSTN2OFhweVpPcXErRHNI
        R0xuQUowejdnMHd6OFdacWtqVEprUlU0UTZDV2FxQTdQMXRjd0pJcTNCeE9ZMUt0
        UWxDL0oxYnArdDJlZldkNytUbERpVHV6ZmtZTGV5MWxPTHRVanZzMzliVDZzN0tO
        SkJCZ0ovdG11Wm9uNUcvSHdSUThabEN5SXNEdytiTzVOMGl6Ry81MTZGb2RaQ0tl
        UisxUHRhVFZYTTVaKzZRT0toQ3hWVTVFSnRIR2FuRCt3d1FaRGt1aHQwTzlzdjdi
        SDBBY0YxUGt4eWlvUHJBanBmdFlVbzNTS3Rpc3lFY0o5eWtZNTF5SWtpeWhaRmZh
        eXhPWU5JTWQyZzZpWVdlalppOXZNdGVOTWQzZTJnbDFxbUhyZ1RBM1c3WXAwZlJ2
        ZVl6bVNVSE1pRVdyRCtVbmdRWVVsbkdUSXJnQjJGbUZXQUpLSUdiM0xVUDBpVGpH
        SmZzaERzT1FTdGhxOVdIZlJUK2Y0VEVsRDB5d2phUkgxeEFDSWF3ckJGUzFnZTFD
        OHVncUVUYlFTRzVtQ0ZqVlVDclhUZlUzbW1wOWJ0YWhUK0plNFBoOWRaY09RTmdS
        Z2JmSEN1eEtKSVdNeERVZjBiKzU4MjNxekhtTmM3M3JqUTRqWmlEaWpwdXEreVRx
        bC95eGFrZ25wb3B5MUpTOU85YWpRVXhhRTVpd2hlWGFwTjIvT1Jyc1UwWVMveUdK
        V2xBcERNZzQ1Yy9VMUpWMzQxbklWeSt6dloySUdXVjNOU3BUektuaW9iVGRnY01E
        N3lzL3JEb2Rxc1doTVFEQVI0TEIxcWpOSnNtN1l6Vkw1ZGtXM2xLU1g3UmNrdk1Y
        R3VDRnp0b3hQS0hyMy8xZEk2Q0Nxbi9NRlhYRkJIUHIvbzBOdkFxOVRINURUUXZT
        OTFwTkxsb1pZTkhVRG1EcmwzVlM5b25aVWtFR3c0K3k2MjUxWWl6YlNnRlpVMlI3
        cEQ0dTRIOWZQWVhyWDVBbUpOZ1UxV1FVR2lISW5FdGJGMmJlM0NjL2lLOWZwRzJL
        ZEFYZFNNOG41QzFuaWFITFlnbnhJN1gwUVBGT0JhdGNUMFlQc1d3YXFHRFNaUlgy
        R0V0eWdqS0V4SzNseUQ0SllOV20rend1K20xU0JtMGZhQnpjT25aMHNBSno2VFNH
        VmVCS2JXeWN1VmhUdHhwWC8wMjk1R1gxK0tBK1U4QTVDSU53VkJVQ2FNUUkvZ3FB
        VXR4TFg4ZWhzN09WTzYvT1ZVWlhDNTdhdmFDcEFUNGVLSHp0andEUGoyK1dpUkZW
        OStXMXpPTFhGbU9kVUJnMHpTblhsZzFaMWNjbGpTc3hXaXZWOEZvdCtJdUhwVlVQ
        bHd5allBdmI4YU9mdGd2bFhXUFlyQkFhWXFMaEs0eXhPVXIvZHEvVEwxWXN0ek1i
        K3o5SDl3dUY1Y2Nid0RLbEVOWjJreFNaaHFmUVY3RVFwZG15SzVGNEVZVEM3d3A4
        Y1grVHFuRUo3UVlxSStFUDNjUnZkSVBLSDFlM2tycmJQWEZLcGpmYzhOK3ZiVkNn
        OXRTM05iSC81MDcxY05QMjA3Nmd2SnM2QUl4YzdydlQvVjN4TFNHTzNSQnRCUQpa
        MFZnU2tkS2d1OW45Z3poY0ViaEZQZVJrVlEvc2VHWHRtWVROdzJVYmxFCi0tLSAw
        cVlMSUtaVTh6QXYvUEcvdGdBL1A2WFFTbHNjcks5UE9sMW04dTlkTkVJCgBEsQQm
        KPDNT51isqYf0bKicx9xn7cocnLIANuqL7htBtMP7gFmA3xkZKM82JCD0pRCnI4g
        0FzT9snWy4l8yu8=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T18:39:09Z"
  mac: ENC[AES256_GCM,data:DTjkffKKCHXDHYBQA/SpPSwq9Hn9CABOJAowVM3sFcmCniOIgWvKkn9jLatpZLeqtK4g286g13/T3+AoZikxP/hh3CdmTyG2KuSEpf096GhRefVcApN1ZsLvaMOiXQR773dhYJ1KSee/ebC2GK8oMXXeMgkZpVyjRUbNh+ZMHXw=,iv:ud9DxItgXvkI6iKyZeGYZ32pVCqYmcnI9HqZCGMnJQQ=,tag:YaliY8EBzyRpgSDOQo0+sg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
