---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./interceptorroute.yaml
  - ./scaledobject.yaml
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
    patch: |-
      - op: add
        path: /spec/values/route/app/rules
        value:
          - backendRefs:
              - name: keda-add-ons-http-interceptor-proxy
                namespace: keda
                port: 8080
            timeouts:
              request: 0s
