---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# openapi:
#   path: http://crd-patcher.default.svc/definitions.json?crd=helm.toolkit.fluxcd.io.v2.HelmRelease&extraProp=helm.toolkit.fluxcd.io.v2.HelmRelease:spec.values.defaultPodOptions.schedulingGates
patches:
  - target:
      kind: HelmRelease
      group: helm.toolkit.fluxcd.io
      version: v2
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: not-used
      spec:
        values:
          defaultPodOptions:
            annotations:
              k8s.ksgate.org/dragonfly-ready: |
                {
                  "apiVersion": "apps/v1",
                  "kind": "StatefulSet",
                  "name": "dragonfly",
                  "namespace": "database",
                  "expression": "resource.status.readyReplicas >= 1"
                }
              k8s.ksgate.org/dragonfly-service: |
                {
                  "apiVersion": "v1",
                  "kind": "Service",
                  "name": "dragonfly",
                  "namespace": "database"
                }
            schedulingGates:
              - name: k8s.ksgate.org/dragonfly-ready
              - name: k8s.ksgate.org/dragonfly-service

          controllers:
            ${APP}:
              containers:
                dragonfly-stunnel:
                  image:
                    repository: chainguard/stunnel
                    tag: latest@sha256:95931468f1958f3db553daffecb9e2d59d876baee59bf3298125608dfe885d03
                  args:
                    - /etc/stunnel/stunnel.conf
                  securityContext:
                    allowPrivilegeEscalation: false
                    readOnlyRootFilesystem: true
                    capabilities:
                      drop:
                        - ALL
                    seccompProfile:
                      type: RuntimeDefault

          persistence:
            dragonfly-stunnel:
              type: configMap
              name: "dragonfly-{{ .Release.Name }}-stunnel"
              advancedMounts:
                ${APP}:
                  dragonfly-stunnel:
                    - path: /etc/stunnel/stunnel.conf
                      subPath: stunnel.conf
                      readOnly: true

            dragonfly-certs:
              type: secret
              name: "dragonfly-{{ .Release.Name }}-cert"
              defaultMode: 0440
              advancedMounts:
                ${APP}:
                  dragonfly-stunnel:
                    - path: /var/run/secrets/dragonfly
                      readOnly: true
            root-ca:
              type: configMap
              name: root-ca
              defaultMode: 0440
              advancedMounts:
                ${APP}:
                  dragonfly-stunnel:
                    - path: /var/run/secrets/dragonfly
                      readOnly: true
resources:
  - ./stunnel.yaml
