apiVersion: v1
kind: Secret
metadata:
  name: forgejo-keda-secret
stringData:
  SCALER_TOKEN: ENC[AES256_GCM,data:7HeGVzpOEjsVdw1m8+SU4q5a+YzGJnHCONlZC3fUskEAHVpQXs7xAA==,iv:RrOSYTTSFeXrPctWYijhgA/fckdghKr85UTmuKQ5Z4w=,tag:6dBUsImqgwHSQ0NT4dpQ7g==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFJkbFo4ZWJZ
        ajNPNjR3blg5eU1WSEhVaXZmb1ZpSWs4SVRKRXc0TXdjM3ZvLzVITzVZV0Y0a2I1
        RDQvNFpKbXZaQUU5RUUwVStsb1NmWWJYVjlyM1BMQWx0eENYRkFKNGhmNTFLZHdP
        bmhrQXR1cktRZHlUa0JiVlptSG1ndTdzWHFYbXhoNFprcm5DTHhQYVNCMk1Ec212
        Z3VkbVVCOWlZOVFpamROcjZmRjFvNEVPc1NLRElmdCtIc3h6NkpLcUQ3SHFLN0hZ
        V0ROQlFUVHpKZU5vU2hDR0NwemoxUXRBZVZ2WmpjRkZVdWNtcUVOcmZoTU8xdWJU
        UXhUczBNNTZkWE91QUgvcXhZZlJBYU8rbENoenhEaXZHcWI4cGE4UDc2QlBLd0dY
        TG10Y0xtZEJ3M1MxUmVTSVhveVo5MWkzZ0RUNks5OEhrTllWeThFWm1hbTNmcXdB
        eXF0TC9rWGZaaTM2T3BYck5SNFl3M01YVndTK0xXOUpycEFLZ0hhbmVxdFBUOVFW
        a1pNUnpEQjIvbUtoNG82VVJuamZhcmJBdGpjcjBYaHF6amJxaGNGWDJzYlR1WFNk
        bGVZamI2YU1UdTJIdmtlUndPcTRkK3J2N2JrMTNUbXBxU2FXK2QxdVgrQTc0Z0tl
        MitUdXZqei9IQ2RwRmJyYjVnMjNuRWdiSmlxcHJjZXNpWGh6TGF5TDVzSVE1TUIx
        MElMaG8yL2krVDB6Q1BFWHlrQ1ZMZHU3djNpMFRPL04yYzFXTWlNWEMrR0wzRzFX
        QWtWczQ4ZmUvSkhKZ1lKWi9QRVZ2Z2hmeUIvb2tSeG0zRjR3NFZmVllTZUdER2ZE
        OHFLN200Z0VJRU5SOVBOTVNhVnMvWFBwSlBITVlmVkx0L0tYbHVzQ2JpWm1lUXhx
        RElobkNPMmNLQ1FHeDBMb1hPL1NiSkxQeHpvRWpONUZYTzJiSWhZK2phZ1ZjMDlZ
        OTBKNWkwSXRpOWt0QmFTVkJiZG5ZNmpiM2R0ZXcweDAzQ1cxVVNwVlRjM3JYWUo0
        a1E1empTbnZ3VU1uUXRsWnRONHB2SVpMWnlqSHErOVZzRVltOUM0aS9WVllKT0c1
        YmxZbVEyWjZDVkUzbVg0QzNmcE1mZ0J0aVRZRzZyNlpNcGc1eFJwODM0dzNOMjEx
        dUlPdUJGNHlPK3NaREVRR2I1R0I2VmpiSEhjMUZRU0pxclJBSitsUVQ5aHFnRFh1
        ckk5TTViYlFnUFdONG44V3UzUTRkU2R5Y3ZXQWM2ME5GZEdZUmxkdVlBeFV5Wkd3
        Q0JkTnhCMjJIcENjWVEzNm1MYnVOTGtlK1ZmN0V3N3A3QW9UUTlIdGhlY3A4c0Uv
        ZGVLNUJvVzltT2p0ZUFoQ3Q3cU11UmRPK25YMWNoTnhReXY3SVp3L0VJcGpncVJM
        K0l2Q1JRRzBNTytIOU82bUVZSTJCUjlaUmU0SjJ3YnpXOUhraTh2L0daaHA0RUh1
        ZmJ2c296RG9naWRkR3BvLzMwRlBLVllmU3FYTUh0VVNCa0Q4VEkrWXpOdER5ZjBx
        akNEUVljdml0RTJlRmZPRnBzTE1QTHZiODE2QWRGSWxzRVh6Q1EwV204Z3J1NWdu
        elRGd3J0YkQ1NGkvRG9WdzJyMm51VTIzN1JXS0RzTDA5ck5uTHZXbXpMZXE5Z2Vo
        NnI4Uzd1cy9FcnkrLzg1L0cwRWlRZzBjQjNTNVJXM3QrNEovUWFpNVRTbGxEeGRF
        UVo1S1J6Y2lQTURpWXJZOGpFV2pvckUxUFFBcmNON2JHa2I2RkhQdFFKVzF0eVBU
        cmRxeEl6TUtaSVV3YnozUTNvdlVtR1hra3RPU0hMVEtvTm0zTGFiL0N0KzZyNWgy
        ZHo2U0ZmNHppd09OOUR3UFA3OGZvQTlnMUN6Q3ZSMXhpZmtLTnR1U0FrMnh4eVBi
        WHVuNDZ0NjBqTVh0d2FKMU9hNzl4K2pydytGcjBLc25ndnFEUGc5bGpIWEZEZwpL
        TExXV1kxZWpiVEQvc0tqOC8rY1pTY3A1Y3QvZk8yY01XbzRPVGZiTTE4Ci0tLSBi
        VmpNampWTll6dlBwT3dvTzVoSmxUNGVmYmJGT0MrOWlVbXphVEd6cjZjCmf4K8RJ
        z3t76TPI2gaB9rBMzDCs9ULQsjzffvdWTYwRfigVQzfqVIbil59L4zYeLz585B7B
        dfnJJqrC3I1hi9Q=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-27T12:16:48Z"
  mac: ENC[AES256_GCM,data:vCaj/ilfKp14gt7uLhHrY/LM2DvZbvR9ZiGVxaVhwNvndIDmHv8DuW7greH4Cy5e0+PXVoLIZkFy3k2NfEqwh6g7tdaMsQpqm9ZBIU/ej4AIV7Dcfe71yucXx1jkj1lH6IM3AODgni/E5+AUXu0zG/wAk9+MylP1DZGDZPWPDs0=,iv:e4bxLoxU5RDDooZAxym1YicM3rd6US2LDP1w2mNWy7o=,tag:eMDzqFecRZTVFnBxpJwZNg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
