apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-secret
stringData:
  RUNNER_NAME: ENC[AES256_GCM,data:hsRq63e0Q0CXp1m4Ums=,iv:tOy1QfJ18xxyZMTySSXR9jemq/wQf8JP/exoQyAEBzE=,tag:Dk/NBycImg3Lj4IKBgSdCw==,type:str]
  RUNNER_TOKEN: ENC[AES256_GCM,data:XB9YmZmI0cTCEZTMtDXGF/7Cp7DyK/IAi1XZrox6mB3CQAWHA1lrWg==,iv:nYudAtNARwb3DcrjY3b384pv0CKf2rHdplEFOyGVYQw=,tag:oWWWiMvSgKfaxBPhTwxQiA==,type:str]
  SCALER_TOKEN: ENC[AES256_GCM,data:1bh6dccf094Qcmrh1HVlE/VUPYukw1q60/zII0HxvmcoCZUbwPmKtw==,iv:9DbI39bJDO66N0tQMMZF9q671IvAbuPMMmptoZSdpwg=,tag:CpLiqnORz/v1R2VAabyxJQ==,type:str]
sops:
  age:
    - recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMFZxc0VmQkV2VTRqRzBC
        ZEJ1ZXFSZnJhT1V4TlpNbThlSjgvUVVkUG5rCk1wN2YrTGRscGx3VmJIeDE5bE9O
        ZTFXVGFPNWliQW42Q1YzS010OXlDWVUKLS0tIFZOVW8valF3Qk1leEF2Tk9zODRM
        SCtFeWJ0bHFFckczaklHUVJpSVpWQzAKAUI6+DE3TugGIRnGo8qCt8wl4ubGotc7
        cqlAFMJjIyHkOufNZbq7Bq2/Ex4nwq0wq5f8FbAQB9O+sB71stuIew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-27T12:13:54Z"
  mac: ENC[AES256_GCM,data:WRlTkhW2qoCy55AClQnfL65L/ze/ucy0uknw93nr2x0z2mHseTbNruk19TYG21qLnz/ILebdCf4Wn7VRB0aHNomzI8sah4CYLVl/gBkxwQtBkvo5YgQQ9RkteUFJY7I+TSnWFv+Y35Q1tnGVeHA7p2PbBbXPLWJeYBX2bW5EUGo=,iv:dKBxlDe9/uWBBpZLWhdKzzGnBcHOrtI/8oGLPL7/KXE=,tag:vQMr+PfLEJopcvxtxd7s8Q==,type:str]
  pgp:
    - created_at: "2025-06-19T02:12:25Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DC0EwVK2S0BUSAQdA/K0f5jrjrvPEk+D73ZbU+juAPhUC0moI8jsBkKL7gDow
        JeFcZJU/oQBa4IKMPbViXnZ4lphIpH38zrnGiZceCivu/iIatO8qytT0S44/j7H/
        0l4BuD04Jg+4d0Kv15lcAMeZaB1LCDLXqnVzap3nzNFHSHZv8IhKb6g6MWEkUr/y
        htdlMndiSLw816xZMy8+F5y5fRdaze3LLd6N7ryDC65w1wQA/TQFnpMcliRVSxgY
        =nW+9
        -----END PGP MESSAGE-----
      fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
