apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-secret
stringData:
  RUNNER_NAME: ENC[AES256_GCM,data:hsRq63e0Q0CXp1m4Ums=,iv:tOy1QfJ18xxyZMTySSXR9jemq/wQf8JP/exoQyAEBzE=,tag:Dk/NBycImg3Lj4IKBgSdCw==,type:str]
  RUNNER_TOKEN: ENC[AES256_GCM,data:XB9YmZmI0cTCEZTMtDXGF/7Cp7DyK/IAi1XZrox6mB3CQAWHA1lrWg==,iv:nYudAtNARwb3DcrjY3b384pv0CKf2rHdplEFOyGVYQw=,tag:oWWWiMvSgKfaxBPhTwxQiA==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHZRQmlrb2NE
        ZDBHZXBEM3Y5MEluanNOS3JoSTllU00yZ2FJQnJBbGg5N1doVklBSHVib1RjVStS
        dkNjYUpuRUxtL2tueEEvV0hDWGtpWmpTVHFvcDVoNURBbGR1OTRRWC9mZE1wL3lt
        cDJGZldMbE1XY29JRUZBNy9KaGc3TFlLbjlCZmlVTHFuZk1zM1VMbS94Q01HZXVq
        MmpDb2Fvem5yeGpaZHAxaWtMcTJEMEc1VjNzZDI5L2RiMHlHcHh0SkQyRDNnRzlZ
        V1VBSkFTVGxrallPVHR1N25VVkN6ZWtIR0ZpYUZkblNNVUV2N3JJQTUrSXRGS2li
        OGtuNjhaWktzdWR0dzVvRysxL0xFeDJkSUNMeWFDbHRnR3pVaUFLL0hoQUtpNUhi
        RHJiV2tQRllPNmxYT3dOUHBlRXIzTjhLNU9mOVBydHZYY2VJRndNdnJqOEU0cys1
        SmdmeEF1cmNpdVBZcXpZUXM0WUs3eUVsWEFoblZnakMyRFFDYWxwd0htNlNoVU5m
        bjI1VUE2cWlLeWZ0UVhtMnBuWUwwMENBNVhyS2toMWUzOUl2aXBReFg3L2VNNUlo
        UkswNXZhN3dxbEQ1UWEzbmZBRjhkR052d0RRS0FLblNFVEtkclhTU2FNRHFYL2x5
        S082N0lGdXhhRnRrZUVsUkhSaENuYnJIRlVmTThTRWdYK1JvZmtiMXNySkZZMlhk
        ZGJnbFJQSWpWMWdISjVUR2pSSlBmRnhsbjg0c3EvK1VWS1ZGVVNSQUhQWEFMU2ZE
        UTBBUkUwalhFVVdnY1c0L0hyTXJ0L0hVTFc5OG8weVc3aU13OG5mRG95MFpUclp1
        VktJTGtnbENpTmdDaGFFNHBIQ1R1ZkFFUUxUTythMmt1MFN0UWJZYm9wNEhhYjI0
        aWd1K3J2TXEwLzkxYWRYc2ZOamtkUHlwQlVmK0M5YUcvZTRpTVlEeE42SFNIYTNH
        Q2s0Z0hhcFNLbXBubTdNR2VHTS84WENyeGJyYzJJNmI4WmlhQ25zc0lQeVI5WGVv
        dnhmU0FaYVVrZkd2bGYxaTQ5S1dvRW9ydjBFV2t3dGZ1R2I5MDNHZFRUN1d3ZG9G
        WXhPa3hJbTBoWVVlelpXV0o4YVozb2o3VDIxMEtGTGszRUpZTUFZYzQ3RVlORDRY
        alAzWVFwNTFNUmRTZXR5bUZ5YTZaYlpFM3Z2bTk0U0NrbWFTODhrS2VzL0FrK1J5
        ODV1V2paeE5qcEVNME9iN3JWbWlHaHhtQUVUbVM0dXlNbVpDMjczdXM5R0JRMi9Y
        eFlEMGtVczEvQWIrQUZ2VFRneEVCYUNSQlZIRklJRjRZbUlsbjI2Y1ZGcG9Ub3hi
        d09ZT3J2UVQ4c2ZWU3J5cGNLY2M5VDNHcTJYelpKQmpJM3ZMb1FyTkFvMExMZUJp
        L3BndElSNGllaEJ6M0ZVMktqN1hmUkVLUHZteDdoT0lRR1p2R1VSZWdMRzRNc2hk
        Y2dNcm5Na2tLQld3RzIzSHBoMmRlUE5ZallHdUtuVFhOcC9BZW9IQkVMbnAyVHEz
        YUNpZEpJR3JUQkpXMEovZ0dNdnM2WHMxQ0NQM2NsTkFTTlBQMUJ5U25FdzlHWTEy
        UW82MlJVOVlCVmphSmwxYWlmNTJ5ZTBuVy9jYVVBRnBVbVJKcnZ0c0lqRit3cExY
        a3dvbDZqa3BWcXBmVzJkK3JWazhNRVVTQUFyRUQ1VnZUd3NZNkNoSE5SMDB0aWFH
        Znl2SlpWNEJxTUE4dHlBMmdaQmxWazdSdStQMWlEWUV3RHFXNXgwNThuN2JkSFl3
        M0dnK0ExSnRaL0RJTjdROXUwVFV4NkROZVVYOUlTaXlyVmN1UTh2aXZWN0lBV25j
        ejRrSlJFUXJIeEJqR3Q0YVhvNkVzbjRiOEFlR0dhZXRJOUZ3SmYrU3l3OUd0R2Zo
        bWhZSzd3a1pPN3VNZmtieXlDVWVjd2pUM01aUDVrTldodEEvcGI2TDR3NG1DUQpw
        RGFOOFZrNkp1Ym5kVlpyeHNKbDVzS0dEaTlHWnhvK1dUL2NNVVBXSnBVCi0tLSA5
        aUR5Q01DbDk2SlVvRzdoOTdITGY2S09vdVI4aDhSUDh2QzlmSDZZeHFVCjNgCzwu
        bOsytZfgtk7RVqMLWqs2Y9jxWT1hdybhgVg97na4Y0r6qJ5hdH2ctWo9P0TTFug/
        LWBEhQxsN9LwnmM=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-27T12:16:57Z"
  mac: ENC[AES256_GCM,data:m9gPnn5rBgzSwmLv4oa4rNgI5ko0fNnQNxgBIUdJrM6pXVgMnRvIyDpo0hwGMqbJqhLC40Hvng9u+iWin3tQedgaGsLE4LeTbqmGlnKO3jF/CPZ6XzyiKxNFiCG86PgyN4vb+XKLa4nNA3foKih/9FvssPJEm4Jd+WaqlPpXul8=,iv:IzlQKnnLfrOjE0fdt5728vSGNzRF6tNd0Kvzol2P/z4=,tag:RfuH/GOuaq2qGN7Zpf8Ojg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
