---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/toolhive.stacklok.dev/embeddingserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: EmbeddingServer
metadata:
  name: embedding
spec:
  model: sentence-transformers/all-MiniLM-L6-v2
  image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest@sha256:7e67e6c7c9b33b85eb32d52a068ba845a2be7d5047702e195211dbe03fd64532
  env:
    - name: HOSTNAME
      value: "::"
  # krr: controller=embedding container=embedding
  resources:
    limits:
      memory: 347Mi
    requests:
      memory: 347Mi
      cpu: 10m
