---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/toolhive.stacklok.dev/embeddingserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: EmbeddingServer
metadata:
  name: embedding
spec:
  model: sentence-transformers/all-MiniLM-L6-v2
  image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest@sha256:d21c17ab9d2087c71d49a12171d1b6fcf324e853146eb3987e83d700079adf4b
  env:
    - name: HOSTNAME
      value: "::"
  # krr: controller=embedding container=embedding
  resources:
    limits:
      memory: 347Mi
    requests:
      memory: 347Mi
      cpu: 10m
