---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: &name grafana
spec:
  image: docker.io/grafana/mcp-grafana:0.11.3-alpine@sha256:130af3b5645c60f2420e9d842b1bafd4b7a327b7e0c5488b92f28c55b2ec83ff
  args: ["-t", "stdio"]
  transport: stdio
  groupRef: mcp-tools
  env:
    - name: GRAFANA_URL
      value: http://grafana-service.observability.svc.cluster.local:3000
  secrets:
    - name: grafana-mcp
      key: token
      targetEnvName: GRAFANA_SERVICE_ACCOUNT_TOKEN
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          # krr: controller=grafana container=mcp
          resources:
            limits:
              cpu: "500m"
            requests:
              cpu: "10m"
  # krr: controller=grafana container=toolhive
  resources:
    limits:
      cpu: 200m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 100Mi
