---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tor-operator
spec:
  interval: 1h
  url: https://agabani.github.io/tor-operator
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tor-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: *app
      version: 1.0.14
      sourceRef:
        kind: HelmRepository
        name: *app
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: replace
                path: /spec/template/spec/containers/0/args/7
                value: "[::]"
            target:
              kind: Deployment
              name: tor-operator
