apiVersion: v1
kind: Secret
metadata:
  name: anubis-key
stringData:
  ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:eMQgoGBFFHofGFTzynFeAxXMS1Ge+UePhj5+XpOt2AEXgSOYSW5Va3D/Dx2jnb/RunFqYHj9whvqzYnF39CSBw==,iv:JkW09xM+a6OkFJ9mgDNlfIfWQ5CJB4Z4hKoXSaa9ZNA=,tag:dHkWSduE/uY0civ9xwLfZg==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHRUQno5RVV6
        VHFFRStXR2dBK20xKzZzRlcyVjIxTVczM0MrWXY0eWhuR3EzT0pOSkVsbG9VckNh
        L0JqWEtON3QydzdlSHJqYzBuN1dtMUFydGMwTUtvVzNjWjROQkpPY1BlR2NSRllC
        TmVFTmlaTTJ3eFo5cUFRUThlR0hBeDVSU2VWUWRzTEs3b0pmcXl1SGJoRm9XR0xo
        MmttMXhhTlZndE56N0tUaDVHeGNWdmx4RWdKSytQbkR4SGcxblJUbDlhbXQ1M3hS
        aXFZaXJma1B4QTUxL1RlWmhMaGtDMlhPcEg2VUlESDlmRklHZWtNU2lDM3hHNEc3
        bWpUa29JVjNTVndyUnFqMU03Z1BKMFc2NWVtbjhVdnhmZk03bkJVWFpzT3I1Wk5u
        VC9MVFZxNVBlaURtQWVkQkEvM1BhOFA0RDBnbEJYNmI2TmVjSlRsRXBVeEpyUDVs
        VU45aFIvam9Gdkc0WldjdDByeHBzbjVhTDVrRllYRFVudnRBQmExRGlsbXZ2V1Fv
        WFZ0Z1M5Um5KRWYrS1dhQzBEWUtNWHNSZmhTVCt0bEVxZzhzQTNHS1h2aWxzdGRT
        VGRrUzdIbDJiSDZRb3RIOVBvTHdxaVVYNFp3c05zQ3k4cjZFM0FPcDZoN0JJMWZU
        UUJybUd1aEpra2kzK1VxMXFqbEd4UDd4eXJaZ1VVckcrNXBCbnUyMDcycGh5N0li
        aW5ReTNPQzI1eFFtRW1qOGQ2SkFldC8rWmZQQllLK3VEZnRjVExrT3pRZXkxVlNl
        QXJCcm9QK0VqNjlkVUJ4c1FsdGZTREdOcTNNRTdDZlJYbEpxM3ppVEw1VHJKWnBB
        Wlowa1ROV2laQkFjUzEyelpnR3ZCUFZSa1Y4UzZLVFdLSGl1QzQ1RUpHdk5CdXcx
        bm5kNEJQZlZjT1ZwWXo5ZWVJaXNLSU43alh2cStqSTM5Vml5MTB0NXM4dkJBSnNv
        L2haYTBiWjZ5cGJtaTlkL3VpbU1JOFlpdXl4cjZ4WXFhS2NUTjgrS0lEaEh3cUhm
        OGozcnBMNkpmR1d1OWpNbWpyYXpJazBMSVpsTUdsOVQwNVNRazNUb3JLcVBJWHMw
        alZtNnBtWWVLampWVXluVEdiZXVFQURxYUVDc1BCVGhnS0x1SUJLcWh5R1RSQTQ5
        NWtTNjN0TEpBcC9TYXllVGRRd3lJUXR2VTRmL3lBVGNpTTU3L1Rmd3ZxWW5YY1BB
        QlVtK3JFQjJjR2xwRithNW5mazZQREtMNU5CUXV2K3d1SDdvd0xZenlRUk9yaU9M
        WFdJeUNiUFhla0VwbFFEeW9VbmN5dThTK3RUVTRaS2Q3MzVreUgyWkJ2UlRzZ00r
        S3Q1VWpNSGNHR3M4L0hPM3NYaW92RGJHaE5tR1Vub2taVmhMR3A3d3BxOGM1QzE5
        blA3RldUeXpPYnc0dThzUmxHMklselJCZ0hFaTl6US9IcmYxZmNuMkt1VlU0Vlph
        ZGE4azZ0UklOQ05tb0JWaThFa3lUTEg1TnErRWEwRDZ3eUI2VEpLMXUwYmI3eGJK
        T1FRS20zNjNKS3NqSnRGeTQrNmE5ejUwTnQyY2hHNnlZMnBGUkNlMll5QkNxUXZz
        RjlDWEN2TWEvZTZvMjB0cnVJNFhCMVJDYzFZWWtGaFRqU0Jrd2VXNkZsRlMyRTNJ
        WklVVGRHeUo3YldMa0NUcEtmdGtGTjMxdDA2RmNzT1htUnhWNGg3TDZZVlZUbUQ2
        dTFCa3BxUUU2aUNObWNkejBWeWo5WHNIS05SLzZPU21pR0xYcEl6b2dwRXB3bVd6
        QXJRLzJ4MUswaWlJMTJSalN0dmZCUDFRRWVrU3hHRVRLaHJQdDRKUDRyUHducjhM
        Q3JCYmdLSXdWQnpIbWhxK3oxcnZhTldtVExPNnh4UWpWV0xhYm16R3M5OUluNzJG
        QVBvTktJZm1pWHhRZ3lSR2FBK1BycFllU2RlOFQzbG5CNnhGU1FMTHVzbEFQZwpS
        K1VVanlyL0RTZTlDTnFIQVZMbXRBSzltdDdoOWtRNEVyQ3FoOUwrdDBnCi0tLSB5
        NldoS2hOZVZQelpIY3ZZWDRIbzZOMStSTksvcFNJZTVvT09zclA3RkRVCtvBxULi
        TAxVZco+c4FSBnowWrdvDPjLX2SvmFBCjsKzTJPSU2onHvoUBbBIHE8BzwG7Tclb
        sXqpzy098+a2o0M=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T17:51:27Z"
  mac: ENC[AES256_GCM,data:vadcX1kkLrQLRmHJKVwtdFdB38QbZan1g4hzzEFFDulIqLPKDoZEGqOUFuyBvpQSn77+WQKR/ii456IdaVFudxd+AiR4cnH31ZlK7VSc8yyLjvSYbgeEGIddPh/na3XmDGD6n8ktF7qSewvExodnhzukyyWp5L1l4E0/sUZs5XA=,iv:H2yRLvx6egG2ofO4mmkbOBviBKxc0d0iDQPWJrfOeOU=,tag:e2utX2cynKCTjAPg21Q6ZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
