# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: qui-secret
stringData:
  QUI__SESSION_SECRET: ENC[AES256_GCM,data:59UVOnj4sftZP071CMz4nq0N0LFdWQQYPE5ObF+T0xJ+3QbMCcxp9q5Vs9wuSR1McVWpDzgBPGLuZDno4T6MtQ==,iv:Pb/aMAZmiGDeUzwQYsOo87BiRG8hNykiDMJ+E8XiC7w=,tag:dYMN6ibu/aowKPRQ4342rA==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFA2TzVOb3Nt
        UGc4TmJ0NlR1Zkk4ZkVyMzJtZ29DazUzUHZaeUhsSURwN1dQd3hEV29maFJOajZC
        S1NSSzZpdWJ1ejR6T2U0eGtaNURGazRnbFNGSVExME5FRzZnZmpKa3hLaVg0dHNk
        Y0NzeXI4YjNlNlhtU1B2UGhxS0doKzV3T0xBMmtoQzk1VFExdHhKSHF6N3JLaWhP
        Vzl2c09hdnhodklMcGV6bGZOZVoxclA3Zmx4SHU4V0pqQXR5OFdFQ1A1OTZyWUJQ
        bCtjWkVNZGdSdDg1WkdaenBXWmlPSnlnZnJBVDg2MWErcFExSUlpWXpMOEk5QVc4
        Z21xTzRtYStBSGNBUHJyUDNVWWFMcUJaV3p0Rm1FY2laUVNWcis2cGp3MHhnMWIr
        bFJmN1g2b0FMc29iSzRwc3c2bW1IK09OK0o0elgxMVBzdFdxa093SkdxbVdRWE5q
        UXhXS2xCNHpMMXRCbDRhbVRsODJvUUt3MXhHVzZQTWJaa0FESnVVS2ZPWEFOUGgv
        Ynd1Si8xSERmd2J3TFl3bGE3a0tSQ1NXMW4yQkJGNUJ5a0JiUDlyUUZZVkpqbEhM
        N1A0LzVoN0tTSDB0UVNaWVpRVTIwRmxMU0NWK3M3ZFR5T05FYlhUOEVuVjFhWnkv
        MUhPcWJmbExLY0xLMGZTdG9UaGc3Q1BtRCtqWjArajF2OGRiZTA0Nk1iZ0lLYmNQ
        SVZVME5CaHVPcXhxOXJWUkloSFFaYVp4eVJBY2UrbW9uV0pkT0NtREZXcXMrYTFp
        dDdObnpQa2k1azUyU3ZMQUEyTG45akc2MjhaMCt5cE43SDc4M3pwVEJoRUhjL2tG
        UExXUWlwMW1pMmhnMk5iYW5IQk5UWEZOdTZncEhTQ0xiMnpnaXN2VHZyS1hWTmFV
        enpYRXpoeE9wRitJY1k3a0FSYzBFTTlUS2pVUnowWFBvRzlQY2prakc3ZHdOaitH
        Y3BqOTJtb0hvdnJuMlRlV2h3eUhlUTIvM0huWStYZ21PTFBaNTQ3WE5TaHl0MFJw
        MFo1bHBieU9rNHEzMWptc2txdGl0cUk5QzRsNlRYeEwrWU5hdm9yZG96KzlWeGNC
        VVQvUFdlWGw3WlM2OEtUWGRva2x6MDFoVmUvQnF0ZmNvZXdrbk5wdy9FQlhKS2NP
        SG5oTGdpV2dTdFl6cUxrQUc0NmE2SHV5a1Y4NGVPb3U3Z3BzWnhGdEJrcUV1UWpl
        SDEzWjBPSWJKTi9RaXJZQ3dPNkp4YUhyMTlqTk9DbjRUWUJ4bnFVNVVWdzJuOFN0
        NzU5aW84WnZkY2NrMzdsZ3dZRExuMnduSXRXdkkweVlrOUxtSGVOTnMzQ1hpWm9u
        c29sL2VKd1o2d01pUFdjVHV4YnFwUjBNaUl4ZzErNkljL3JVcElPNlF0T2dreVBD
        UTJrK3czK01rN2E5dlhLUTMycHZJOEpCZXQ1bU5PbjNkbHFMcytSazkrR3d0Rmtm
        YVNFZHRHVkdlYUlUUzkvcEsxK1liSTNkK1FxL1VSU3pweDE2TEJzWjU1UUZFeFJZ
        UFk5MFlXeVhnVHdMaTRwRmFTZ3lVQ0VsbmI0MUNVaCtzblhyZFQrWi9Ec3l1eFJ4
        RFJWdG1mNWJva2lQU3RaenZML1dUL011dVBRN0tXRTBKNERNcGEreERMTkxVNENq
        OVBYUlkxQkJIR2VMZXRpeTcyYUJtWVN5aUxsbnlrUGwrN28vdVJMa0EzL3JYb1hz
        UUl5QjVyeFpNQzF4eXF0c3k0cE5XNkRSOHI3TnAyK0RrOVlheU1XVkxiQzNtRUxS
        SE9lZ1NmdDJudWZzR3hnay83dmZockFjUVpNM3U0MUpXcUxhc1hmUE9JSTNGYzRP
        YlU2bnpvWWVKWklJRHlveFlFUGsxNytFK2ZEWUFGNk9EaGpZa1lkMjhIdUlod3BU
        K0s4amRyNkRYbUpHbVo3a2M1MVI2cnR2bStEbGx3c3RhajB4YWZET3RramRLZwpj
        ZTJXYkJhMHdUWEx5VTNqSlhaUG9pNjNMbXRsU1VSZm52NUMzMkowclpVCi0tLSB0
        MlpoT1BUblYxUzV6ZHVxc3IyaW5jOTRPOFlyT0k2SFA1WmJOS2xnanp3Cj0YpTLe
        aB2fPbH5MtgsJClggTcvTE24vzdFHp4JvYZ4qSldy0n5hSHxm56XFb2OjxfRtB3a
        W8KtZAqvctvuZ9I=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T17:58:32Z"
  mac: ENC[AES256_GCM,data:R7UG2w7EdeqNJJ5qOBM2UK1WrOH6gVA80ZFlDg7fRDcTx7nLqC9qrpT8oQVB06DD8TSGvazk3QQQkuZGKqa03jtqbv/DvmXJ5LQpzVHmmmEjEk4uGp2Xrf5BzNaShX3oqIatPVbUaKCr6peFnY2+i+qwG5HxNuCCAQZNR+Wz8Cc=,iv:nJOZ6IcnuH9Q6A3bj+B7dhzFiKIafYYmd1dAVvrmdfI=,tag:3QhUp9z4gU2TGAxNeRyaCQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
