---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-standard-trixie@sha256:01182316b7e3b75799a390a064a78f52109f8671b51999d5701fba37cb2fdd8a

  certificates:
    serverCASecret: postgres-server-cert
    serverTLSSecret: postgres-server-cert
    clientCASecret: postgres-client-ca
    replicationTLSSecret: postgres-client-cert

  storage:
    size: 10Gi

  bootstrap:
    recovery:
      source: &src source
      recoveryTarget:
        targetTLI: "1"

  plugins:
    - name: &plugin barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: &store garage-store

  externalClusters:
    - name: *src
      plugin:
        name: *plugin
        parameters:
          barmanObjectName: *store
          serverName: postgres

  monitoring:
    enablePodMonitor: true

  postgresql:
    pg_hba:
      - hostssl all all all cert clientcert=verify-full map=pooler-map
    pg_ident:
      - pooler-map pooler-rw all

    shared_preload_libraries:
      - vchord.so
      - timescaledb
      # - pg_documentdb_core
      # - pg_documentdb
    parameters:
      timescaledb.telemetry_level: "off"
      max_locks_per_transaction: "128"

    extensions:
      - name: postgis
        ld_library_path:
          - system
        image:
          reference: ghcr.io/cloudnative-pg/postgis-extension:3.6.2-18-trixie #@sha256:f68b1f6ad6a72ff042d36cd32fdbc31e5fcdab0fe55e9d4c9226c1c8edf12c9a

      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v0.5.3 #@sha256:c310ede47f7f82bd257c3e53806d60680d5899c318ca946fb313efad9a90a78e
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib
        extension_control_path:
          - /usr/share/postgresql/18/

      - name: timescaledb
        image:
          reference: ghcr.io/shusaan/timescaledb-testing:2.24.0-18-trixie #@sha256:dae25c2dde06455214ac5553b51d3ef2d48fe84795c2cfa48c51c6e15877044e

      # - name: pgcron
      #   image:
      #     reference: ghcr.io/ardentperf/pg-cron-testing:1.6.7-18-trixie@sha256:c537ff41c2846a26527defeb261d0d5d9cd113d7d43eadad28b8620726a7a5fd

      # - name: documentdb
      #   image:
      #     reference: ghcr.io/documentdb/documentdb-kubernetes-operator/documentdb:0.1.3@sha256:3c69aabf31892ccc41dff22b889ef75bc2673ff68440a5adbc8c37f868f61a7f
      #   dynamic_library_path:
      #     - lib
      #   extension_control_path:
      #     - share
      #   ld_library_path:
      #     - lib
      #     - system

  managed:
    roles:
      - name: pooler-rw
        ensure: present
        login: true
        superuser: false
        disablePassword: true
