# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/fluxcd.controlplane.io/resourceset_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: &name postgres
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  inputStrategy:
    name: Permute
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
    annotations:
      fluxcd.controlplane.io/prune: disabled
  inputs:
    - role: pooler-rw
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      selector:
        matchLabels:
          postgresql.cnpg.io/role: "true"
  resourcesTemplate: |
    apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    metadata:
      name: postgres
      namespace: postgres
      annotations:
        cnpg.io/skipEmptyWalArchiveCheck: enabled
        kustomize.toolkit.fluxcd.io/prune: disabled
    spec:
      instances: 1

      imageName: ghcr.io/cloudnative-pg/postgresql:18.1-standard-trixie@sha256:ec0c0d60f9462b49f4c6f2403fd680ac43a063fc793f5d570a21a3cea8e627b5

      certificates:
        serverCASecret: postgres-server-cert
        serverTLSSecret: postgres-server-cert
        clientCASecret: postgres-client-ca
        replicationTLSSecret: postgres-client-cert

      storage:
        size: 8Gi

      bootstrap:
        recovery:
          source: &src source
          recoveryTarget:
            targetTLI: "1"

      plugins:
        - name: &plugin barman-cloud.cloudnative-pg.io
          isWALArchiver: true
          parameters:
            barmanObjectName: &store garage-store

      externalClusters:
        - name: *src
          plugin:
            name: *plugin
            parameters:
              barmanObjectName: *store
              serverName: postgres

      monitoring:
        enablePodMonitor: true

      postgresql:
        pg_hba:
          - hostssl all all all cert clientcert=verify-full map=pooler-map
        pg_ident:
          - pooler-map pooler-rw all

        shared_preload_libraries:
          - "vchord.so"
          - "timescaledb"
        parameters:
          timescaledb.telemetry_level: "off"
          max_locks_per_transaction: "128"

        extensions:
          - name: postgis
            ld_library_path:
              - system
            image:
              reference: ghcr.io/cloudnative-pg/postgis-extension-testing:3.6.0-18-trixie@sha256:ec21540f5799561a9b05ca188fd28ce32852a826f48d80329260940855f5f558
          - name: vchord
            image:
              reference: ghcr.io/tensorchord/vchord-scratch:pg18-v0.5.3@sha256:c310ede47f7f82bd257c3e53806d60680d5899c318ca946fb313efad9a90a78e
            dynamic_library_path:
              - /usr/lib/postgresql/18/lib
            extension_control_path:
              - /usr/share/postgresql/18/
          - name: timescaledb
            image:
              reference: ghcr.io/shusaan/timescaledb-testing:2.23.1-18-trixie@sha256:4709935bed4cce5977bc4b1858a94e2e80f22f0303217163a9e97b8898e33ee2

      managed:
        roles:
          <<- $roleNames := list >>
          <<- range $k, $in := inputs >>
          <<-   if kindIs "map" $in >>
          <<-     $r := index $in "role" >>
          <<-     if $r >>
          <<-       $roleNames = concat $roleNames (list $r) >>
          <<-     end >>
          <<-   end >>
          <<- end >>
          <<- $roleNames = $roleNames | compact | uniq | sortAlpha >>

          <<- $roleObjs := list >>
          <<- range $r := $roleNames >>
          <<-   $roleObjs = concat $roleObjs (list (dict
                "name" $r
                "ensure" "present"
                "login" true
                "superuser" false
                "disablePassword" true
              )) >>
          <<- end >>

          <<- toYaml $roleObjs | nindent 10 >>
