apiVersion: v1
kind: Secret
metadata:
  name: garage
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:MqZGdWwGN7zG2k3tBBmYvtoneFeIh10EiNs=,iv:zcZtfeGwX4QpNmM1QM4jdR2p4QUVoiLKnnhdVeCN19s=,tag:PzZuSYvo+Es2bgBjX31/WA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:UjM+K2Yc67m9qTf4aUYwVfTTKm0meACR+8HGWl7QR+/sUtpaLDYDh2ZFrETav+YeY5u0AcvC6p37xigaEOppjQ==,iv:fheltYco5buXenSo5XGx8sqCdZ9vYnKIGKHBF0PsLbo=,tag:DSPvim0EAGRS9FFbQcIOlA==,type:str]
  REGION: ENC[AES256_GCM,data:eTpx8KHq,iv:Fn4wZ3TgtTG51r4PKjtZgct78tyPZRF69GY0ApGtPig=,tag:MxrLUdbFh6NYFEKkWgNHzQ==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFE0K2ZDdHNJ
        a3RYekVWMmN1VWpNM1loODlYR09ZOTdGRW5SdkJ3THcyanNDNHUvRVZnazZmVGIx
        alkrSGpYTU0rRUF5cVpTR1NIUHpqRXF6QzNlbW9UbFl5TXRYV0FaUkJqZitERHJL
        NjRZZjloYkI3RDduMXc5L3k2RndUQnhFTS9EZUY1bnByV1VnOG1RdGJ3cGJ2YXlX
        VytnVldYQXIwRXJLZ0ZrYUhuRFdIbDJQT2c1N0NONlJKT095SHl0QUpYRmY2dzBs
        V3l6czIzQjJ2NkRtOWcvaVlZTkk5U0hReURSYy9hbVhuRHpXOFJ0OWp0QWptOG9H
        eXVQeGFKUnJETTFnaFAvb1R5ekl1VjJzYklmTzZoeU5hb1dpT0ZZWlFoTHkzdVdB
        T2QydFJaMU5QaEYyTHVlZmpTYWRQV3VDb0JZcHhsY1FXeDNLNG84QTZIMUdPZHR2
        ODlDTW0zRUszOExRdTQzRks0THg5NzZ6akR5Q2gvZnNuRFhlVm56UVhrUEwrVFQx
        TG1US0d3TG1ZdUFEMElCZkQ2K3FRanVYYS9QMTJRbmpJeGkrTm1HRllqSzhpREpU
        amxZUlZCc0szS083OUhRQk0xUXJwN3RFS29MdXlVL3RXQURWKzN5RzhaTTR0a3VG
        R2E1cG1xMit5UTBTc0h6MGNEcUxXTEcxNm5yNmFnSVJMVDI5VlV2bXc2d0dOSjIw
        U29pRjZYVEFtZW5nak9PZFpKNDBNdUhHUGs3cThaV2U4S1VLSDJUNDVOOHVObng3
        TEdZMU80cnVESTEvUnFBVkNLSWQzUWcrbCtkVC8yU21XUHQrc2hvUTlJM0xObDNs
        UmR1QUJDUW1xRVhONmhRQWN4SHJ4clQ2YWlaNVNYQTRSZ3dRUUJSZDhYUytwcUJs
        MXR1a3NxRjY5TjRVaUlVU01KR1dJN2VUeTNnQkwraUxBdmlSeDJaZXJyTFdseDF0
        K1ZaaW9xdFYrSGRTWkdLVklYVXdoaHdvVEY4ZmlBNThSeW5QbW1BbER6clV2dldB
        RW8rV004SlJxM0JwQ3NKL2xoVjN4andiRlp6aCttVndBdlV5R0tjaVhRMzBBNEJY
        cWJGcWpUcmtxMlRqaFh1YzBKL2xRU25BQVgrbTg0QUcxUjRZUHF6OXYzR0ZibEJw
        MHllRnF1R3V2NllVbngxcmNyNGpudGs3Z0Z2OG9YRlNHWDljNmt5ODVYV1k0VDRi
        VjRETkkvdytGWmhqdUlNNGpreEZZRFFzLy9BSzAwMTFDYjV6V3hqVysrWlFrR1dN
        MFBld0FtQzZjTmpJaVJ2QjFvVHp5amZiZVplUTZjSEtJcFVBcFd3dVBQY2ZYU1Mv
        MFhCS3dxSi8ydldBWXJQek9HN2QzeFphME5DOStvTzZlVS9lSTBJNTk1K0ZVRGt1
        d1d2V0dBcHRpbEFxQUF6L0hyZkVDbkJPQmlSRlZISkMvL2Y0Mjk5MFVxS1REYWlq
        bkszQ3RFMkJOc2swSnltZlB6S0grcVdEYnpjdExSOEIvQ1BmNGpWeDZ0elpvckdu
        MWZ2MHMvU2RyYjBuUy9POUZ4REh2dk9nWGpsOExBS0ZuTXVqVVFURXFuenNRa0ha
        NUJPOS94SGxsSWVsVzlyV2M1MlBBaWZHdm1xa2V2elIrbTN0eVJqdzJURkt5ZUR3
        R0grTi9DRmIxUU14RDZMNjJVaUMvWUVBMlAzU1NUVXF4NXBXbHB2K3ZsN2JBOVNS
        OXhMcGlSSkF2VS9DU0w0YTdoVHF0a2gwYVNyQXdlemZ1bE5Fbjlyc0E4U0Rlclcr
        TWdBMXRZcUJORWROcDgzOTA4eE1RcWRaYkhVMUtwZmZTQWpreUwyN1hIZHZLeWxs
        dkFwZFkrTFV4d1ZFQ2Q2Q3d6VCtWM0VocEpvbVcxWG9xTWhsOU9nQkEvZlJueDhI
        MS9Gd3ZOVTJXaVpuZHlGcHJVVDB3Wm1wYmFiTldSVUlOUytPVUUyRDdRYURaZwpr
        amtKMUhQWkVJVThBempKNi9hdk9UN3BQeGRBQzVFSjg5QnRDWnBwdDRrCi0tLSA5
        R3U5QTlVK0JjY0xBZ015ZElNVzVINnZXNEllMndHWGo5elVaM2dMY0trCvNWFri2
        olMkOefuW0MFfGvwncw+RmOX6R0EVFiUJeR9OV9W3Nk/HZmb33K1NgzvwuYMbNGM
        Xv3TEAl3NagwLH8=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T14:22:37Z"
  mac: ENC[AES256_GCM,data:zn8OSX9LNwGctQ7cIlAb7Ea7TEwvltIUm5G+jumkGViCHokuv1uz3j3Nv4s2Q84rDehGJaUebaDCXkpp5yi2V+AN3a7Gb7kHUABvKl6oAJntj0Dv0U62Z4LoacQ4sRS6btJwq0Ey7wtH/Vz5EGkOnhmkxQWYZFqzIf8mLh7Qwxc=,iv:I7jZgsIxpFS5XsdahSnsmelg1+Q13T8bl8qUqDQRDi0=,tag:x38Ny/vFzGpPLPAlDDzseQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
