# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secret
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: network
stringData:
  api-token: ENC[AES256_GCM,data:U3iqSmWXKoVUcLx0BFoWQgjZUyS0SobNID78eusn4ICzCSd4A2fJjg==,iv:YoXPtlytnd4bRyVr06NM4ISKss5hWVCXthghe14vJCU=,tag:Q4aLRP2qlCBHMnU7rGAarA==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEJVQWJ1b2xS
        eXpCMVUvbmlRaFhZQVhLMXZ4eFBNMEdVUGhFemZxWnlUQjIvcUJXSmhZT2g5UWxa
        K0N4b3dyaFdrRnZoc2FqNy9RbFJKYVZXUlo2bDU3ZzhQT2hIbHF0R0FLQlhaaFEw
        c0F5bkI1Y05HUjFHTGNrdndsamo1aFNHRUpDb2gxUEJCNDdQdW5iK3RZSWZVZldq
        TVFuMml2U2tZZ1JINGhPOVZTMEhSSE5WSWV1M2dPeHFEa29LL0h2MmplTi96WERz
        K0RXSUNzZCtUVEYzQ09yM2NyRWFsRHBwOUJBaUQ4MzlOeVY5bFQxNWQwMUdEVUdG
        RnZvMGJGUWc0WHdIZ0txZjI4dzNvcXIzMTRuTWdydXVtZmlKRVQwVlBVZ3phRlEw
        S2diVGYyZm9GSGhpUitZM2RKWUFiMXZuR1VRNTk4VDdZVnlEQkYvUjhKU3BsVXVs
        TVNsQUhzS0N1NnVMQVN0d1FLbnZOcWdXYXFReUl5WlZlWTdydnhKM3NPYmovRENK
        eEJzdDlvV1BhTVVpWlVRS0xvZW4yQlM4SldFOFhlTzRtV2hPQVJRUEVoZWtLdldY
        OGZ0TTVnVktHRGRzeEtKWk1CaUJ5RkRIY3hIdENRbGZFQmp5VFk0UnlkMk1mbC93
        bEYrM0I3WUxtMStRcW1DcGRQQ3VqSk5NczkyS2c5dzVMSy9MWlhIS0g0c0tQT0dv
        UkJzbC82VjY4ZGJBUXJzbm5mUFg3SzBDekk2WVNrR0J5NUxTQjZoMkNmOXB2OW50
        SGJ5S3RvYUduU1d4dDdDOWFEc2liQzY0dEh4VWM3K3NRRGJvSVc0Q3RDZUFqQXEr
        N0FCUFB2OUtEeFkvdkIveEVmaG1UOW5OMGtodTZYKzZocUdrNFozTHFrL216RU9V
        c3hNM1o4QkRRRkI2c0NhNDJySjBrQmRoNjloSkNmK256UlNlU3ZtN3BSaEEvaHFk
        VzRHN09rQlg5ZWE3SjhMdnhLSXVvekxCM09SQ1RtSE1zMm9oOTgya3hPYlZsemxY
        NzUzd2xSNSttVitPOGNqYk1iOEVQR1FORjk1emRFUno1VU9ORysySS91dXlrZDYy
        alhIMFcvbUdTbWxxSnFzZWx5Y05YMStYdzdNTlZxTUdjYU11M2QwREowTCtGaURE
        NGdjZ2pjV2FaNCtPMjlITUcyYjYzaFZ6ME1kRFpkcW5JeEYvalhMdVJyVjRRZ1do
        WkJkKy9SS3BVQVlzaklQQW5nNzlrbVl2aTBacERza254dVhsU2RmSGtxOTBZL082
        Ui81RXdscFlVVjV1U2pkd0JtbVNLR0hHUW42ZUxpbUVXNExnRVpQaEl0bXh6a2M0
        ZmV6bW5JVHpRQXcxd3czbWszZDJoSUhGQy91aVgrUmcvVFI2aDN5cXZEQzEwQzNR
        ZkdJTzNTK1RJSkNhRGVCOGEzZXM4Ym9iYnp4WWJhcGZ4MllpTkxkYzEwdDRMaWxa
        U2hnNGRmcU56Z1ZaRHByanJRV2FiUWdPTEJieWxzaUFyTU14UEp5RnpabmNhRE9F
        cGhCdFI2ZUNKS0tpV1VaM2dTZXEyeVpJNmxKRHg2RExoSlp6cWFmOWVOMjIvODJW
        eDZ5dVhTbzVUeHM5Tm80djkvRGN4d1UrbCt6RWlOK2hYcDY4RXUvZEFnOEZSR0NG
        Y2RHSTVpWUs1SzZ1dU8yV3pQTytrOUV4M3g0cXluN1RDNWNpWU9JdHFwcUNySlUr
        T29mNjFOSUNySFB4OWdJdCt2Wis0UUpYMEk5Vm9JaUJtUEI4UmJNVHFkaUh5OTA5
        M2hYRUE0aTZUbnhCRG0vSFdYWXZ3akxtZGhUNjROYXNHYjl2YUt6V1JLcEpGRHJN
        dEdCKzFYbEFNeStGVDd1anBJZGZuSW95Um5QZ2dWaGYwbThuVm9nUDgwd1hxc3Rw
        N3BUYUJPWk5sZ0xOYnhRRlduVi9idWRzK1A1M01SSkZtVytmU1Fpb1d2YzFIdwpa
        UlE1YTllMGFhdm11Um1LamU4WFhtaHlqZjZuN29mZytldmZVTkV5R2dNCi0tLSBK
        ekNxNVRiUUN5ZVJaeS9takxiR2NxaXZPOUNYQk44Wmk4RzUwU1FGQm13CmDsqKUo
        VBzxutrn3HDeiFyTYKgm0HCp/b48POi5aiRvZpBl7sFRvfjlXL9EwoMEQHH8/q2I
        t3MOGuDeJuCH02s=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-15T15:37:31Z"
  mac: ENC[AES256_GCM,data:t4tUrTWNI/uAmIxROr7MrPjdGC7far3FcsCU+edxgiJsTB0pYp16dj264FQTTq19TgmNnfM2irM20wFJIX4eHzjXciBew+BqxwT3AThwBqGnyE1UctCVZx58opZSWO0LzeEWVI9aXSqsBd9+u1866L9GSXc/eEShV3HPpXoxAuI=,iv:ovINpYYexnV/is/Dip9UoWlGPE0CPq6TYC2Fd5WGHZo=,tag:7o/e+py8Q/qc2++RT+iNTw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
