---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: towonel-agent
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.4.1
  url: oci://codeberg.org/towonel/charts/towonel-agent
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app towonel-agent
spec:
  chartRef:
    kind: OCIRepository
    name: towonel-agent
  interval: 1h
  values:
    controllers:
      main:
        replicas: 2
        annotations:
          reloader.stakater.com/auto: "true"

    agent:
      healthBindAddress: "[::]"
      services:
        - hostname: "${MAIN_DOMAIN}"
          origin: &tunnel tunnel.network.svc.cluster.local.:443
        - hostname: "*.${MAIN_DOMAIN}"
          origin: *tunnel
        - hostname: "${SECRET_DOMAIN}"
          origin: *tunnel
        - hostname: "*.${SECRET_DOMAIN}"
          origin: *tunnel
        - hostname: "voltkonekt.pl"
          origin: *tunnel
      tcpServices:
        - name: turn-tcp
          origin: stunner.network.svc.cluster.local.:5349
          listen_port: 5349
      udpServices:
        - name: turn-udp
          origin: stunner.network.svc.cluster.local.:3478
          listen_port: 3478
        - name: palworld
          origin: palworld.games.svc.cluster.local.:8211
          listen_port: 8211
      inviteTokenSecret:
        name: *app

    directConnect:
      enabled: true
      irohPort: 51820

    serviceMonitor:
      main:
        enabled: true
        serviceName: main
    monitoring:
      prometheusRule:
        enabled: true
      dashboards:
        enabled: true
        grafanaOperator:
          enabled: true
          matchLabels:
            grafana.internal/instance: grafana
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: replace
                path: /spec/template/spec/containers/0/env/3/value
                value: "[::]:9090"
            target:
              kind: Deployment
              name: towonel-agent
