---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/fluxcd.controlplane.io/resourceset_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: cluster-apps
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "5m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/created-by: flux-operator
  inputs:
    - namespace: agentgateway-system
    - namespace: ai
    - namespace: automation
    - namespace: cert-manager
    - namespace: cnpg-system
    - namespace: crowdsec
    - namespace: database
    - namespace: default
    - namespace: dns
    - namespace: dragonfly-system
    - namespace: envoy-gateway-system
    - namespace: external-secrets
    - namespace: fediverse
    - namespace: flux-system
    - namespace: garage
    - namespace: gitea
    - namespace: infisical
    - namespace: kanidm
    - namespace: keda
    - namespace: kguardian
    - namespace: kube-system
    - namespace: kubevirt
    - namespace: kubewarden
    - namespace: matrix
    - namespace: media
    - namespace: network
    - namespace: observability
    - namespace: observability-privileged
    - namespace: openclaw
    - namespace: opencloud
    - namespace: openebs-system
    - namespace: postgres
    - namespace: renovate
    - namespace: rssflow
    - namespace: stunner-system
    - namespace: tailscale
    - namespace: tekton-system
    - namespace: toolhive
    - namespace: tor
    - namespace: trivy-system
    - namespace: volsync-system
  resources:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: << inputs.namespace >>-apps
        namespace: flux-system
      spec:
        components:
          - ../../components/common
        decryption:
          provider: sops
        dependsOn:
          - name: cluster-meta
            namespace: flux-system
        interval: 1h
        path: ./kubernetes/apps/<< inputs.namespace >>
        targetNamespace: << inputs.namespace >>
        prune: true
        sourceRef:
          kind: GitRepository
          name: flux-system
          namespace: flux-system
        wait: false
