apiVersion: v1
kind: Secret
metadata:
  name: vernemq-auth-secret
stringData:
  DOCKER_VERNEMQ_USER_ADMIN: ENC[AES256_GCM,data:dOk6BvsaaTNDSvI5WXfoMkLHvZGr/xp2IQaTpO4dC1XGQPz8hYN0RXh2Zuj1SmLpxgFjSKRu7Rybje9sNnYk5A==,iv:NCidHrw9xYmvHGczcVDJcLxFnwhC9FjB7zqJSrwVkko=,tag:rySBEARcKseyLzA/o588pg==,type:str]
  DOCKER_VERNEMQ_USER_MQTT: ENC[AES256_GCM,data:29+rTQDLf3r5IJb1M0e9oJMnKiA6W7gLB6CP/R/w4MvJEL2LZdH2uVr/WQb6aXHCrNrXx/v9IaPDWehJ+4IX2w==,iv:qAYZJ9UpX4gprnwghiQIhy+mrm5r5otkn14EaCHOzX0=,tag:nhx4CGfg3F8WM9hliXXy0g==,type:str]
  DOCKER_VERNEMQ_USER_SHELLY: ENC[AES256_GCM,data:t0Lp7fiCPm9m0N0HO3jjeFn5RAmIVptDoTuxLeirRR+dG6974eD1Fn1/sHvWrrIo6Qa7yglVu5ttFqAxD5zYCw==,iv:kmGoTnWB93s/SYdWWo+FauMt1qsYmvJAqTRFUcGjNL0=,tag:wSXw+MH4f8pFfCzn0hgP8Q==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFF4a2Vwd0Q5
        dit2WVY4NUJYMTNSNUFKVGtCakV2NmMxaDdNU1MwRFdTQjBPQm1oT0pNdVQzSFVU
        Z1YvbGZMbVFtdVpab1RMdlREbHA5L2Yxb3l6OWlpK0RCWVk4NmlmZk8yNnNEOTFq
        ZENEZTIwOUlXelZCKzlUYi9qdWFJcFNiWEtBSlJTQzBpRTBmcm9Vd3N5QVJHdzVs
        L2s4bzZLUkRVb2djek4rWE5jaXB1ZGVPcmFDZnNTTEgvY0xJRU1tdUJxNHRMNHRw
        dUtPamoxNjZLeGtLYy9jLzY3L2NZcXFnME81SWVDNEZudzA2NVg0bERhYi9zS2Za
        Mlcrd1orU2RNNWpLNzBXenFCdGFTWlRQRllPRHR2VEVSa3lpeTIyNGlGVWkwdGhZ
        YThmUDJvN1RMZzVVQUNvV3VrbXBaWDhzdUJ6aXFTc0xvdUVFamRvSHRuazdaeFNY
        eGI2b0RWYWg0ZmZSZVB2T1p4bTZYeUpOUXFTUzliSVdWL2tWMWxtS0pPREcwQTg3
        VU4rS3YrWjFySjNRWVYyM3U1NkFwdVRyT3hSTFNXeFVHcW9PTXdMQU02UXMyYVBp
        eFRlcVVXNmtwRERWSG93b3FyWXA0b010MEdoRUtDNk9sN2trQjh1SFhBMmNkbzBE
        ZVdYa1J0M2dOTUpMdTNodUtJaHp6UHZPMHk5UXJEdkszRXVJSjd6cDgyL1owcFFL
        OUtjb0U1anRVc2tTR3FlVUh5R0JVWVlJNExobGE0aklpU245cWRqaEJWRDJaWWp0
        dnF1Vkx1RTFKaiszUkI5bk1TV3NxckxBclZ0TFNFN2t2QzE1aWtLN0RHRjR5ZU96
        NnZ1aENNcldrZHQ4UmMrbXJrakVHNmlOeWVVbU51ZmJsWFNJUzVEeDgzM24vOG41
        NUZUNkF4SnNXZldOUVJtbGxXMi9KMmxZM0tlKzlUVDBJWG54dHhQank2LzZuY3p1
        ZFlET0RWVFcwdENHeGx0Qmt5WVFmRWtHOHJVUk1yQVBBUU80SnY4Uks1UTFtWGNi
        ckUwODFSVWNtOXdGR0ZSUDNuZkloRzlVMUw0NWtHQ1k3VTlDMTVGeS9haGxaaXQx
        MXk2Rm1md3kvSWxWUE5qeTFncXE1aElrRndsS2IxZGJFcysyQlo5cXc5RzNQMWZM
        NE8yTnhiWU9GUkFXV3F4eXZWSndzelE4RndqVGwvbEpKNVE1RWlzTU04SHVrTE50
        N2cwY2tlVTUxdUQ4eHVJS2ROZnFxc0U4ODY3Q2tiSGVXNWI2VEtHWWtJRmVRWkdv
        eFZvZFZHeHVDM3dDQkswcHdJZ2gydjk2UU9tR0hKWVJSbkVPUUE5NWhaVFF2dHlS
        MnlaZzdqeW9TOFdvRUxjTnJkTTl3RUVqby93NVByUi9MRnNPZ1ZwY251Vm5hRm9R
        bktKeWFLMVN3VkRLbnBXRWlwSC9BYzRhMVpuYWd2RENKNTdkakczQjhLeDlhYTEw
        ZjFMaFdMb0ZMdDFET1djRzd1ck44dHB2Sk5JRm9zTkNMR3k3Nm5tZVVOekNwMjdX
        cWtkbitGdloxZEZGbmh4dzd2NzlhSUpOM0pXMUs3Vi9sWlg2TGxBTGtJMm80SCtW
        b3dSNEorUlhvazltL093Y1VBUjdiWDBIbitNeU4zckNMcFQ1VTBJYnI2elVZMlEr
        cVJ2REhNTG5HOXAyRThqVGoyTkpjc1FXdXlyK0xBODZLdWU4MTh6T3prR3YxNGpG
        cEN6U0dmb1Jnc3JaM2wwSXhZbzNEeDNIRWtwYmo2VUZWQ0xRb1R4MjBKaE5GR3NQ
        ckxzRkQ3RUdnYSt2R01GNG45VjVqL2pON0hsQzV3bXpSZ3MxWWZHWW9xenptUTh0
        WU9zSHhnMmc4VE5kdHpOV0ZKSEpESDZESGxnTDZBWTlMWUtTeGlnc2xGN05qc2Q0
        U0liUENzMGJlWkpNMGcvQy84UXRtaG9hTjhONWszTEJselpUWFZnZ3V6TnNZQQpw
        UWkzKytnZVRybVFYR2hrb3U5REFpZVBkaVIxOVE5NU1tdXlDZXNsaTdNCi0tLSBC
        Y0ZxZHFFMUh2RmhpSkVaMTdpeXlFRFhJSjZmZzZyVTQrRzJFa2NSbGlZCvZJPNCt
        8W8bxg1u3Rovz2qesA5WXIWzRphJ7G3RoAhb93bOMbb/en4GLDv816hL704dfmJ3
        UT5wS53cZtCAsds=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-13T04:00:16Z"
  mac: ENC[AES256_GCM,data:N1ftEI0HoCOQ7jTNm0UAnHp5SCvxUXOdMesWjUvwiuSTQWFLOUstbVXp1vp0JkhS1dApxGotf5CnpsCnn4eK+L2D9rLDj7rDbpz908z9223IZ4mEHPfGztdMJm0U1ISqgc6RME8yJdGKJnBrLCvPpNh09twXMTGRsq6KB7eM//8=,iv:aKSotoz460H9m58DTof8IloedteVNxmnMdy1mpP5f/I=,tag:iAMUOOhuSN0X4VqGRR0xRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
