token_manager:
  jwt_secret: ENC[AES256_GCM,data:b6znetv2VlODlBc4QFXLddm1Fy4CVmK2VmTyY2C8izY=,iv:VQvqBRjenP1KH7V2OvVA+rwOH5bsbUlqB7xWHilVivQ=,tag:nZV/SRlU3/5V/UF8Sppzlw==,type:str]
machine_auth_api_key: ENC[AES256_GCM,data:Bqga83iYHuDkgoI1+O4LDUr9M1TJ481z8ABFDy/u40w=,iv:jKb4CqSOeXXoUnP57Hf5J+p3tYZzKQCq1GnbeSEIYvM=,tag:9mZ6vuOYii8Gz+VasxbVsQ==,type:str]
system_user_api_key: ENC[AES256_GCM,data:lzNtx4kHfatq1FFR1S8cUs1gP6QNVb+t3jfvWMqFUps=,iv:InKDwdoV3BnQq5ymZm0mAMBu8hJ/OGVQzq797l15bgE=,tag:XKU8Y96NKU3rFoMfJ1X41w==,type:str]
transfer_secret: ENC[AES256_GCM,data:VIwm6uoYH458cOFeYZ/hQpIhoIksNlT6zn2ApmsCd2w=,iv:qzXlvAJzyhaGgj4GX29P2g3gec+x1UIhiDkfVmtxz9E=,tag:nAVLTQ+w7qZM4beOGjLjbw==,type:str]
url_signing_secret: ENC[AES256_GCM,data:VV49b2IU6P0yQx6sYlFX7/rYETRLg3tnsjUOKbnflBM=,iv:3PiU8W8OfePLd8hLruKI9JSRkpCE2uNpVh6HZpYKQoQ=,tag:+WptqgLNOwcq/J2f4OrRxA==,type:str]
system_user_id: ENC[AES256_GCM,data:dLbtz8IoT2vlL0d7CqrjAJp82GrCRzxfvqbTpiQICMaG4lBi,iv:ZJL1ZES9PJn7/95eNCq+XmMFTm2eXXhBIByFu5yCyB0=,tag:2WoHZPQDtA8zZ4muBK/MMg==,type:str]
admin_user_id: ENC[AES256_GCM,data:jcExqTeyBqFd10LtourDkTi/0AIZpII8Cc92PG0zgOzq1udy,iv:HHZexUIpHkXA6PcZJv0uVG7N5VokAIYMLBnTRd5RWeg=,tag:Cfon4jaBorExQZ60hWfwKw==,type:str]
graph:
  application:
    id: ENC[AES256_GCM,data:NLZkW1QpyPorcbHUbZSQJW32PpDPssjRbo9PvIiskIsmiU2o,iv:HlEkWmZ7fVRpfywgBQGhT0Hddx5ne4GxFw2Pz0GVLCQ=,tag:voYfI+wzUPwjxrH1i4Xepg==,type:str]
  events:
    tls_insecure: ENC[AES256_GCM,data:wqrU61U=,iv:YY49OSfZqCjXvPRd5EH3fJDKI4FEzfwdgY24DI0iJD8=,tag:X8azyZMEr4BFNtBRTeEvug==,type:bool]
  spaces:
    insecure: ENC[AES256_GCM,data:IAa29B8=,iv:+bCfdPicXQo5qsll1Y/zWOW06+Ebv0YYewbfvEjho+c=,tag:WkgeQXqquS5toGNnATcmsQ==,type:bool]
  identity:
    ldap:
      bind_password: ENC[AES256_GCM,data:9lkW7Rzm6oqlF4N+/oTQ0CxCX/nOGVJga9hzEzWB3+E=,iv:7PUoj/RCmX1/QTqbjoez8XHxRJk0srxNP6M6YaNqAcU=,tag:6nBwR0dM0VIfoWFtYCgZ9g==,type:str]
  service_account:
    service_account_id: ENC[AES256_GCM,data:F7vwLD31q2KLddyS2gWubIY2zM0FbSEG6x0ZK7/5PrVhTqRb,iv:EyW9pAhl+J5e9WhF8HYm42rCHHox2GrcMtOW0DiQa5E=,tag:4TBaz9vNA3bcZZHxET2Tcg==,type:str]
    service_account_secret: ENC[AES256_GCM,data:CxWIfLtAHxQ54da6+UslhwAzBFbtQyPZDPRda/ReZOE=,iv:Rr78zSw3KXhH0K5VUYMsd6B4d45WyQU+8hiy6aIBFkg=,tag:lj5FjYnI98mwUbKMbAge0g==,type:str]
idp:
  ldap:
    bind_password: ENC[AES256_GCM,data:6x/8u39szHL3aUb3bpjYcKeKhsGWkwR5RF494GAHfQs=,iv:Gvmgfo81yPzGp52McX+kH9XE/YAQ23ZwAaVXkz/1LPE=,tag:1ipneTOAZhKhhpzrbQ3M4g==,type:str]
idm:
  service_user_passwords:
    admin_password: ENC[AES256_GCM,data:E+9+RC9GD4+KnyG8c2a6BLa8nR8eUHeXKq4U9uGj7jg=,iv:ZGMCDt3RCvASttEljTCFEyzQ3KWh6dYR5CX6o3xyl/8=,tag:P5VTB+sNhOFq6sN3JMt4zw==,type:str]
    idm_password: ENC[AES256_GCM,data:wprHlbpmMQ8Ss1hj1B5N7goPTqDe8eTXsNDYc6XwWyg=,iv:iuDYXK16tiPHRbRlWAONREjcPscTWXJjZU5oL2n8Snk=,tag:C1iL7+JeTo96woLCI+RonA==,type:str]
    reva_password: ENC[AES256_GCM,data:ziCt+IuCxb6SfZqQt0nK5lvqA3iphcBA0VuJyJWSFgY=,iv:Irzxm//kPdgZhriqfn1rCHvDwAEFib9XzVJoWWLhI7c=,tag:ikfISs2B6RwwE1OoEXP/Ig==,type:str]
    idp_password: ENC[AES256_GCM,data:z/o5Ec/kscgAmFbXANxkcXqV+xllXfZkmOM4uIhqaIw=,iv:8ENPhRqRs+/5azLUwJcyWXVAi0+5xcNURUlLMr679cs=,tag:fI4TlVIFLdxl6nME7FVxMQ==,type:str]
collaboration:
  wopi:
    secret: ENC[AES256_GCM,data:VCTxrq7DQxwzqNOtG6uDkH2WcsTEP51HpWvSLrHO4eo=,iv:TuxVDU4ZrSBn89bNjPucA8mppmlNMGTI5hE+7g0vNpM=,tag:LQvRIVa5ADmjQpLjn4kGbg==,type:str]
  app:
    insecure: ENC[AES256_GCM,data:1sb8QwQ=,iv:jF9Ul3pufLiO62G1EF4voSqVoMr+bCDdPCEnMu+5tBw=,tag:QAWY+aUCRYXs6aHuHdMODg==,type:bool]
proxy:
  oidc:
    insecure: ENC[AES256_GCM,data:GDNmTn8=,iv:IqrOYPGgFXEW+qE3XFlmvhzALaDGXzpcog6vIqNALCs=,tag:QcxXAp3YS8k2P5W/o18CAg==,type:bool]
  insecure_backends: ENC[AES256_GCM,data:FiL6W0Y=,iv:A73eVA+mH0yNLuPkNTbxjnkXsQNdYyoNPhicIN8vwlU=,tag:rF5t7mqHqQpd7FUFcURBoQ==,type:bool]
  service_account:
    service_account_id: ENC[AES256_GCM,data:FDxa//foRKeHkTeYuXyE3E9X9zXPTIoqH701s7NeVfRqVK9h,iv:DsQfmY9cKFUioRESxrgFm+ksdh6vL8qDoWAES7uJ8/s=,tag:MJ64iWRljnyV/O+qV4L83Q==,type:str]
    service_account_secret: ENC[AES256_GCM,data:c1u3U2nkZQZsR54QQLek+jCiozq9dl+4uSd5WiF0OpQ=,iv:0NIFvBxQjNOvcfvbuaTa9LAnYBFWWAfnQhkiX8deEOE=,tag:ByqtLEy0rpVqCZJGiz3qQA==,type:str]
frontend:
  app_handler:
    insecure: ENC[AES256_GCM,data:VjegYIg=,iv:bj9G/kChDlTkHehm3pthYPeVGeHzGZXWbOBZ1Z8ayyM=,tag:OD9nG7gciYvcwLGY1PvkHg==,type:bool]
  archiver:
    insecure: ENC[AES256_GCM,data:NVvyJmQ=,iv:iV5jX/uvautQMhIBGqWnyvtLgXRYDQHxA0kqXE29eJw=,tag:mLKsl6S1mCMm+JmvW2aJxQ==,type:bool]
  service_account:
    service_account_id: ENC[AES256_GCM,data:xfGca/ynVtO396lk4HjKuoz6tgR3e6LQF9gj3wRqfdyPpOpe,iv:4MJ9ED3Jr9QzUR9zL+PQAtCoDWe+Ca3FCf5SY/X8fuo=,tag:nb8+zbUY8F2uB00cE+njlA==,type:str]
    service_account_secret: ENC[AES256_GCM,data:YYRkn80s0Pl0B8+FYHtM8S9J8xohzW9Wh153jVnYfY0=,iv:8QOvsec3KVXOrfvZ+2y9UoohL7MwuJ7CgA29X2Cgf7A=,tag:/hwdwy802TWyA8n8D0gQaA==,type:str]
  ocdav:
    insecure: ENC[AES256_GCM,data:OpXT+Ro=,iv:iOADWRm/cw23bl8ri2NZdxnLqpOMok/ZDgJ0ewbLZuo=,tag:40lC02AEpcq0cXpJtYyU/A==,type:bool]
auth_basic:
  auth_providers:
    ldap:
      bind_password: ENC[AES256_GCM,data:557Csv+7p8+xXtXqytfwsIGBazTVqqDJkl3sQHOt4YY=,iv:A2MxmskpMfA/P20dE/AnsLZYnfEj+QW6krbL3DM1ouA=,tag:LlZaXtOthQ74RphOU5h+LA==,type:str]
auth_bearer:
  auth_providers:
    oidc:
      insecure: ENC[AES256_GCM,data:R9b71kc=,iv:FxeSL8MwY8+prDsRmv6yOMR2ONoTrhLDKYPU0B6gM5M=,tag:dQrjn8r9OpGP8LsM79Igpw==,type:bool]
users:
  drivers:
    ldap:
      bind_password: ENC[AES256_GCM,data:omtiFLVWEKSzp4nwF+ogijWiuHt17ure3cVLzekyex0=,iv:XFtwrcFZimTmcqRplde0Q4wVqfDSiTU1Xm2F+F+dauA=,tag:c2ZXzZwpGlZUxd/5mui+OA==,type:str]
groups:
  drivers:
    ldap:
      bind_password: ENC[AES256_GCM,data:IXIbBorCAdPr/bpFaDcojrkxOjH9N32VjGt7U8jvAbw=,iv:klZiBKxsHSmgLftmSOzUwbM5i7+k+9indT6YiFJqqKs=,tag:GQf3WptUL2aSfY5TJUr/2A==,type:str]
ocm:
  service_account:
    service_account_id: ENC[AES256_GCM,data:Mfl7LHvFzbODf+ej39BJ81p+4gV1e0Wzg/NLKDKz5sAk2h0i,iv:eBJoKj9EqFe1Fp9AZcL5y+OYYDhrUUq037AJH3iScXs=,tag:jfxiDyj/K1qSfxT2QwabQA==,type:str]
    service_account_secret: ENC[AES256_GCM,data:cqKWDeL2OEyRkSKhfTfjkuzVNzGwY3dPS0nYZEf6ECY=,iv:YYQyembwIzgIXe8LL713EkxA+kfRcTXIWGfKLdAdSxw=,tag:br8PjWNofvovsA1NVO4sxg==,type:str]
thumbnails:
  thumbnail:
    transfer_secret: ENC[AES256_GCM,data:RdbYYGgQaG1iHLTz/z7/OV5fRGvHUD/OCAPFJZQBF9s=,iv:V3yOdJBEQFGNHmNv5MJAUuWLAEZ6SG0k2xY1cvPxOEI=,tag:VgdKIiFBkw4UQGqtC8ch0Q==,type:str]
    webdav_allow_insecure: ENC[AES256_GCM,data:+wydxjk=,iv:zRUn0KlRY0KlApBFJVi5feBS314DgOwElG4y5wve140=,tag:UXXRQdyXV2BzK0pVm3vD1w==,type:bool]
    cs3_allow_insecure: ENC[AES256_GCM,data:xnmWPac=,iv:F6d3a2a2tmMxFuC7VKhUBMcWM+ESANvnVhwaq/y2dWU=,tag:pFZUXZ9U3Pf5iXdoUA8qmg==,type:bool]
search:
  events:
    tls_insecure: ENC[AES256_GCM,data:86Yg3wk=,iv:XgVaPfxhBtihDriCxy8j676gk0ZWl0EJch1wVRDZBro=,tag:GtCvXE3j1lK+wI2X8dT+RA==,type:bool]
  service_account:
    service_account_id: ENC[AES256_GCM,data:SMuVuYSJHwOZfamMZS76eisACj7waa/vAfNuEbg3AgrcUESM,iv:Qkt//Ys74DtTSuliew/NzhQTzdP6eqxe6jJbKLvgQ7c=,tag:Jym27LXp5i4qh/OlFp/xGw==,type:str]
    service_account_secret: ENC[AES256_GCM,data:zmvXBzudXokt1FpYI34PJ85igggBVDGfinblDBuqVkY=,iv:BdF5K5hLTQENS585Hw7MUqJe/YJu/0BpVomkC9KbBls=,tag:jzcnacALlc/jkfWuLmDo0g==,type:str]
audit:
  events:
    tls_insecure: ENC[AES256_GCM,data:6/4K7lY=,iv:SN5QYFBeZeOGQF09ZpvrPznT19Mmnqj7DoFfLKofHMw=,tag:PlEs1sJHU3LE6+GUDgB2Xw==,type:bool]
settings:
  service_account_ids:
    - ENC[AES256_GCM,data:fZ5nboV9WIYceJqp7eyetKS8/XfhDe5+Wo8ZGpQFNO9y3rEE,iv:P51tZDV/BanUSUMvhI6kRG8HRHvDoL1kck2SU+0zFbQ=,tag:BZTp8yzk1jGSHT/IMzLLgQ==,type:str]
sharing:
  events:
    tls_insecure: ENC[AES256_GCM,data:sSc+vtE=,iv:jxWhjcF73+i9KWz+2wPXkDtVGTqU2+wNA8s3MlyKkgU=,tag:SOtqe0kwpSklK96pYAQ+qA==,type:bool]
  service_account:
    service_account_id: ENC[AES256_GCM,data:ssBRoct2QmAodg/0vQo9nyiIpIAAJiPs6B2+gjbHSiwbZ6gj,iv:6APYl82umwk78EOqgy2y+t7j7EqdowkykcW1FDiKzs4=,tag:/WDuCUXWl6d4ZgbFsFQGDA==,type:str]
    service_account_secret: ENC[AES256_GCM,data:FaonGKO96VK3N+m6MZv9FbI8XZQq2gmERqHbiqv1c6k=,iv:ftMlYjWNwgRpfb2/xn0YA9vBLzeHqJpgh1FWRXsDjFA=,tag:brAw9LnUOxdKnZhsNIXFew==,type:str]
storage_users:
  events:
    tls_insecure: ENC[AES256_GCM,data:mVxjLsg=,iv:m3xVfNsVoWbqITtWt7AOrgIXRhBKu9u+IvcmVWqdeOg=,tag:qLbHtjP2zAs+rTDxj9XcrQ==,type:bool]
  mount_id: ENC[AES256_GCM,data:cVs+dDT/5RLB3CfgPbXH286OXJvcMEbvQEjiGssxhYeMjkzQ,iv:X50rDtI1kHoBqj9y2HKT9TnrJGPCnazaIWgHNAlx7XQ=,tag:kZNbHfQXvnhIYce+9/huNw==,type:str]
  service_account:
    service_account_id: ENC[AES256_GCM,data:ZIHwcMBrv9lTGLEVHFS41962kQVtGo+IMbhGbr9rweFIYMd1,iv:pYu2vTlnhzUV4sL0suoSFKHNICzuPks7bkPQxu+zyhc=,tag:9GJZQ5ugPMO5lSYgrE1jJA==,type:str]
    service_account_secret: ENC[AES256_GCM,data:EAtCRxpw3wl+e4rIFTUSGFgzaemr1Ugy04hYWv5T6uQ=,iv:/RISI2wBbfwWnLjcYW+2d9fFVBbn+LkWQCCR1qUU+V8=,tag:nquYnNBxU5LjPnCXZiLUjg==,type:str]
notifications:
  notifications:
    events:
      tls_insecure: ENC[AES256_GCM,data:yiu4Oqs=,iv:MmL7KmH8Ld6Hw834Bv7p3BX7OH8Pz4whlQ0N3z5I9Ec=,tag:j9kJxu6p5wQSS5GrMxDqyA==,type:bool]
  service_account:
    service_account_id: ENC[AES256_GCM,data:ElotHyFRzcw2FSNY0HDdJPJrtqXkyzNtFjwoEAFGRzuvTj//,iv:HcJWdj3Nu/cjt/owlKw5PDMYb0cg8Z6ev41kEbaeZoA=,tag:j+/3MQxAsgX9m83woEwGJQ==,type:str]
    service_account_secret: ENC[AES256_GCM,data:zyYsP3/1Wz7mTdJWl37JrOnI3z726ydyVerJwtyucgk=,iv:VRArowFBHx2q6f84+ZIhpnl5Gl7djzEyaxmJvDN8FiU=,tag:c+NBMa8TSMfMt/dsfD4LTQ==,type:str]
nats:
  nats:
    tls_skip_verify_client_cert: ENC[AES256_GCM,data:i8yLL4I=,iv:iIBteehbEZuhAsWr0Eg1rkj5zGzBD9SwddjjoGY5Rhg=,tag:Gb6rTiTYTSLhrnphay0Eew==,type:bool]
gateway:
  storage_registry:
    storage_users_mount_id: ENC[AES256_GCM,data:83Ec9Q4/Dt/9W2C7PLs2Xs/OSRkz9CavG5VjcgCxCTb4lxyu,iv:yy/hs/Z3BgG1pbN3UurOiTAKiyg3iNVjSxO1WW5seI8=,tag:tGWdH0nREUnDCu//WoEM3w==,type:str]
userlog:
  service_account:
    service_account_id: ENC[AES256_GCM,data:wIp3ysiBt6ZGMev55whpVW5gAQp05jC6iRKpVTKhbAG4tkAL,iv:+fFLS4YkmnvBU5L0ku0lfP5oVBvYuiTK9ze6hOCy+ls=,tag:3PNKmt0PEZTQy78NC5yr6Q==,type:str]
    service_account_secret: ENC[AES256_GCM,data:ql1mBPakxFiMH6AFZ9AVj/0l6VzNBcJQrIAiIe5mvb8=,iv:cdpu614X3DKnEIVVyfG751RloCRzs+0HF5vkw02GvA4=,tag:S/P0c5M4A4FqVfcMKeyIPw==,type:str]
auth_service:
  service_account:
    service_account_id: ENC[AES256_GCM,data:HEgn+Uw1qjLox10gVIKlO/4VolcwxRRx6pmXrwqBH0RS0Bbk,iv:+DUud+J6hqwQM7RAob7Wt+ldS7TWufc7NZ+k4gPqBbc=,tag:xZ0Ogw7fFRAI5XChZshF8A==,type:str]
    service_account_secret: ENC[AES256_GCM,data:B0d45tPCiSJDivMYnt96GQGT0vt5E4OTq7JU+MqREwU=,iv:bNpNIF1owmh1bOfrk6SD+V/NIiFpR4LoZy0xvv0mdyE=,tag:efmUCrqWCQnmnkbUG6HXmQ==,type:str]
clientlog:
  service_account:
    service_account_id: ENC[AES256_GCM,data:oP6XSiS1Nw4W9f1DGOFMCpzqAwJvmDpkjn1prqXQ1tFGtsWk,iv:OMrpSKLRd1bnybJMLPMDdyncXxwDw3G295m2Ut0Ct9A=,tag:LeQebjwNZBSqC7AleLsDyQ==,type:str]
    service_account_secret: ENC[AES256_GCM,data:yhaiy290odqv0Kz1xq71+YQxURsjshDeO00M3NxjPGw=,iv:kGnjVLmYp7kCMsRVfSznCwIdddo48DZCdNXJ2otsrzc=,tag:3sjTK9jBWiTXTHnrHZ9Heg==,type:str]
activitylog:
  service_account:
    service_account_id: ENC[AES256_GCM,data:vIUE9EsAGV5oB1DupGs8Fv5S97/BivqNKChlhowKP5W/btbv,iv:BNh2Iw7iAzeKM4ACgU+kBuPuCXuoJL1GAsQOLx8OqcU=,tag:Ql8DK6+GxiquUYIscYQQEg==,type:str]
    service_account_secret: ENC[AES256_GCM,data:tTSoZfR+wy49efH6UI0d7ErNswY5J7PvN5nfrmuOy6U=,iv:mElxSrfhQkyFyxKhc7JTWoSGfHSMtWLVUsFs8NI6z60=,tag:cnDuZIbjc7Ly1TLUERgmow==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOTRhUVNsUDJ2TkE1VUdT
        a0NwS3BxbVBicGorWk5IaWkva05CQnlLWHdJClcxWTZpeSszcWNhTmZlM0Q4WE9x
        MS9mVXA3MkVITVZoa1VWMlk4NzZRQWMKLS0tIE8zUDN3bjZuamd6eWZzS1hYVFJu
        REkxcHZCdVNiOHRyeE1vbmdqUGhWZ2MKJkPaoxWdT21SYDGyxXzcvmRR8D8C+Ak/
        h/u02bqakK/bXjNzaAxZKTWwwPNlViZTbxCDAfiWx7mALhDcFxX1Rg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
  lastmodified: "2026-06-01T22:07:58Z"
  mac: ENC[AES256_GCM,data:8bNAAKwv1EYYIorNbOyGbuFqL6GFCubbF3tE3qndPOHcc/ojfT7OuozUdUPiNq3iHQ0La21Nh89rzVCXEstP4WSo75qlNSFzGP6dDP6TlFJdJ24zoLxNh/F8YmlAd2g+llT8+TMhKOQGmYr3DInpnqV6/JSzJnq6s3S7gHiLqGA=,iv:GHq5TolCjXL3SputTNomZChcj24eetr8MhZ4vbWZDnc=,tag:Tj9W2a+bAQkQzw7azmDJJA==,type:str]
  pgp:
    - created_at: "2026-06-01T22:07:58Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DC0EwVK2S0BUSAQdA1xOxEMf/NPB0krZwCPTb94YgQzVJ1QCYMFfmG1E0HUow
        jwoY8YlHEl/0m2XhRhC5Z8WBqbR+1SGMvdlvEXZJSetH8YmEJzkob/aJFtjHzumv
        0l4BJ1TAOOB4ExUHxb7rbkN/eHXxXrQaC1xGrfaJscqFfGXMi1FEKZwpTJOaEpNM
        00TbwOAt9wFoUZULPrFDlE2YRO1DcAe/MYL5iga/xRdE+DjqxbXQCalHC1TtV/JG
        =WLrf
        -----END PGP MESSAGE-----
      fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
  unencrypted_suffix: _unencrypted
  version: 3.13.0
