---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: gofinger-configmap
    files:
      - ./resources/fingers.yaml
configurations:
  - ./resources/kustomizeconfig.yaml
