apiVersion: v1
kind: Secret
metadata:
  name: mautrix-meta
stringData:
  as_token: ENC[AES256_GCM,data:pmq1/GMr/P46zKTBSGxlh0Wn9s/STGPSHvC8H13MBRpWlnQJgjRkuRMfry3n8MzJJDBOerHdFf+/jKL984guYHQ+HrbcyMEVHgLQcgLx2mUOG4wn9WO6098EI1xc4LIsQomkqUStMuR+rrdx5eTBxq+hL1W1V+DN3/F2CeZ3vqo=,iv:QwDIhfcQkvznZ+kMoxfRR/PkfCPvYaUeorEiVraHOpk=,tag:SgrTzkkXldUTsgYYogjTrQ==,type:str]
  hs_token: ENC[AES256_GCM,data:JEZ//P/b7wTlb31mXu/EIRj9qMLpdgzQ1CqgQUBEEZHQybxcBRzO51EINePkjWERAkDVGIhgscoLEfdYLt8B7DXg7t+hl+qILdfzCnulJndUgMnDPs9atbkEzNIHf9PmDQiuo0MAfpNOR53OdvmqWsCHNTrfou5bVQohQp2W3xU=,iv:M514aJwxn0d6Pe5JdlLbNhKuqEXlJeeUlwxTvtJ7ADY=,tag:r3sQCc7d5y4uul6/ac6jZA==,type:str]
  signing_key: ENC[AES256_GCM,data:CZdFl8gFF/grYyhnL/f46H2DIBeuEZqPZRaL8c6I1pI=,iv:c3Wd2XrH8CatGcXV+BG6mim1x4qV7ezNZ/WA37Mvv5Y=,tag:YXA7eP1ff3TuydwXoBJrjQ==,type:str]
  server_key: ENC[AES256_GCM,data:mI2Teg4pWkI72PmDE4HGN30LkjTsW0LkGBg2y9/yG95Jh30C5V1xWcu9XEE+dZW8NxLTSce/1nx7Dw==,iv:soauvjcFi5wMocEZq5ysOflKHEibcuo+6QtDfO6izHM=,tag:1LhciV59zc1j1MG2H83s/Q==,type:str]
  double_puppet_token: ENC[AES256_GCM,data:YKSkf1qztU4kvKSZ9fGsBzzRbVeNf2uoYwr8rpUCIgU8JXZ4Xv/xyJOfX8yb7NlzKWkz9tZ3heq1ze9xI+c6YoPdB2wChxSD96l0MvQ2pdkVZ6/Hd3ROadbmpcl3YD1MEs57pGEl6UF84G5MCMJvm+qNwWeTxjgg46IEZXshef4=,iv:Ii+iencvbYx8nemo2AExzs4cKsNK/FH6uWQx09JSqXQ=,tag:DAW3cJdkckyyhAd6NAmx+Q==,type:str]
  pickle_key: ENC[AES256_GCM,data:n2B3LhDjfRt3h++hWmq+QGfNVxaCKpI17yXRMRRdRpBruGygB5hI5avrjk8mvkHPyVKpcodKjDnSH3YVhim7CA==,iv:iLqZPWR6EAfCHFjjfX0Yl/vO9aXXUxWxOu7z2VmWeRw=,tag:krAaNFehU9GnKycTTiraBA==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGE0WjhCUTF2
        N3FMYlBzbTNpbll3MzhIS0FtYXN2T25xSm1wcXlEdGVzR3poUHQ2SnpsL3g2dFNv
        UHJXVDc2cDU2MHg1ei9oZ1Bmczh0b0d5NHNNaHhBQUM0K01IYVpyYVNrWVdzL09V
        SjQ1UHJqRlJ1aXUreWlOYUdqelh1TEwwalB0d1VXTG1EdC92eEpxQmhzYm9nUWVJ
        RU9rVSsyM01yUGxYdVhtZlpqQ2xPMGN2Y3hNRG9SQ2FFR1A0dkxqcUxIZFc1aW84
        SjM2WU9zVHRqaEQxZ3VHZjhWUVVtUmNIc3owalJodHZKaWw1c1VKNGl5SE53SDEz
        VEcyRHR1Q0R1dlZSeENCVXNBaW5YS082SlhWbExSV083azhuaHZkL3Y4NkhMOUdl
        cmxQUC9PdUxxaDIzY1krc0FyUDdnUGZuVWR4WXpRenJIanE3NDhRQlZzUldabzBG
        M3RDakZ2VXRHRkhLQXlDOE5Fd1JlSGU0R1JONVI2WDBtRTFkSjNKd1NES0NkNTBk
        dEN1VUsyS3VCMXdnRVJzS0lLVW5Ka25hSHIrWGFOTnpCSjFtUlp5UTd1cWJORCt1
        M0pwa3RYUlZKZUdJNkNjTHFQeTFvT2UrR2w3a1QrRysvbjJ4bXkyUjJodTRQQURT
        NHVYWmllQ3ZnaGhGdTZrcWNrYjJqajFmV0sxekZrNGhzUXRPM24vZVlyZTQyUDFs
        NDhkekR2Undza1VLUWdzY1NnQUNWb1BIWXJMT0xHTUtaQ292VkJIMG9MNzkwRmtV
        aVE5K0ZhSnBCdGpjdDZWWWhCQkMvY0JVdTZ1dlVURU9XWDd5ZStETHpnRDZ0R2Zo
        VVYvRFRzQmpvWTNiZ2hPZDB2bVhWWnhMOXkrTGN0cExyR3ZPSDh3NnFGdW9XNllC
        QzJrWFY0aDlkSE0rLzM3QUtEbWg2WlV6WnFQczR1ZEVqbDlYZ3Q1Qlo3VGs3Y0hI
        QjFkMXlXZzVHQXp6MGRMTlBVQ0gvdWVFWFU0c04yRXlJc1ZyZWdrNm1wdEw1WHdo
        ZDZBY1JLWXlLMm5UOG0zTWxjRXRlb1BVTStMUnZRQU9xeElocm1YNG5SRVNrcm0x
        MjhJRFh3M3hITUtwWTdBeksrSndxcENnaklvNUg2RWV0VmhNQzNkSUdLNVUwb2Ey
        SCtOWEdzUXNUMzdhTmwyR2hWOTdRQkt3TFFUTE5hOW5EdkZIVTFLT2QxeGdpcjcz
        V3VZcE1YSGVXNXRTSDF3S0lHV1c0QVZDcTl6ZUxmK1AxUGNvTUVPUnEyUTRHM2hk
        QVFIV3FLRHJzcFBZejBqcFRLUkxMclA1Tk1GVU0yUlZEYm80ZWFlZUtTQjVJajUz
        dytKdy9rRE5NNUVHUmdPWjVyWUMrZlRiZjhZbjg0R3Zwa3FSUnoxejZxczB2N2Fl
        WmQzcE5VaXM4dnVLcXJCQU92c3VrU0VEYndxbmZsWW9Qa3hvelRVV1pxcDBzcmxi
        R0ltdnBNOVo3SkNpSDM0eHFmNzhucUFncWk0MWd4ajdxSUg4enpFTkFDZW1jRGVD
        YWV0Mk1aRUdMWkdoNmN2TzBOZVI0Vnl1cGw2NzkwcE96UzdXeGxzQmwyV1lWRnRi
        YTlVY0kybWFJa1lJSnV2T051aUZha1ordVNIOXpkY0RyVy9CWTBRWnN2bVAwZE11
        aXlGQWJtbmc5WFVjZlArM2l5aU80MFAxWjAyeUZkajZnTjJmVWhWelFHM1AwVHlV
        S2ZqeVpWZHNkYndycVh4M2dobTlLN212L1FrbjlXWjEzVVMwN3RBOG1xdEJMeGxz
        dVB3WmQ3UXpKS2swOVcrd2RvVXptTTUwVkZDVExJWmZOcHBua2lFTTdIL1dTeEpT
        WlhXVnJoQ0Z3QjdIeTN1SnpORXY0dkNOU21vSTJCdWpoSTVTdGpSTWRJS245SmMy
        V0x2SWRKeTZCL0N0ZjVyYVVIWngydncrdDNDdjg1TGltc2NWV1VUbCtNcnBEdwo4
        Mml4bGIvN2IvT0dGUzc1RmFlQms1cGVGclNwOWt1TFJrOXJSSUVhc2xvCi0tLSBB
        bDhMRDVlREdVWktmMzRQQUV0ektvZ2ZkeUN2L3plMFljNXFNbGVHRU84CkGU9rJC
        3wz9eJwfanvzcvxf1rDSfOs84mc2blIuAyGSF1gGxGJIWkRgF6SGCagIe7vBUC7I
        e//57tKH9gyXbfk=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-03T11:25:37Z"
  mac: ENC[AES256_GCM,data:dZ90d01RrpsjrFPF/9wu4pIgtqwOBSXGdiEwlcUTfN965b3OFPolGuigsp5yQZSu/1xlMYGmOXLh64RullBm1OEnQhUkUqMePLNKVCLcBzkjA2CZ5bMC7V1sVBvGnn/IMCavRc9+/7a8hfAU64Sjiu6chFAdFJcocd9k6jVkWsM=,iv:Ggw4EwfVHq9ugKMWkRJ0HvQqk6l0CA8wHaFzocZguKQ=,tag:85btZkHVVrZx+4oyCpQLsQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
