apiVersion: v1
kind: Secret
metadata:
  name: slskd-secret
stringData:
  SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:pVJ2imZ8PIyGSXK3,iv:MOSf+/rsi5yDM9FmlQtI0YSL87azfWyF5mpsRR1NKVk=,tag:deUukuAUdz7337TocXoOfw==,type:str]
  SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:ogMUl4JF6Q51XnOjYp6kMFYqLa8VzZVise9itA7WHac=,iv:wy8xIP385pvCdDg+iPzeWBrn/oC0kbRvtvQUYlKllJA=,tag:pbt15iSTif6EYLN5CkMUEA==,type:str]
  SLSKD_CONTROLLER_API_KEY: ENC[AES256_GCM,data:rfWlcMS6GyxYQEqhE4jKaShYWvDNxkz5LYEkvVRIFaI=,iv:rOhJLQHJoTMPavwg7CzYpKxFVaL1hRYPJtW10I+GPnM=,tag:BgKDKE/j9sK8+Xnk2cd0wA==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDZSUDlPWDNE
        enBNTnd1QnZCc1J5Q1VLdXFZQzVMQ0JmNVRLRm1SY0taOVdPb0p6SzQvRU5VR3pE
        Vmx4Y1UzMVVxS0xHbS80K2xPTVUyRzE5UDJPZ3JpN0tBVk5Oa2VYUlp4ZzMvSjJB
        MUZRY0l2c1VkQ1QzWnNUUGxTeGhSbThabC9WNGtSWC9ESUsxWnB2QXJEMGhZZTFs
        K1VzVTZ2VFZCZ1g5c2UwendMekJWdW5VbGhjZXUrSnlhcytMSWpHZlN4bjVjQlU0
        WUtZekhjYkhyNzIyMkJDMENFSnNYNmZtQVlkMlFNY1I1d1gxTHZKeTE1ZlpMM1VP
        d1IrK3B2NUJJc0xKSXBZK3ByT3Z2Q0JEeXRlMzQ2cUhMSVRvQktmZUlyMFRZR3lL
        VTJxUk9xTUFqWmtOUUFaRGZpV0JIbHVoODR2ck02Sy9FY3V4S0JSajlJUHhOZlRS
        QlUzbmRWMUhJNENZamlPQVU3WkRzaTgyNjhZL1NjZlV6dythc3FGR0ZQYlR2b0dO
        UlMrTlF5YjVpZldoSWZxTFRNaFh6TmVPc2RNUExlKzZqY2kxcFhsbkZSQ2lRTjVn
        Q1RPelVwZ1FOREtmTVgwWFNNamVHUVNnMnpMbE04MUJKNXNCczdBWXdoQmkvOTZq
        YUR0MDA0dTdqWUlZek5oU1h4b01mTE1VcHZJT2xUSEV2Tm5iMlJFRUFzNmY3OFlJ
        eDlmdE9BU2MvRmdRaVBRUDkyWTRRdE02YW1LWDVBUGExS3Q3K3RZL05XQnhQU1JF
        OXhZTWJjdE1SZ1BaK2lCTmtkU3g2d1FGSm43NG9kSVM2TVVkdjNTYWdZWVIyQTRJ
        QjgxcVhHQUgwUHJJeXZTTkFneDN5bFNZK01uY2ZDdTJjTExMalQ1YkdIZTVKbDVC
        OEV2VTB3SmIwbGNnSnFuVUxXTFYyRHZCYkRmbUt2THh6VmUrTFNuMXRadU5QNEo0
        ZHpNM1Zob3JyR0E1ZGR3QzZYUCtaRWxxNkd5a3ZKT3dNclVWb3ZYTUhwejJYZ29p
        YUx0ZS9GVjd0UUxrcG1SejF2eGdDSXJoRGZSZFRURzFablNydGxPK0VRUU9XamRK
        QnMvOFVxZ2YvU2FuWnAzZzlvc01TdlBhUmwvWllKSlgzN29ET25iUWZmKys0RDkr
        MFFBK0thT0RnM0ljL2Jpb0R2SUxVNnZXU21SeWhrOGxldjJQbFpRajduNDBvOWlz
        R3NvWlVkSTYxN090TTNPdU50S2ExWXRLRTZzTzF1QVNpRU1NUGxwa1ZLQUEvajls
        SUhqTC8zRFJWdmRFdTBKUG1SRitkYXUreGVlV3c0VGlhbkUyUG9mRWtNTG9QaDhi
        ZnFlU1l1ZlJUbXNLRGt6QWNremZ6TFI1MS9VRko4ZVh6RkNRRzlZakFhOVJaVjZ6
        N2p4MVB4Y01wWHR3V00wL2RMVnJrK3g5MjdDbVRZNUtZVXczWVpFZ2l2RDNCMU5x
        RUk2d3UvUXJpRnUzS3BYMk1TVzU0Yk95VXFubGJ2Slhza1FlSlBxZEJRYWdSMTEr
        RlZLVStaYXZHWUNDL3pNZDlOdkdxbXc3ZE9xSm1SREoxaFBiWGlwMzdKUThLbGZY
        VWRBOVBjdmU1N0c3Z29wcXV1U2dRQkc0aFk5M1F2N0NqQVVOM1RzeERTY3ZwQWdH
        QTRNckRsQm5lUEEwSjdKMjFZNlgxckx3NmNPTHlxOHhoNFA5bys5Qjd1Nkh2YXU1
        NStmS2dSaG9vUlErRGNRYUpnczh1enAwajRyTTJ6UitQMTdUYXc3c0I0MmR1Wi9X
        dHdOZkNvbEEwZ0hlSXNOQko3TFlPNTk1VDNJVmltcEdaQ1VSQVNZNzAyTXcrNS9w
        VFljOVJiYjJvY1pzYlNuOEpiK1B4SWc2dC9DYWJ4T25JU0xXZjlSUVM0QkhaQlY5
        S3lZS1g1SHlBSysvb1p3cVdmNnE5clFpMFZkWUVlbDk4SlZtNWlFdmpoejFYUQpk
        a3duQkxRbFV3d3IvanQwRGtuYjkzQ2RqN2lwNWZ4dkYySzVuL2lXcVA0Ci0tLSBO
        eG8wL05LdzgrMVVJcW93dkpFT05ObFFTVlFXOGdxUXM5QjhTTU4xZ0s0Cvmmourr
        /LznuhqiY4Ferg4/shKis2AKUg2frVdpr1OPRA8ZzHXBLvhQui/mNagShh6DvVc3
        R7LjA9dW24DMtlM=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-21T22:41:48Z"
  mac: ENC[AES256_GCM,data:Ze+P8PYX0Cutf7pTrIjUeqs51ENsoqSjIZV3ROTcZL7nIQmkuMF8qW9dvQ8OF4xAqgKR47eshV82/5UaHrlkn+R5id7zjyG43MRRZprMPpBBPJUQWHkpJU8M0XEbtcw9W2MdUfulT1x5cNzzyiY/S+7SzIld01gSuy2bam2ZlWw=,iv:hYQX4NR88IYK883IwVBujB/SaYjqIN3BG0fzf2EAuW4=,tag:looIPjf9CZMhrKcWJJcMAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
