apiVersion: v1
kind: Secret
metadata:
  name: krr
stringData:
  FORGEJO_TOKEN: ENC[AES256_GCM,data:eE99N/Xca8RUJ8Q8XoyKE8l/TU2oFXFTZKW3iJyhFTL7FnJcFS1d/Q==,iv:ptlDBOgkeHvq9J7Mp5XQ+5AnAYwV3muJ9ViPntGsc08=,tag:PLe4iub+EhylBTc0VlM81A==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFJIdXMwRTRs
        QnVROFR2WXpFeEZGSjFTcTVFSDZrQzJmUnhQVUZpekJnVnVlQTJuRUdROEJmNzlx
        c05ROVJGWlBRT3JMTnVJZU1KbnNCNFduTnh2aHdMREkwdWpWdDNaTDJhZUtCK1hU
        RmF3OTdmbXJ2TUhHVUdQZ3Bubnp5YlhnNVB0aW9xdnJEeHgwZjVxeS8yZW9OaHpt
        T09YeVRPUVhDQllTdUlGY0Rub0w4OTRNcko0VjJZVk42SFJzWG9oRHJpUXJVQjFI
        dE1rM29RLzZLSHhmRUlRdlArcldjNGphbHh6MGl5MzdDa0pQS2JLaVNGdHhralJZ
        VTR1M1A1eVVEUVNlSktNTXdYZkVMMVcrTjUvV1lWV09jUFE2NTlMSzQ4VkhSTWE4
        UXIyMlBmU2VPZ0Z6aENWK3BNQnpWU1ZFOFFmYkhabE1kKzNuNE0yTDNMQlZMdzBt
        dTF5ZDJydWxJYTAwNXpnK0h1UklYa2YxbzJGVTlyRTFobVRIb3BIdzhHZHFnQm1H
        eDB2dCtSb3FmSWErYm0rdkpGR3VIcWhFY2laZXQ5b09Ocmo3WDcvb0toOHFxS2tv
        U1pPUTAwOUFLaE5yck9HKzRtaU9jOVR2MDdmVElwbHp1TVpaME1YbGxEQ29SR0ti
        VGtlQ29EQ3d6MkFXVVoxaitMM2swRGxVSVJVYmhLVlAxK040WWlnZmIySmlQaU1I
        ZEQwS3ZzUDRDbkxwRFZZZmVVdiswaEI3dGxTOWlXS0NtcU1SNjlhL2JwcWRnbWdZ
        QTdJWTdGQ2hwUUtJbTZ5dmJOS0xJeUNZUGVWOVZzOEdVNEhld0phb1NzWUVRMWd1
        VjZxWVNVcDFUeGJUWVZiRkhydUM2N2RRZVhBcHFsa2R0U0wxZU1PNllwbElBamFO
        UUdsOXl2WC92dm9yOFBiTjhyZmhSZFlQS0VBcjVkcU9DQjlCOGJGc2M1VDZkZ29N
        clV5VnQyQkZkSitZQjNsdG5kbTUwSVc0SFY5RCtUZnpmVm54S1BuSEZMTzBMZWdW
        WlBwcEdYVWFhU2dQcExiVy80V0JGS1hLNzdEd3p4RGFFQmdxOXJBUytDL3F6azRn
        NVQ2WUZ3bE9IOVM2eTZWU0JYV1NZdUQ0N1pQN3hmUlVxbW9aUTVsQWtSb0ZsLzE3
        eW5rWHNhVDAySGRyY0Zmc1ZKZjcrdS9od0R6VTlUQVppTWZGMk9ETURtN1V0NGQy
        dFVjQnArQjBDTitxeis1REhkVWs1UUk2U05TMlQzU084STFDN21QMXJDRThNWFpD
        U29pbjFtTUpwRHZ6RURtM21rTE0xcmE4eUVic1B4MmgydDhjS3c4b0pnRUQ1NENy
        MEVoQTh4WEpOanFyRnZSTmlXeUJsN0JOT21aeUtLaDFmeHk3ZW5Jc1UySk12eFVv
        VTJPa05SM3ExSXpHaFg1ZGkzYnE5bVZtbXFWTnVxZC9UN01GcEtjQldEV2VLeFhL
        Y1JPUVdKeEI4VUplQnRXcDM2SkZtWTVyeE1hVGhJMnJLcDgyV1pLTDlCVC9uKzN1
        THd2b1dKWU55OFdONGxwTUxYVm1CYTNBWmlZWHBsL0ZOdlIxV1dNaXJic2JoREhT
        QnlkdlhYb1c1Z0RIODRMTmtPRjB1cUlET2ljU3hoakVPa1VzdU5sdWI5NXJlcUJs
        L2l1Z2pHYzVtdXdRdFJQUWdBRmQxVkkzQS9IUWwxcUtDN0h2UStYRWFwZlVqbFZD
        NDArNmh5QkVzMUlVWlNpcUE1UDI3NUk1M0JKaFlVM0Z5eEdFcFNTZFR6TVZzQ2xh
        ZHJ3R1VWQjBJcmIyeUU3ZFVOeVpWc25oQTV4TXc2Mk9TSDcra2pWQVdRL0dTLzlu
        dnZQS3d5LzY1M0kyaGNJa2tkVGlUVHk2dkthTUNibWV4enZ1N2ZvakluZFlQQ1lv
        L2phREwxV2x1MnJtOXBpeUZPblpyRzArWENnejNRK3pIMjlvZnltejNRMGtYZwpB
        REY1THl1cm1sdmJMWC9WUUNoZzZ2eXNOZllDWXVMVklkcjdQZGVTYWFvCi0tLSBF
        WFFNNnVHOVNPaEpvV2ppazVXTWh6d2owTmJDQVNYWkRSM1N0S245T0xZCnajh4NQ
        g+dIbu9itth8vAjdHYz6k4dyiAlNP9Q79uYASubZklu6DX7Xerl5ky7QevPvsKQE
        7vr0h+nFtH7d2EU=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T20:43:29Z"
  mac: ENC[AES256_GCM,data:R/tphB368pq/UAK0YN74jsYA4p159MJaBYUFZ+diXqb3ZeaKW/d5RSL+ITwYse+sR36ESUbxpv6wgSnraqMRyjqg6njfFIq/+iaQTRSrXylneJVxKNwoX7ERr9GBYvGv2N8Q/4/FQHyOf58JcBh8Snk3Qu9FzbeOePTpEiiZHDM=,iv:JeFeCtGnvp1xlFJSoxwd4BnXa888qLPMUtc3jt5qBJ8=,tag:3MaXcO2tomv1SGPiJCmwbg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
