# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cross-seed
stringData:
  CROSS_SEED_API_KEY: ENC[AES256_GCM,data:O+R/albkD0rstv4R22UYCBCnge4EdGxJdMkzZt6bUDzg+JatGoJSMds9gSSo0YIP,iv:w/OZ179fNY95uFlvWohTKhDqE+IaJNnZ1OmLokKze+M=,tag:m5WklppMWLh2oa1TMD63jA==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDh2TVpQb3Rr
        SUtHK0J2S0F0ckR0YmU5d2doekd5M1lrMUNTRzJZNEZMQURJOFpxaWkwdGlxVExJ
        SWoxMkFWcGg3STE4OEdHSkFvT05MY0lTRjhqVmY5K1dEQkszVDVZMzc0RDlFTGpo
        QlNFUWx2ajVBeUduMmlUUURiKzF1QzRzMWNJYStSRUVzWkNNRTB1R3oza0dBb2h2
        TzVwbUJNSG9yNkFtR2NsU2JEaUxuWGUvMDh5dzBFeVNKR1NsWHFyZ3J2OU9ic0Zu
        MnJrZDlWUUdCMkdGZ3pvWkdQMjVGQWlPZGdJTkZhQ2dHZUFwUTFxeVE5MEZ2ckVJ
        QURSVVJPa280UVNOVzRvNjcra0o5eGhMc0ZEUEgyVXdKZVdkR2lpeTZja2pGUGs4
        QjNZakNPbStialFNWGZ2dTBIc0RIOEdVZVFReUNZS1ZxQmpUV2RNbndDU0ZXdWF0
        M2RTZTh1ektWZktyWkcrdkJEaU1wOE9EQnZFN3Z1SEdiYURHcXFBVGxmSm1tZ3Ba
        dW9veU1xa0hDbERJVFJaTU1UV1Yrcm83M0tIaGRLSUpScjBNRW93a3hJUE42bDRB
        dkVCakZ6MFVTYURvL05mLzlOQjFEZ2hZbVZIUnRKUkp3U2kvWk5hNlRrUzY3UVVB
        MHhsUFRpc25wLzdWdjdUa3hjNlZtMXpvRFFrSEo5c3ZLTGhMbndvdHg3SzRKczBz
        dGpNcjJJMmxHZVdPd28yNFFCYzRid0ZrSEdhblJvdVBNM05PMk1nekVPZVVoc0xV
        QUpodkE5ckt5dCtJV2dQY1Y0T2ppZ0IxVGZ0OFZDYVFnSWdHZkRNMnBMbkFhYis0
        a1RxR0tTZ1l1VnB2RXFhanlUZTg4UG1VVW1uVHhZSTVHcjdkVDlMNWhSZVNYek51
        ck9kMkpkMFNFWUYwbjJSYjFneVNTZmVFb3FicEk3N0ZCazk4aVBCT2ZFWHRTKzJV
        dWdUbGtpLzRrcEhvVC9wUnV1cGp6d1ZUcWExWDUvNUgrWmdKdWZRbGxPdEsvM3pP
        eXN5bGZ3N0RkbHpNOU4rUWNSZWtPVU02OE1jN3kvT0ducXRsd055eXBPRmVvL3Vw
        R3FSaEdaZnNURDZaTjgyMDIxN2pOTy90T2I0MmhoU3RmVzgxM3Z0YTBzREhBSTZD
        Z0JJSVlXV1E2VVNlZHNTRlplRnE0a1FBR1RtVFd6dnZ2b0FGQ21PTDZRRWJlbmJB
        RDNlcEFLdHBzQ3JvMzBCakh6cHBKRktvdW9XNHpuejNOWlJRMS9nUnByeEJKb2dL
        a21ENnAwS1hwQ1krUXlkdFRCaDJXYkc5Y0dlVEk5SVEweldsZUJCOFJhMmg3ZVM2
        cHB4ZUI3K3k2UjhEYlp4UWxLTFVySTMvNlVFQWtUOCtpcnRObTVmNHZTUDR0b3Ev
        c29iOGtvTWpOcloveVdHVm1PL3dka09vQkRtTmorTm9JdHBDQXcvbXlTVVlzTTdk
        MXJIZTZ3MFNoWmFKeGJDc3dIVm9ubVB1NHBSaEQyZlhGb2E1V05FcWcwcG5hTE8r
        aUJVVkdBcDMvODM2VXBrN2hXR2QwME92VEQ2cVg5RFBKbWdqTExlR0VBVERpT29Q
        eU5KcGE4RVlrS1huRi84UnQ4bmowcktzZHNXcU1Ncm9PdHZKckpYa2VhV3RmZm1p
        YWxnejIvRFd5T2lHZWJ5WDNWLzNPVFoyMllaOFRseVJWdWw4WXFjY01FZ0p1MmtC
        RUVSQjlMdFBHMDFVMnpSYXdOZlJ3WUNKSGhwV2FSemRVRW04eFV4WlJGcnA3am1X
        UGo2aVIxZWFoYTNRVkprK1NHZ3NUeEhnZUlVRUY3QkNmUzdoWGJtbVE1MmZNZkkr
        OTlOSmJFVEQvU0w4M1hYS1NXVFVlNGxnTTRvd29GMitxWXkyUFhWRHp6U0dqblRm
        MVVjTURNRlArRm9Idkh6Q25FZUx4cmlCU3JrV0NnRk9lUFhpZjZ3SjdVME1DQQpx
        U083RSswcHRQQXVQTWVGSkhaMjQ2aFJqTHpkUzhRUkVldmlmbm9PWTBzCi0tLSBn
        WkVDSGcvYWROa1JhRnB3cStSejZrb0c3RU1TMGQrbWU2VndtTzRDeDVjCh1d05As
        bfgiVeZgAFMz3lWwZ2yCbL2rS7TB3NAZdEJFtgcu+O2HNt8LszQSCC+gFQHqykL+
        e4tIxjAwNNnzOrM=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-12T11:48:43Z"
  mac: ENC[AES256_GCM,data:/YTRdAjC16+g4cjAbqXE94QB0FgnO43f3uv80/tJtgyjQAJQPKK5gFViB+d/rSnMISkSbUWDK2hLEQ4RUu4Sz0WAn8V0kXN2kO1h9uKYgLt5NqRlGoKLUQao3Z1p9ux+Kd745Y5pgJ7kGVhDrhkz/vWKHIJSeeuMG+B1bKTQuks=,iv:pTIl+IjhQiEoQ0hcbSM7pgjwmjNgKanMCwaTXCSEtm8=,tag:4yBuqyYOHQz/ireMSv67/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
