---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/cdi.kubevirt.io/datavolume_v1beta1.json
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: archlinux-root
spec:
  source:
    http:
      url: https://fastly.mirror.pkgbuild.com/images/v20260415.515674/Arch-Linux-x86_64-cloudimg.qcow2
  storage:
    resources:
      requests:
        storage: 30Gi
    storageClassName: zfs-spark-block
