---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app openclaw
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: *app
  dataFrom:
    - find:
        path: "/${APP}"
