---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {
            "openid_connect": {
              "OAUTH_PKCE_ENABLED": true,
              "APPS": [
                {
                  "provider_id": "kanidm",
                  "name": "Kanidm",
                  "client_id": "${APP}",
                  "secret": "{{ .PAPERLESS_CLIENT_SECRET }}",
                  "settings": {
                    "server_url": "https://idm.${MAIN_DOMAIN}/oauth2/openid/${APP}/.well-known/openid-configuration"
                  }
                }
              ]
            }
          }
  dataFrom:
    - find:
        path: "/paperless"
