apiVersion: v1
kind: Secret
metadata:
  name: volsync-b2-template
stringData:
  REPOSITORY_TEMPLATE: ENC[AES256_GCM,data:/CsyCKiLulKVT0oYOF241pzkJFt7g9etz7SvD6t0a5MyDVNXEg3zNGnBDLb2NKaRT4Fv2ap80jM=,iv:LhJWcToc2VA+KeaY+Y6HIy3t174Zr0DJzjQAhOkiB2Y=,tag:bUjq6gdgYokBATDncqp5ng==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:OOkg9sEqCAiCa/1pTG/m6NpdbxTDUbbf6w==,iv:FRCJ9YMIKN4qY2OZnNCFkxI6C/3tEO3cwpeH0oM3LVg=,tag:CosO6IYQ+al7S0Q+WU+glg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gcnQ1fRMqIZes+q/jlmQQBmpHtH7Pda5CXbXOXFteQ==,iv:yRka9PHp2xKZEEHO9gu7SlmD8xx6N52/ARAbzq8LLF8=,tag:hXOsYpQ+wVHzW5P/649vvA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:L+2SqSC+LoZKQrCEJOXwsBhEDxyAcDh17GWi57dNtV51q28v09UpaNcer/XcJh72v3rSiifsva4GBH+kLPAHnB08BrNuC5KmZcdqTpzWRBZlcoJdy4ylnnYAg/R3py+32RmODEg4VrBtabB2fwNRXNubL2OLT7z5oc9/6ZRQ3V0=,iv:G3WqaT1ntTbB3BeMJ7Adl/+28SLjgPlzPP9G5zo5ias=,tag:Li1Q3sN4qv0jUEDNmsVqzA==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEg0YUJ5YnVD
        cXgyU0JxRSs2UWR1MzJSVG9keGRWeVRPRmpSNjVjRXlXYmg4YkZKVHRCV3BEc2Nv
        WU1RSWJrOXFOWG1mbFNLR281WXJucXBFN3NlQ3hoNmtCdE5qQ2pLMStublRJQkt0
        SkJuNjMvbVJiQUdMTHlZWjFwb1dpeHpsNU0xeGs2bjZPRlExTlVGajdXN25iQjhY
        R3kwRXBtR0x6OTNkaXhDZmxndStGYVJHWUFZWEVrdkNkQTM5VWNRRHZ3bkpFdExU
        RmRBSDRzaHNyU0V3aFZ2MzJwQnlRa1dSM0lqbzZ3aE5QMlJKL0YyWDlyTWpYVG9v
        MTZYWnVDSUo1ellqMWpIR05aS2N2eHZkSkVZdkhWYkZmd1JmRWFMSTR2LzVhTXZr
        MWFtZ1hoMXczTzd5UFN6RnRMU052QmZ3YlVqOWJWeEl0bnFjS2FYOUJ5NS9sTUEw
        Y3pxVldnbmIwcFRWM3hvVjQ4NjdVMXlYcFloUHltT2QxR1RUNnRmbWdNK2FEaTZY
        N2krZUJSK2t1cjRQYTA3cDI2Z0xiRXBJY2FDUjdUSDh2VWFZSjNNZUFxcXdDcmE5
        NFhBemI0dkZGSmpYTC9UVDFsd2Rnc01LUUk1NHRRUllqTlhQRG1EWkNIcTBEOGpt
        Si9tc092WWEzTTJpUVo4akk3TkR0b21WOHZkbllOd3o3VURxSXdpT3daMDdnejlq
        MXBjQVFBSTB2dlhmRHpqTlJqclc5bW1iOEdWTHdhVUZkcUtKRkZ1bHI3NlFQemNQ
        TW1ZL0ZZWHR3UUs2Z1NMbVpXc1plenlhYy9pOVUvU1NGczNaamIzT0prTGFScE1W
        MTZ0blVncng2UlpxQ0NkZVFmbEV2dUVkV3lOTk1mbGk1VnpYZXJjZ1Ntc1BKQTkw
        NUZEYkloRDNPQnJ1czJKaUNTQVB4QUExRU54SXdJTFlZUDZYWnFqamFrUzVndTBh
        eW8wZE5RRlR0ZE9jTEs0L1BmVVE4aHFLQ25RQjkyRkd0M0ZCa29BSkErcTI4YUJo
        bW9vVXJMTW4wcm45MENZajlJRktGeUlVak1VQXg2VzMyMjVzOEFNQ3RmZFZRMUlD
        SDV6YTZCRi9SU1daR0FMdk5tVzBRMXJ1MlhTSkRjN0VyanVOUXFlRUZ1Mmx0cnF6
        ZVh4M3hEUjRiOWRlaU5SYzBuVVg2cHBBRVVOWlh2VTByMVVOVzVVODI4VEhDWmk4
        cGw0LzVkZWpHekl0NEQ1NFpnTXJScFJSRlNUenRGS2FsaWloTDRNWUNQY1dycUQz
        NEc3SHN0cEw4N2JDN1hBMHhQN3NNc3hNZGp5ZVgyNGdRTEJqTWtmcTJDTk1abHpF
        Qi9JaEprb0FadTA2ajdoMG5iV3VsOEg0TWVoa1gyT1NlMlVSQmFNbTI1bVM1UEFy
        b2V5d0htWlBOeFEvMFhKMlZwWVd5TDFNOTdlY3g1cTVMcklhM1M4MzZmcWcwS0xz
        Y1pnVFZPdTlXemJDOWhOa3JrcExPVTlWTFlkbGFaVG9QZXMxa0JYdzRXNGRlTWRl
        SzE1NVlVQ0RKay9LMGRldHNEQzd6NlhWV2w1QklCdlhPaU9KbWdxR1JJU1Vzajls
        a2ZnMkZhdzcvSXliU29HL2RUdTI3Y0phVGlmNWF0K09UbjUyMDhzWENjMGp3T1Y5
        bXY1SkJSRzVkZUp3REFnVUpieDFZMGF2Y1VYaE45QUpLOXR3OERVNEhoT2p1RHVP
        K0ZLUDdPV25tNTRINklxQ242aFNEd0JKN1ZMa3BtcTgvMHA4ZWgzWHA1V29DS3c1
        bFpEbjlseWMrYi94ZUhhYXpQOVpQcC9lOWlJU2dCNjFzLzdaQUxZZTVHWm9RTlFB
        QVh5V1FPSW84QTFRNmJ2UXVsSG9ubGRBczRvTkF6NW1ZK2p5MVEvOWpsakwyYjhQ
        aG5PMWR3K1hvQXV1Z2JJdkI2clEzbTdIY3JQRnRtL3J2VVFqVHJOMTlINkpGZwpW
        aGpnTm5OOE9hWDQ2c1hORFUvaTRyenVhYTg4ZHlNb1VpS3B2SW9idmFBCi0tLSBh
        NnVTOVJFbEVlMDA3OTBGU2YzTE5qTFFNVzErRnFQSmRreHFIK3lpTXZNCtXF6D10
        2IBe/qRfPBe2Du7u9h1hREGB4T7Xq6OYbesTW5JQppn00B4SVMoVY9w14ESpYUq1
        Tf82hxpdW/ILSKU=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-24T03:35:35Z"
  mac: ENC[AES256_GCM,data:WxlqgLMaNksXpe5VTivDnbHUTikjT9wl0tCoEt+SMInbhCWqxVa1lqXp6G3OVEo0c/PnumPjMdXUmvMv2lgemrGZcKjhGLohtxYn6wOcWjRe3NhrXn337MAikkYCgSu8FVsL0fCRmapbpg3/gx6NPutn9bjyQXlt2Eg73GF0xg4=,iv:Kz7apwQehYT3CB+mLledsy1qOVNhV9XTdgV4peUqsHw=,tag:dcdBw0Aogx0kdLqGFO5bNA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
