apiVersion: v1
kind: Secret
metadata:
  name: volsync-template
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:UpPhIrYC3IvJgGMEHD7gA/qKOXK9g8FJkJo=,iv:VuGFAWAtXvQGDOqC5qdREXcVFl9GRmzzZOx9jIhxQbQ=,tag:WlIBk9itxkIHMzY0eVTi4Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xCx5OWKyzWveaKfc9WMNnzUHBqNxRYSaeQU1UsUAybcemmcQP21Q4yoRjjCHvj5BYNrNuu24wCoP0x8CXfuF7Q==,iv:R8u7o18AmAFdAPcFy+Xg2zJgfTC40cqtVrMr/kUTAyM=,tag:W6FZZfE4n0JMi+m9Q2sFEA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:vm59MWTTviyg6XgFFNBQeh6hzyAW/tjR9u4XUZVThg5qLByvtMvmqkhyW1IfR58pay42o42ieOPZ2H89U0YJiUeCaLOMl3X6aVGRG79C580XhwQ53jLOtDGne0CRrrGAZTYXCcatkAGQE8gg+p8jSJTQfcBgZYaoUO92tcPV5l0=,iv:tL92IIhJS77eHTW+q02pjE02I91AzRz76GRl+y0QRYM=,tag:/OH6nZeVh0fBwSUglFAaEQ==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFZWdmlmUld2
        WjBRV2FIWDgzVzdFWUdQUFcrbnRNQVk2U085UXhHQWpTMGdPejZQR05aY2R3N0l1
        YUozWUVLSGduOXljUHdTQTRhUFNsNFhDRkUwaUJqVmNqTE9JQ1dVMUoyL2lEak9M
        U2JBSGlRYzc0aWM0ZTRtR1k4R2hzZGtYSkVIb09pelFJREhndU5sWHJMQmkxbUIw
        dnBpOE9XS0RLc1kwN25wWmdWdnJERVRIWXZTSHpxR1pzYUdOckl1ditUamF3MktS
        WlQwc0FkU3h4dDFqOGZadkJqTzhaWGJFUlBjTkNtVDJXZVpaS25lMlN5ZjZBamtm
        QWp0ZXZhbzlBTmNTcnhMM0RPVVNkeFNrRnVXVTB6M0UvSWJPd3UyaWZldzNPQjlQ
        Uk9NZmNVNmI1SmtaUlVYUWVMcjN3ZG1LTHFDNlhMUFJXSHhNOXlUKzNnT0hJYzM5
        MHRaUVd0V0M2NkNiY0szbXZWNHl0VWtObDJXakMxWEVQTUZ1cVBYTUhnT0hQQTRE
        akY4UTVKZ0VvdHhoRGYzZ2tldzk5WTRUQWFFVUkwN2hKTjhEMzZabzlRVlRtTXJw
        R2ZZLzVhR0NuRFY2dGRuTWhyL3JKR3M0T00rMUVDR3VGeDYvUXJFcUlzSVNjZFFS
        eEVJMEdrOVkvOWxUVnVPc2JoUklKekx6ZWl1U0tCWUsxNFgzYXlLSnZXNnlCd1l1
        eGtWNENhUmRtVmc3SWtFOE5oSVlRcDhjRERVcWkxTHhIVFpZUlA2MjlXT0dGR3JN
        VGpGaE1pcThGZEZIOHZRc0VYUTZGdXRPaUlnYzVCMW11Z0hSWWw1S1RPZDFIYURU
        NTdubm0vd0REbVE2MXY0eFp4OENDTG9mL2w2VE9Ic0RaMzM5bHhmclFndkV3ZmlB
        MFc4SmxibFhLeDVJV2YyYVZBRDBDRnFoSnJkc1J2clZNQlpJcUZxMkVtQ0ZXWUoy
        eFVmNWRlRlhTeVhYeEtHUjBycmxnYjdTeFp1V0k2MUdVaXFrcHdJbkliWkVzcHMv
        YW1pSkxHazNxVTF4Y2xwbjBhNzdZbHVqZjZBdWxTZ3RTWG9MNEsrVkFBdUE4TkhJ
        dHJHMDhHTWxRbFNrZ29sYWZ3UHM2dEllS0ppNHZtR256MW9DQmVmb21RQnJaYmxB
        RmllSmR3SEVLMy9aNkdzdFZFTFd4c3Jia1NtM1l5TldXaGFzRWhiM3RTTUwyNkF5
        QXhHZnZzM0dvODYxejR2bEVaMEwrZ0YyNE9CYjFPMmpBZ0dNQTFyMFMwdXk1b2RN
        RmNOWDlCLzBTSzBQOUsyQW9SdDd1c3NlbkZ4M1c1M3BSWHVMZkxzQlcwMzhhUWN5
        WlZCYmFKVjhFSXBUNGZ1WGpXaDEvdjJRZXpKWUExUW14ZlFtelR6WEZ4SzJwWGZo
        cTBuVTZoc3ZrQUFid1RGZVVGVkpiU2Y3eE9QdGxIQ1A2emFFanozeDV0SDNpK2ds
        dHVaNlVDYjl1Tm5aNWxoN0g2dU5iQzRnUTl0aXp0Wk9TTnRnUTJCRE9COFVpUGhZ
        MXVkRmJPVE1aSGt2UzNaMzRPdkxIQ2g1OG5ZQ2ZtYzE4czI3eUFycHovaFJ1dm1F
        K1JmaDVOTEQ2M3pyVElSNmIzZEFaOU9qU240ZUd3K0lGdzZlaWVmQjZrUDEvcmps
        SVdzMnV1VnR0T09oZ3Z4eXl0c3doamtJNWc0UVhDZVpRYnkwUU9IZE9sNkwwaE10
        OXpGVzlKSnUrSTgxVHVMYnRjcGpCMXFLekJHZTI1Y3VSY2lEVGhKYUxvNi9iS1pX
        QmZmekVTR0tjNDBIdXNkMHRZWXV2b0crd3dML21sa0ZrZWhLOE1sMlBndlJ3Wi8w
        M2RXREZmTEFqcFF4TStOSy9XRU1YRTBpUmp2aEdUSUljS1BmbEZMamU3bTBmVEFv
        U0xGKzdUZW9lUnVpZUVsNWtqM1JGUjc5M2xvU3VtbDBybGpGZlRuQlZLMmlGQQpG
        NlZkUHdMS3JTT3MxL1FLOXcrdTJ2RTlpTnVDWHN1bkQvZ2UvT213L0VnCi0tLSB5
        NE9CbmpscU1qb0ZGaTAxWFdXS0J2TW1DWG1kUnpDWlhHNzRxZWlHSldBCkeFs3mB
        eSukoHWAv9PLBfz+MIAyLxRuQtIEU0ZOTgUIgmWncxhfbAhmERnWJTEaf/FiMcHe
        rmHs/lUMlwjKHJY=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T14:21:09Z"
  mac: ENC[AES256_GCM,data:gw+2PB+qgDw4u8bCCXtr3fj50eUYEmZMcZflFIF7wqdE0gSSNlJDZRoMp81Uib+R+MDQnXKVvXzBa608nyZfs4/51ikXHHsF1OMMkZ1ZPSLCXSco+jnfqn++VBJv6aQxpcw7D66xlvj+hL6YYH9VKffxtogQGLQqqrbqIcKL80g=,iv:t+YOOA1OBXpGamAzE6B/8fJ18zocsff+N6ccZ115QM0=,tag:ezW+o8LQWo0Ukd1LQ5ztEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
