apiVersion: v1
kind: Secret
metadata:
  name: volsync-mega-template
stringData:
  RESTIC_PASSWORD: ENC[AES256_GCM,data:0jhAeMgnP1W3mVcq9ddXBY2mFo0kkkK6hmr53kdbu8Ly6GqJJkOJyApHgXRNNytM0j9plaPR6tWIXB6jPwaejBt2bNk0kdJm5cONR1XYBQQxOsnYI415RB2m263ptkBWRWzbN0eoGMsNMxGzrHylxpB5nyecJP12G/RIO52YIAo=,iv:pLoMJQmiRgbKG+lCwBdNK1AF2dkDXeLPhtmsiIZmLdI=,tag:iSheq83PWR3wAcQE8Me/Kw==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGhndGYzdE1r
        WVlnaXg0ZFA1UHNmdmZ6L3lkSWJnWDl5cktDQmV5K201d3BLelJpRlRFWmhobnJq
        Q2lObmQxTkxhZitkWUhpc1krYXpiRkpYb0RZMkFmaEs0QzRvMU1EYXhkalJMS0oz
        Qk5nU1dxWnhsUFV3eDBDcWJkOGFUV1lmL0o1TEUvdzZOMlV1YzJwSlJ1YTNWeFFu
        S0hYZThIR0VEK0IxN1U2Tlc3QUVPWWprbXNqTWNYbFZZN3dDT2lVdFlOZnc4aEVn
        T1l0dmhncWordVo3RzcwZWk5cVBFWkNGV3pqTnRlV0Ivdzk2bytMZ2lpKzRXMVls
        M1hBOVR1SW5HMloyenNjb243QUFiZnh0ajRlRWVaMHh6b3lUVS9rTXBva3ZzeTEr
        eDJUK1pQVXVwb25FSklXRVZlR3hwQmVvYVNOakp4WVFnN2JyMUE1dEhZY2pYMUNK
        Y0FPckVQUHRJYVdHWHVVaXVZRkd0M09pWUl0bWJhRlNiT0hlYm1EclQ3NXVDRWV4
        R3VuazE5TzltbzlRdndINTdpRXl4RjZFZDIxcWNFVDhsbmhuM0RmQnVUbDdhMVdD
        OC8zcmtXZVNIUEFNZzFBTUtJUG9XcjJjVDJ4MTh6UElsWGVENndqK09Pd2JocFk5
        YUtpMkNFcnVVbFdwMjVPOWhMM1UrQm1UV2ZCUTVVMkNLSCs0aVI5aEMyd0tGVFFa
        ZGhKZWJJR0VvcEpCUHgyZU5UNjRubXJxdUNtMkNpdnVkbnN6MnNUY0prNEpyMmZj
        RThXdE9MekZ4Y0FyMWZ0eU9WRU51dGRiTFV2cmxDS01JZUxTN1FDODVyQmRaN0d4
        elorQzY0RVoxOTVJOGl6REZvVk1Yb0RndzRDUWpod3M1ZktIUWFxcGpBNGdoZmJu
        UTRKQ1NyeEVybUJSakx3d3VodVdpaWd0M3FXbWJCUVdxbWx4bXRPSFJ4UVpSODlk
        ZFQ1dmdpNTROWjVjcFBmOGU3UHQ5U3JaQ1k1dG1rQXVnNkJUT0dXYTJxVnVuWGh3
        ZWk4bStUS09kR3JYTExVNmpKMno2VkpJZlNzWUtYVjdWUFVvdmhTVWhKK0hkWS8w
        Y2lSdHllRHZqbS9MblVhc2k4bllzdCtLYjB3RmlEblJwdm5ZRm5TanJuMHRwQ04r
        UUZJUGZQbmdVTFJxT1VUUERLNnI4N0pnNlZJWFk3Tk95UHB1aHFhQ25IaTU4WXBP
        R3djQkpiY1hCbUpVaHg5WDVpV0FjdDBLRW9lc3Z6ZVlod2dCdzdWT3g2YTIvRzVJ
        Y1hJZFQ3SzgzbEJqdlFUYTUvVE9KOVAxNU5nbExkdUorOWdrSE04VlVWdHhhNEZ2
        cGFBVGpiTzdIMk1xVk9BSkJmNmJySjBNVjRZNUY4bDk1VHA0bHJDZTdMaC8xZmh3
        ZzYyS0syalN6V1BDaHVKc2xZZFRjenIwUmRjc29RRkJ4Yi9LWUk3ckZqaFJLL25C
        ZXIvYVFRbVVIc3YrNmxJNE9hSDZVOGtaS3h1VWlJK01od3hTUUo0aWRubkwwRE9n
        TzgyczZkc29vNzN5ejVHK2JUaWNmMFp2d0tWNnR6YXg4em4vSWlDaU9QL1JVNHlq
        Rnc5RnpVekFrK1l1eVNNYjJjTEpybWhmV292bUl4TExrdlFsdE4vU0lla0pmbWdX
        VDg0Y0pJOVFtcVVmaXZiRVRCSTl3VFBoa2Jpd3IxdWZlRW1NcWZXcUVWUml0MnFZ
        eURHaTI3ejluN0xGeHE2WGRZcit5b0pFNVZ0MDZLRFp0ck14cERKK2srMTJ4RElS
        ejhUVHdHbGFCSkg4YldvM1Y4WnRVUHNDV0xjbERxZ1hHL2ZhbVRKOUtTa3JGTU9p
        T0d0RTFjcGt2WGUwc25saGV3eVE4Uk52dVZCUUFwK3lMZXFrejE4c3FPNkRpSE1P
        b01sWUl3ZkRpMjZTd0lvV0cxY2tLc3gzbGp2Qmc0YnczMUVjN1U5TUdOWEhjUQpl
        WU93eVlFaFIzUERyNUtadzhpTTNMWFA0OUNRN0ttVEMxM1hEL3ZrZHhZCi0tLSBZ
        T0NiODZ1MjlqTGQ1aHo3WXVSS1RMT1kyY1BRc2t1T29sZGVuRU50TmFnCtrUmji/
        XBtEBn+OvUy91cKPALiDOLz9xUQp6pjenvZWrQSushrnsvdWc9j/2jiDe1cNbNEb
        6qQ++ys8cYKxbog=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-29T05:19:28Z"
  mac: ENC[AES256_GCM,data:nEJa1y+SyUv2i3qJGob+GAC94QwgLJahGyIQfA5lYn07XnVX5bX7FQq6UYdsokZzGDaKEhFmoD3w5QhTNb8l1OYcMS+ht/iPPeNOpg0MKny6mxgr0yvg8aAo49SUppf+m39BYYnTczKAkll/pRHGEaSuRRrZPk7va/dizshPUks=,iv:KEphdAGJuYQyUKbxpG2sTzPfN4KK51tegcyT/pTBMAw=,tag:Wj8149bB5KsBn5B42kWknA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
