---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: forgejo
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 16.2.0
  url: oci://code.forgejo.org/forgejo-helm/forgejo
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app forgejo
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    httpRoute:
      enabled: true
      hostnames: ["git.${SECRET_DOMAIN}"]
      parentRefs:
        - name: external
          namespace: network
          sectionName: https
        - name: internal
          namespace: network
          sectionName: https
      backendRefs:
        - name: forgejo-anubis
          port: 80
      matches:
        timeouts:
          request: 300s

    tcpRoute:
      enabled: true
      parentRefs:
        - name: external
          namespace: network
          sectionName: ssh
        - name: internal
          namespace: network
          sectionName: ssh

    # https://codeberg.org/forgejo/-/packages/container/forgejo/14.0.2
    image:
      rootless: true
      registry: code.forgejo.org
      repository: forgejo/forgejo
      tag: 14.0.2-rootless
      digest: sha256:5552c9e25f353760420b8ac7a7f0f0a788ff571bbfd8e2c1e93503d3e2e1b87a

    gitea:
      admin:
        username: ""
      #    existingSecret: forgejo-admin-secret
      #    email: "m00n@example.com"

      oauth:
        - name: kanidm
          provider: openidConnect
          existingSecret: kanidm-forgejo-oidc
          autoDiscoverUrl: "https://idm.${SECRET_DOMAIN}/oauth2/openid/forgejo/.well-known/openid-configuration"

      config:
        database:
          DB_TYPE: postgres

          HOST: pooler-rw.postgres.svc:5432
          USER: forgejo
          NAME: forgejo
          SSL_MODE: verify-full

        server:
          APP_DATA_PATH: /data/gitea
          ROOT_URL: https://git.${SECRET_DOMAIN}
          START_SSH_SERVER: true
          SSH_SERVER_HOST_KEYS: ssh/ssh_host_ed25519_key
        lfs:
          PATH: /data/git/lfs
        repository:
          ROOT: /data/git/repositories
        repository.signing:
          FORMAT: ssh
          SIGNING_KEY: /data/ssh/id_ecdsa.pub
          SIGNING_NAME: "Forgejo"
          SIGNING_EMAIL: "forgejo@${SECRET_DOMAIN}"

          INITIAL_COMMIT: pubkey
          CRUD_ACTIONS: pubkey, parentsigned
          WIKI: never
          MERGES: pubkey, basesigned, commitssigned
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true
        service:
          ALLOW_ONLY_EXTERNAL_REGISTRATION: true
          ENABLE_INTERNAL_SIGNIN: false
          SHOW_REGISTRATION_BUTTON: false
          ENABLE_PASSWORD_SIGNIN_FORM: false
          ENABLE_NOTIFY_MAIL: true
        openid:
          ENABLE_OPENID_SIGNIN: false
          ENABLE_OPENID_SIGNUP: false
        queue:
          TYPE: redis
          CONN_STR: redis://localhost:6379?pool_size=100&idle_timeout=180s
        session:
          PROVIDER: redis
          PROVIDER_CONFIG: redis://localhost:6379?pool_size=100&idle_timeout=180s
        cache:
          ENABLED: true
          ADAPTER: redis
          HOST: redis://localhost:6379?pool_size=100&idle_timeout=180s
        actions:
          ENABLED: true
        mailer:
          ENABLED: true
          FROM: Forgejo <forgejo@${SECRET_DOMAIN}>
          PROTOCOL: smtps
          SMTP_ADDR: smtp.migadu.com
          SMTP_PORT: 465
          USER: forgejo@${SECRET_DOMAIN}

      additionalConfigFromEnvs:
        - name: FORGEJO__MAILER__PASSWD
          valueFrom:
            secretKeyRef:
              name: forgejo-migadu
              key: password

    deployment:
      env:
        - name: PGSSLROOTCERT
          value: /var/run/secrets/root-ca/ca.crt
        - name: PGSSLCERT
          value: /var/run/secrets/postgresql/tls.crt
        - name: PGSSLKEY
          value: /var/run/secrets/postgresql/tls.key
        - name: SSH_AUTH_SOCK
          value: /tmp/ssh-tpm-agent.sock

    service:
      ssh:
        clusterIP: 2001:cafe:43::ef37

    valkey-cluster:
      enabled: false
    postgresql-ha:
      enabled: false

    persistence:
      create: false
      claimName: ${APP}

    extraVolumes:
      - name: git
        persistentVolumeClaim:
          claimName: git

      - name: postgres-forgejo
        secret:
          defaultMode: 0600
          secretName: postgres-forgejo-cert
      - name: root-ca
        configMap:
          defaultMode: 0600
          name: root-ca

      - name: forgejo-ssh
        secret:
          secretName: forgejo-ssh

    extraInitVolumeMounts:
      - name: postgres-forgejo
        mountPath: "/var/run/secrets/postgresql"
      - name: root-ca
        mountPath: "/var/run/secrets/root-ca"

    extraContainerVolumeMounts:
      - name: git
        mountPath: "/data/git/"

      - name: postgres-forgejo
        mountPath: "/var/run/secrets/postgresql"
      - name: root-ca
        mountPath: "/var/run/secrets/root-ca"

      - name: forgejo-ssh
        mountPath: "/data/gitea/ssh/ssh_host_ed25519_key"
        subPath: ssh_host_ed25519_key
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: *app
            patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: ignored
              spec:
                template:
                  spec:
                    volumes:
                      - name: dragonfly-stunnel
                        configMap:
                          name: dragonfly-stunnel
                      - name: dragonfly-certs
                        secret:
                          secretName: dragonfly-forgejo-cert
                          defaultMode: 0440
                      - name: root-ca
                        configMap:
                          name: root-ca
                          defaultMode: 0440

                    initContainers:
                      - name: dragonfly-stunnel
                        image: cgr.dev/chainguard/stunnel:latest@sha256:bd75c58ee97c9139081a177509734b2aa1beaead0afe784d9d74741eb5a44451
                        restartPolicy: Always
                        args:
                          - /etc/stunnel/stunnel.conf
                        volumeMounts:
                          - name: dragonfly-stunnel
                            mountPath: /etc/stunnel/stunnel.conf
                            subPath: stunnel.conf
                            readOnly: true
                          - name: dragonfly-certs
                            mountPath: /var/run/secrets/dragonfly
                            readOnly: true
                          - name: root-ca
                            mountPath: /var/run/secrets/root-ca
                            readOnly: true
                        securityContext:
                          allowPrivilegeEscalation: false
                          readOnlyRootFilesystem: true
                          capabilities:
                            drop:
                              - ALL
                          seccompProfile:
                            type: RuntimeDefault
          - target:
              version: v1
              kind: Deployment
              name: *app
            patch: |
              - op: add
                path: /spec/template/spec/initContainers/-
                value:
                  name: generate-ssh-keys
                  image: &image ghcr.io/m00nwtchr/ssh-tpm-agent:0.8.0@sha256:21679ac2c857da0b5ef2c3c272c5310ebc157473c12fe83f41af8671633b2e10
                  imagePullPolicy: IfNotPresent
                  command:
                    - "sh"
                    - "-c"
                    - >
                      mkdir -p /data/ssh;
                      if [ ! -f /data/ssh/id_ecdsa.tpm ]; then
                        /usr/local/bin/ssh-tpm-keygen -t ecdsa -f /data/ssh/id_ecdsa -N "";
                      fi
                  volumeMounts:
                    - mountPath: /data/
                      name: data
                  resources:
                    limits:
                      memory: 128Mi
                      squat.ai/tpmrm: 1
              - op: add
                path: /spec/template/spec/containers/-
                value:
                  name: ssh-tpm-agent
                  image: *image
                  imagePullPolicy: IfNotPresent
                  volumeMounts:
                    - mountPath: /var/tmp
                      name: temp
                    - mountPath: /.ssh
                      name: git
                      subPath: ssh
                  resources:
                    limits:
                      memory: 128Mi
                      squat.ai/tpmrm: 1
