apiVersion: v1
kind: Secret
metadata:
  name: forgejo-ssh
stringData:
  ssh_host_ed25519_key: ENC[AES256_GCM,data:AhGhFrR3Uzt5xsj+4Y+cxhwfGoQXbbfiPg1K/lAZOJEa66atyQckkoQDTW5UgL6fO4FmWKgnlK5yFw9J1ud/+8+BsnzmsmcaFjVXaFiv3v+yYrAlC92BllsbTOZh2VhMr6ALTsrxvcMRGq9JIAeboxa4dnL6894TCCsUxSDjblBVCZsPM19nCLFsPyeT194xADX2SUIqDR5NVpzbtFXkz7DkwqhGGaVHlgKEHgAv9oUZxDnlacLuFR1roZtS2GPwemDG/zB5HVAKjG4BVbV9RiNZuiqKRzYKcFMGVQDKJXtuHudjfa7SQOgV0EnPvWooLHmtmFYVzufk4/SS0Q7NnRutH4GH1kjHQhpKJumjkoFMBv37+fYJApAnv69LDbpWdSf46u1oFx5DjvIU9kuv6XyCL0MAYPidzDY27ExmT8mFNhxqjno8Py6yAqvLCXxMgNP7Y/PVHmf63sQPuXwkXuWb6DhXp5YcXPi0gt3nX33MwrEj5t707ti/T7/NjkQzcNqkxHXpReQ/e8J4n5ICd5qB7wk3nrJr8JHi0seQk54TtQQ=,iv:UE9RuGvcXhOtbtmcXwPYLJX05YSFue/ysOSen5jYphE=,tag:0dJZF7fHTxVar95y83pBLA==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IENJbTkrT1gw
        NzJpYno3MkFPTTZqY1hoK2FycEtWeENLSUhHMGJVTGVMbW9ZbjFZY0xjcXRLdkVo
        aWFzbitqOHJaVmhZSHhaejJmU2krSGJVaHpvcFZvendEZGZreHBLdVhjcGhYdWZK
        WmhqcVNxNXA0MnJHa1ZwR0lUNUdoNXN1T1JjdkRVTmpNKzBJcTJyTjBXK1JoWW83
        T291bTB3aVhhcTRlSW41ZEY1amExWHNBTHczak5DTEJmSjVMaFpDbXdPZldQZ2oz
        SkMrU0tMMmgwTE9QMHFmbi8rVngxMnEveW5rWTI5ZVNFN2FlYk8rVTZUalhWYkVF
        SnBkUzJZMmFNNzRWcWtRbllMb1BMekZTaWo3dEs0cWxoMmhHdmNCS1BvdjdnQmpn
        U2g1MWVXM0RUOUJhMURoWlRDYzd6ZFF2K1l1T2pEQXFZejVNRlNFOTF2cXI2RFIy
        QVNINGVuME9oMEQweUN4c21qRjhtNktvVUVQWUVyam5wT3BBcmRUcm5YY1FhalpW
        bmJPaFFsaXRDcXVJYkNVK2hIbEZmQnRMc3FpeEFZRzJvYm5jZ1Zqall2bFpPVytT
        Ulh6bHpPcXI0cGtNakIrZHBzQXpjeXV2RUxvSmRTM2REZnoxWll2cDJNQnV2NUs3
        RW91UXJXSnJQREp3MnpLNXhENWNzSGF4cjVQc3VZa0pxanNmZnNMdDZxMWNWVG9L
        Z3lMeHVweHRsbVlEVGtSSmZXekE4Um8vaGdtcERHUWlsMXN0R25URWozRTdNQkJj
        dk5WKzNQenpqMVc0WFdGSXJUWmJOTDQ2ZkRNVkpQN0JTeU4wTmJOUDdBdnRSd0pV
        Mm9WL2o1RXpzeC85QVdTYk4xYk9nanBhSmV3YkNFRlFiUzJ3MkdNVHBzRGY5blpS
        VTNoc01rYWpZMWhHakZjV3dXZjhJalFLZ2Mxd05EQVFJM2J3VDc1L1ozUkpjTlVo
        L2V3VnlCbUc0cmsvNitXdG9hYU15cGFIK0tjN252NGVkZ2IwdCs0MnpGMUVkUmJU
        OUttVmJHU3FqUEZBRExnR20yM2Uyc2lQZDkzak9tQmZNWGlkZzBSUUZwL2t1SitI
        MzE1WGhFamdZd01OWUg0U3dyY2V1YmNSemh5STFyWk4zL05lTHlibnM2ZDR3c3ll
        U1JmSzhHazZmZzBJQm1JYlg4WjRTK1NLMkNrSHFlVEd4Rkc3Z1YrdE4rS1h1VS9K
        a05aVkxVQm85UFcrTzE1M2NGU2EwYlc5SFdJcnRvUHJMTmZSdXV4K2dUVTJqS3Vp
        SVMwaThhbTdDeU1WMGNlMTlBSVpTMEUwQWdxcUVTWitrMkcrWXFoUmliOHB5WjVq
        ZmRPclFybExvMHpiZDhzeFhYVk43RWRGWU45bjZ2SXNxc2FuWnBsbGhSb2NueHNN
        VTBKNjQ2T2pYbnQ0RDdBaDk5bU5PcGxIdDFUYXphNEJpTWdZcU9hcXVVZjZvaGtD
        OUt2UzU5TmVlNTJxM0JoZXFWa3JzdmZXSE1NRy9zTXNmd2JMQlRQTjhqQWpBYmVv
        b0FLMGhkditSTVNkR0Q2d1owcHBmbjNXRmFNNXhmSXV4YVdhOExPM3lMS3dkUTlP
        Vmg1bDd5amRaNWhIK2xZMlhONVJhVnQzOU1QZTFrMU1zblBzeisyT3JGYU9RNDRH
        cU5pdlorc01CV09sUVFEaU5XTGNQdWxsbnE1NmlPWnE5SnhpWDdOOGJnd29QNlBX
        aG9EUVJMeklmNHRsaUF4QlgxQVJqa25zYmRaYVZBNGprRDVzTysxRWRYc0RROW1B
        WkVVbFlnK1A0ZE9CeVg2ZnNSa1Jad3p2SXZqQi9RbXJTWEkrQ21SNXc4d1JLdE1s
        ZFBTbnN4UkswcHhlWjdNNW9nSWZMbmpKNFhyY3dieGFrb3d0RWpwL1lUUTNVRFJi
        dndYdFJFR3RuOXhDbU82dlBIL1JoRDdMcGI0M0s3UzFTL3duQUNMQytya3ZFQQpM
        V2YxaDF3dlRRREpTM3NPY2w2cWVlY0JoTjRaOGpMUS8yRW90eWlTOUc4Ci0tLSBP
        Qnc1aExab3E3OTRIS3RIZ3lqMGFHZlIwT0xtdnd0M2ZGb3lVbU5LSFVBCifbPuHj
        xmkgcMIlrl9983dypzpbIzpTzduT97GpuEm2z1aaVj5PtA35yOqjmnRLwYI3J7Cg
        V7A4Hw1NdQHRhrw=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-28T16:18:27Z"
  mac: ENC[AES256_GCM,data:PML4cY5CIYp69ZwjQBjh8V52lRFQ7xOaPxkFOaLMQ6ZoKSKGh0HZMtmty4p6FyoIkezsXOqr4+TMSetp+nMD9KaflVgSGrFF35AjXFyOfQh8aqjf1j4VOxKl6d2Xbx8wwSopn75hZZs85IxKb4VUR8zCJ3Whnjbpx/EiAUTo8Ak=,iv:3LmjIht5pnexHWXHbnt54iu8Kqt7HCFlXa2kget68vM=,tag:n5HdzlrWFwugki131n4T/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
