---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/fluxcd.controlplane.io/resourceset_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: ns-tls
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  inputs:
    - {}
  resources:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: &name "<< inputs.provider.namespace >>-server-ca"
        namespace: &namespace "<< inputs.provider.namespace >>"
      spec:
        isCA: true
        commonName: "<< inputs.provider.namespace >>-ca"
        subject:
          countries:
            - PL
          organizations:
            - homelab-cluster
          organizationalUnits:
            - "<< inputs.provider.namespace >>"
        usages:
          - cert sign
          - crl sign
        nameConstraints:
          critical: true
          permitted:
            dnsDomains:
              - ".<< inputs.provider.namespace >>.svc.cluster.local"
              - ".<< inputs.provider.namespace >>.svc"
        duration: 8766h # 1 year
        privateKey:
          algorithm: ECDSA
          size: 384
          encoding: PKCS8
          rotationPolicy: Always
        issuerRef:
          name: cluster-ca
          kind: ClusterIssuer
          group: cert-manager.io
        secretName: *name
    - apiVersion: cert-manager.io/v1
      kind: Issuer
      metadata:
        name: *name
        namespace: *namespace
      spec:
        ca:
          secretName: *name
