bots:
  - import: (data)/meta/default-config.yaml
  - name: asd
    action: CHALLENGE
    path_regex: ^.*
  - name: allow-anubis
    action: ALLOW
    headers_regex:
      Host: ^anubis.${SECRET_DOMAIN}$

openGraph:
  enabled: true
  considerHost: true
  ttl: 24h

status_codes:
  CHALLENGE: 200
  DENY: 403
