# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: migadu
stringData:
  MIGADU_USERNAME: ENC[AES256_GCM,data:Xb5+/wAj0SZdI5ylcK+/kQ==,iv:GXWbpoGRI/3y9365/2RDrcteKVt6ufFu0Ou5na9bE+4=,tag:QDZJaG0sREMYYCJA7dQvbQ==,type:str]
  MIGADU_TOKEN: ENC[AES256_GCM,data:VaU8LPw9tgRUIRWGlC4DW9Bv1mNUkfPEg+0FQBUGnkdhpD5rh2Voq6RiW0+y+SlchBlwZlpBKsXL5VcsxDJdSHWgyIQPq8VEpOUjwYNbtkCrlhdTz1M=,iv:ekrX8BNXRZmfdXYhAXLzXf1mqPYRS1Q4IGfzsdoeZYc=,tag:fvCc1B5iJJcKowlrsHyM3g==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGZBQXBRZDYz
        K051NTFJTVNUWk5PczFRZUZkY1A4R3JmYXRCNkFpdm1SUDVSbnoxVEZoSzU2YXEx
        dDJWNTMwNGJ3dFRGakMzZnJ2dStZUkEwVVducytKbWpYMk5aYzdOa1puMDdKaUpC
        cTVpU00wMXNDT1N2VGt4V21oWXJWb0dSTjhIY2hpdFdDc1JIUmZpZWF4S295eXo5
        Nkdrc2xVeFlHbGlYcmwzK0h0Sm9oRmxSZUk3TTBPRXl1TVNRL2tHVlZuaG5mN3JM
        VFZXckxJbWFNZUZNUjZUSUg1NDV2djRWWm1aNUpTdlFPNUxxOUFYS2YvZ2xheEJZ
        b0NxSElndXhkcG9kZFRtMXY3VDRMMTBNUzRBTmdjQUliZnlVN3R3YnJKWEdNeUQ5
        Nmp3OXVkVkFlTlNZQ1I1N0pNSzNTcHFiQ3JyZjRvYnFCbHJMUVZySUdTSWlpN3FV
        dzM5alRsNGxESStQQzFCTlE0THBGYjBBL04rQUZBTUU3amY4c2NRNXU2RU91SmpF
        S0VZODY3azJVd2ZQcVVSV1F3eWMxd3dscmJ4VE02cTBUbmFPT2k4RWI4K3UxY2RV
        YnJRMnNGM0c2WEllYytOcFdYYWpyTE1MMnJzMDRiaGVFbXB2Ylg4ekRqODVMWmFo
        NVMvSVNSclNpU0NMWGIvK3NEdVB1elhUa1M4L3UxQXlhUFdhcmhMdDlYVm5GMUl5
        eTBXMCtZdG5XSjBxekU5QldQVE5XN0tHbDkzVWorLzRqbzhCaTE1MjE5TXJzclBx
        dFduS3RCRkZxdk4zam84VlorN3pOdFVvZ2ZvRWFJU0NpQ1hRdWVXU1NJZlVzNGtE
        Zmo0QitaRFBqS3JuZUpqc1hJb3o3bVBjZEpnOUdaOXQvUVlJVXFkRTk2K1Y4MnZt
        cE0ybUVUL1ZuMXpUQ1pDRm5ycHhSYkhZNEVhekQrQW9RbmN0SzhPWTZhWjdQamtW
        V2p3dUhpRDkyUGs1NEZZNFdiTDhSYmhIanIrNmJLK2lNK1dyV0hLK3JVR1pCNEZt
        dllRSkRIVWVVWjNudnZKTFQraFFKYjFjai9OT1VDcGpjT2ppSERtNXdReHlpL2JF
        VXUvQmxCdm1XTmt0cTRGRnpqQ1hwS3Y0RjdSMDVpYlEvWnZoWUE1RHJOMjNxb0I1
        enpDcjBqeGxKM0w2bUUyVkdtYjE1cUxEbzJhME53eTBuQkZ2NlVWYzZKcnprY2wv
        RFVjejRNYWo3NGppMndueWpZUEZ1b3A3OGpsVE9VQkdFa0k4UTk0R1JsQlcrS1o3
        dzYrNklFS21NUDdPU1V2OHFDNjZYUVo1YzN5N2tpbEZkZGhzYnZKMHJyQXhjZ3lZ
        UURDbCtTQUhVR0RsSURQWFRGcXZ1S1VDcy9ic2xRSzNvMTc4di9uNGpNd0kzdzE1
        UUtVVU1EWlAyTXNvRDFEZ1pjMXh2K3NlKzBYejJFK1l6MjEwWFNRZ2hzOFNaeUdu
        Q3cxZ294N0Y3a2RwaFVrMU4xSlo5T2x2ZmI4cVBRVW12VGxKOWN6NlJ5U1d6T3Bz
        bHZNWjgwbEM5SFQ2VG0wT0lINk90NXZ3SEhCTDdsVFR4V0JIWWpXZVVuc3Y0VGp5
        ZTBlVmZHZmpwMWhuc2tPcTBBSFVtS05UU256OUhaVTVGQ0pIZjBPdUNpK2tYTmJr
        M0c4RW04eWQ5dVI0S3djYTBoTGtzYkhDaW1tMnM3RWtzMDBoQTRtQWhJa3JqUHdu
        c0I3VDhZU2ZoSjFNMko5QS91TUVmVHdBVFNKclppNVZnVnJtbndKMlFBbVdjMUcx
        QVdaZFU4N1dYR0JjTzQzYTlraTUza2Y5SzhnK2gzbzhhWGpnd09OenFEUFZUM2R5
        UWl6LzFKVG5EZUwzRmxxd0YyVXRQTVRIRTNTRGtyNmxUZFpZUFpnU2phOHJPSS80
        bHNZRWtlZHd1dkkvVE0yWkZBSi8wZTFzMXJMT2oraTY5UkpBb2R4MTkvN3Bkdwp6
        Z0UydkRlZDBqRW1pVldWdlAvMjErZWtMVFZMTG1mOFZkdk1CMk1hODVJCi0tLSA1
        RXIyejJER0JZWnRPTTh4MEo2SzF4MndzWWYvNHRhRFZjUDFJMkxMcGdVCtFJqwlr
        5OJwrJcSzCw12GksBgrEWs23D7RhjCXOjQ8Z+9hUX0Y2wyss7o3dcaY2Gd7ZYvev
        Kiv9j0aYvmlZVZ0=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T05:48:40Z"
  mac: ENC[AES256_GCM,data:3u3Ailu+duisWpmliYYhSrwp61iaJE+drLMyPjZHK4wp5YaYQWql20aaz9SeRvL1FGcCI39TgF+ZCLxd4quWTAH6mV9U20cTJ5V0og8hApPmKwRj4dvJOuIu831Cp+1ZwDHMm69kxDdSSkbs6xuhnXaV0Xt+0y2FnUcHlRoL1Q0=,iv:8aUidcFbm6ghziLWI7AGAcHR5tZNMx086bcgUtnzKDk=,tag:C1EHQQyiKXlZae6XTK7Jug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
