---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  replicas: 2
  snapshot:
    cron: "*/5 * * * *"
    persistentVolumeClaimSpec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi

  image: ghcr.io/dragonflydb/dragonfly:v1.40.2@sha256:18afa43e911f1dff18c7d1eb452361876d9702bb1cdff5c5d75c69617a4065c9
  args:
    - "--bind=::"
    - "--admin_bind=::"
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
    - --cluster_mode=emulated
    - --lock_on_hashtags
    - --default_lua_flags=allow-undeclared-keys
    - --dbfilename=persistentState

  aclFromSecret:
    key: acl.conf
    name: dragonfly-acls

  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi

  resources:
    requests:
      cpu: 100m
    limits:
      memory: 512Mi

  authentication:
    clientCaCertSecret:
      name: dragonfly-client-ca
      key: ca.crt

  tlsSecretRef:
    name: dragonfly-server-cert

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532
    fsGroupChangePolicy: OnRootMismatch

  networkPolicyEnabled: false # see ciliumnetworkpolicy
