---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/admissionregistration.k8s.io/mutatingadmissionpolicy_v1alpha1.json
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicy
metadata:
  name: add-dragonfly-stunnel-to-helmrelease
spec:
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded
  matchConstraints:
    resourceRules:
      - apiGroups: ["helm.toolkit.fluxcd.io"]
        apiVersions: ["v2"]
        operations: ["CREATE", "UPDATE"]
        resources: ["helmreleases"]
  matchConditions:
    - name: labeled-helmrelease
      expression: >
        has(object.metadata.labels) &&
        "m00nlit.dev/inject-dragonfly-stunnel" in object.metadata.labels &&
        object.metadata.labels["m00nlit.dev/inject-dragonfly-stunnel"] == "true"
    - name: controllers-map-exists
      expression: >
        has(object.spec.values) &&
        has(object.spec.values.controllers)
    - name: target-does-not-already-exist
      expression: >
        (
          "main" in object.spec.values.controllers
            ? (
                has(object.spec.values.controllers["main"].containers) &&
                "dragonfly-stunnel" in object.spec.values.controllers["main"].containers
              ) == false
            : (
                has(object.spec.values.controllers[object.metadata.name].containers) &&
                "dragonfly-stunnel" in object.spec.values.controllers[object.metadata.name].containers
              ) == false
        )
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: >
          [
            JSONPatch{
              op: "add",
              path:
                "main" in object.spec.values.controllers
                  ? "/spec/values/controllers/main/containers/dragonfly-stunnel"
                  : "/spec/values/controllers/" + jsonpatch.escapeKey(object.metadata.name) + "/containers/dragonfly-stunnel",
              value: {}
            },
            JSONPatch{
              op: "add",
              path:
                "main" in object.spec.values.controllers
                  ? "/spec/values/controllers/main/containers/dragonfly-stunnel/image"
                  : "/spec/values/controllers/" + jsonpatch.escapeKey(object.metadata.name) + "/containers/dragonfly-stunnel/image",
              value: {
                "repository": "chainguard/stunnel",
                "tag": "latest@sha256:95931468f1958f3db553daffecb9e2d59d876baee59bf3298125608dfe885d03"
              }
            },
            JSONPatch{
              op: "add",
              path:
                "main" in object.spec.values.controllers
                  ? "/spec/values/controllers/main/containers/dragonfly-stunnel/args"
                  : "/spec/values/controllers/" + jsonpatch.escapeKey(object.metadata.name) + "/containers/dragonfly-stunnel/args",
              value: [
                "/etc/stunnel/stunnel.conf"
              ]
            },
            JSONPatch{
              op: "add",
              path:
                "main" in object.spec.values.controllers
                  ? "/spec/values/controllers/main/containers/dragonfly-stunnel/securityContext"
                  : "/spec/values/controllers/" + jsonpatch.escapeKey(object.metadata.name) + "/containers/dragonfly-stunnel/securityContext",
              value: {}
            },
            JSONPatch{
              op: "add",
              path:
                "main" in object.spec.values.controllers
                  ? "/spec/values/controllers/main/containers/dragonfly-stunnel/securityContext/allowPrivilegeEscalation"
                  : "/spec/values/controllers/" + jsonpatch.escapeKey(object.metadata.name) + "/containers/dragonfly-stunnel/securityContext/allowPrivilegeEscalation",
              value: false
            },
            JSONPatch{
              op: "add",
              path:
                "main" in object.spec.values.controllers
                  ? "/spec/values/controllers/main/containers/dragonfly-stunnel/securityContext/readOnlyRootFilesystem"
                  : "/spec/values/controllers/" + jsonpatch.escapeKey(object.metadata.name) + "/containers/dragonfly-stunnel/securityContext/readOnlyRootFilesystem",
              value: true
            },
            JSONPatch{
              op: "add",
              path:
                "main" in object.spec.values.controllers
                  ? "/spec/values/controllers/main/containers/dragonfly-stunnel/securityContext/capabilities"
                  : "/spec/values/controllers/" + jsonpatch.escapeKey(object.metadata.name) + "/containers/dragonfly-stunnel/securityContext/capabilities",
              value: {}
            },
            JSONPatch{
              op: "add",
              path:
                "main" in object.spec.values.controllers
                  ? "/spec/values/controllers/main/containers/dragonfly-stunnel/securityContext/capabilities/drop"
                  : "/spec/values/controllers/" + jsonpatch.escapeKey(object.metadata.name) + "/containers/dragonfly-stunnel/securityContext/capabilities/drop",
              value: [
                "ALL"
              ]
            },
            JSONPatch{
              op: "add",
              path:
                "main" in object.spec.values.controllers
                  ? "/spec/values/controllers/main/containers/dragonfly-stunnel/securityContext/seccompProfile"
                  : "/spec/values/controllers/" + jsonpatch.escapeKey(object.metadata.name) + "/containers/dragonfly-stunnel/securityContext/seccompProfile",
              value: {}
            },
            JSONPatch{
              op: "add",
              path:
                "main" in object.spec.values.controllers
                  ? "/spec/values/controllers/main/containers/dragonfly-stunnel/securityContext/seccompProfile/type"
                  : "/spec/values/controllers/" + jsonpatch.escapeKey(object.metadata.name) + "/containers/dragonfly-stunnel/securityContext/seccompProfile/type",
              value: "RuntimeDefault"
            }
          ]
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/admissionregistration.k8s.io/mutatingadmissionpolicybinding_v1alpha1.json
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: add-dragonfly-stunnel-to-helmrelease
spec:
  policyName: add-dragonfly-stunnel-to-helmrelease
