# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/fluxcd.controlplane.io/resourceset_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: dragonfly-acls
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: dragonfly
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      selector:
        matchLabels:
          dragonflydb.io/acl: "true"
  resourcesTemplate: |
    apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: &name dragonfly-acls
      namespace: database
    spec:
      refreshPolicy: OnChange
      target:
        name: *name
        creationPolicy: Owner
        template:
          engineVersion: v2
          type: Opaque
          data:
            acl.conf: |
              <<- range $u := inputs.users >>
              ACL SETUSER << $u >> NAMESPACE:<< $u >> ON >{{ index . "password_<< $u >>" }} +@all ~*
              <<- end >>

      dataFrom:
        <<- range $u := inputs.users >>
        - sourceRef:
            generatorRef:
              apiVersion: generators.external-secrets.io/v1alpha1
              kind: ClusterGenerator
              name: pw
          rewrite:
            - regexp:
                source: "^password$"
                target: "password_<< $u >>"
        <<- end >>
