apiVersion: v1
kind: Secret
metadata:
  name: mealie
stringData:
  OPENAI_API_KEY: ENC[AES256_GCM,data:HIuJDoHkrkuQBSs4JVRHJWUM/cGjKECHoA==,iv:Zr5cx7UB+9tL9m/9+ihqk22aFiYrxjDoilCrwtolN9E=,tag:mqKj/99RoUmXEl31Zeup/w==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFJJZmNzaHZv
        Zks1eHp4b1EvWnRkeGlYMVVGVVg4OVlVQWplU25FSVlYRVlsNXlxWlArTnVKdENT
        bFp1ZDlmdXJCSkJVSTg5dmM3NWNjTDF3MFFrRDNSYU9PWXBEWEZlcmhJZngyUVEz
        S0o2Zi9ES3Y5RkJTcU5ER01PTVY1TmZDKzV2b0JjR293ZVcxWlFtNTFKN0IraWhm
        amxVQVBDZWhtSURudHNIZ3A0cTNubUw3ZjdNbHdsY2licnZkRHJ0Q1RQWTg4QXdo
        Z1R3bXhzNkx6dnA2RUZqRi9US2NSK0lneU54aGFMeVVYTGc4cHFnSmJtMXhtMWto
        aktBQk0vRkpERnFycitORFF6Vmp6QzBUL3hySEpORWNUOHNoU2JvbGVGUGN4ZkZ1
        NjJVdUF3MjVsWUdnY3JaNlRjWTZ0UnBzOUpGaEdpaUkzR2xXaUYwVnBhY1hLY1Rl
        Y0Q2V014Y1hrbVlISFl4RmpoNjE4Nkc3UDBVUWU5bE1Tc3d0c3RJbmxpQzJKQkNs
        OHdvOFp5TFMyN3ZINm5mU2JFOCsrRHpQUGZMU3MxdFZpSldhUmlXOVlVOHRrZFIw
        NERGMkVhb2w4eWE0N1ZyaW5PMGgwR2pYS0lQNlpTT1I2UjZva2JiUStDK0tDV3o3
        T1ViQXVRMEhBbXBubjVucWhsTjc4ZU9uQXlXSXYrMFBQZmNLWVp3ZVdON2FtbFlm
        QTR2MHFXNFhpQzVuRnYwWlZvT0UrNFVuL0RMVkRpZitWTldxKzNIL1M4cSsrUzVu
        UDQwdDlFa3h6WlZmWFkzRWlJazd0Y2cwR21pRXdURkJtTDBHMFVqUkhCN0loY2d1
        TUNSaEhZL3NoakFIcjRBQ2NqcE5FNHNKQ3VlczI4a3d6WW5Nd0l6UmdlM1czcVVZ
        QWJuMGI5MER1Y1pxUEhYUEtKWUVlRm1ldmN2SHhSK25sbWhFWjJBTk5hcTZRVFht
        dU41TW5XbU1JYW02S0Y0RUVIRFZrMlhKdzFFN1VHVlNDbzJ4T2lqOVdncWl2U25z
        SGhzNkpnVTVBWkNoY2l3QlQzS3J3Y21DbHBKRm0xSW5HcEdHUy9iS29mN0U1dERy
        SndqbHJvNEJYMy9mMVRIMGpxcW14WTR6UThJNHVzR210RFlhUFRSSVA0OFRqWWFM
        V2VVaWp1MmZtSzF1cFRyNTk3UGNJNWxaMWthRkRrZ2ZVOTBpQjZCWmtrN1hPaGVZ
        RFlNMkNGQTcyL01oYzIyQjdUWlYyS0JaVi9jU0lWQVhTV0hpVHMyd1lDcTM2b0p2
        YTlLV2RjRWN0dGJhQ2FSRjN6QWlISE5nWmJ0UnlPemJkNHFLOTh1dGVNclBGTFF4
        SjNJQXM1RU92K1cyb1g2MkZxQjR3VWNleEFpUXV2dXkycEF4Rmh2VE5iZ1BUbDYv
        dGFTT04zdEo1bGdiWG9hbmx5MUxQTjZNTzZVZURwSTVXRWZJQlFSS0g4VDlqZUww
        ZFpGTkRCZzdoMkxpcHR2MTR3TWZyd0hRNm9CNjlPYWlwZ3NDWDd1RlhsVll5MFlR
        VnpZRVMxUmd6WTBnMEdMNlhZUGd2bzFOZExTa0FJdnRPTW1HdmNkb2MxTmROZmFh
        S1FOVVNUdnJHcEk5RWc5bmtyTWZVaENhUDY4OE1pSXlRWGU4SWJDcFJ4V3I2WVcr
        SmNiSGFISHYxaE1hWVZnWUdnQ2ZyTjRienc4MHhNMjhJWGE1Vy9Yc0d6UHBpaWZG
        UitqdHp1U1UyNUh5Y0I5UHBWRS9nVTgxby90NXdkWmd6bHFDWkxPRmdacUNmQ1JT
        Mk9wN0dOV2lxd2cwcXp1SGc1V3dxZENaMHN4aUVGQkZ4S2w1OENGYTNvV0FPYSt4
        SVhjeHlPWFNESDNyeDYxb0VWSGxFUENXeVpVTXFtK3pyR3V2YTUwOTNUbE5CS2lq
        T1JIV0FWdFJVSDBaQzd3OFlONUVXbStFMkl1YmQrc2ZKREdDVTZDdVRWN3FNdwo1
        Z2VuTkpybDhVdVZKeUlrTmJ3eDAvMnkxOWR2UkxFUjA4SWRJWXpnSHNJCi0tLSBl
        Q3BUZ1RoRjZOd2lkZGFNSTdmQ2FXMDhvaHZ0NE1KbHlwUkt3cUt4UlB3Ciyz5dvL
        ZAtW453PxqHz5/DTVwTsivv3pa2vmyS8PH5dKLrXFs2J8IRxnM+ecB41X57KRVAD
        feD3dF1o9pzDxpQ=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-11T05:30:11Z"
  mac: ENC[AES256_GCM,data:HkwnjZjsXqI3k3iYeGEzVeDm8USaCnIdcCZ91G7WlpFS7FnETtkiND+0dYlMqRB0/1ExZ8ufOtBvcEvX+AWa2ibSpj/cbA41hPzxtsHrRztm7LafO7/QhXPiHymuv0Je8LqzQQk7XVcdEOmsN019m0Ux+uU3rYmv+R8XGO99Rts=,iv:5poxL8EHSmWDLH7nm1ecEIWJkl1MpvW12cqc0rRwJJw=,tag:7LC+kGzeKrmBY2rRBL0NEQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
