---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app tailscale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: tailscale-operator-values
    template:
      data:
        values.yaml: |
          oauth:
            clientId: {{ .clientId }}
            audience: api.tailscale.com/{{ .clientId }}
  dataFrom:
    - find:
        path: "/tailscale"
