apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
stringData:
  client_id: ENC[AES256_GCM,data:6DbaJvxixRH+nKGG/mQHadILWDbXv53C3lqrurQDwSrw0kg=,iv:6SjUCGj+DwKekge8rm23XqUpouiv29aKCmDUw4x3ZXk=,tag:JIBbLk9ETDn8POoFPSLxDA==,type:str]
  audience: ENC[AES256_GCM,data:UCZUfjzQWAizZtdIHiEmcKxCnJ+u+zBOlWJ6F+CYmvjb/7pX5NqN7I9hiUCFdLqDWu7R7m0=,iv:PzbWPF0p+RaCXCLkkcF4NaFjRg6+laeeo3hCf9j2mzA=,tag:0ZqyT62ryHvbBfspKUMTdQ==,type:str]
sops:
  age:
    - recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcnozMGprM3RSa0dnZzVt
        VGkxeUVYbzQ4R0N4N2N3MTNhZnJ0eTVKVmx3ClB3Q3hDb0JWRWZjRHhvdWtDQ3Fw
        Nks2UjBIYXhTL29wQjFGVTB5Vm40K0EKLS0tIG90UVVGZEVVRGNXK25NcFdLbFZB
        ODVSRmpEVENNTkJXUUFwT0hiUVNCckkKeMmPkTql8ugyy9LZnetiYDBgbyHam38D
        ucbs1ITY6BAHAGDNKpy7ORHgg/lKVeOHLW+AcGV4Ow9Ze0FMEyMEiA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T03:53:07Z"
  mac: ENC[AES256_GCM,data:li2ajq7GdRvsZ6dZ4/T0uIbL3BjATmgYNwUfoY0V8S2BHDkaeURo5hCTbDbCtn2Vfi2PYo8OdUUtBs9J4RIh8iWBgsA6f08LuhY/m/1hO607yvUvv3ykmVQYLLjJTV41vKxucJ0m919/tPRTu5gQNoEKMfAAFZi+fXjFSr/a5jM=,iv:MYM7/h7hrsdYM2BVhV33Pd/z2W4ED9mfAWKhLJ6PXSw=,tag:Ee51GQG87wa0UI+yaI93Ew==,type:str]
  pgp:
    - created_at: "2026-04-03T03:52:57Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DC0EwVK2S0BUSAQdA+iIwqEUzHj9KusNoODgMFpnBitByQcgHYbVsfatR9hIw
        1r8QXC8u8HSW+SRqFQ7kGrEgIGiZUvKM8hxSj3Rrrw7Qbl55wFlcn77lJbhsoYxn
        0l4BOCEEAB4FL6HwWO3WZqepRC1KG04lojdSHb5SFGgYHUtDgDLE4fcfwFD424Jf
        Ze0XOuMY7LUhJ4Dbj63/PwoyFsAGf36z6vOAN04fpx7uToqb7cfMKBREzDtQnEuB
        =C3hW
        -----END PGP MESSAGE-----
      fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
