---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}-b2
spec:
  repository:
    kind: ClusterRepository
    name: b2
  retention:
    keepDaily: 7
  compression:
    compressor: "zstd"
  sources:
    - pvc:
        name: ${KOPIUR_PVC:=${APP}}
  verification:
    deep:
      capacity: ${KOPIUR_CAPACITY:=5Gi}
      schedule:
        cron: H 5 1 * *
    quick:
      schedule:
        cron: H 3 * * *
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=csi-zfs}
  identity:
    username: "${APP}"
  mover:
    securityContext:
      runAsNonRoot: true
      runAsUser: ${KOPIUR_PUID:=${PUID:=1000}}
      runAsGroup: ${KOPIUR_PGID:=${PGID:=1000}}
    podSecurityContext:
      fsGroup: ${KOPIUR_PGID:=${PGID:=1000}}
      fsGroupChangePolicy: OnRootMismatch
