---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kubewarden-defaults
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.11.1
  url: oci://ghcr.io/kubewarden/charts/kubewarden-defaults
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/kubewarden/helm-charts.*$"
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kubewarden-defaults
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    policyServer:
      env:
        - name: KUBEWARDEN_BIND_ADDRESS
          value: "[::]"

    recommendedPolicies:
      enabled: true
      defaultPolicyMode: "protect"
      skipAdditionalNamespaces:
        - openebs-system
        - kubevirt
        - observability-privileged
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: policies.kubewarden.io
              version: v1
              kind: ClusterAdmissionPolicy
              name: no-privileged-pod
            patch: |-
              - op: add
                path: /spec/namespaceSelector/matchExpressions/0/values/-
                value: tailscale
              - op: add
                path: /spec/namespaceSelector/matchExpressions/0/values/-
                value: gitea # runners with dind sidecars
          # - target:
          #     group: policies.kubewarden.io
          #     version: v1
          #     kind: ClusterAdmissionPolicy
          #     name: drop-capabilities # temp: allow NET_ADMIN in media namespace
          #   patch: |-
          #     - op: add
          #       path: /spec/namespaceSelector/matchExpressions/0/values/-
          #       value: media
