---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kubewarden-defaults
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.11.1
  url: oci://ghcr.io/kubewarden/charts/kubewarden-defaults
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/kubewarden/helm-charts.*$"
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kubewarden-defaults
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    policyServer:
      env:
        - name: KUBEWARDEN_BIND_ADDRESS
          value: "[::]"

    recommendedPolicies:
      enabled: true
      defaultPolicyMode: "protect"
      skipAdditionalNamespaces:
        - openebs-system
        - kubevirt
        - observability-privileged
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: policies.kubewarden.io
              version: v1
              kind: ClusterAdmissionPolicy
              name: no-privileged-pod
            patch: |-
              - op: add
                path: /spec/namespaceSelector/matchExpressions/0/values/-
                value: gitea
          - target:
              group: policies.kubewarden.io
              version: v1
              kind: ClusterAdmissionPolicy
              name: do-not-run-as-root
            patch: |-
              - op: replace
                path: /spec/mutating
                value: false
              - op: add
                path: /spec/namespaceSelector/matchExpressions/0/values/-
                value: media # gluetun
              - op: add
                path: /spec/namespaceSelector/matchExpressions/0/values/-
                value: observability # something with victoriametrics
              - op: add
                path: /spec/namespaceSelector/matchExpressions/0/values/-
                value: trivy-system # https://github.com/aquasecurity/trivy/pull/10134
              - op: add
                path: /spec/namespaceSelector/matchExpressions/0/values/-
                value: tailscale # sysctls
              - op: add
                path: /spec/namespaceSelector/matchExpressions/0/values/-
                value: gitea
          - target:
              group: policies.kubewarden.io
              version: v1
              kind: ClusterAdmissionPolicy
              name: no-privilege-escalation
            patch: |-
              - op: replace
                path: /spec/mutating
                value: false
          - target:
              group: policies.kubewarden.io
              version: v1
              kind: ClusterAdmissionPolicy
              name: drop-capabilities
            patch: |-
              - op: replace
                path: /spec/mutating
                value: false
              - op: add
                path: /spec/namespaceSelector/matchExpressions/0/values/-
                value: media # gluetun
              - op: add
                path: /spec/namespaceSelector/matchExpressions/0/values/-
                value: tailscale # NET_ADMIN, NET_RAW
