---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: garage
spec:
  allowedNamespaces:
    all: true
  backend:
    s3:
      auth:
        secretRef:
          name: kopiur-garage-secret
      bucket: kopia
      endpoint: garage.garage.svc.cluster.local:3900
      region: garage
      tls:
        disableTls: true
  encryption:
    passwordSecretRef:
      name: kopiur-garage-secret
      namespace: kopiur-system
      key: KOPIA_PASSWORD
  moverDefaults:
    cache:
      capacity: 2Gi
      mode: Ephemeral
      storageClassName: zfs-spark
    podSecurityContext:
      fsGroup: 65532
      fsGroupChangePolicy: OnRootMismatch
    scratch:
      capacity: 1Gi
      storageClassName: zfs-spark
    securityContext:
      allowPrivilegeEscalation: false
      # readOnlyRootFilesystem: true # issue with verify jobs?
      capabilities: { drop: [ALL] }
      seccompProfile: { type: RuntimeDefault }
    ttlSecondsAfterFinished: 300
  scheduleDefaults:
    timezone: "${TZ}"
  server:
    auth:
      insecure:
        acknowledgeInsecure: true
    namespace: kopiur-system
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: b2
spec:
  allowedNamespaces:
    all: true
  backend:
    s3:
      auth:
        secretRef:
          name: kopiur-b2-secret
      endpoint: s3.eu-central-003.backblazeb2.com
      region: eu-central-003
      bucket: kopia-7dc5
  encryption:
    passwordSecretRef:
      name: kopiur-b2-secret
      namespace: kopiur-system
      key: KOPIA_PASSWORD
  maintenance:
    enabled: true
    schedule:
      full:
        cron: 0 3 * * 1
      quick:
        cron: 0 6 * * *
  moverDefaults:
    cache:
      capacity: 2Gi
      mode: Ephemeral
      storageClassName: zfs-spark
    podSecurityContext:
      fsGroup: 65532
      fsGroupChangePolicy: OnRootMismatch
    scratch:
      capacity: 1Gi
      storageClassName: zfs-spark
    securityContext:
      allowPrivilegeEscalation: false
      # readOnlyRootFilesystem: true # issue with verify jobs?
      capabilities: { drop: [ALL] }
      seccompProfile: { type: RuntimeDefault }
    ttlSecondsAfterFinished: 300
  scheduleDefaults:
    timezone: "${TZ}"
  server:
    auth:
      insecure:
        acknowledgeInsecure: true
    namespace: kopiur-system
