---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: kopiur-garage-secret
    template:
      engineVersion: v2
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      data:
        AWS_ACCESS_KEY_ID: "{{ .GARAGE_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .GARAGE_KEY }}"
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
  dataFrom:
    - find:
        path: /kopiur
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-b2
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: kopiur-b2-secret
    template:
      engineVersion: v2
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      data:
        AWS_ACCESS_KEY_ID: "{{ .B2_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .B2_KEY }}"
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
  dataFrom:
    - find:
        path: /kopiur
