apiVersion: v1
kind: Secret
metadata:
  name: firefly
stringData:
  APP_KEY: ENC[AES256_GCM,data:5m8aCE8358V4mzU4uMFrZ/Gk7FpiXCG870DLsDyIKO0=,iv:LzfCdMMPSYOs7+AOjqONZ8VLS9Wh3GD4aVg/mTgsczg=,tag:3z9gpM/PXP1REjeqNHcSDQ==,type:str]
  CRON_TOKEN: ENC[AES256_GCM,data:Te/LFywyQkXunDWLeVHjR71x6m+61UFKxu9uoS8CLPk=,iv:yFJu4NWCGEmEmLw3Xv6ayHmo6+iASGX6ILtybbKh60w=,tag:up1iMK9zL+oA9KPoPGHR+Q==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFk5YWIzQlZa
        aHFKamF0RC9wTGNoVDdDV2s1UWZjdkVJc0trRFNzN0dKcnk1Z053d3VyUzBIMUR1
        dUx1aWdWMWRXQ3RJdmZXdE5Cd25NNVU3QUZHSGdlcXY5RVhlb2RzYUEvVEdBV25a
        d1A1bVE2cTVuQlMvd1lSSkVoMjRxQmZjdCtlQnJmNVU0WGw1Wk5iRzNBNjNWemwv
        OVpuR1g5TmZNVStZWUhlT2wvWEQ2QWdBV0w1QUl0di9nQytjQmJxQ0NsOS9NWEwr
        dkFERks4L3V5Z3A2ZzJXdWNqSjdkUTRYQ0JMVmhNL0ExRUQ1cnluR2FQZkkrUEhE
        RitSbzlVOC9LYTRMN0ZhK3QvTzU2czVsL2ZFU1VFeWkxK2tUMnJOMUk0ZEQyaldm
        aXZreFZJYm9WeWlMTDk0dGgwMWZNNnZERTNpVEdmd3A3VGxnR0drbUdMcmhCTXFH
        MDcxWTJLejg5WnNZL3VRZFg1bEl4M2dKaUtpY2FCaFIvblJQTUZTd2h4MURkWFhu
        b0RvTTUvUGZLd25tL3p2a1hsdVFydS9UN2ZTZ1FLSzRRM2kweVpXUVdNSkdzT3Yw
        bW00ZFRzcVY1Q05kd1hCa2ZDSmgyRkVmcWxkYWMyRFR6ZzBKamlTSjVzcDFQN3ky
        ZE9CUnZSdlE1RTlkaEdYNlpkRWUwdVpsQlRSbHFDL0lZbHo4T1NQRWRWaWNmdFRm
        NnNXQ1h5QnFQVjdYUXZpRDQ0ZHRWRFhMU1NXMG5xWW1DUzZGREZTM2hKTkVnRjQw
        eUkwYVBBSmlNajY3cjhTR3pSWEkwekJPYzJrVWJ1NmhGN2RGbXZTZ0Z4V0R3WUVm
        aGZkdzlYcEM2K1NFQVQ2VXFuN3FISHQxcUVFTFhDMnBad21kWVlTblErT3N4NUY4
        UW5DT25ZSmVwQStKUmdFK0ZxRFdPa2QvdDVCSVlyM3hsZWpvMmU5bk9rKy9nVGRJ
        SE5DZkNydDdlQm9jcDhFZnNyZzl0bHo3MS8vKzN1dkJsZUo0U0hKU1djb3hpN0t4
        TDNSR2xVSVNiVU9jUE9ob3dUZVJXa1o2dzRwOXowN1Z5bkI2Z0ZKY2dUeFNzaVhN
        OXRwYVpIWjZmSWErK1Z4STllZ2hRR1JlWTlZT1llNUcvTVkzeEVBM2wzVS9pR2hp
        YmhhSmE3em10VjhVQ3QxS0lJUVIrMGFMUHI3QktnUVNxWG9DQTdtSFpHMmJsazl4
        WDlQaS95RXQyVFpRcmNQSDBVRFJ5bU1GUlUyUXYrWWZUT3Nta0E4ZGRIODdkRHlx
        amk5OEt3N0Y5Q3FZYlZDbzNqak9jb3Z2RHlpaHZWY25IdkxjRnQzekJITVp5RVVG
        TGhPbnppM1FRLzRaV2tES29ITkhyZElyVVh4OWpSL05NRnFjMG9JcUlNaTM4U3Bk
        ZXRycTNQWXhYWWZTSmI2QU9qUUpKSHl0OWxJNnlGM1VPNml5b0NGbXNlbXRhVEVW
        TGJxdjVWYkczQTg0a3pIcmhzUGsxcTc3UFVhRHUwZU9vVXB0N2NBMlZjcVFJWWJK
        SEZTQy9FbFI2VWUrUzYwaVJuSXNNOVNVaHFuaG5lekYyOG9Ra1JHaUJjM3M5TkVT
        YWZxRUxDRnNtZDh6VmRWTng3VGdwTkdGbWdLMEkvdU43RVcrU1Z0UmtZMWQ1V3FR
        RmZ4YVlNNTVCeEU0dnYyZEN3OEhmeGlBYlhLZmFqRjJiV3JTcW1objdzaSsxejVv
        M0ZvYVZuMko5VFdwSUJ3aHZ2clZvOGhVS25KWDlaY2R2V0tqd0ZzZTd4RTY3QVJk
        QUpFYm9VbmtFdXJhNTAwRE14NzNKQW5mcmRvQnFVNXlJWFh0UnJTTWdDMzlxNTNz
        eVA1REdJSG5jQWMvODdBdlpHMW9qZWYyNDZpeXdKZ1FTeW9DL3ZVTWd3ekxUeGlG
        RXBOamxEUWRWak1xQlJMMEJRWGhwZVVHd091NktMemw1aG40SUYvU0JLQWdMdwpN
        RlFCdjFGbzd2V1RhbTdyRVE4eVowRG1YK0VQMExPODZBQWVOUkVJWURvCi0tLSBP
        UWkycVVHa25OQXdIemFYQTNNOGM2YUVRTzZreXVBWEVRa3dmRU5Qb1MwChFvuRa2
        nY5epy8Zay1k85HIG7I6Kuk3d/541n4WWEhElENdQ/PEnUz6Nd4iJ+3Y+eUVOV7X
        Dg9iNjhEpudNFG4=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-07T22:16:22Z"
  mac: ENC[AES256_GCM,data:3cXwrtOQHhhqUNl75AfsX3M1Aw6xBVaEYTD0q/gfm0NoieCuCEAqkhOO3WxsWd0hWZt67Zv9gbTvN90js7gZRMIZpjCkLAot+A8LmB5UVhLR8QBhNW4RU6TsWeIUitIAr5EhJEZKnbK2h8vt1hFpKOaBwNAaNw941eMtFRH+ldM=,iv:AXZur0OV+3A/C5qiI1xaj2+VBd1Y8gtv0fZWLsrnWDo=,tag:RHoTc9dHwtxuw6jLrqP1Kg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
