# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: lidarr-secret
  metadata:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: homepage
stringData:
  api_key: ENC[AES256_GCM,data:rbzkO6RVqVSv+3LObpvgp1SoJiIpBsWxYmYlcb+5wTs=,iv:uaGNcp6RGMdQPIIZhlmB/4aNo1Mn7gWR2ATY6zWGYKs=,tag:DfgaPHzURS8m5pE0TxSwqQ==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEhGMUVuaGYr
        LzZMc20xb0NDT0hGMG9UVlhlcGxKNi8rcHhvb1BRdFZheVlRaFBNaFFPTkVKRlNp
        ZzZsSlBHU2tCZGhUdWJ5bzdnMFRMRDdNNlVPLzZkOE9oQmJOd2x1WWh4MEZGbjE4
        dU1vamcyUjBiKzJ6QnlZMUMwWXdOVUl1cnRPZkN1bFFHQ29YOUdNR0ZkdlkwM1Fy
        dHhKZ1VKTnFzaHB4NDFyd2tBTzdrU0p1VGE5WnNoY1FqMHFFaEpwcjJpZlMyc28y
        bmJEenY0aWhWdE51MUM5U1NjbHJ6UzZLdWdLVXRuMDBXTFFUcU90MVc4QWZ4RW5z
        NUtHUTJEQytteDMyUHRJNUphbVk4UTVaSmZlWUkzcjZYcWdBMmdYTUh3MHRSWGFR
        a3QyVUlidmQyQVp3SjZSQ3pjdkJEYllENEpLV0dRQkRmMlVtSGJlSkdrOTZPNmlD
        VElnWGIzaFJReVY0OTI1YXhWLzJFWWRTc3RYR1ZmZnU3UE83cHNhanRwN0FPNFh4
        KzliZngxV2hoTklTMTVsVC9BWHMxTTlBbG9ia2JIanR2TXJFL0s0cFFhbVZSQWY5
        UllwSXc2UCtpaVEwaHFuNm9NMnhhT29aYks4S05iZU5mRFBtRXdydHdKWkUvQ3Na
        S3NmaVQxZjRnK2l0ZHRUM1RJVWZQSFFCWGlYM3FWeHp2S2VENTg1QU1HUWJ1RzdN
        SjhDR3dtQy9HR1QrSFlrejlubEJ6YXErWGpHR3lLdEJiMVhkK0E3UmcrOGRKWXBW
        ekdnUDJObUptdm9MTGYzQkxWZVlFY1A3TUxraEl3ckR5WnFWTGx2RVBXSldBUHdu
        S3NST0J5VFZWZll1M1NNUmZRL2VXSDVCWnl5ek1uaS83OTBGT0M5b05EK1VabXd6
        RGMzQVN6MUJNc2o0UHZ4WHM0cjJHbUxwK0s3NVV6Z2h5Vktmb2RqSTFWWGZDSkRx
        VXBSU01pVzkyYTRBcG4zenRpQnNTeWFlN3dUcGZqVkN5VTNPRE9PSTJHVlhyOGpJ
        RDlpMXFXRTdNeU5xQTY0OEk2alNmUWFWTjNMSExRNHJIUHlCQk9MWFRickVVZ0da
        SXNlOWNBSmVjbnFoM2RySGxsMnRxTzJTK2xsLzluV2tackhWMnNkZ0tTY0RaYngr
        dWRoaG9XQVRKN1hQUnlHbDRJT0xRQmJmd0hnRStDdzk4NFBwTEpyRXBJeXViR1oz
        cUo3Uit3aXF4eE5PeWM0amxLMEp6cjZWbVoyN0tzTmdrbEp1a0N4M1AvN091RXRF
        OE1IQlhERFpENm1PN3ZUSG9BbU45dUs5Z1Y0Z0p5bk9UZDVNYWRySVFEWHpuWVY3
        Z2U5SkZjM3M1dUZhWkNMQ2s1UnM2a3FJdTd0QTBxQkZxUlFlbHJ3dFV0N3NFQmhI
        bnVqVitGQTEva1VubkpKWW4vNEpXWWFrcFluMzVBMTZhcWoyL284c3k2YXRoaE9O
        dUpaRjJXeXQxYmxzVVJpdFYydUxkbEpaWENsOHhQaThvK0IyeXMvNXVzbFRVN2s0
        S3ZEb3NRRlhiSlMwNjc5UDNJd045ZnlyZEIvUDJpdy9BWWhja1A1d0Jsc1E1Z1VE
        ZlUvT21kRURYMUthMHp0dDNLWHlHc2NpYkNWQ2hDajB2YmdnMWNza055cU5ySy93
        dDR6NUpBSlN0SzhTOXZJY2tRbVJOenBtT21Nbk1sRVVhVHo2ZTFGQnRkS3FpQXhT
        REJXb1hTVHdXS2RiMG1BbnF6a1YwYVQ3ckpnVkJjV1ArdHNnTWIybVE4ZnBzcURP
        YjFhbXhxaU1BUjJMd3p5MFpNajBFa1lIQ0JWSExlcVdIdDBQTUdmYXBtdUdTWEtl
        Wk1HTCtEMndaQk9uUGNYdWx0RW1FeE4wNlZYQnRRcERzaktLOVdOdTR4TUV5U0pm
        TW9WVnpvVE5BUDFUVlFUMERjbVEwZ1pFSW9qelB5SzUreFNZNktLYUhIYjhmQQpO
        RE9SenlEWllYNUtCTmxIM2pWK2FqcHZhYzNFcHZkdENCMTVjZDVDa3lJCi0tLSBF
        ZGF0NEp6bjVkdS9iUzBHTjRlbm14cUR3UUNwM0tFT2FGMVlXeFM5MThvCvl5OzZ1
        lYIcJwDUaz/QU5HUM8IDn5/uDk4mjhuj4n0dZXcL22yDBKse3BTtluTy4M240hSJ
        OlNJ5cmipII059Q=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T23:11:27Z"
  mac: ENC[AES256_GCM,data:PnAmIs2OuaCm1nua/sNY/TCUjjjKiT1+rf9LhrPs0UsdfS1v1NFslQYKXNIb5rjfvC1tbnzwRD/McQg4sKRHGHFsuab+NDFFthYNzuONNmhIM1kU3WVVp7C9vTbRPzWFKcCDCnWEDN8xoZsUXVA23z3KvXviix5rjuT5Is4Fghc=,iv:9aSl8Yzz56wOke1E4IIOnVclyTsjAHkD3R4/0kGZixI=,tag:1m6uEu1+w499DXJXn0GZKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
