apiVersion: v1
kind: Secret
metadata:
  name: baikal
stringData:
  admin_passwordhash: ENC[AES256_GCM,data:vGqXuHI8cCrowNM1a0GJKQbJa0rq4sQxEkV9HQk9ZZPWIV88gUSIMQYrXC1nyBA/vrAIuwNznLEhrxUR/rO7yw==,iv:6qJn9rNw5hFXlgmBjGHTyAVifSYv7bEyhLKb10aG23w=,tag:Tq8gdOHrx9Cj5EaEKG+fuQ==,type:str]
  encryption_key: ENC[AES256_GCM,data:CNY4kTY7btVqTEIgv+uDCXoFUHFixpxicn7pYtpPIQM=,iv:lZO0Qfdvb34XkXht4MhbV2/1jm/BEN4frrlYPrDyxUc=,tag:AfRiKZURQvx7Nh+2lGTK9A==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGdPeVBjTkdJ
        eGo5dmwvQkZLdnZDVGhRMVpMdVlTVnIxSHJRYXV6WW5JQnZORFQwK2JrMU9ObG16
        RXZhMHphS2pQVzFOeEJBU09uNnNkYW5nVkZKd3JJZkdLVE1tK2xtaE9pR1FQczNH
        NnFGTGQrcExaYzdrV0VqeVQ4dGh4aDMxTjA5M3BQSjVrcno1OStIakovZzlUcTc1
        UmErY2hjU3NnWXZlWUgvODYxV2xhS0ZKcnlSZ1lLRkZXVnlaM1ZVZUNwMjNmMGhG
        S1BsU0dJREhxTkhiUTFwYUZObkxaMnZCYk1oVzlUd1NjRUhTZWJGNTVLZkNWbFdS
        TGhzR2J5MTRuc0dIVUVVajlpRUxiNEYrNWJhQURlUThiMFc1Vi9hYjRzZEVKa3J1
        SmNmdHh2VTV4a1llaVN3L3R1V210M0NENjIyamZEWU9jUmowc2dxSUJFeXAvc1VF
        YlZYTmhNTHh3dUQ4Z3U2bW90OWZFejRJaUZlMU1jQUZ6Q0NIRldkRlJKK3BIS3Jv
        UzdYdGh1RmIrZGIyUGpBeGJEdmlIUXVzZmdCWjAzankvUGhKVjNTNVlLbE9RQ2RK
        QmdCMU40TlgzYUorWDRPZU5OVFE4QzBJT29VZm0rRFZ3RGdtYVkway9heHVyZ0FX
        ZnlXOTV5ZHZNNmVHMTMrcGZpR0RlRGpjYkJoTzh6enhaUnNPNnBnYkZQelJzSDJL
        R3ZGUjBjUDU5WnIrR2Jtak9DM216UlRLa1JTam1VMndpMnRhQnNtWVZ2dFYzbXFF
        UVJHL0RER1c1d1VDY0tvVkZGbThxcXV4VTFDMGVOUzJsaHlBNDZ5S1BzaWFCQ0xE
        dDQ1U0dXbHJpN2hhRFlUTHJuU29FS0hoVEFVdXJPcVREeWJDNWNiclpJaElVZ2ln
        SUhGQ0R0ZUlnREExNUt0TmgxZ205VzNySmRhNmR3bThwS3FKNEFldUM0RFVCMDU1
        Um9ZT1JUVzdRMWxuanFlLzJjM2JReU5hVkFsbUY0U1hXTEEybnhwNzFFT0F3VU4v
        cjNDcDlodGt2MFUycm1JTWdGbE01WjhVcWRDenVKell3ME5xVjlIUzdHRWFhL043
        WXhha3RrRmFhVFRrdnlZVVZpMzAvR0gwcXFVL2xmaXNXRmdxNjRPQXBPdVpPMStE
        T0hMZzlZNFNwdFQrOVlHVFo4Q2g0a0trek1xTHhkVHg4T2IzQWJTdUptVDBVQkZy
        YStTZ0pzNkY1UjBhZW9FdzNmNVVJNzl5bVhnVDBQNlhFeUdRQnBxcWV0Y0hKSDBV
        dWJyZFhvVWg2TU0wcnZ3bk5WWTdRd3M1UjNzVmxkdXJxbVBISnFCajh1YStpSFYz
        VXk5ak5QWHkrdXNDZXgrdnZPc3piWHJnZGt3NmZzRDgwWndLdGVOdWNoK3lxWWRx
        RkFTajhYTXJwTTZlSHNTQ2ZpWTMrelo4em5mdnhGcEVUdzdRbCsvN1psOWhwcWZm
        MU14ejFJcDhRZGcxR3BtRHM3Q1BEbDVFMUwzUCt6aHhjRjZrVzQyYnBUSnBHdzZ3
        dVRQWjAxWkxFRWVWazE1T1pOaWRZTFUvOFdIaFc4QnZ1SjU1bitQSitJaG1PTmJv
        OHJ1ZU84ZEd1QzR2OUZMek9uZEs1SThadHJnazN0RVV4dTFHOTBPSzJtWDlYSFE2
        eVI1b2Q3aE9Hd0ZYanNQd2tZRjNKTjE2OGxNaEMzMW1mTnE4MzVvQ1dPWDJ0bE9C
        SXJ0dDVBbGVtVGR0R0xFOWpzM2s0T2NuWCtSajdMRWZHd3pqZlE0Szg2ZUpwMy9m
        T2hCdHdJRjhITGkwUGlYeElxMGtTWnJvdHRDUHlvbmIvQ3FkdEpEQ1J3ZTJVTFJD
        VzEwNEMrUEJaaS8xMmZsUERxTExGb3Z6N0JlbzJwWDVnNk52ODFzMEdiWG0yeFR5
        NGUvMldDbXpkUW0yWStpbHdVM1VGZlVsRUJwZ2xtbDBBUllTemdDV3Z1N1VFZwp1
        MmZFQThwK3pYVjlJTm5TcXdkNHNYeE0wVGJVY1JDNVpHY2l2Ymt1NGhBCi0tLSBO
        Z0xMS0ZvbGtQRHJ4SVZoYzNXNG9GYjdEY0liQmgwTVBqRHh5eDFiSVFFCj9YEF54
        ia7NIyVrveJL8hvoRLQ/Td/0VKUzen/bUYLokN9M+D0b2usG4XSawEm3TFsbxq3r
        9us+YQdnj2sNecY=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-02T12:37:22Z"
  mac: ENC[AES256_GCM,data:LSVSV06kR/hqQiNkQK2+/dyQHz7SDK8kaWIRb2sRUkQsVOEINSCpU1NbdPokm6LPkpGoq2s9QFaEcGMBd8E7rp7NsGO8CwHdEeb2s84/oYoqMHva2IOSA6ss+6KxlUtmqD7D+GBesioAYiqVkjpRBKOBblzhR7fm5WEe0MC0GtU=,iv:sUd557ZYqBd3xyEyZrVT++fI7H/x539G2ReIdc+rrRk=,tag:1YHNMfSzd+335PR/yJ5lfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
