apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:/cE11E/33Rg62GE=,iv:IySw5P/1K+XwIqWZpgVAVbDCq10Cr6kPu/d0mPa0jn4=,tag:Vsq5ovgUO0vjmAWJ0kreJA==,type:str]
  TZ: ENC[AES256_GCM,data:ttg6viia29OHLq9LVQ==,iv:HYa8Do3gNyxy4BpAcpBsaS/3L5BtDJStIE5eKbuRomU=,tag:DF+8S3r5Z22rUVqLikT4sg==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG44YXltRUJO
        RWJjL2k0bmdPWXZseWNBT2RqMVhVV2ltSW96Wk5ZdEtmQzVlV1o5ZG0xc2srSGJp
        cGp1K2QzUWtPSXNrNTMvZlllMXkvbTdFd0pEb0lnN2NxVVFTOS9SVFJ0Y1hlTkl4
        MnlIZnFERUt1eVlIRVgwWE5PWHlOaG1OcUNmZFJOY1R6SG8yQ2Npb291VGJTZFcr
        bWVEWThBc0t6WjFZbHdqTFgwYmVxVWtmZ1MxeUU0MTZrYlp3Y2tpNHlRUTNnVWdR
        KzZuQlBJZVBCdDlmZTRNa0VJNzIzcGtPS3FmSk8yclU4K0s3ZGdhdDNYelJvamxa
        N21Sak5LbUJ1U0l2czc5Yy9IbzVCalkva0lKaWZxdDAzd29OUFFXc3dQTUtTTjRt
        b3o4b3YycU1UZWFub2k3eEM0QjY3eG1EaWc0N25adXR5d2tFblZOVFdwcVVGOEEz
        aGlsa05IU2E0QVJFNUdsUDRSelFhNitUODRnRmtJdjIxbUdOSTF5clYvTlNVcjdS
        Y0gwU2hYaFJVbmdwYUh5bTQ2V2JzYnA5MjhOWGhFdTRRaUZBL3Q1SDY2WkNJdWMr
        OVlNMDZEQ1IvTm9tUjNiWWNMYnlrdkZKOWFFQllTTUZMZGJQTzV1ZFJ3WGszOVd4
        UGdkT2xjOUlxV3docjNrYWNpZlZnaFpSSkVMenorSnluRE1ZYlFwSlYxU0h0TG1n
        U2NNSlBhV1lHaldQQS9UdnR6Q3lNb2RjZFREQWtzMHprMnhLSUR0Q0VvWE9naHBP
        eldjbDFsT3g0MjdpTGh2dlNONThvMDFiNWpDNjVteTdWVW90MkNVelF4ejFsMWxL
        UUxNUlVCWTZhc3RteW9KanhoUHg5NHNhYUhKc1dQRjE0L05XenFLaDQwSkRSL213
        dTcwODdDMjhjNk9nS0ZpV3BPQjh0SFZwQVdLM0o0NXUwc2s0eUkvRE9nOFZZd2Rp
        YnoxZWR5VDZ5MTQzRzJSMHRLWFZTZ2NlVXQ5eTIyV3pYLy95RVRaUG82dW9BYWNa
        Qnk3RDVLSm5SQnNpQlE5S3lhZ1RVRGVxZTJleTFVbTNML0l1ckx5cDMxRmJ0Ukx4
        cTVxYjBxNTQ3cHM3bmxINDExb29ZUkhZcldHL2NIUUc5Sk5Ma09GTVhwTDZ2SFZv
        SzJha2haZ0prSG1DSmt1Z292RU1scUd2MmdKeEdHV090UldNdVg5bE4reXRacU55
        Qk9QL21sM3VEY3ROWjR0WFNydkkyZWovZko0REwyRVp5N0tBZG81ZWxYS25MSnh2
        c0RidUlZbGg1V3J0Y0lLNW9HSWU2S1gxWExnUnlRSkxBUk5USXg4TVZJR2tUOTR1
        RzNzMHpUWlBaQ0RTUmFjNjlYYTduby9ma2p2WThhZ1BVazFQU2o4TkhPTjIyU2Yw
        ekFCVDBpK0hzRmFBNG9lQm1BNHNleXZISm5TZ2oyM0RmNmF2b0ZQQzV1L3NmdDVH
        RDRwbFB0ZlNSUFFydTAvUENYMEFkYVhLRDFoL2szejNEeWMzbmxBZXB0cUYyL21U
        Uzh1MUQ5WFNlUkhhQVVYcDB3d0tNSnFjQm0vQkdEK20vS1N5a0syMGQ5WWJHY2NI
        MXJ2VHorbDFyOXJNMmtaWFJQU2tIYm9TV1lNSjVoUjZqbHQyUXJxYlZOSGZ6UFNU
        SGxYT0RTOTNxdEh2RGo3NmhiUkpGcGk2V1VzaldNb0RiYmczL0dsakJQcURtWkNH
        Q1F6NkNxRnRnQ3c4ZWNBalRFaS95ZWt4THlVMG5ValdXaXZEK3E0WGVWaHVaaDRv
        cXdtaHFXTFBaTW4rMU1TR0t4eG85b21qMk5vNnl3WUF1MnJsbXNqMVZ1aEdzcktj
        UG1UYmQ5dllQeHhDU1VOL3NqNkpkamtMMmNaa0JFNk1ZTjV4R2R0WU5LVVpUbGxN
        dVROZDErVWNsU1JUUGtveWZ3UmJBeVZYVU9rZ2d1UzdBMmw3THFkYTV6MDhWdwpo
        MnZ3S1RwWnZKVmdDaytXUm1pVlpLQjIxL0dQQnZ5N3RCT0MyWnIxVk9JCi0tLSBJ
        ZXN4ZVhKd3VCU2F6cFFqNldZWmhqV25zN21TRm82M3hWWlNiR29xYk84Cj7d99kw
        AUVp/OxMZYq53h3D52OlOru1Vnwov+ftRGbr38grNd+89nW5wrZOTVBYRrzwp1SZ
        mGg1uVyWdygzfYk=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-16T12:35:31Z"
  mac: ENC[AES256_GCM,data:E03UhWMXN8Za8IeVenEE9m69KujR7J4Uz73OjJs7IkxfYI6X9zOQrStlrymsV90OxE4rSBouL32/QlkzM8eh+MwytoSxNUO1yLe3jb4p1gI2c4RJUDrMum8oAoPmkI2GCHNyfUZ3Tv8LS1h+83R4QEjd5Z5FwqVwEajGYK/tQgU=,iv:z64QypOWbloljyDYDIXCb7RfW5zVpR+lIpLCQ8eDM30=,tag:o+naL2pgCao7b2ErJcYhsQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
