---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opentelemetry
spec:
  interval: 1h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app opentelemetry-operator
spec:
  chart:
    spec:
      chart: *app
      version: 0.106.0
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
  interval: 1h
