---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sftpgo
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        # initContainers:
        #   wait-oidc:
        #     image:
        #       repository: curlimages/curl
        #       tag: latest
        #     command: ["/bin/sh", "-c"]
        #     args:
        #       - |
        #         until curl -sf https://idm.${SECRET_DOMAIN}/oauth2/openid/${APP}/.well-known/openid-configuration; do
        #           echo "Waiting for OIDC provider..."
        #           sleep 5
        #         done
        containers:
          app:
            image:
              repository: ghcr.io/drakkan/sftpgo
              tag: v2.7.1@sha256:26095be794616b5ce1cd08a24244dae7c1eda18073c482f58a8d1948237240b0
            env:
              SFTPGO_DATA_PROVIDER__DRIVER: postgresql
              SFTPGO_DATA_PROVIDER__CONNECTION_STRING:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-postgres"
                    key: url

              # SFTPGO_DATA_PROVIDER__PRE_LOGIN_HOOK: /scripts/pre-login-hook.sh
              SFTPGO_TELEMETRY__BIND_ADDRESS: "[::]"
              SFTPGO_TELEMETRY__BIND_PORT: 8081
              SFTPGO_SFTPD__BINDINGS__0__ADDRESS: "[::]"
              SFTPGO_SFTPD__BINDINGS__0__PORT: 2022
              SFTPGO_HTTPD__BINDINGS__0__ADDRESS: "[::]"
              SFTPGO_HTTPD__BINDINGS__0__PORT: 8080
              SFTPGO_HTTPD__BINDINGS__0__OIDC__CONFIG_URL: https://idm.${SECRET_DOMAIN}/oauth2/openid/${APP}
              SFTPGO_HTTPD__BINDINGS__0__OIDC__REDIRECT_BASE_URL: https://{{ .Release.Name }}.${SECRET_DOMAIN}
              SFTPGO_HTTPD__BINDINGS__0__OIDC__SCOPES: openid,profile,email
              SFTPGO_HTTPD__BINDINGS__0__OIDC__USERNAME_FIELD: preferred_username
              SFTPGO_HTTPD__BINDINGS__0__OIDC__IMPLICIT_ROLES: "true"
              SFTPGO_HTTPD__BINDINGS__0__ENABLED_LOGIN_METHODS: "3"
              SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_ID: *app
              SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: kanidm-${APP}-oidc
                    key: client-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &metricsPort 8081
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        forceRename: *app
        ports:
          http:
            port: 80
            targetPort: 8080
          metrics:
            port: *metricsPort

      sftp:
        type: LoadBalancer
        ipFamilies: [IPv4, IPv6]
        ipFamilyPolicy: PreferDualStack
        loadBalancerClass: "io.cilium/node"
        annotations:
          external-dns.alpha.kubernetes.io/hostname: sftp.${SECRET_DOMAIN}
          # lbipam.cilium.io/ips: 192.168.69.133,fd5d:a293:f321:69::133
        ports:
          sftp:
            port: 2022
            targetPort: 2022
            protocol: TCP

    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
          - name: external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 80
    persistence:
      config:
        existingClaim: sftpgo
        globalMounts:
          - path: /var/lib/sftpgo

      # data:
      #   type: nfs
      #   server: nas.internal
      #   path: /mnt/world/media
      #   globalMounts:
      #     - path: /media

      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
