# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: open-webui
stringData:
  OPENAI_API_KEY: ENC[AES256_GCM,data:hfqG8aQJ6CKOEyCQqnADdbwjJSoKqU6CCA==,iv:KIMvlPGzqFYmZ1fvVsPjYTVzIBO1/ca+y9F6y8yAqh8=,tag:M1SpvryAzm3U4YgOgZQWyQ==,type:str]
sops:
  age:
    - recipient: age1pq1sfdg9tmhrcm3vj85fswr7svd9k6s6r4yg9gm8xdsfvcusqpkddr8y7hr4wrxtvkpxp0d95zyqtavstaqc8hfxapd9p7jf6ndt34nrpdsdn3hfzm9awszqkmhw7q47r79xuqay6u96wf27vdr0yz8xukndna5rrf57s0v3wkz4tjy9q6u2f9k4ym3uqed85vgjdrj0lgfv40vzk8h3jpj52q87vtnl0ln0j87fqk54p2ee3q47kpe908j8c399srq9fv3ys3mhqa9fx3hpeuznpwqpgxlttzy0c2j9pxfj94pwtxl0xrgppzrylq6n4dv4g7fgjk6m28lfgq3snqfj9h4f0uhwxkwjsleuzs4v7aggef6rzkecpf9vw3l75wfnweu4yt4n3e7s3kjw8xw0p2zv3rtptf2vpc9jvghg4m5yzqhw6vrhc2pjc088jrd0ph9mhqx5r9y3q9snwwmcy5udwagsykz2frupkc392pstfmc7w54t7ph95jhlgjuqfdfsggdwj99axngtek2hhmp996q0d6tkujy5ug05vvttntzqxxhqnplmwhdj7ze5gscsz3shmrnfzc9sc33y968ffjymjm5f8grdpesxtzkg2zz7kmff94q8rsg0nc7c95u664drsp8u3nry6869ndw224edc9h4dazlff342kdj6qaeg0hraaqacc59f3yzlgpj9j6sj0jj97trfwtm33yz37jqhk2s6psdfdkwstykl62pksmksedch8d96xp0tspyr28trlphddl29zwnure7rv6q2d6vqfnqepqgfxzgz9y0a4j9xpm3s4as2vp4d77su7grx2ulatcxaxsvv42rd9p6p52jsgelmuqv6ncz93dmykcqpdtedps8yeyd20wnfu0t95ql3xzsvnze685efr0vua0kfgjhgmh05ec0z6h8094j2dv5kdh4mrwxk4zpe48ythsqemtkwe5fsa87s537khhjt03q0kjwysmcvjgs77fq0y5n8hwsjge6n8ne5ny4rm9n83zhfd6tpysue06rary2r29jcz2f6v8f90pr8959avjnv23w905qm5azvpnf0y0yua2mzv9cumytgm7skzvvtr9g37287unv2wxfxdxw7ragpqqlgm2ew6j8yngyzpcyq88y7d4rfzqwadt5lk3hkxz2nytqw2nukw97wx275699938dslp0vv3r2fl9samrjk9cj79fqalhxscxux99jz36mpxq9e8ft2u2dkpcjc07qfvz7n29v9my7j3ey26r2zwsk5954mqz8rlpj3x2fqh2yvfwjd80yukzujt33avva9d09wgc7zpc4pf52sznqmwywdswfjjcetcf3uqzhwfs4lc2dfznzrqapz5qk464npfhye9nj0sdqs2l8fry4kpc8s79st9csf3mppqr8ap8x7y4rh8hq0zck24r5kzaavyn8wrdq4wgrsl2vl40eyshkxxuuwz2x6vc3q0rvnkxj5z9sgv9cuxje0vggnepgm67k9yms4mq9esswyzs44crzq25gxx9yrpgczn8r985j5e3y7760pf5r9kkypkrmgyryxhlqdchxavwur4kkhzvxgg5y2h6ega9wpmsju5a06ehd6dvq75rgjwna72yykvuwq5ep23x2zr74aw7qnw06yj0zznr9vnhr8kxw7zt39sc6s5kuxc87s9xd47vc7utkky775necsmzxrtpd9hldll5s4tqw5cfqagv6kkyl8h3ygecx6l93zq699cyu62egeys6aes4gydacfvmmpxfgt334wk70n7yv5ukyqw5mey8yhg624c7ws3q686ey2aytjcnuckrfj3zsr722082qph7gcpj2zx5t73q8u3cqh760sfkvs4ugh6em392lfc28xjhpth7kewzuuhedevh6wt9n9tv5tl7dl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHRqTFA3Y1pJ
        WHc0VkRkb0t0d01pUVF4aDl4Y3Z1L2pBdWpBUE5ZNGdqYUNmb0gvcHpST3hIbFgz
        bnRKcmFqMkJ6L3V3NHJLUHFmdVUyS1N5TnVSbDd5T2lYUTFVaERnbW1wSG1tb3Jw
        QVFteEhuUWEwbEVSbm56SkVoa3hZWVIvOTRSVFloa1BObjRrZ2JUZVZhcm83eGFs
        TFQwWUExdEpGY1pWY1VReHY3VW9FZXh4a2FaSlRYZ09EMlEyYzhieW1GTzFKSnZC
        N1hCSVZTTzdkaHBVNnNUeGdDb05wUjN0YVo5VzFIVU8vcStCL0NIU2ZXTEVXOG00
        V0JOeVdEREpqOXVqNkNjcHdtNHRmVFZBUGV5K21JRG9nNzZjcnd6NVlLVENKY01T
        YXpZVkkxVXVOM3dhZEFPYVNGTXRIVWdsZVAxUnNadWxIRU1CdjBuNlRhTFNYZTJP
        SGplYUd4aS9XTjYrWFRzNzRwK3N0SUYrMU5JSHgzaHFnMGhWWUVabDB0cU90MGdJ
        bUx6NHB1dEZWbnhqMzhyOFA3NlVoNWdLY1lCc0dRTkxKSW5sTERySkdNZjlHL0ox
        d09RVnlXOUVpeGJhM3dsR1lNcVViRS9VSEVOVkpRQUcwbTZNUkpucFRnTTdrSE9T
        bVJSREtsUVMrY3lmS0llL1dvcUVUS0t6QkxTVVFnSDVkaWdXYUMwOXVrL0ZIUVhM
        ajBYdi9KdGZYVGJSVWdkL1BIMFJKVS9BWkJUd21SV3hFU2E0dUFpQnpaV2N1M2Y0
        a0JJL3ZWMUVrQk85ZTlPM20vOGgxRFZETzUvRzJKRjFRdmlqM040NXF3TVZJUEo5
        RjFoYkd0WjRCeko1TkVTckdGRFJNZjFsL3JOQ3o0aEFLZGR3aHA5TlREWVUremwy
        M1Q5UlpUeWNWVktOSVU0bU9LYlk3VnBwTnNhMGdhZUN0QUFHUTFIS0ZYRTRHL3hP
        ZUpvMGhEbGJRMXBEU0VCcURmUjdVMUREcCszbXozWnVaVHpDcW5INVBlbjNjL3JU
        UzFPWlMzbUtVM1NRNTVOamloc3k5S3g4ZjlqYlhDeHZGM1liVGRRd016bGgvemlP
        RXY4N2s5dUdMbG1Rc0ppWCtrNkthZ1gzNHVicXF0MEgyWWxJa0ZSUmxXQWFhTGNn
        RUdoRGNMT1ZEVDdmeUh4Zm9VaG1sSFV4amtkeUUzbXA5TlZXM01CK3EvQ05UTWFr
        cWZYSThzdDlnd2NiNnBOR0V1RjdBUE5XSDJ2c05kUzVlVFRSMmxvZjRpME1VWnNL
        QVNlQ1ZtZHJJU2dzUDFYSWdXNys0M0sycjljYk5yS1owMVBsQ1E4bjd1MExBaUc3
        UnJKZi9JQkFrZXB0V0FEcXdpYTVBVTBRS0E3UDRvb1lIamd5M2gxVTF2aE9SbUs1
        YTNuY3JCMGxTeHFDckh0NWMrTXNheXJjWFJKNi9lU0RTeG1iQXZlK3I1NDhtbkQz
        dnJGcStIZ1FMcFRqY2lZR1p6RFh0cXM4QXpLL2g5dnlhTlFMalZWYVVHR0R6ZEpL
        eUhydlRYYk1CVmd0NUc3clZpbGkycU9zaFpsM0V5cm9wZExHT0VvTk9CWkQrb01n
        YTdSTWJpK0pINjJuamZobFpFV3diblVHM0NLMEpoZXJRTzlqbUFqakJJdXRHSTRL
        TzZXSTUwbVlCWGxZSkN4TFA3cGtJRjdueVU3N3FDTDJqRUdBMGVNeTJRd3dLNDlU
        TnhGTm1MblJhNUYwOURLT3NWWnJPWUlSem5VV0EyK0tacmdyQTlUMlMzZXg1eVlu
        VlFKMkNVaTdjY3dPM0UyVFUrMHZha3puSkt6Vm5yc2htWFZ4L2g5dFJ1RlFPUWFq
        MFhSWlN5VXBxa054MUVRZjgyZFRUSFhOcjZrWC9aWjNhTzJDR2Z2cmtHMHNleXBo
        eGQrU0ZoYWFIU1F3VjYrRXFNWldCeElGSmN1eHRBSFZ6ZVRZRitWclFPVk5jUQp4
        T0F3aVlXRFc2RUZHQ0NFTGpJd3BFcnZWK0RBc2JEeCtXbDhTd05pbCtjCi0tLSAy
        SXRFSjBCdE8reVhrRWlXdmxXVzk0Q29kbWNPMjBORGF2VjZHRDVKNDd3ChESZRSy
        a1oeXJ8B+N2Mjt3we2CvqnQDDfGxEiltQKjT1PaAowZFWx/C3ochgAWlpAnYLpWG
        NM03p/s8AyDUj/g=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-11T05:37:14Z"
  mac: ENC[AES256_GCM,data:au25xWE4mbxX/mOQ/8Wtv+fup9k/ivC9zSlfFRXw8ea2f+5gp4li+4ymPlIMK362GOzgDK/uQcU53zfQieQV7HYnK5VtQrzMYBFscSV+j7XY1sv/hSwTGBl5YOPUcLmehScPR55d2b9jPOaD4Gisp1lFeKfMrw6r9uTSA6+fycM=,iv:NWy6ZmxdWa63XgJtjplUitwkU+6HKRUXXkE2l9TCxXw=,tag:VCkHeQAoo0qc4URCUJazTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
